### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mickaelaccensi**
issue #81 : correct flag status to read time with new CF convention when month and day are written on only one character : YYYY-M-D

issue #82 : set log message into SCRIP comment to avoid misleading error detection with gnu compiler

issue #83 : update scripts to use generic way of read/write
                   correct bug due to misuse of NAME instead of UNIT in ww3_grid.inp

issue #88 : initialize pointers to avoid random value assignment

issue #89 : outbound list display issue

issue #63 : add check on NDSEN to avoid print on wrong IAPROC

issue #90 : regtest ww3_multi namelist : points file path

### CODE REVIEW

**Comment by CarstenHansen** [comment]
I browsed the file changes. It completes PR #69, and also PR #57 by @MicahDavid with my suggestions.

**Comment by ajhenrique** [comment]
@mickaelaccensi I ran the regtest matrix for your PR using the NCEP R&D machine. All tests passed, and relative to the latest develop the differences were in the tests that have not been bitwise identical for some time now (we still need to figure out why in some cases). mww3_test_03/./work_PR2_UQ_MPI_e, 
mww3_test_03/./work_PR3_UNO_MPI_e, mww3_test_03/./work_PR2_UNO_MPI_e, mww3_test_03/./work_PR2_UQ_MPI_d2, mww3_test_03/./work_PR3_UNO_MPI_d2, mww3_test_03/./work_PR1_MPI_e, mww3_test_03/./work_PR2_UNO_MPI_d2, mww3_test_03/./work_PR1_MPI_d2, 
mww3_test_03/./work_PR3_UQ_MPI_d2_c, mww3_test_03/./work_PR3_UQ_MPI_d2, 
mww3_test_03/./work_PR3_UQ_MPI_e_c , mww3_test_04/./work_PR3_UQ_MPI_NC_b_c, mww3_test_07/./work_PR3_UQ.

There was also a small difference in the stdout from ww3_ts2 ST4_PR3_UQ which seems harmless, indicating perhaps that the stress table had been precomputed in the baseline we used:

<  Reading 3D look-up table for SIN4 from file.
---
>  Filling 3D look-up table for SIN4. please wait
>  WAVEWATCH III ST4 TABLE FOR STRESS III  4.12    2.599285      9.4999997E-03
>    1.430000             100         200          50  6.0000001E-03

Here are the full matrix reports: 
[PR86_develop_matrixout.tar.gz](https://github.com/NOAA-EMC/WW3/files/3712448/PR86_develop_matrixout.tar.gz)

**Comment by maccensi** [comment]
thanks a lot Henrique for your help, go for the merge !

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Review by aliabdolali — APPROVED** [review]
@ajhenrique Henrique, It looks fine to me, please merge :)

**Review by ukmo-ccbunney — APPROVED** [review]
Thumbs up from me, @ajhenrique

**Comment by ajhenrique** [comment]
@mickaelaccensi will add his matrix.comp output here for consistency, regardless, this PR is ready to go. Merging!

**Comment by ghost** [comment]
with a long delay, here is the results of matrix using namelist options, there are expected differences due to all the issues corrections. However there is a last bug detected with mpt compiler on w3src6md, see issue #117 

[PR86_develop_matrixout.tar.gz](https://github.com/NOAA-EMC/WW3/files/3777708/PR86_develop_matrixout.tar.gz)

to quickly summarize the log differences : 
mww3_test04 : nest point output printing and incorrect external output point file path in namelist
mww3_test_05 ! work_ST6_PR2_UNO_MPI : bug found in w3src6md.ftn, see issue #117 
mww3_test_05 ! work_ST6_PR3_UQ_MPI :  bug found in w3src6md.ftn, see issue #117 
mww3_test07 : nest point output printing
ww3_tic2.3 : switch NC4 added in metadata of ww3_ounf
ww3_tp2.15 : grid ST4 table output
ww3_tp2.2 : nest point output printing
ww3_ts4 : external output point file path not correct for nml

**Pull request merged**
