### PR TITLE
apply auto-formatting

### LINKED ISSUE #797: Update white spaces via automatic scripts
**Is your feature request related to a problem? Please describe.**
A PR will be coming that will delete trailing white space and fix the indentation so that "ifs" line up with "end-ifs". 2 spaces will be used to delineate this change.  This is following the https://github.com/NOAA-EMC/WW3/wiki/WW3-Code-Style-Standards 

This is a disruptive change, and a two week period (starting today Oct 21, 2022) will be given for anyone to submit PRs before this change.  

**Describe the solution you'd like**
A PR to the develop branch which will update the white spacing in the source code.  This will be done after https://github.com/NOAA-EMC/WW3/issues/796 

**Describe alternatives you've considered**
This is following the code style standards created from the [code standards discussion](https://github.com/NOAA-EMC/WW3/discussions/551)

**Additional context**
The script/tools used to do this will be shared so that others can employ this on in-progress code to help with merging if necessary.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# Pull Request Summary

Apply auto-formatting to all files using 2-space indenting. Remove trailing whitespace.

## Description

Reformat using emacs auto-formatting for F90 using two space indents starting in the first column. Removes trailing whitespace.

### Issue(s) addressed

-fixes #797 

### Commit Message

Apply auto-formatting to all files using 2-space indenting. Remove trailing whitespace.

co-author @mvertens 

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
Hi @DeniseWorthen , I see this is no longer a draft.  I wanted to just verify it is ready for review?  If so I'll start the regtests.  Thank you and @mvertens for this work!

**Comment by DeniseWorthen** [comment]
I believe it is ready.

**Comment by MatthewMasarik-NOAA** [comment]
@DeniseWorthen awesome, thanks again.  I'll start the testing.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen @MatthewMasarik-NOAA  -- It's never too early to start testing, however, this is the first of the "disruptive" change PRs, so it will be merged at the earliest on 10/5 and as promised, we will work on any PR that has come in prior to that first.

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA @JessicaMeixner-NOAA This PR is up-to-date and ready. I was testing the analog PR in dev/ufs-weather-model and got a change of baseline. I got differences in the out_grd files for the all the coupled C96mx100 tests (though not the HAFS, c192 or bmark tests). I want to confirm that a change of baseline is possible because of PR #741.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I will be merging this PR shortly.  @MatthewMasarik-NOAA will be creating a PR for syncing the develop to the dev/ufs-weather-model branch very soon as well.  As you mentioned, the changes in baseline are because of PR #741  (The baselines still matched before PR741, the log files of what changed are included in the PR test of 741 as well).

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Thank you @DeniseWorthen and @mvertens for these updates!! 

Only the expected diffs in WW3 and confined all changes are white-space only: 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_ta1/./work_UPD0F_U                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (5 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.17/./work_a                     (1 files differ)
ww3_tp2.17/./work_c                     (1 files differ)
ww3_tp2.17/./work_b                     (1 files differ)
ww3_tp2.6/./work_ST0                     (1 files differ)
ww3_tp2.6/./work_ST4                     (1 files differ)
ww3_tp2.6/./work_pdlib                     (1 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
```
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/9728127/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/9728128/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/9728129/matrixDiff.txt)

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA @MatthewMasarik-NOAA I have been keeping a parallel branch of ufs-weather-model which I have been incrementally updating w/ the same changes I've put into develop. I would suggest you allow me to make the update to the ufs-weather-model w/ my parallel branch. I know where the conflicts are and how to resolve them.

**Comment by JessicaMeixner-NOAA** [comment]
If @MatthewMasarik-NOAA agrees, he can merge everything up to your commit, and then you can take care of the rest of the conflicts with merging this PR to ufs-weather-model if you'd like.  If Matt would prefer to do it all as planned, he can continue with that.

**Comment by MatthewMasarik-NOAA** [comment]
Hi @DeniseWorthen, @JessicaMeixner-NOAA and I have been working on a PR that will also include the whitespace commit, and we're pretty far along with it.  Since it's also a learning opportunity for me submitting a UFS-WM PR, I'd like to try to complete the process.  I definitely appreciate the offer and if it weren't for learning I'm sure I'd take you up on it!  I'm going to continue working on it but might reach out if that's OK, if I run into trouble with the whitespace commit merge.

**Comment by DeniseWorthen** [comment]
The commit to dev/ufs-weather-model must also respect all the changes that are required on the CESM side. I know what files we have changed and why. It is critical given the time-line we have that no changes are made that will break CESM.

**Comment by MatthewMasarik-NOAA** [comment]
@DeniseWorthen I may backtrack and go with the plan @JessicaMeixner-NOAA mentioned, where I'll create the PR for everything up to your commit.  I found the conflicts to be resolved are more than I want to take on for my first UFS PR.  Does that still work for you?

**Comment by DeniseWorthen** [comment]
Yes, that is fine too. It will be better for me if the baselines are updated so that I can verify nothing changed w/ the mesh cap.

**Comment by MatthewMasarik-NOAA** [comment]
Great, thanks @DeniseWorthen.  I'll proceed with the PR to UFS as agreed on.

**Pull request merged**
