### PR TITLE
Fix to issue #1047

### LINKED ISSUE #1047: Duplicated oasis calls
**Describe the bug**
In certain circumstances oasis_get is called twice for the same field and time, causing OASIS to crash. This bug was reported in #858 and was supposedly fixed in #998, but it is still present.

**To Reproduce**
Read water levels from file and receive winds via coupling at matching time steps, while coupling at T+0

**Expected behavior**
The oasis_get call for winds at time  zero happens twice, which causes OASIS to crash.

The fix here proposed is simpler than the one proposed in #858, and causes that the oasis_get calls at time zero only happens once.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by ukmo-juan-castillo**
# Pull Request Summary
Call oasis_get only once at the first time step

## Description
This PR fixes the bug described in #1047 by ensuring that oasis_get is called only once at the first time step when coupling at the first time step, even though the time loop in ww3_shel runs twice for the first time step in certain circumstances (driving data is read before any coupling data is received, and the driving data file contains information for the first time step).

Labels that should be added: _bug_

No change of answers are expected from this PR

### Issue(s) addressed
- fixes #1047 
- fixes noaa-emc/ww3/issues/1047

### Commit Message
Call oasis_get only once at the first time step preventing OASIS crashes.

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
Thank you @ukmo-juan-castillo.  I'll start the regtests for the review.

**Comment by MatthewMasarik-NOAA** [comment]
@ukmo-juan-castillo, could you sync this branch?

**Comment by ukmo-ccbunney** [comment]
@ukmo-juan-castillo The changes look sensible. I'll run the regression tests.

**Comment by ukmo-ccbunney** [comment]
@ukmo-juan-castillo I am getting some failures in the `ww3_tp2.14/work_OASICM/` regression test:
```
 *** WAVEWATCH III ERROR IN W3WAVE :
     ENDING TIME BEFORE STARTING TIME
```

**Comment by ukmo-juan-castillo** [comment]
> @ukmo-juan-castillo I am getting some failures in the `ww3_tp2.14/work_OASICM/` regression test:
> 
> ```
>  *** WAVEWATCH III ERROR IN W3WAVE :
>      ENDING TIME BEFORE STARTING TIME
> ```

I only had one doubt in the code, which is moving line 2002 inside the if just before.  Could you please try running the ww3_tp2.14 tests again with the latest change I made?

**Comment by ukmo-ccbunney** [comment]
> > @ukmo-juan-castillo I am getting some failures in the `ww3_tp2.14/work_OASICM/` regression test:
> > ```
> >  *** WAVEWATCH III ERROR IN W3WAVE :
> >      ENDING TIME BEFORE STARTING TIME
> > ```
> 
> I only had one doubt in the code, which is moving line 2002 inside the if just before. Could you please try running the ww3_tp2.14 tests again with the latest change I made?

Sorry @ukmo-juan-castillo  - I am still getting the same error.

**Comment by ukmo-ccbunney** [comment]
@ukmo-juan-castillo 
The regression test for ww3_tp2.14 (OASIS coupling tests) all passed OK now.

**Comment by MatthewMasarik-NOAA** [comment]
@ukmo-ccbunney thanks for this update on ww3_tp2.14.  @ukmo-juan-castillo I'll submit regtests for the review.

**Comment by MatthewMasarik-NOAA** [comment]
@ukmo-juan-castillo I ran with your latest update and I get the same timing error for `ww3_tp2.14`.

**Comment by ukmo-juan-castillo** [comment]
> @ukmo-juan-castillo I ran with your latest update and I get the same timing error for `ww3_tp2.14`.

On the other hand Chris run the tests without problems. What is the difference between your tests?

**Comment by MatthewMasarik-NOAA** [comment]
> > @ukmo-juan-castillo I ran with your latest update and I get the same timing error for `ww3_tp2.14`.
> 
> On the other hand Chris run the tests without problems. What is the difference between your tests?

Hi @ukmo-juan-castillo.   Okay, that's interesting that @ukmo-ccbunney was successful..   I just submitted a re-run of that branch to be on the safe side.  

In the meantime, here's the log output from the run (using fd90d927):
```
+--------------------+                                                                                                             
|    Main program    |                                                                                                             
+--------------------+                                                                                                             
                                                                                                                                   
   Processing /scratch1/NCEPDEV/climate/Matthew.Masarik/projs/PRs/pr_1048/ww3-fix/regtests/ww3_tp2.14/input_oasacm6/ww3_shel.inp   
   Screen output copied to /scratch1/NCEPDEV/climate/Matthew.Masarik/projs/PRs/pr_1048/ww3-fix/regtests/ww3_tp2.14/work_OASACM6/ww\
3_shel.out                                                                                                                         
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
oasis_init_comp: Calling MPI_Init                                                                                                  
                                                                                                                                   
EXTCDE MPI_ABORT, IEXIT=     1                                                                                                     
                                                                                                                                   
                                                                                                                                   
EXTCDE MPI_ABORT, IEXIT=     1                                                                                                     
                                                                                                                                   
                                                                                                                                   
EXTCDE MPI_ABORT, IEXIT=     1                                                                                                     
                                                                                                                                   
Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1                                 
                                                                                                                                   
EXTCDE MPI_ABORT, IEXIT=     1                                                                                                     
                                                                                                                                   
Abort(1) on node 2 (rank 2 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2                                 
                                                                                                                                   
EXTCDE MPI_ABORT, IEXIT=     1                                                                                                     
                                                                                                                                   
Abort(1) on node 3 (rank 3 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 3                                 
                                                                                                                                   
EXTCDE MPI_ABORT, IEXIT=     1                                                                                                     
                                                                                                                                   
Abort(1) on node 4 (rank 4 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 4                                 
                                                                                                                                   
EXTCDE MPI_ABORT, IEXIT=     1                                                                                                     
                                                                                                                                   
Abort(1) on node 5 (rank 5 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 5                                 
                                                                                                                                   
EXTCDE MPI_ABORT, IEXIT=     1
                                                                                                                                   
Abort(1) on node 6 (rank 6 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 6                                 
                                                                                                                                   
EXTCDE MPI_ABORT, IEXIT=     1                                                                                                     
                                                                                                                                   
Abort(1) on node 7 (rank 7 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 7                                 
                                                                                                                                   
EXTCDE MPI_ABORT, IEXIT=     1                                                                                                     
                                                                                                                                   
Abort(1) on node 8 (rank 8 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 8                                 
Abort(1) on node 9 (rank 9 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 9                                 
                                                                                                                                   
EXTCDE MPI_ABORT, IEXIT=     1                                                                                                     
                                                                                                                                   
Abort(1) on node 10 (rank 10 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 10                              
Abort(1) on node 11 (rank 11 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 11                              
                                                                                                                                   
 *** WAVEWATCH III ERROR IN W3WAVE :                                                                                               
     ENDING TIME BEFORE STARTING TIME                                                                                              
                                                                                                                                   
                                                                                                                                   
EXTCDE MPI_ABORT, IEXIT=     1                                                                                                     
                                                                                                                                   
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0                                 
slurmstepd: error: *** STEP 47458177.21 ON h36m03 CANCELLED AT 2023-07-28T20:27:53 ***                                             
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.                                                           
srun: error: h36m03: tasks 0-11: Exited with exit code 1                                                                           
srun: launch/slurm: _step_signal: Terminating StepId=47458177.21                                                                   
srun: error: h36m03: tasks 12-23: Killed                                                                                           
                                                                                                                                   
ERROR: Error occured during /scratch1/NCEPDEV/climate/Matthew.Masarik/projs/PRs/pr_1048/ww3-fix/regtests/ww3_tp2.14/work_OASACM6/e\
xe/ww3_shel execution 
```
<br>

In the logs above I'm a little surprised that MPI_Init is called more than once.  I'm not as familiar with OASIS coupling though.  I'll post again once the new run completes.

**Comment by MatthewMasarik-NOAA** [comment]
The test returned and it throws an error like before.  Here's the matrix12 log file with all the output in case it's helpful
[matrix12.out.txt](https://github.com/NOAA-EMC/WW3/files/12232990/matrix12.out.txt)

**Comment by ukmo-juan-castillo** [comment]
> The test returned and it throws an error like before. Here's the matrix12 log file with all the output in case it's helpful [matrix12.out.txt](https://github.com/NOAA-EMC/WW3/files/12232990/matrix12.out.txt)

I need to run some tests myself with the latest version of the code, which I will try to do tomorrow. I have the suspicion that the fix is not needed in the latest version, but it was necessary in previous versions.

**Comment by MatthewMasarik-NOAA** [comment]
> I need to run some tests myself with the latest version of the code, which I will try to do tomorrow. I have the suspicion that the fix is not needed in the latest version, but it was necessary in previous versions.

Okay, sounds good @ukmo-juan-castillo.  Thanks for the update.

**Comment by ukmo-juan-castillo** [comment]
It is as I suspected: this PR is not needed any more because the latest versions of the code does not try to initialize twice the driving data at the beginning of the run. This can be easily checked by looking at the model output: in older versions the OASACM6 test would have printed two lines like this:

>  Updating input at 2011/09/02 00:00:00 UTC

while in the latest version of the code this line appears only once.

Conclusion: This PR and associated issue can be closed as they are not needed, I will do it now.

@ukmo-ccbunney , I am afraid this fix will need to go into a new hotfix for our PS45 code.

**Comment by MatthewMasarik-NOAA** [comment]
> Conclusion: This PR and associated issue can be closed as they are not needed, I will do it now.

@ukmo-juan-castillo Thank you for providing this resolution.

**Pull request closed without merging**
