### PR TITLE
No data on zero meridian when resolution ratio > 2

### PR DESCRIPTION
**Pull request by SanderHulst**
Please see NOAA-EMC/WW3#242 for a full description.

Oh, and release/zero_windspeed_on_zero_meridian should have been called feature/zero_windspeed_on_zero_meridian.

### CODE REVIEW

**Comment by aliabdolali** [comment]
I checked the regression on NOAA HPC, with the diff in known non b4b cases.
[MatrixDiffNCEP.zip](https://github.com/NOAA-EMC/WW3/files/6143721/MatrixDiffNCEP.zip)

**Comment by JessicaMeixner-NOAA** [comment]
@SanderHulst  thanks for your patience with my slow review.  I've been looking at this off and on for the past few days and I'm still stuck on the following: 

Why do we not also want to apply the same theory on https://github.com/NOAA-EMC/WW3/blob/develop/model/ftn/wmupdtmd.ftn#L1369-L1372 
so that we would then have: 
```
              IF ( FLAGLL .AND. ICLOSE.NE.ICLOSE_NONE ) THEN
                J1 = 1 + MOD(J1-1+NXI,NXI)
                J2 = 1 + MOD(J2-1+NXI,NXI)
              END IF
```
?

Is it just that your case you had the >2, so you focused on that, or is it that the ratio of difference is smaller so even without the wrapped interpolation of the points you don't see the line like you do in the case you showed in the issue.

**Comment by SanderHulst** [comment]
I did not consider the equal resolution case, but I don't think it will show the same behavior. The root cause is a negative index that is not folded. The code for MXA .NE 2 is:
```
            IF ( FLAGLL ) THEN
              IXC    = 1 + NINT ( MOD (                             &
                          1080.+X0+REAL(IX-1)*SX-X0I , 360. ) / SXI )
              IXS0   = IXC - 1 - MXA/2
              IXSN   = IXC + 1 + MXA/2
            ELSE
              IXC    = NINT ( 1. + ( X0+REAL(IX-1)*SX - X0I ) / SXI )
              IXS0   = MAX (  1  , IXC - 1 - MXA/2 )
              IXSN   = MIN ( NXI , IXC + 1 + MXA/2 )
            END IF
            DO J=IXS0, IXSN
              JJ=J
              IF ( FLAGLL ) THEN
                IF ( ICLOSE.NE.ICLOSE_NONE ) JJ = 1 + MOD(J-1+NXI,NXI)
                IF ( JJ.LT.1 .OR. JJ.GT. NXI ) CYCLE

```
The actual problem is in the do J=IXSO, IXSN loop that looks left and right of the cell center and causes J to be negative .

In the equal resolution case, J1 can not be negative because XR always lies between 1 and NX. Right?

**Comment by JessicaMeixner-NOAA** [comment]
@SanderHulst apologies on the super slow response.  I just took a look at this again, and you are correct we don't need anything for the other case.  I think this is good as is.  Thanks again for this update!

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Pull request merged**
