### PR TITLE
Fb port2hera

### PR DESCRIPTION
**Pull request by ajhenrique**
Branch FB_port2hera provides changes to make WW3 package run on Hera, the NCEP/NOAA R&D machine (replacing Theia). 

Includes 
* Several Hera updates for running WW3 under NEMS
* Adding hera port to w3_setup 
* Changes for porting regtest matrix to Hera in scripts matrix_ncep,  matrix.comp, run_test.

### CODE REVIEW

**Review by aliabdolali — APPROVED** [review]
@ajhenrique Bravo, You are good to go Henrique

**Comment by ajhenrique** [comment]
@aliabdolali @ukmo-ccbunney please review this PR. If approved, it will be merge after the ERDC pull request. The present PR adapts the package for running successfully on NCEP's new R&D machine Hera, including changes for NCEP's NEMS coupling. All NEMS tests and WW3 regtests completed successfully. However, a comparison with a previous baseline via matrix.comp is not possible. Let me know if you need more information to approve this request.

**Comment by ajhenrique** [comment]
@JessicaMeixner-NOAA please review the changes made for porting to the NCEP R&D machine both at the esmf and regtests capabilities. Thanks!

**Review by ukmo-ccbunney — APPROVED** [review]
All looks sensble to me @ajhenrique.
The only thing that I would say (and it is being a bit nit-picky) is that there is inconsistent use of the equality operators `=` and `==` in some of the `if` statements for cmplr.env. I think both work, but I believe for string comparison in bash `==` is the correct choice.

**Comment by JessicaMeixner-NOAA** [comment]
@ajhenrique  All the updates I made are in your commits now. 

I tried running NEMSfv3gfs and the fv3_wrtGauss_nemsio_c768 compset failed.  I can send an email with code and log file information if needed or if you have a branch that works I can test that?  I couldn't find a branch with WW3 porting to hera for NEMSfv3gfs so I just made my own local updates.

**Comment by ajhenrique** [comment]
> @ajhenrique All the updates I made are in your commits now.
> 
> I tried running NEMSfv3gfs and the fv3_wrtGauss_nemsio_c768 compset failed. I can send an email with code and log file information if needed or if you have a branch that works I can test that? I couldn't find a branch with WW3 porting to hera for NEMSfv3gfs so I just made my own local updates.

Hi @JessicaMeixner-NOAA , I've added a branch ww3_hera to the NEMSfv3gfs vlab repo. Please try that pointing to branch FB_port2hera and let me know if that works. Note that the compset may take longer than the 30 min walltime limit for compsets, that limit may need to be increased. Thanks.

**Comment by JessicaMeixner-NOAA** [comment]
@ajhenrique  I assume you have successfully run the ww3 tests on that branch, yes?

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by ajhenrique** [comment]
> @ajhenrique I assume you have successfully run the ww3 tests on that branch, yes?

@JessicaMeixner-NOAA  Pls check comment above: "[WW3 regtests completed successfully](https://github.com/NOAA-EMC/WW3/pull/107#issuecomment-536142060)". 

@ukmo-ccbunney I've made the use of the equality operator consistent in cmplr.env, thanks for pointing this out. I noticed there are more instances of inconsistent usage in other scripts that we will tackle in a separate cover.

In view of recent discussion offline, and thanks to approvals by @aliabdolali @JessicaMeixner-NOAA and @ukmo-ccbunney  I'll go ahead and merge this PR to develop and close.

**Pull request merged**
