### PR TITLE
Remove NetCDFv3 Support

### LINKED ISSUE #358: Remove support for NetCDF version 3
Currently, WW3 has two build options, either NetCDF version 3 or 4.  NetCDF version 4 was released in 2008.  At this time, we plan to remove options for NetCDF 3 in WW3. 

This work would be planned for the end of May 2021.

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
Remove NetCDFv3 Support

## Description
NetCDF v4.0 was released in 2008.  At this time, we are going to remove support for building with NetCDFv3.  There are still options within the NetCDF output routines for NCTYPE=3 or 4 however, the only build support will be for: WWATCH3_NETCDF=NC4.   

### Issue(s) addressed
- closes #358

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)? yes
* Reviewers: @aliabdolali @mickaelaccensi 

### Testing
* How were these changes tested? matrix
* Are the changes covered by regression tests? yes
* If a new feature was added, was a new regression test added? no
* Have regression tests been run? yes
* Which compiler / HPC you used to run the regression tests in the PR?  NCEP hera.intel 
* Please provide the summary output of matrix.comp (_matrix.Diff.out_, _matrixCompFull.out_ and _matrixCompSummary.out_):    
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/6638762/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/6638763/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/6638764/matrixDiff.txt)
Only the usual were not b4b.  This was tested before the last merge with develop.

### CODE REVIEW

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA with this commit, do we still need to set the following or we can embed them `setenv WWATCH3_NETCDF NC4` and `setenv NETCDF_CONFIG <path to nc-config>`?

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali there were no interface changes in how to set-up and run the model, we still set NETCDF_CONFIG <path to nc-config> and WWATCH3_NETCDF to NC4, if someone sets it to NC3, it should bail out (see line 407 of w3_make).  We could make another PR to remove the need for defining this.  I think if this is desired, we should remove it as a separate PR, if others disagree I can go ahead and remove it here.

**Comment by JessicaMeixner-NOAA** [comment]
To remove the dependence on defining WWATCH3_NETCDF, I believe the main issue would be in w3_make where we decide to compile the netcdf exes or not.  This could be changed to be triggered off of if NETCDF_CONFIG is defined or not instead: 

```
  if [ -z "$all_programs" ]
  then
    if [ -z "$WWATCH3_NETCDF" ]
    then
      all_programs="$reg_programs"
    else
      all_programs="$reg_programs $cdf_programs"
    fi
  fi
```

**Comment by aliabdolali** [comment]
The regtests ran successfully with know non-b4b tests

[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/6656532/matrixDiff.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/6656533/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/6656534/matrixCompFull.txt)

```
mww3_test_03
mww3_test_07
ww3_tp2.10
ww3_tp2.15
ww3_tp2.18
```

**Review by aliabdolali — APPROVED** [review]

**Review by mickaelaccensi — APPROVED** [review]
it's all good for me

**Pull request merged**
