### PR TITLE
SMC speedup

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
# Pull Request Summary
Added extra 1-dimension arrays with duplicated data for IJKUFc, IJKVFc, IJKCel, to make the data more contiguous, which can save memory bandwidth, achieve better performance.

These additions originally made by @Yun1Liu, see https://github.com/ukmo-waves/WW3/pull/30

@ukmo-jianguo-li and myself have reviewed the original code in the above PR.

## Description
The performance of SMC grid is limited by the memory bandwidth, because it needs to read
the 2-dimension arrays IJKUFc, IJKVFc, IJKCel many times.
In the loop, only 2 cells of the column (such as IJKCel(3,j), IJKCel(4,j)) are used,
the pre-fetch on the other cells is wasted.
So these arrays are kind of "AOS" (Array of Structure), I built some extra 1-dimension arrays
like "SOA" to make the data more contiguous, achieve better performance.

On the PRC NMEFC workloads, these changes can achieve 17% performance increase.

### Commit Message
Added extra 1-dimension SMC cells arrays with duplicated data to enable contiguous memory access.

### Check list  

- ✅ Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- ✅ Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [n/a] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [n/a] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? **Local tests, regression tests.**
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) **Yes.**
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? **Yes; Cray XC HPC, GNU Fortran**

### Matrix test results
SMC regression tests are identical.
All other tests are identical except usual known non-b4b tests.

Regression test matrix results to follow...

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@ukmo-ccbunney - 
 @aliabdolali is still on leave, so I'll be running the tests and do a review.  Please let me know if you'd like for merging to wait until Ali is back and can review as well.

**Comment by ukmo-ccbunney** [comment]
> @ukmo-ccbunney - @aliabdolali is still on leave, so I'll be running the tests and do a review. Please let me know if you'd like for merging to wait until Ali is back and can review as well.

Hi @JessicaMeixner-NOAA - apologies I forgot Ali was away.
Anyhow - please hold fire on this one: I have some errors with the multi-grid SMC regtests (mww3_teest_09). I will investigate and liaise with @ukmo-jianguo-li to get them fixed. Until then, I am switching this PR to draft.

**Comment by UKMO-lsampson** [comment]
I have been assigned to this PR by Chris, I have merged changes from an updated develop branch and reran the regression tests.

Here is a summary of the regtests output from matrixCompSummary.txt.

**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (11 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (9 files differ)
ww3_ta1/./work_UPD0F_U                     (0 files differ)
ww3_tp2.14/./work_OASACM6                     (1 files differ)

Further details are available here:
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/9072497/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/9072498/matrixDiff.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/9072499/matrixCompFull.txt)

Since the regtests have conformed, with the exception of the known B4B differences, I will suggest we change the PR from **draft** now once a review has been completed.

**Comment by ukmo-ccbunney** [comment]
The difference seen in `ww3_tp2.14/work_OASACM6` is due to an uninitialised variable and is covered in PR #737

**Review by aliabdolali — APPROVED** [review]

**Comment by aliabdolali** [comment]
The regtests passed successfully on NOAA RDHPC with pre-known non-4b4 cases.

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (17 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
```
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/9120909/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/9120910/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/9120911/matrixDiff.txt)

**Comment by ukmo-jianguo-li** [comment]
Congratulations to @YunLiu1 , @ukmo-ccbunney , @aliabdolali , @UKMO-lsampson , @JessicaMeixner-NOAA , and all others involved with this SMC grid improvement work.  Well done everyone!

**Pull request merged**
