### PR TITLE
Feature/nml

### PR DESCRIPTION
**Pull request by mickaelaccensi**
# Pull Request Summary
update all the nml files in regtests based on the automatic conversion bash scripts in model/tools/bash
only keep the header of each namelist 

## Description
all the bash scripts have been updated to correctly convert the inp files into nml files within regtest directory
a new feature was added to only add the header of each namelist in the nml file instead of providing all the default values of the variables, which was too hard to maintain and update.

fix issue #696 

### Commit Message
update all the nml files in regtests and keep only the header of each namelist

### Check list  

- [X] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [X] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [X] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [X] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? matrix_cmake_datarmor
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) yes
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? yes
* Please indicate the expected changes in the regression test output ([Note the known list of non-identical tests] (https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)). no changes if using inp files, only minor changes for ww3_tnc1 which use nml by default
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_) 
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/8629991/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/8629992/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/8629993/matrixDiff.txt)

### CODE REVIEW

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Assuming this passes regression tests, the changes look good to me and will be helpful in reducing the amount of changes as we move forward.  Thanks @mickaelaccensi

**Comment by mickaelaccensi** [comment]
@aliabdolali any news on this PR ?

**Comment by aliabdolali** [comment]
@mickaelaccensi I made a pr to this branch, to fix the failed regtests (it was related to regtests/bin/run_cmake_test). I also merge noaa/develop

**Comment by mickaelaccensi** [comment]
@aliabdolali it is merged

**Comment by aliabdolali** [comment]
the tests ran successfully on noaa hpc, with pre known non identical cases.
```

**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4                     (1 files differ)
ww3_tp2.6/./work_ST0                     (1 files differ)
ww3_ufs1.3/./work_a                     (2 files differ)
```

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/8730296/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/8730297/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/8730298/matrixDiff.txt)

**Review by aliabdolali — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali  (in reply to https://github.com/NOAA-EMC/WW3/pull/680#issuecomment-1133192249) there is no diffs with ww3_tnc1/./work (16 files differ) in this PR .  Are you referring to another one.  I do see evidence of the issue reported in #700 though (Not caused by this PR either).

**Comment by aliabdolali** [comment]
I need to check it next week.

**Pull request merged**
