### PR TITLE
UKMO staging [develop]

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
This **staging** branch is simply a branch from **develop** that is used to stage multiple PRs in the UKMO repo to facilitate a merge to the authoritative NOAA develop branch.

This staging branch contains changes from the follow UKMO PRs:
 - https://github.com/ukmo-waves/WW3/pull/6: boundary checks to the SMC input files for ww3_grid
 - https://github.com/ukmo-waves/WW3/pull/8: 360 day climate calendar
 - https://github.com/ukmo-waves/WW3/pull/9: Coupling time
 - https://github.com/ukmo-waves/WW3/pull/10: RTD support for ww3_boun[dc]

See the individual PRs for specific regtest output.

All tests compared as OK with the following expected differences:
- **all** tests are showing changes in `*mod_def*` and `*ww3_grid*out*` due to the addition of the `calendar` option https://github.com/ukmo-waves/WW3/pull/8.
- the `ww3_tp2.14` tests are showing a difference in`TOY_OUTPUT.txt` (extra line saying `APPLE Partitioning`); this line was originally output randomly (processor dependant), but is now always output.
- `ww3_tp2.18/work_TIDE_MPI/ww3_prtide_current.out_diff.txt` shows lots of differences - this is a known issue (see #225)
- The usual differences with `mww3_test_03`

The complete regtest suite output is provided in the attached zip file: [matrixComp.zip](https://github.com/NOAA-EMC/WW3/files/5001977/matrixComp.zip)

### CODE REVIEW

**Comment by aliabdolali** [comment]
Hi @ukmo-ccbunney and team,
Thanks for doing this great enhancement and fixes.
I ran the matrix on noaa hpc as a double check and noticed a couple of things.
As you reported, all mod_def* are not identical as expected, mww3_test_03 and ww3_tp2.18 carry the known issue.
See the matix.comp outputs [matrix_diff_ncep.zip](https://github.com/NOAA-EMC/WW3/files/5009687/matrix_diff_ncep.zip)

Here I have a question and one comment:
1. I could not run the following tests:

```
./bin/run_test -b slurm -c hera -S -T -s OASACM -w work_OASACM -C OASIS -f -p mpirun -n 24 -o netcdf ../model ww3_tp2.14
./bin/run_test -b slurm -c hera -S -T -s OASACM2 -w work_OASACM2 -C OASIS -f -p mpirun -n 24 -o netcdf ../model ww3_tp2.14
./bin/run_test -b slurm -c hera -S -T -s OASOCM -w work_OASOCM -C OASIS -f -p mpirun -n 24 -o netcdf ../model ww3_tp2.14
./bin/run_test -b slurm -c hera -S -T -s OASICM -w work_OASICM -C OASIS -f -p mpirun -n 24 -o netcdf ../model ww3_tp2.14
```
Do I need to do sth on our hpc for coupling or I cannot test the COU OASIS OASACM switches?
2. We have two miles stones for your developments, please modify the header accordingly for version 7.10 (coupled model) and 7.11 (rotated grid).

Other than that, I am quite happy with all the changes.
Regards,
AA

**Comment by chrisbunney** [comment]
@ukmo-juan-castillo Are you able to answer Ali's question above in my absence? It is regarding running the `ww3_tp2.14` regtest.

**Comment by ukmo-juan-castillo** [comment]
What is the error you receive when running the ww3_tp2.14 test? It is probably something to do with netcdf or other libraries.

**Comment by aliabdolali** [comment]
Hi @ukmo-juan-castillo 
Those tests did not run because of `-C OASIS` so I thought we need to have this coupling option on our HPC.
AA

**Comment by ukmo-juan-castillo** [comment]
In matrix.base the -C OASIS option is added to all the ww3_tp2.14 tests. This test should compile the oasis library and link it properly to the executables that require it. If this is not happening then there is something in the ncep matrix file that needs updating. Did you set oasis=y in your matrix file to run the ww3_tp2.14 tests, and if you did, did you receive any error message?

**Comment by aliabdolali** [comment]
Hi @ukmo-juan-castillo 
Yes, I set `oasis='y'`
in matrix_ncep, we define the cmplr=hera, therefore the command line is
`./bin/run_test -b slurm -c hera -S -T -s OASICM -w work_OASICM -C OASIS -f -p mpirun -n 24 -o netcdf ../model ww3_tp2.14`
it comes with the following error:
`ERROR: cmplr.hera not found`

if I change cmplr=intel, then it ran fine, but the rest of matrix is broken.

**Comment by ukmo-juan-castillo** [comment]
Could you try to add the hera compiler to the list of accepted compilers in the script:

regtests/ww3_tp2.14/input/prep_env.sh 

and try again?

https://github.com/ukmo-waves/WW3/blob/5c361aaf3085bb5ac04931493b9c1eae1c15b5d9/regtests/ww3_tp2.14/input/prep_env.sh#L29-L42

**Comment by aliabdolali** [comment]
Thanks, @ukmo-juan-castillo 
Now it is running fine.
There is one last issue:
`cp: cannot stat ‘../input/r-ww3.nc.OASACM2’: No such file or **directory`
Could you add it?

Also, have you  updated the headers following milestones:
version 7.10 (coupled model) and 7.11 (rotated grid).

**Comment by ukmo-juan-castillo** [comment]
You can copy the r-ww3.nc.OASACM file, it should be the same. The script ww3_from_ftp.sh should be copying it to the right place. In fact, most of the OASACM and OASACM2 files required are the same.

**Pull request closed without merging**
