### PR TITLE
Add switch ifdefs for wmesmf SCRIP

### LINKED ISSUE #505: No rule to make target obj/wmscrpmd.o needed by obj/wmesmfmd.o
**Describe the bug**
I'm trying to build WW3 and I'm getting this error: 

```
Processing ww3_multi_esmf
---------------------
No rule to make target obj/wmscrpmd.o needed by obj/wmesmfmd.o
```

Looking at this line:

https://github.com/NOAA-EMC/WW3/blob/dd317947d14e06cb4bc713f53197e194f5e88a65/model/bin/build_utils.sh#L858

Do I need to have `SCRIP` set or something so that wmscrpmd is added to the list of files?

Or should I not be building with ESMF at all?

**To Reproduce**
I run:

```
./model/bin/w3_setup model -c gnu -s NCEP_st4
cd model/bin
./w3_make
```

**Additional context**
Running on macOS using GNU 9.4.0 with the following modules:

```
Currently Loaded Modules:
  1) hpc/1.2.0       3) mpich/3.4.2       5) g2/3.4.3        7) png/1.6.35    9) netcdf/4.7.4  11) w3nco/2.4.1
  2) hpc-gnu/9.4.0   4) hpc-mpich/3.4.2   6) jasper/2.0.25   8) hdf5/1.10.6  10) bacio/2.4.1   12) esmf/8_2_0_beta_snapshot_14-debug
```

### LINKED ISSUE #506: wmesmf needs SCRIP/SCRIPNC CPP ifdefs added
**Describe the bug**
wmesmf has recently had calls to SCRIP/SCRIPNC subroutines but the SCRIP/SCRIPNC switch files were not added.  These calls need to be added behind the SCRIP/SCRIPNC switch file calls.  Additionally if a check should be added to ensure the SCRIP/SCRIPNC switch is used to complete the new parts of wmesmf and abort otherwise.  I believe these are the new features added for HAFS. 

**To Reproduce**
Try to compile wmesmf without SCRIP/SCRIPNC flag. 

**Expected behavior**
We should be able to compile wmesmf without SCRIP/SCIPNC switch - and/or we should add appropriate checks in the check switches routine in build_utils.sh. 

FYI @uturuncoglu @aliabdolali @kgerheiser

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
Adding switch ifdefs for scrip in wmesmf

## Description
When the addition of corner points was added, we used scrip subroutines but did not add the switch ifdefs.  These add the ifdefs.  There is no expected answer changes for this, but it should solve the issues of compiling wmesmf without the SCRIP switch. 

### Issue(s) addressed
- fixes #505
- fixes #506

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)? yes
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) no version number increase
* Please list appropriate labels code managers should add for this PR:   
 _bug_
 
* Reviewers: @aliabdolali @uturuncoglu 

### Commit Message
* Add SCRIP ifdefs for wmesmf 

### Testing
* How were these changes tested? These were tested in the ufs-weather-model control_atmwav test which does not require the SCRIP switch.  The SCRIP and SCRIPNC were removed from the switch file and the test with these if-defs still succeeded.  (Note, to run successfully also had to fix some warnings in a print statement, but I'll push those changes via a separate PR as they're unrelated to the issues here.) 
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) No, we do not test wmesmf within the ww3 standalone regtests
* If a new feature was added, was a new regression test added? no new feature
* Have regression tests been run? no, as the regtests do not cover this routine. 
* Which compiler / HPC you used to run the regression tests in the PR? 
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):    
Please indicate the expected changes in the outputs ([excluding the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)).
* Please list which labels code managers should add to indicate code changes:    
No code changes.

### CODE REVIEW

**Review by aliabdolali — COMMENTED** [review]
I know this was raised for the CMake build and ww3_multi _esmf. Did you test the ufs-weather-model with the changes? considering SCRIP is in the switch, it might be unnecessary.

**Comment by JessicaMeixner-NOAA** [comment]
I only tested in ufs-weather-model on a test that I knew did not use SCRIP and I removed SCRIP and SCRIPNC.  As reported in the PR, this test succeeded.  I did not run a full test in ufs-weather-model without changes.  I can do that now.

**Comment by aliabdolali** [comment]
> I only tested in ufs-weather-model on a test that I knew did not use SCRIP and I removed SCRIP and SCRIPNC. As reported in the PR, this test succeeded. I did not run a full test in ufs-weather-model without changes. I can do that now.

that would be great, then we can proceed with the merge once WW3 regtests outputs are ready (tonight)

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali I ran ufs-weather-model with the wrong WW3 branch, so I'll have to re-do these tests today. I'll post results when I have them.

**Comment by aliabdolali** [comment]
I have the following changes:

**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
mww3_test_05/./work_ST4_PR2_UNO_OMP                     (1 files differ)
mww3_test_05/./work_ST2_PR3_UQ_MPI                     (11 files differ)
mww3_test_05/./work_ST4_PR3_UQ_OMP                     (1 files differ)
mww3_test_05/./work_ST4_PR2_UQ_OMP                     (1 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (6 files differ)
ww3_ts1/./work_ST4_TSA                     (3 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)

I need to do further analysis, something is wrong. I'll let you know.

**Comment by JessicaMeixner-NOAA** [comment]
That is indeed strange as the regression tests should have no impact with this change.  I'll run some tests too.

**Comment by aliabdolali** [comment]
Here are the outputs of my comparison, with just pre-known not b4b cases

*```
*********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (13 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (7 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (5 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
```


[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7565406/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7565407/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7565408/matrixDiff.txt)
s

**Review by aliabdolali — APPROVED** [review]
We can merge it once the ufs-weather-model passed

**Comment by JessicaMeixner-NOAA** [comment]
Okay- the ufs-weather-model waves tests run on hera: /scratch2/NCEPDEV/climate/Jessica.Meixner/PR_WW3/scrip/ufs-weather-model/tests/RegressionTests_hera.intel.log (I tried to copy it here but my hera window is temporarily acting up and I couldn't get the transfer to work).     They even work without the other fix if you don't have "error" int he directory name that will trigger warning messages as errors (oops).

**Pull request merged**
