### PR TITLE
Bug fixes for thread in w3_new and initializing variables

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
Various bug fixes discovered while working on PR #285  

## Description
Bug fixes include: 
* Adding routines in w3_new for threading.  This seems to fix some failures for ww3_ts3 that occurred in testing 285 
* Added a few missing files to .gitignore
* Initialized GA0,GAN,GD0,GDN to zero.  While some compilers (and combo of switch options) automatically initialized this to zero without issue, MPI_OMPH for ww3_ts3 cases when testing 285 did not.  This seems to fix the issues there, however is a bug in the develop branch not in the updates in 285. 

### Issue(s) addressed
* No issues were created for any of these issues.  All issues were discovered while debugging the other PR.  

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)? Yes
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop), [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number): No need for version update 

### Testing
* How were these changes tested? Regression tests on ncep hera.intel are in the queue now 
* Are the changes covered by regression tests? yes/no.  All are bug fixes 
* If a new feature was added, was a new regression test added? Just bugs, no new features. 
* Have regression tests been run? Running right now on NCEP hera.intel 
* Which compiler / HPC you used to run the regression tests in the PR? 
* Please provide the summary output of matrix.comp (_matrix.Diff.out_, _matrixCompFull.out_ and _matrixCompSummary.out_):    will be attached when finished. 
Please indicate the expected changes in the outputs ([excluding the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)): 
No changes are expected.

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
no errors in the regression tests, comparison is still running.  @aliabdolali they are /scratch2/NCEPDEV/climate/Jessica.Meixner/PR_WW3/PRbugs/WW3/regtests in case you need this before I get a chance to post them myself

**Comment by ukmo-juan-castillo** [comment]
The changes seem sensible to me. I will leave Chris to run some tests on the Met Office computer.

**Review by ukmo-juan-castillo — APPROVED** [review]

**Comment by ukmo-ccbunney** [comment]
Thanks @JessicaMeixner-NOAA  - changes look good to me. Well done on finding those uninitialised variables.
I will run the regression tests here and post the results.

**Review by aliabdolali — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
Only the usual tests that are not b4b on NCEP computers were different.  Log files: 
[matrixCompFull.out.txt](https://github.com/NOAA-EMC/WW3/files/6472834/matrixCompFull.out.txt)
[matrixDiff.out.txt](https://github.com/NOAA-EMC/WW3/files/6472843/matrixDiff.out.txt)
[matrixCompSummary.out.txt](https://github.com/NOAA-EMC/WW3/files/6472837/matrixCompSummary.out.txt)

**Comment by ukmo-ccbunney** [comment]
Just for completeness, I can confirm that the regtest all passed OK here with the usual exceptions:


```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UQ_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (7 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (10 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (9 files differ)
ww3_tp2.18/./work_TIDE_MPI                     (1 files differ)

```

**Review by ukmo-ccbunney — APPROVED** [review]

**Review by aliabdolali — APPROVED** [review]
It looks good to me after running the regtests and reviewing the code changes.

**Comment by aliabdolali** [comment]
See the matrix.comp
I ran the matrix on hera using intel and impi
[DIFF.zip](https://github.com/NOAA-EMC/WW3/files/6476186/DIFF.zip)
The expected non-b4b tests are:
mww3_test_03; mww3_test_07; ww3_tp2.10;ww3_tp2.15; ww3_tp2.18

**Pull request merged**
