### PR TITLE
Add ESMF profile memory statements 

### LINKED ISSUE #450: Add Memory Profiling statements to wmesmf
**Description** 
Need to add ESMF memory profiling statements to WW3 NUOPC cap (wmesmf).  

**Describe the solution you'd like**
Follow similar statements (and option variable name) as in FV3GFS or MOM6's NUOPC Cap.

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
This adds ESMF profile memory statements in the ESMF cap 

## Description
This uses ESMF calls to optionally add memory profiling information.  To turn-on this feature in UFS, in the nems.configure file under the waves section set ProfileMemory to true. 

Author: @DeniseWorthen 

### Issue(s) addressed

- closes #450 

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)? yes
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number): none needed 
* Please list appropriate labels code managers should add for this PR:   
 _new feature_, ..
 
* Reviewers: @aliabdolali 

### Commit Message
* Add ESMF Memory profiling in wmesmf

### Testing
* How were these changes tested? With ufs-weather-model S2SW tests within ufs-weather-model pr 790
* Are the changes covered by regression tests? By ufs-weather-model tests
* If a new feature was added, was a new regression test added? no
* Have regression tests been run? WW3 standalone reg tests were not run as only wmesmf was updated and this is not currently tested with standalone WW3 tests. 
* Which compiler / HPC you used to run the regression tests in the PR?  ufs-weather-model PR #790 hera.intel 
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):     not run 
Please indicate the expected changes in the outputs ([excluding the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)).  none, only changes in wmesmf 
* Please list which labels code managers should add to indicate code changes:     none

### CODE REVIEW

**Review by DeniseWorthen — APPROVED** [review]

**Review by aliabdolali — APPROVED** [review]
It looks ok to me. I will run the tests for it.

**Comment by aliabdolali** [comment]
The tests ran successfully with pre-known non-b4b cases
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (7 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
 

[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7178687/matrixDiff.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7178689/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7178690/matrixCompFull.txt)

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali  -- since the WW3 standalone regression tests do not test wmesmfmd, it's good that nothing changed.  I've run the ufs-weather-model tests before submitting the code for review, but that's the more important tests here, right?  Have you run those?

**Comment by aliabdolali** [comment]
> @aliabdolali -- since the WW3 standalone regression tests do not test wmesmfmd, it's good that nothing changed. I've run the ufs-weather-model tests before submitting the code for review, but that's the more important tests here, right? Have you run those?

It is running now, thanks for the hint.

**Comment by aliabdolali** [comment]
The ufs-weather-model also passed successfully.

**Pull request merged**
