### PR TITLE
Feature/scalefac

### PR DESCRIPTION
**Pull request by mickaelaccensi**
# Pull Request Summary
add functionality to :
- read compressed 2D spectra as netcdf in ww3_bounc
- create compress 2D spectra as netcdf with ww3_ounp

## Description
the compression is similar to what is already done to compress the wave spectrum in ww3_ounf 
which means compressing the variable as SHORT and applying a log10 factor with an offset of 1E-12
This done by setting the value 4 for the netCDF spectra variable type in ww3_ounp.inp as described below : 
```
$ -------------------------------------------------------------------- $
$ ITYPE = 1, netCDF Spectra.
$          - Sub-type OTYPE :  1 : Print plots.
$                              2 : Table of 1-D spectra
$                              3 : Transfer file.
$                              4 : Spectral partitioning.
$          - Scaling factors for 1-D and 2-D spectra Negative factor
$            disables, output, factor = 0. gives normalized spectrum.
$          - Netcdf variable type [2=SHORT, 3=it depends, 4=REAL]
$
  3  1  0  4
```
or in ww3_ounp.nml : 

```
!     SPECTRA%TYPE          = 4            ! [2 = SHORT, 3 = it depends , 4 = REAL]
! -------------------------------------------------------------------- !
&SPECTRA_NML
    SPECTRA%TYPE          = 4
/
```

### Issue(s) addressed
fix issue #466 

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)? YES
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) OK
* Please list appropriate labels code managers should add for this PR:   
_new feature_
 
* Reviewers: @thesser1 @aliabdolali 

### Commit Message
2D spectra compression in WW3 input (ww3_bounc) and output (ww3_ounp)

### Testing
* How were these changes tested? 
  running ww3_tp1.11 with input (uncompress spectrum) in work1
  running ww3_tp1.11 with input2 (compressed spectrum) in work2
  then uncompress result file from work2 to compare it against work1 : 
   cd work2
   ncpdq -O -U ww3.Point1_196806_spec.nc ww3.Point1_196806_spec.nc
   ncap2 -O -s 'efth=pow(10,efth)-1E-12'   ww3.Point1_196806_spec.nc ww3.Point1_196806_spec.nc 
   ncview ww3.Point1_196806_spec.nc
   ncview ../work1/ww3.Point1_196806_spec.nc
* Are the changes covered by regression tests? no, new test added in matrix.base
* If a new feature was added, was a new regression test added? ww3_tp1.11 using input2
* Have regression tests been run? ON GOING
* Which compiler / HPC you used to run the regression tests in the PR? INTEL
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):    
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7197911/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7197912/matrixCompFull.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7197913/matrixDiff.txt)

changed are only related to character format in ww3_ounp*.out

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Should we create a new label and add it to this that "input file changes"?

**Comment by mickaelaccensi** [comment]
> Should we create a new label and add it to this that "input file changes"?

it would be a good idea

**Comment by JessicaMeixner-NOAA** [comment]
> > Should we create a new label and add it to this that "input file changes"?
> 
> it would be a good idea

@mickaelaccensi it might also be helpful to describe in the text of the PR about how the input files change.

**Comment by mickaelaccensi** [comment]
> > > Should we create a new label and add it to this that "input file changes"?
> > 
> > 
> > it would be a good idea
> 
> @mickaelaccensi it might also be helpful to describe in the text of the PR about how the input files change.

done

**Comment by aliabdolali** [comment]
@mickaelaccensi is it ready to be reviewed and tested?

**Comment by mickaelaccensi** [comment]
> @mickaelaccensi is it ready to be reviewed and tested?

yes it's ready to be merged, I've added the matrix output in the PR message

**Comment by aliabdolali** [comment]
Here is the summary of matrix on our hpc with intel, impi (Hera):

**known non-b4b:**
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (7 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (7 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
**Expected changes:**
ww3_tic1.4/./work_IC2IS2_IC2b                     (2 files differ)
ww3_tic1.4/./work_IC1IS2_1000                     (2 files differ)
ww3_tic1.4/./work_IC2IS2_IC2d                     (2 files differ)
ww3_tic1.4/./work_IC0IS2_1000                     (2 files differ)
ww3_ufs1.1/./work_b                     (1 files differ)
ww3_ufs1.1/./work_a                     (1 files differ)
ww3_ufs1.1/./work_a_nth                     (1 files differ)
ww3_ufs1.1/./work_a_npl                     (1 files differ)
ww3_ufs1.2/./work_b                     (1 files differ)
ww3_ufs1.2/./work_a                     (1 files differ)
ww3_ufs1.3/./work_a                     (2 files differ)

The changes are in ww3_ounp log, for example:
<   Processing time : 20120103  180000 in        1files. Step          1out of       1000 pass    1
>Processing time : 20120103  180000 in        1files. Step    1out of 1000pass    1

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7211820/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7211821/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7211822/matrixDiff.txt)

@mickaelaccensi can you confirm?

**Comment by mickaelaccensi** [comment]
yes I confirm that the changes are about what you have shown

**Review by aliabdolali — APPROVED** [review]
it looks ok to me.

**Pull request merged**
