### PR TITLE
Update ww3_ounp.F90

### PR DESCRIPTION
**Pull request by Biao-Zhao**
I conduct a numerical experiment using Cartesian grid and output spectrum at some points. I found  that  the units attribute  of variables "X" and "Y"  in netcdf files are meter. In fact, it should be 'km'  according to the  values I set in namelist file.

# Pull Request Summary
 

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
Hi @Biao-Zhao, could you describe more what you're doing and what you expect?  I haven't been aware of an issue with ww3_ounp.F90 in my use of it, but I admittedly I don't have as extensive of a background as some others may.  If other's with more experience, please chime in.

From what I know though, values like those hard-coded into ww3_ounp.F90 should follow some standard, and input files (like namelists) should adhere to the standard decided on.  What is in ww3_ounp.F90 for X/Y is meters, and is default "mks" units.  So without other knowledge, I believe these are the units that X/Y should stay in.  I would suggest making changes in the namelist file that account for what is in ww3_ounp.F90.  Does that all make sense?  Or did I misunderstand your intent?

**Comment by MatthewMasarik-NOAA** [comment]
Hi @Biao-Zhao, I wanted to check back with you on this PR to see if you have any comments, and if you still want to keep this PR active?  I'll keep it open till the end of the week, then close it if there's no more activity.  You'll be able to re-open though, if you change your mind.  Thank you.  Cheers

**Comment by Biao-Zhao** [comment]
Hi @MatthewMasarik-NOAA . sorry for my late reply. I didn't notice your comments. Here is my situation.  I have conducted  numerical experiments using Cartesian coordinate.  my ww3_grid.inp are listed below:



And here is  my ww3_shel.inp file:


Following is my ww3_ounp.inp file:


So, If you look at my ww3_grid.inp file, you will find that in my case the model domain covers a 601 by 201 rectangle grid with resolution of 1 meter. And from my ww3_shel.inp file,  you will find that the model will output the wave spectrum at x=62, 112, 162, 212, 313 and 412 meters along y=100 meters. After executing  ww3_output,  I got the netcdf file with following variables:



From the above snapshots, we can see the units of variables "x" and "y" is "m", which was absolutely not right.  I have checked all the variables out in netcdf file.  It seems that everything is reasonable (wave spectrum, mean wave direction and significant wave height, etc.) except the units of "x" and "y". This implies there is no problem with the setup of namelist file.  Really hope my explanation will help. If you have any questions or comments, please feel free to contact me.  

Cheers 
Biao

**Comment by MatthewMasarik-NOAA** [comment]
Hi @Biao-Zhao, thank you for the details.  Let me look a little closer today and I'll reply back this afternoon.

**Comment by MatthewMasarik-NOAA** [comment]
Hmm.  I'm probably going to need to need someone from the community that has a longer history with WW3 to chime in here.  I can follow your set up, and can see the `x` values at a factor of 10^-3 from your input values, though all the documentation in ww3_grid.inp is pointing towards the values being meters for a Cartesian grid (in particular here it emphasizes that it is meters and not kilometers, https://github.com/NOAA-EMC/WW3/blob/8eb35962c396267b56d569ef32a27be0d5bb1657/model/inp/ww3_grid.inp#L644). 

Could someone from the community chime in here?

**Comment by ukmo-ccbunney** [comment]
Hi @Biao-Zhao 

So you are correct - although the wave model domain is defined in metres when using Cartesian coordinates, the `x` and `y` variables are output in units of kilometres from `ww3_ounp`

See this line in `ww3_ounp.ftn` that writes the `x` coordinate:
https://github.com/NOAA-EMC/WW3/blob/8eb35962c396267b56d569ef32a27be0d5bb1657/model/src/ww3_ounp.F90#L1823

Here the point location (PTLOC) is scaled by `M2KM` (=1e-3) to convert to km. 

However, as you have pointed out, this is indeed contrary to what the stated units here!
https://github.com/NOAA-EMC/WW3/blob/8eb35962c396267b56d569ef32a27be0d5bb1657/model/src/ww3_ounp.F90#L3208-L3211

So, I can confirm that the output units for variables `x` and `y` in Cartesian coordinates is "km" and the unit in the netCDF meta-data is incorrect.

I agree that the units attribute should be changed to "km".

**Review by ukmo-ccbunney — APPROVED** [review]
Looks like a typo!
Values are indeed in km (see my comment).

**Comment by MatthewMasarik-NOAA** [comment]
@ukmo-ccbunney, thank you very much for confirming the units as @Biao-Zhao found.  I'll do a check to confirm the updated output is as expected, and proceed with the review.

**Comment by Biao-Zhao** [comment]
Yep. it is a typo.  and  thank you two guys @MatthewMasarik-NOAA @ukmo-ccbunney for  checking this. Have a nice day!

**Comment by MatthewMasarik-NOAA** [comment]
Update:  the tests came back and there are a _lot_ of differences, which I somewhat expected for the file attribute change.  To help with sorting through the results I just submitted another set of tests with the PR branch, so I can use the matrix.comp script to compare against itself and weed those out.  Thanks for your patience @Biao-Zhao, this will be ready to wrap up tomorrow morning.

**Comment by ukmo-ccbunney** [comment]
> Update: the tests came back and there are a _lot_ of differences, which I somewhat expected for the file attribute change. To help with sorting through the results I just submitted another set of tests with the PR branch, so I can use the matrix.comp script to compare against itself and weed those out. Thanks for your patience @Biao-Zhao, this will be ready to wrap up tomorrow morning.

Hopefully the differences are all just in the spectral oupput netCDF files?

**Comment by MatthewMasarik-NOAA** [comment]
> > Update: the tests came back and there are a _lot_ of differences, which I somewhat expected for the file attribute change. To help with sorting through the results I just submitted another set of tests with the PR branch, so I can use the matrix.comp script to compare against itself and weed those out. Thanks for your patience @Biao-Zhao, this will be ready to wrap up tomorrow morning.
> 
> Hopefully the differences are all just in the spectral oupput netCDF files?

Yes, from a quick look they all appear to be that.  I'm assuming they all will be, I'm being a little lazy on checking each manually ;-)

**Review by MatthewMasarik-NOAA — APPROVED** [review]
#### Code review
Pass

#### Testing
Pass

**matrix.comp:  vs. develop branch**
The unexpected differences here are due to the attribute change of `x/y` units in netcdf output from `m` to `km`. 

[vs.develop.matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/13242660/vs.develop.matrixCompSummary.txt)
[vs.develop.matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/13242661/vs.develop.matrixCompFull.txt)
[vs.develop.matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/13242659/vs.develop.matrixDiff.txt)

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_01/./work_PR2_UNO                     (1 files differ)
mww3_test_01/./work_PR1_MPI                     (1 files differ)
mww3_test_01/./work_PR3_UNO_MPI                     (1 files differ)
mww3_test_01/./work_PR3_UQ                     (1 files differ)
mww3_test_01/./work_PR3_UNO                     (1 files differ)
mww3_test_01/./work_PR1                     (1 files differ)
mww3_test_01/./work_PR2_UQ                     (1 files differ)
mww3_test_01/./work_PR2_UQ_MPI                     (1 files differ)
mww3_test_01/./work_PR3_UQ_MPI                     (1 files differ)
mww3_test_01/./work_PR2_UNO_MPI                     (1 files differ)
mww3_test_02/./work_PR1_c                     (1 files differ)
mww3_test_02/./work_PR2_UNO_c                     (1 files differ)
mww3_test_02/./work_PR3_UQ_MPI_a                     (1 files differ)
mww3_test_02/./work_PR1_MPI_d                     (1 files differ)
mww3_test_02/./work_PR3_UNO_MPI_b_c                     (1 files differ)
mww3_test_02/./work_PR3_UQ_MPI_c                     (1 files differ)
mww3_test_02/./work_PR2_UNO_MPI_d                     (1 files differ)
mww3_test_02/./work_PR2_UNO_d                     (1 files differ)
mww3_test_02/./work_PR2_UQ_MPI_a                     (1 files differ)
mww3_test_02/./work_PR3_UQ_MPI_a_c                     (1 files differ)
mww3_test_02/./work_PR3_UNO_MPI_d_c                     (1 files differ)
mww3_test_02/./work_PR1_d                     (1 files differ)
mww3_test_02/./work_PR2_UQ_c                     (1 files differ)
mww3_test_02/./work_PR3_UQ_b                     (1 files differ)
mww3_test_02/./work_PR3_UQ_a                     (1 files differ)
mww3_test_02/./work_PR1_a                     (1 files differ)
mww3_test_02/./work_PR3_UNO_MPI_d                     (1 files differ)
mww3_test_02/./work_PR3_UNO_a_c                     (1 files differ)
mww3_test_02/./work_PR2_UQ_MPI_b                     (1 files differ)
mww3_test_02/./work_PR3_UNO_d                     (1 files differ)
mww3_test_02/./work_PR3_UNO_MPI_a_c                     (1 files differ)
mww3_test_02/./work_PR2_UQ_a                     (1 files differ)
mww3_test_02/./work_PR3_UNO_MPI_b                     (1 files differ)
mww3_test_02/./work_PR3_UNO_b_c                     (1 files differ)
mww3_test_02/./work_PR1_b                     (1 files differ)
mww3_test_02/./work_PR2_UNO_b                     (1 files differ)
mww3_test_02/./work_PR2_UQ_d                     (1 files differ)
mww3_test_02/./work_PR3_UQ_c                     (1 files differ)
mww3_test_02/./work_PR3_UNO_MPI_a                     (1 files differ)
mww3_test_02/./work_PR1_MPI_c                     (1 files differ)
mww3_test_02/./work_PR3_UNO_b                     (1 files differ)
mww3_test_02/./work_PR1_MPI_b                     (1 files differ)
mww3_test_02/./work_PR3_UQ_a_c                     (1 files differ)
mww3_test_02/./work_PR3_UQ_MPI_b_c                     (1 files differ)
mww3_test_02/./work_PR3_UQ_d_c                     (1 files differ)
mww3_test_02/./work_PR1_MPI_a                     (1 files differ)
mww3_test_02/./work_PR3_UQ_MPI_d_c                     (1 files differ)
mww3_test_02/./work_PR3_UQ_MPI_d                     (1 files differ)
mww3_test_02/./work_PR3_UQ_d                     (1 files differ)
mww3_test_02/./work_PR3_UNO_d_c                     (1 files differ)
mww3_test_02/./work_PR2_UNO_MPI_b                     (1 files differ)
mww3_test_02/./work_PR3_UNO_MPI_c                     (1 files differ)
mww3_test_02/./work_PR2_UQ_b                     (1 files differ)
mww3_test_02/./work_PR3_UNO_c                     (1 files differ)
mww3_test_02/./work_PR3_UNO_a                     (1 files differ)
mww3_test_02/./work_PR2_UQ_MPI_d                     (1 files differ)
mww3_test_02/./work_PR2_UQ_MPI_c                     (1 files differ)
mww3_test_02/./work_PR2_UNO_a                     (1 files differ)
mww3_test_02/./work_PR2_UNO_MPI_c                     (1 files differ)
mww3_test_02/./work_PR2_UNO_MPI_a                     (1 files differ)
mww3_test_02/./work_PR3_UQ_b_c                     (1 files differ)
mww3_test_02/./work_PR3_UQ_MPI_b                     (1 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR1_c                     (1 files differ)
mww3_test_03/./work_PR2_UNO_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_a                     (1 files differ)
mww3_test_03/./work_PR1_MPI_d                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_b_c                     (1 files differ)
mww3_test_03/./work_PR2_UQ_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_c_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_c                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d                     (1 files differ)
mww3_test_03/./work_PR2_UNO_d                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_a                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_a_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d_c                     (1 files differ)
mww3_test_03/./work_PR1_d                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_c                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_b                     (1 files differ)
mww3_test_03/./work_PR3_UQ_a                     (1 files differ)
mww3_test_03/./work_PR1_a                     (1 files differ)
mww3_test_03/./work_PR3_UQ_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (2 files differ)
mww3_test_03/./work_PR3_UQ_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_a_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_b                     (1 files differ)
mww3_test_03/./work_PR3_UNO_d                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_c_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_a_c                     (1 files differ)
mww3_test_03/./work_PR2_UQ_a                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_b                     (1 files differ)
mww3_test_03/./work_PR3_UNO_b_c                     (1 files differ)
mww3_test_03/./work_PR1_b                     (1 files differ)
mww3_test_03/./work_PR2_UNO_b                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_c_c                     (1 files differ)
mww3_test_03/./work_PR2_UQ_d                     (1 files differ)
mww3_test_03/./work_PR3_UQ_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_a                     (1 files differ)
mww3_test_03/./work_PR1_MPI_c                     (1 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_b                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR1_MPI_b                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UQ_a_c                     (1 files differ)
mww3_test_03/./work_PR2_UNO_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_b_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_d_c                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR1_MPI_a                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d                     (1 files differ)
mww3_test_03/./work_PR1_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_d                     (1 files differ)
mww3_test_03/./work_PR3_UNO_d_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_c_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_b                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_c                     (1 files differ)
mww3_test_03/./work_PR2_UQ_b                     (1 files differ)
mww3_test_03/./work_PR3_UNO_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_a                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (2 files differ)
mww3_test_03/./work_PR2_UQ_MPI_c                     (1 files differ)
mww3_test_03/./work_PR2_UNO_a                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_c                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_a                     (1 files differ)
mww3_test_03/./work_PR3_UQ_b_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_b                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (14 files differ)
mww3_test_04/./work_PR1_MPI_e                     (1 files differ)
mww3_test_04/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_04/./work_PR3_UQ_g                     (1 files differ)
mww3_test_04/./work_PR1_MPI_d                     (1 files differ)
mww3_test_04/./work_PR2_UQ_f                     (1 files differ)
mww3_test_04/./work_PR3_UNO_MPI_b_c                     (1 files differ)
mww3_test_04/./work_PR3_UQ_MPI_c                     (1 files differ)
mww3_test_04/./work_PR2_UNO_MPI_d                     (1 files differ)
mww3_test_04/./work_PR3_UNO_g                     (1 files differ)
mww3_test_04/./work_PR3_UNO_MPI_d_c                     (1 files differ)
mww3_test_04/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_04/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_04/./work_PR3_UQ_b                     (1 files differ)
mww3_test_04/./work_PR3_UQ_a                     (1 files differ)
mww3_test_04/./work_PR1_a                     (1 files differ)
mww3_test_04/./work_PR3_UNO_g_c                     (1 files differ)
mww3_test_04/./work_PR3_UNO_MPI_d                     (1 files differ)
mww3_test_04/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_04/./work_PR3_UNO_a_c                     (1 files differ)
mww3_test_04/./work_PR2_UQ_MPI_b                     (1 files differ)
mww3_test_04/./work_PR3_UNO_MPI_c_c                     (1 files differ)
mww3_test_04/./work_PR2_UQ_a                     (1 files differ)
mww3_test_04/./work_PR2_UNO_f                     (1 files differ)
mww3_test_04/./work_PR3_UNO_MPI_b                     (1 files differ)
mww3_test_04/./work_PR3_UNO_b_c                     (1 files differ)
mww3_test_04/./work_PR1_b                     (1 files differ)
mww3_test_04/./work_PR2_UNO_b                     (1 files differ)
mww3_test_04/./work_PR1_g                     (1 files differ)
mww3_test_04/./work_PR3_UQ_MPI_c_c                     (1 files differ)
mww3_test_04/./work_PR1_MPI_c                     (1 files differ)
mww3_test_04/./work_PR3_UNO_b                     (1 files differ)
mww3_test_04/./work_PR1_MPI_b                     (1 files differ)
mww3_test_04/./work_PR3_UQ_a_c                     (1 files differ)
mww3_test_04/./work_PR3_UQ_MPI_b_c                     (1 files differ)
mww3_test_04/./work_PR3_UQ_f_c                     (1 files differ)
mww3_test_04/./work_PR3_UQ_g_c                     (1 files differ)
mww3_test_04/./work_PR3_UQ_MPI_d_c                     (1 files differ)
mww3_test_04/./work_PR3_UQ_MPI_d                     (1 files differ)
mww3_test_04/./work_PR3_UQ_MPI_NC_b_c                     (1 files differ)
mww3_test_04/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_04/./work_PR3_UNO_f                     (1 files differ)
mww3_test_04/./work_PR3_UNO_f_c                     (1 files differ)
mww3_test_04/./work_PR2_UNO_MPI_b                     (1 files differ)
mww3_test_04/./work_PR1_f                     (1 files differ)
mww3_test_04/./work_PR3_UNO_MPI_c                     (1 files differ)
mww3_test_04/./work_PR2_UQ_b                     (1 files differ)
mww3_test_04/./work_PR2_UQ_g                     (1 files differ)
mww3_test_04/./work_PR3_UNO_a                     (1 files differ)
mww3_test_04/./work_PR2_UQ_MPI_d                     (1 files differ)
mww3_test_04/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_04/./work_PR2_UQ_MPI_c                     (1 files differ)
mww3_test_04/./work_PR2_UNO_a                     (1 files differ)
mww3_test_04/./work_PR2_UNO_MPI_c                     (1 files differ)
mww3_test_04/./work_PR3_UQ_f                     (1 files differ)
mww3_test_04/./work_PR3_UQ_b_c                     (1 files differ)
mww3_test_04/./work_PR2_UNO_g                     (1 files differ)
mww3_test_04/./work_PR3_UQ_MPI_b                     (1 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tbt1.1/./work_BT9                     (1 files differ)
ww3_tbt1.1/./work_BT9_MPI                     (1 files differ)
ww3_tbt1.1/./work_BT8_MPI                     (1 files differ)
ww3_tbt1.1/./work_BT8                     (1 files differ)
ww3_tbt2.1/./work_BT9                     (1 files differ)
ww3_tbt2.1/./work_BT9_MPI                     (1 files differ)
ww3_tbt2.1/./work_BT8_MPI                     (1 files differ)
ww3_tbt2.1/./work_BT8                     (1 files differ)
ww3_tic1.2/./work_IC3_A0.5k_MPI                     (1 files differ)
ww3_tic1.2/./work_IC3_B0.5k_MPI                     (1 files differ)
ww3_tic1.2/./work_IC3_V1_G                     (1 files differ)
ww3_tic1.2/./work_IC3_B2.5k_MPI                     (1 files differ)
ww3_tic1.2/./work_IC3_A2.5k                     (1 files differ)
ww3_tic1.2/./work_IC3_A1.0k                     (1 files differ)
ww3_tic1.2/./work_IC3_A2.5k_MPI                     (1 files differ)
ww3_tic1.2/./work_IC3_CHENG                     (1 files differ)
ww3_tic1.2/./work_IC3_B2.5k                     (1 files differ)
ww3_tic1.2/./work_IC3_B0.5k                     (1 files differ)
ww3_tic1.2/./work_IC3_V1_h                     (1 files differ)
ww3_tic1.2/./work_IC3_B1.0k_MPI                     (1 files differ)
ww3_tic1.2/./work_IC3_B1.0k                     (1 files differ)
ww3_tic1.2/./work_IC3_A0.5k                     (1 files differ)
ww3_tic1.2/./work_IC3_A1.0k_MPI                     (1 files differ)
ww3_tic1.3/./work_IC3_2.5k_PR3_UQ                     (1 files differ)
ww3_tic1.3/./work_IC3_V1_G                     (1 files differ)
ww3_tic1.3/./work_IC3_2.5k_PR1                     (1 files differ)
ww3_tic1.3/./work_IC3_CHENG                     (1 files differ)
ww3_tic1.3/./work_IC3_0.5k_PR3_UNO                     (1 files differ)
ww3_tic1.3/./work_IC3_2.5k_PR3_UNO                     (1 files differ)
ww3_tic1.3/./work_IC3_0.5k_PR3_UQ                     (1 files differ)
ww3_tic1.3/./work_IC3_2.5k_PR2_UNO                     (1 files differ)
ww3_tic1.3/./work_IC3_V1_h                     (1 files differ)
ww3_tic1.3/./work_IC3_0.5k_PR2_UQ                     (1 files differ)
ww3_tic1.3/./work_IC3_0.5k_PR2_UNO                     (1 files differ)
ww3_tic1.3/./work_IC3_0.5k_PR1                     (1 files differ)
ww3_tic1.3/./work_IC3_2.5k_PR2_UQ                     (1 files differ)
ww3_tic1.4/./work_IC1IS2_1000                     (2 files differ)
ww3_tic1.4/./work_IC2IS2_IC2d                     (2 files differ)
ww3_tic1.4/./work_IC2IS2_IC2b                     (2 files differ)
ww3_tic1.4/./work_IC0IS2_1000                     (2 files differ)
ww3_tic2.1/./work_IC1                     (1 files differ)
ww3_tic2.2/./work_IC2IS2                     (1 files differ)
ww3_tic2.3/./work_IC2IS2creep                     (1 files differ)
ww3_tic2.3/./work_IC2IS2scat                     (1 files differ)
ww3_tic2.3/./work_IC2IS2dissip                     (1 files differ)
ww3_tp1.4/./work_PR2_UNO                     (1 files differ)
ww3_tp1.4/./work_PR3_UQ                     (1 files differ)
ww3_tp1.4/./work_PR3_UNO                     (1 files differ)
ww3_tp1.4/./work_PR1                     (1 files differ)
ww3_tp1.4/./work_PR2_UQ                     (1 files differ)
ww3_tp1.5/./work_PR2_UNO                     (1 files differ)
ww3_tp1.5/./work_PR3_UQ                     (1 files differ)
ww3_tp1.5/./work_PR3_UNO                     (1 files differ)
ww3_tp1.5/./work_PR1                     (1 files differ)
ww3_tp1.5/./work_PR2_UQ                     (1 files differ)
ww3_tp1.6/./work_PR2_UNO                     (1 files differ)
ww3_tp1.6/./work_PR3_UQ                     (1 files differ)
ww3_tp1.6/./work_PR3_UNO                     (1 files differ)
ww3_tp1.6/./work_PR1                     (1 files differ)
ww3_tp1.6/./work_PR2_UQ                     (1 files differ)
ww3_tp1.8/./work_PR3_UQ                     (1 files differ)
ww3_tp1.9/./work_PR3_UQ                     (1 files differ)
ww3_tp1.9/./work_PR3_UQ_MPI                     (1 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.19/./work_1B_a                     (1 files differ)
ww3_tp2.19/./work_1A_a                     (1 files differ)
ww3_tp2.19/./work_1C_a                     (1 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ts1/./work_NL5                     (1 files differ)
ww3_ts2/./work_ST6_PR3_UQ                     (1 files differ)
ww3_ts2/./work_ST3_PR3_UNO                     (1 files differ)
ww3_ts2/./work_ST4_PR1                     (1 files differ)
ww3_ts2/./work_ST4_PR3_UNO                     (1 files differ)
ww3_ts2/./work_ST6_PR2_UNO                     (1 files differ)
ww3_ts2/./work_ST6_PR2_UQ                     (1 files differ)
ww3_ts2/./work_ST3_PR2_UNO                     (1 files differ)
ww3_ts2/./work_ST1_PR1                     (1 files differ)
ww3_ts2/./work_ST3_PR1                     (1 files differ)
ww3_ts2/./work_ST2_PR3_UQ                     (1 files differ)
ww3_ts2/./work_ST2_PR3_UNO                     (1 files differ)
ww3_ts2/./work_ST3_PR2_UQ                     (1 files differ)
ww3_ts2/./work_ST4_PR3_UQ                     (1 files differ)
ww3_ts2/./work_ST1_PR2_UNO                     (1 files differ)
ww3_ts2/./work_ST2_PR1                     (1 files differ)
ww3_ts2/./work_ST6_PR1                     (1 files differ)
ww3_ts2/./work_ST3_PR3_UQ                     (1 files differ)
ww3_ts2/./work_ST6_PR3_UNO                     (1 files differ)
ww3_ts2/./work_ST2_PR2_UNO                     (1 files differ)
ww3_ts2/./work_ST4_PR2_UQ                     (1 files differ)
ww3_ts2/./work_ST4_PR2_UNO                     (1 files differ)
ww3_ts2/./work_ST2_PR2_UQ                     (1 files differ)
ww3_ts2/./work_ST1_PR2_UQ                     (1 files differ)
ww3_ts2/./work_ST1_PR3_UNO                     (1 files differ)
ww3_ts2/./work_ST1_PR3_UQ                     (1 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
 
**********************************************************************
************************ identical cases *****************************
**********************************************************************
```

The PR branch was run against itself to confirm this is the case.

**matrix.comp:  vs. PR branch**
Comparing the PR branch against itself, there are only the known non-b4b differences.

[vs.pr.matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/13242699/vs.pr.matrixCompSummary.txt)
[vs.pr.matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/13242701/vs.pr.matrixCompFull.txt)
[vs.pr.matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/13242698/vs.pr.matrixDiff.txt)
```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (10 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (17 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
 
**********************************************************************
************************ identical cases *****************************
**********************************************************************
```

**Comment by MatthewMasarik-NOAA** [comment]
@Biao-Zhao thank you, and nice work catching this attribute bug!

**Comment by Biao-Zhao** [comment]
@MatthewMasarik-NOAA I'm honored to be involved!

**Pull request merged**
