### PR TITLE
Bugfix/nml

### LINKED ISSUE #1062: UG mesh crashes with ww3_multi.nml when loading input wind field
**Describe the bug**
ww3_multi with only one unstructured mesh forced by wind crashes when using namelist ww3_multi.nml

**To Reproduce**
./bin/run_cmake_test -f -N -S -T -s NO_PDLIB -w work_ma -m grdset_a -f -p $MPI_LAUNCH -n 2 ../model ww3_tp2.21

**Expected behavior**
it should works in the way as with ww3_multi.inp

**Screenshots**
image

### PR DESCRIPTION
**Pull request by mickaelaccensi**
# Pull Request Summary
correct issue with ww3_multi when requesting restart2 and using nml file instead of inp file

## Description

the bug was introduced when merging the branch NCEP GFSv16/GEFSv12 #140 in 13 Jan 2020. No regtest was added in matrix to test it.

The PR propose to :
-correct issue for ww3_multi when outputting restart2 and using nml instead of inp. see #1062
-add scotch lib in matrix_cmake_datarmor
-force CFX, CFD, CFK to be outputted as type REAL if NCVARTYPE is set at 2 (=depends) for netCDF output
-add test on ufs switch to enable corresponding regtests
-correct typo in ww3_ufs1.1/namelist*.nml
-correct namelist in ww3_tp2.3 to enable TH1M and STH1M outputs
-replace 'echo' by 'basename' in matrix_cmake_datarmor to restrict the search of keyword in the filename itself

### Issue(s) addressed
- fixes #1062 

### Commit Message
correct issue with ww3_multi when requesting restart2 and using nml file instead of inp file

### Check list  

- [X] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [X] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [X] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [X] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? matrix
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) ww3_tp2.21
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? OK
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* ww3_tp2.21 : now it runs with nml
* ww3_tp2.3 : now it runs TH1MF and STH1MF activated
* ww3_tp2.14 : print differences (duplicated in develop branch)
* ww3_tp2.6 : differences due to truncated variable with scale_factor (corrected in PR #1050 )
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/12587010/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/12587012/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/12587013/matrixDiff.txt)

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi  - Thanks for making this fix.  Adding the regression test has been on my plate for a while - Hopefully that will come sooner than later, but we'll see.    Can we add to the commit message a note about the netcdf update too? It seems a little tangential to the stated update as is.

**Comment by mickaelaccensi** [comment]
> @mickaelaccensi - Thanks for making this fix. Adding the regression test has been on my plate for a while - Hopefully that will come sooner than later, but we'll see. Can we add to the commit message a note about the netcdf update too? It seems a little tangential to the stated update as is.

is it clear enough now ? Let me know if you want me to modify the commit message

**Comment by MatthewMasarik-NOAA** [comment]
Hi @mickaelaccensi, I ran the matrix and the PR branch run reached the wallclock limit in `matrix03`.  

I believe the issue is in this run test call
```
Running now options: run_test -b slurm -o all -S -T -s PR3_UNO_MPI_SCRIP -w work_PR3_UNO_MPI_c_c -m grdset_c -g curv -f -p srun -n 24 ../model mww3_test_02
```
It seems to have had some sort of internal error shown here, but then seems to have got passed it, but then timed out
```
SI nbPlus=       14884  nbMinus=           0  nbZero=           0
 SI nbPlus=        7396  nbMinus=           0  nbZero=           0
 SI nbPlus=        7396  nbMinus=           0  nbZero=           0
  
 Grid 1 size        3721
 Grid 2 size        1849
 
 grid1 sweep
 grid2 sweep 
 integration stalled: num_subseg exceeded limit
 Cell         1625
 Edge            2
 Grid            1
 Fraction of segment left   0.599999988869029     
 integration stalled: num_subseg exceeded limit
 Cell         1625
 Edge            2
 Grid            1
 Fraction of segment left   0.599999988869029     
 integration stalled: num_subseg exceeded limit
        .
        .
```
I attached the full matrix03.out file:  [matrix03.out.txt](https://github.com/NOAA-EMC/WW3/files/12664494/matrix03.out.txt)

**Comment by mickaelaccensi** [comment]
@MatthewMasarik-NOAA this issue is also present in the develop branch, actually it seems that all the regtests for mww3_test02 with options -m grdset_c and -g curv are crashing. This bug should be solved in another PR since it is not related to my branch. Does it sounds ok for you ?

**Comment by MatthewMasarik-NOAA** [comment]
Hi @mickaelaccensi, none of my develop runs are crashing.  Are they for you?

I just noticed though that this branch is out of date.   It's possible updating could resolve the issues.  Please sync up and I'll re-run the matrix.  Thanks

**Comment by mickaelaccensi** [comment]
I've updated my branch with the develop. I thought it was done but I may missed the last one. 

And yes I have the same issue as you with my up-to-date develop branch. Have checked that you have the postprocessing done for all the mww3_test02 work directories ? Especially those with grdset_c and curv grid. Because in my case it does not crash with an explicit exit code, it just stop and do not create out_grd.* and so the post processing is not done

**Comment by MatthewMasarik-NOAA** [comment]
Hi @mickaelaccensi, thanks for syncing.  I'll try re-running both develop and the PR branch.   

Nope, I didn't get an explicit crash either, just what was shown in the matrix03 out posted.  We'll see what these re-runs look like.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
@mickaelaccensi Good news, syncing resolved the issue in the new runs.
<br />

#### matrix output
```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
## known non-b4b
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (12 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
 
ww3_tp2.3/./work_PR2_UNO                     (6 files differ)
ww3_tp2.3/./work_PR1_MPI                     (6 files differ)
ww3_tp2.3/./work_PR3_UNO_MPI                     (6 files differ)
ww3_tp2.3/./work_PR3_UQ                     (6 files differ)
ww3_tp2.3/./work_PR3_UNO                     (6 files differ)
ww3_tp2.3/./work_PR1                     (6 files differ)
ww3_tp2.3/./work_PR2_UQ                     (6 files differ)
ww3_tp2.3/./work_PR2_UQ_MPI                     (6 files differ)
ww3_tp2.3/./work_PR3_UQ_MPI                     (6 files differ)
ww3_tp2.3/./work_PR2_UNO_MPI                     (6 files differ)

**********************************************************************
************************ identical cases *****************************
**********************************************************************
```

The new expected diffs are limited to tests within `ww3_tp2.3`, each due to the following six files: 
```
  log.ww3 
  mod_def.ww3 
  out_grd.ww3 
  ww3_grid.out
  ww3_ounf.out
  ww3_outf.out
```

* [matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/12684606/matrixCompSummary.txt)
* [matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/12684607/matrixCompFull.txt)
* [matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/12684605/matrixDiff.txt)
<br />

#### Code review
PASS

#### Testing
PASS
<br />

**Comment by MatthewMasarik-NOAA** [comment]
Thanks @mickaelaccensi for this PR, addressing a number of corrections.

**Pull request merged**
