### PR TITLE
Feature/st4tail

### PR DESCRIPTION
**Pull request by mickaelaccensi**
linked to issue #172 and #164

**code update:**
include Romero dissipation (GRL 2019) in ST4 (W3SDS4) and cleanup W3SPR4 W3SDS4
Add gas fluxes : whitecap coverage and entrained air AIRCMIN and volume of entrained air constant AIRGB ( Deike et al. 2017)

**update abx2/aby2 (new mssx mssy mssd):**
rename abx2 and aby2 to ab2x and ab2y
define abx2 and aby2 as cos² and sin²
update formula : TH2M(JSEA,IK)= MOD ( 270. - RADE*0.5*ATAN2(ABY2(JSEA),AB2X(JSEA)) , 180. )
update formula :  M2 = SQRT(AB2X(JSEA)**2+AB2Y(JSEA)**2)/MAX(1E-20,AB(JSEA))

**clean up ST4:**
change SDSC1 to SDSBCHOICE =1 ! 1: Ardhuin et al., 2: Filipot & Ardhuin, 3: Romero
remove SDSBR2, SDSLFGEN, SDSHFGEN

**b4b bugfix:**
RREF initialized just after allocation to get b4b with unst regtest ww3_tp2.7
RREF is not used for unst grid but it's written in mod_def anyway

**regtest:**
[matrix.zip](https://github.com/NOAA-EMC/WW3/files/4503385/matrix.zip)
done with intel-comp/18, impi/2018.1.163, netCDF-Fortran 4.5.2
changes by ST4 clean up : mww3_test_05, mww3_test_08, ww3_ta1, ww3_tp1.8, ww3_tp2.10, ww3_tp2.15, ww3_tp2.17, ww3_tp2.6
changes by abx2/aby2 : ww3_ts1 ww3_ts2 ww3_ts3 ww3_tig1.1
not b4b : mww3_test_03

### CODE REVIEW

**Review by aliabdolali — APPROVED** [review]

**Review by ajhenrique — COMMENTED** [review]
Looking good. Thanks @mickaelaccensi for the improvements.

**Review by ajhenrique — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
FYI you need updates to wmesmf to compile (see: https://github.com/JessicaMeixner-NOAA/WW3/commit/c72eaa07cdb220c0f7fdbb7c391c5d353df3e706)

**Comment by mickaelaccensi** [comment]
I have not mentioned that I let in the code comments the version 7.XX. I let you overwrite it to the new version with the corresponding milestone.

**Comment by ErickRogers** [comment]
Hi @mickaelaccensi . Where we have ATAN2(ABY2(JSEA),AB2X(JSEA)), should it be ATAN2(AB2Y(JSEA),AB2X(JSEA))?
image
(The code should use the sin(2theta) and cos(2theta) terms, which are now AB2Y and AB2X. ABY2 is the sin^2 term.)

**Comment by mickaelaccensi** [comment]
good catch Erick ! I've created an issue #1511 to correct it asap

**Comment by ErickRogers** [comment]
Thank you Mickael.

**Pull request merged**
