### PR TITLE
W3UNO2MD OMP bug fix

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
Reference issue #169 
Fixes bug where OMP directive fails to compile due to undefined QOLD variable if T2 switch is not enabled.

### CODE REVIEW

**Comment by ukmo-ccbunney** [comment]
Interestingly, the Intel compiler does not throw a compile error if you include undefined variables in the OMP PRIVATE statement - it silently ignores them.

The Cray and GNU compilers are not so forgiving though and refuse to turn a blind eye...

**Comment by ajhenrique** [comment]
@aliabdolali I've included you as reviewer for this PR: this is a bugfix that would in my view not require a full regtest, only perhaps regtests that use the UNO and OMP switches. @ukmo-ccbunney for the record would you be able to run those tests and provide summary of results? Thanks!

**Comment by ukmo-ccbunney** [comment]
> @ukmo-ccbunney for the record would you be able to run those tests and provide summary of results? 

@ajhenrique - Sure. As far as I can tell, it is just the `mww3_test_05` and `ww3_ts3` regtests that are affected.

**Comment by ukmo-ccbunney** [comment]
Matrix comparison of relevant regtests with my previous regtest baseline run (commit fbebf9) shows all tests are identical. 

Full matrix output here: [matrixCompFull_OMPH_UNO.zip](https://github.com/NOAA-EMC/WW3/files/4193315/matrixCompFull_OMPH_UNO.zip)

Excerpt from matrixCompSummary below.

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************

**********************************************************************
************************ identical cases *****************************
**********************************************************************
mww3_test_05/./work_ST1_PR3_UNO_MPI_OMPH
mww3_test_05/./work_ST1_PR2_UNO_MPI_OMPH
mww3_test_05/./work_ST6_PR3_UNO_MPI_OMPH
mww3_test_05/./work_ST3_PR2_UNO_MPI_OMPH
mww3_test_05/./work_ST4_PR3_UNO_MPI_OMPH
mww3_test_05/./work_ST2_PR2_UNO_MPI_OMPH
mww3_test_05/./work_ST4_PR2_UNO_MPI_OMPH
mww3_test_05/./work_ST3_PR3_UNO_MPI_OMPH
mww3_test_05/./work_ST2_PR3_UNO_MPI_OMPH
mww3_test_05/./work_ST6_PR2_UNO_MPI_OMPH
ww3_ts3/./work_ST1_PR3_UNO_MPI_OMPH
ww3_ts3/./work_ST1_PR2_UNO_MPI_OMPH
ww3_ts3/./work_ST6_PR3_UNO_MPI_OMPH
ww3_ts3/./work_ST3_PR2_UNO_MPI_OMPH
ww3_ts3/./work_ST4_PR3_UNO_MPI_OMPH
ww3_ts3/./work_ST2_PR2_UNO_MPI_OMPH
ww3_ts3/./work_ST4_PR2_UNO_MPI_OMPH
ww3_ts3/./work_ST3_PR3_UNO_MPI_OMPH
ww3_ts3/./work_ST2_PR3_UNO_MPI_OMPH
ww3_ts3/./work_ST6_PR2_UNO_MPI_OMPH
```

**Review by ajhenrique — APPROVED** [review]
Looks good! Thanks for adding the regtests outputs.

**Review by aliabdolali — APPROVED** [review]
It looks good to me.

**Comment by aliabdolali** [comment]
thanks @ukmo-ccbunney and @ajhenrique

**Pull request merged**
