### PR TITLE
IC4M10: New Wave Attenuation Scheme

### PR DESCRIPTION
**Pull request by erinethomas**
# Pull Request Summary
 
A new wave attenuation scheme (IC4 method 10) based on Meylan Horvat Bitz Bennetts Ocean Modelling 2021

## Description
This PR adds a new wave attenuation scheme for IC4. It is based on Meylan Horvat Bitz and Bennetts, Ocean Modelling, 2021. It calculated wave damping based on scattering due to sea ice floes. It requires the use of the IS0 switch (no additional scattering term) and sea ice floe size diameter as input from ICECOEF5. 

Suggestions for a reviewers: 
Labels that should be added:   _new feature_

### Commit Message
IC4M10: New wave damping scheme in sea ice based on Meylan Horvat Bitz and Bennetts, Ocean Modelling, 2021. Co-Authors include: Erin Thomas, Cecilia Bitz, David Bailey, Nick Szapiro. 

### Check list  

- [X] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [X] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
These changes have been tested in fully coupled climate model simulations (E3SM and CESM) which have fully coupled wave (WW3) and sea ice components (the later of which contain sea ice floe size distribution).

* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by erinethomas** [comment]
@cmbitz @NickSzapiro-NOAA @dabail10

**Comment by MatthewMasarik-NOAA** [comment]
Thank you for submitting this work @erinethomas!  One quick question, this is submitted to the `develop` branch, do you know if this should be submitted to the `dev/ufs-weather-model` branch?  This related PR [#1211](https://github.com/NOAA-EMC/WW3/pull/1211) was submitted to the `dev/ufs-weather-model` branch.

**Comment by erinethomas** [comment]
No we meant to put this in the develop branch -the E3SM + CESM community would like to eventually use the 'Develop branch' as our common WW3 code base - which needed the new attenuation method we are both already testing for wave-ice interactions.  It looks like the same method was already put in the UFS branch (@NickSzapiro-NOAA - is this the case)? I am unfamiliar with how PRs and new developments get shared/merged between the develop vs UFS branches?

**Comment by NickSzapiro-NOAA** [comment]
@MatthewMasarik-NOAA This IC4M10 is the same scheme as in dev/ufs-weather-model. Erin will also PR a "numerics" change for how the attenuation is applied for this scheme. If/once approved, our plan was to replace what is in dev/ufs-weather-model with this IC4M10 + numerics change. If that sounds good to you

**Comment by MatthewMasarik-NOAA** [comment]
Okay, thank you for that context @erinethomas @NickSzapiro-NOAA.  I will need to look closer into these two PRs.  @JessicaMeixner-NOAA had been handling #1211, but will be unavailable for the next few months while on a temporary detail.  We have actually needed to post a [Temporary PR Policy](https://github.com/NOAA-EMC/WW3/wiki/Commit-Queue#temporary-pr-policy) to adjust for this.  Once I've had a chance to spin myself up on all the details I'll report back on how to proceed.

**Comment by erinethomas** [comment]
@MatthewMasarik-NOAA - thank you! there is no rush on our (the E3SM/CESM) side - we just wanted to start coordinating our efforts back to the main WW3 repo :)

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA - thank you! there is no rush on our (the E3SM/CESM) side - we just wanted to start coordinating our efforts back to the main WW3 repo :)

Perfect.  Thank you.

**Comment by MatthewMasarik-NOAA** [comment]
Hi @erinethomas, I wanted to update the status that we will need to wait to process this till ~November.  Sorry for this delay.  We're looking forward to reviewing it that point.

**Comment by sbanihash** [comment]
(posting to the right PR!) Thank you @erinethomas for your work on this pull request and your patience as we were handling other tasks during these past few months. I have reviewed the PR and tested the changes to make sure it does not change outcome of any WW3 runs not using this new feature. Everything looks good but since this update will add a numerical solution to the wave attenuation, I would like to ask if you could maybe follow the steps in a similar PR (https://github.com/NOAA-EMC/WW3/pull/1176) and document this new change in the WW3 manual section. If that's not possible at this moment we appreciate it if you could open an [issue](https://github.com/NOAA-EMC/WW3/issues) and assign it to yourself so that you could add it whenever you are ready to do so. I already see a nice link to the document that @cmbitz has added to the next PR . Another suggestion is that since these new changes can not be tested in the current ww3 regression tests, it would be great if you could take a look at PR 1176 and see how a regression test is added to that PR and try making a similar test case for your changes. The test could be an IC4-M10 case inside the ww3_tic1.1 and besides checking the steps that can be tracked in [previously mentioned PR](https://github.com/NOAA-EMC/WW3/pull/1176/files#diff-3589e2082baa9eea5303fe7fce9872cdd1476064878b1363b6d9b54cf0afea08), you could also reach out to me as well and I would be more than happy to help set up this test case with you. Thanks!

**Review by sbanihash — APPROVED** [review]
@erinethomas a new PR has been created with a regression test added for this new feature. With the addition of that test and successfully using this new capability I can go ahead and approve this PR. An issue would be added for documentation that will be assigned to you and you can hopefully address it in the near future. Thank you in advance.

**Comment by erinethomas** [comment]
Excellent - thanks!  Yes- I will work on documentation.

**Pull request merged**
