### PR TITLE
Merge develop to dev/ufs-weather-model 

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
Merge updates from develop to dev/ufs-waether-model 

## Description
Merging various updates from develop to dev/ufs-waether-model, including: 
* updates to how charnock is set for IC0 flag. 

Please also include the following information: 
* Add any suggestions for a reviewer  @MatthewMasarik-NOAA 
* Are answer changes expected from this PR? None 

### Issue(s) addressed
No issue, just routine merge from develop to dev/ufs-weather-dmoel 

### Commit Message
Merge develop to dev/ufs-weather-model branch

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? With ufs-weather-model tests hera intel and gnu: 
[RegressionTests_hera.gnu.log](https://github.com/NOAA-EMC/WW3/files/10824944/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/NOAA-EMC/WW3/files/10824945/RegressionTests_hera.intel.log)
* Are the changes covered by regression tests? yes
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?  Yes, all tests passed.  No comparisons made as this was done within the develop branch PRs. This just confirmed the merge resolutions didn't unintentionally break anything.

### CODE REVIEW

**Review by MatthewMasarik-NOAA — APPROVED** [review]
The code review looks good.  Intel/Gnu RT logs show all tests pass.  Approved.

**Comment by aronroland** [comment]
As for the regtesting I understood that all regtests will have changes due to the fact that the unstructured namelist is written also in the case of a regular regtest and I have changed it now.

**Comment by JessicaMeixner-NOAA** [comment]
> As for the regtesting I understood that all regtests will have changes due to the fact that the unstructured namelist is written also in the case of a regular regtest and I have changed it now.

@aronroland I think you are confusing this PR for another.

**Comment by aronroland** [comment]
> As for the regtesting I understood that all regtests will have changes due to the fact that the unstructured namelist is written also in the case of a regular regtest and I have changed it now.

ups, i hit the wrong button ... sorry!

**Review by MatthewMasarik-NOAA — APPROVED** [review]
#### Update to PR
* CI fix.
* SCOTCH library for geographic domain decomposition.

These changes have passed testing separately in WW3 standalone.  
For UFS RTs the updated logs from @JessicaMeixner-NOAA:

* [RegressionTests_hera.intel.log](https://github.com/NOAA-EMC/WW3/files/10875430/RegressionTests_hera.intel.log)
* [RegressionTests_hera.gnu.log](https://github.com/NOAA-EMC/WW3/files/10875431/RegressionTests_hera.gnu.log)

Re-approved.

**Pull request merged**
