### PR TITLE
Fix:  Gnu regtest CI failure

### LINKED ISSUE #1251: The recent commit 629d27a has added a Github actions file (regtest_gnu) that fails with a syntax error message
**Describe the bug**
I update WW3 on my repository with:
> git pull https://github.com/NOAA-EMC/WW3.git develop
> git push origin develop # where origin is git@github.com:CarstenHansen/WW3.git

Upon push to my own Github repositoty, three 'Actions' are run, of which the third (regtest_gnu) is a new one in commit 629d27a and fails with the annotation:

"Invalid workflow file: .github/workflows/regtest_gnu.yml#L95
You have an error in your yaml syntax on line 95"

**To Reproduce**
I update WW3 on my repository with:
> git pull https://github.com/NOAA-EMC/WW3.git develop
> git push origin develop # where origin is git@github.com:CarstenHansen/WW3.git

Then Github runs the thee 'Actions' _GNU Linux Build_, _Intel Linux Build_, and _regtest_gnu_.

**Expected behavior**
I wouldn't care if the file regtest_gnu.yml was omitted. But it should not have a syntax error.

**Screenshots**

**Additional context**
I am not familiar with Spack, but I tried to check the file regtest_gnu.yml file with [https://rhysd.github.io/actionlint/](https://rhysd.github.io/actionlint/) . It seems that lines 95 and 94 have no syntax errors, and hence there may be a complex of other code errors.

### PR DESCRIPTION
**Pull request by MatthewMasarik-NOAA**
# Pull Request Summary
Provides a fix for the Gnu github workflow `regtest_gnu.yml` added in commit https://github.com/NOAA-EMC/WW3/commit/629d27a3137929bbf91b19d212437606135f0d20.

## Description
* Provide a detailed description of what this PR does.
  * There are two fixes and an added commented out section to address the failure:
    *  typo in `key`
    *  indentation needed for previously commented out lines
    *  Commented out post run lines to avoid failures there
  * I wanted to point out `regtest_gnu` contains a working regtest w/ MPI running on Github Actions, which is a big milestone itself.  Thanks to @edwardhartnett who did all the heavy lifting.
  * At another time the post run comparisons should be fixed.  This is a lower priority currently. 
* What bug does it fix, or what feature does it add?
  * Bug fix for new Gnu regtest CI.
* Is a change of answers expected from this PR?
  * No.  The changes are confined to the github CI.

Please also include the following information: 
* Add any suggestions for a reviewer 
  * @JessicaMeixner-NOAA @edwardhartnett  
* Mention any labels that should be added:  
  * _bug_.
* Are answer changes expected from this PR? Please describe the changes and the reason why in addition to which of the following labels would apply: _mod_def change_, _out_grd change_, _out_pnt change_, _restart file change_, _Regression test_ 
  * No.  Only CI is modified.

### Issue(s) addressed
* Please list any issues associated with this PR, including those the PR will fix/close. For example:  
- fixes #1251 

### Commit Message
Fix GNU regtest CI failure

### Check list  
- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [x] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [x] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing
* How were these changes tested?
  * In Github Actions CI.
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
  * N/A.  No model code changes.
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
  * N/A.
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):
  * N/A

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
I updated the header Description and PR status.   @CarstenHansen, let us know if this fix works for you.

**Comment by CarstenHansen** [comment]
Yes, @MatthewMasarik-NOAA, your fix works for me on Github Actions without complains.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
Thank you @MatthewMasarik-NOAA for the quick fix for this, and thank you @CarstenHansen for confirming this works!

**Comment by MatthewMasarik-NOAA** [comment]
> Yes, @MatthewMasarik-NOAA, your fix works for me on Github Actions without complains.

Perfect, thanks for confirming @CarstenHansen.

**Pull request merged**
