### PR TITLE
Extra TP field and direction/magnitude outputs.

### LINKED ISSUE #296: Extra gridded output fields required
As part of adopting WW3 version 7 as our operational wave model (from vn 4.18) we require some extra gridded output fields to be generated by ww3_ounf. The internal data for these fields already exist, but just needs outputting in a different convention or unit:

  - Peak period (from peak freq)
  - Wind speed and direction (from U and V components)
  - Current speed and direction[ (from U and V components)

My proposed solution to do this is to add new output field identifier/flags for these but internally reference the existing variables (so no extra I/O or memory allocation is performed by w3iogo et al.) It is then simple to add an extra output in ww3_ounf (and the other gridded output post-processors) to generate the required fields.

For example, requesting "peak period", will cause the "peak freq" (FP0) to be written out by w3iogo. The reciprocal of this will then be output by ww3_ounf as peak period. The same goes for wind speed/dir and current speed/dir where they will be written in a magnitude/direction convention.

I propose the following new flags/IDs

  - IFI=1, IFJ=11, ID='CURD' : Current speed and direction
  - IFI=1, IFJ=12, ID='WNDD' : Wind speed and direction
  - IIFI=2, IFJ=18, ID='TP' : Peak period

Before I start working on this, does anyone have any objections or thoughts on a different solution?

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
Fixes #296 

This PR adds two features:
  - Peak period (TP) output field. This field is derived from the existing `FP0` internal field, so does not generated an extra I/O in the `out_grd.ww3` file. It is implemented in the `ww3_outf` and `ww3_ounf` programs at the moment.
  - Alternative direction/magnitude output for direction fields (as opposed to U/V vectors) in `ww3_ounf`. Controlled via a `VECTOR` flag in the namelist file (not implemented in `.inp` file - defaults to true*)

Two of the exitsing regtests have been modified slightly to test these new features.

_\* it was decided by the repo managers that we would not add new features to the `.inp` files with the intention of them being "frozen" and deprecated in favour of the new namelist files._

### CODE REVIEW

**Comment by ukmo-ccbunney** [comment]
Regtest results to follow shortly...

**Comment by ukmo-ccbunney** [comment]
Regression test results are attached.
[regtest_matrix_fb_extrafields2.zip](https://github.com/NOAA-EMC/WW3/files/5895065/regtest_matrix_fb_extrafields2.zip)


I have updated two of the existing regtests to test the new TP field and direction/magnitude output.
  * `ww3_tr1`: WW3_OUNF (netcdf) now produces a new TP field and the existing WND output is now formulated as direction/magnitude 
  * ww3_tp2.11: WW3_OUTF (text) now produces new TP field.

The other differences are all in regtests that have existing known differences:
  * mww3_test_03
  * ww3_tp2.18/TIDE

**Review by aliabdolali — APPROVED** [review]
@ukmo-ccbunney It looks ok to me. I am going to test regtest on NOAA HPC.

**Comment by aliabdolali** [comment]
@ukmo-ccbunney is this PR ready? I can run the regtests on NOAA HPC if you do not have changes. Thanks

**Comment by ukmo-ccbunney** [comment]
> @ukmo-ccbunney is this PR ready? I can run the regtests on NOAA HPC if you do not have changes. Thanks

@aliabdolali yes - this one is ready for testing thanks.

**Comment by aliabdolali** [comment]
I checked it on NOAA HPC, everything went well and we had expected differences. 
[COMPNCEP.zip](https://github.com/NOAA-EMC/WW3/files/5941101/COMPNCEP.zip)

**Comment by ukmo-ccbunney** [comment]
Great - thanks Ali.

**Pull request merged**
