### PR TITLE
Update ww3_gint to interpolate restart files 

### LINKED ISSUE #829: Update gint to regrid restart files as well as output files
**Is your feature request related to a problem? Please describe.**
Need restart files from global models for regional models. 

**Describe the solution you'd like**
Update ww3_gint to regrid restart files.  This assumes that the frequency range is the same. 

**Describe alternatives you've considered**
Use netcdf restarts and have offline regridding available. 

**Additional context**
This has been done in feature branches and needs to be reintegrated to the develop branch.

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
This PR updates ww3_gint to optionally interpolate restart files.  

## Description
This updates ww3_gint to interpolate restart files as an option.  This is selected via the input file by ww3_gint.inp in the first line to now have the last option: 
`Time, time increment and number of outputs, and optional T/F -- option (default is T) to indicate out_grd (T) or restart (F)
`
A new set of regression tests for this is added: 
```
./bin/run_cmake_test -b slurm -o all -S -T -s MPI_OMPH -w work_c -m grdset_c -f -p srun -n 140  -t 4 ../model ww3_ufs1.2
mkdir -p ww3_ufs1.2/work_l
cp ww3_ufs1.2/work_c/restart.hafsl ww3_ufs1.2/work_l/restart.hafsl
./bin/run_cmake_test -b slurm -o all -S -T -s MPI_OMPH -w work_l -m grdset_l -f -p srun -n 140  -t 4 ../model ww3_ufs1.2
```
which shows the use case of initializing a regional system from a global system.  

* Suggestion for a reviewer: @MatthewMasarik-NOAA  
* Mention any labels that should be added: _new feature_
* Are answer changes expected from this PR? Only for the newly added test. 

### Issue(s) addressed
- fixes https://github.com/NOAA-EMC/WW3/issues/829

### Commit Message
Update ww3_gint to interpolate restart files 

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [x] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? matrix 
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Yes, new test was added 
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? Yes, hera intel 
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.): 
Only the new test 
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/11091340/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/11091341/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/11091342/matrixDiff.txt)

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
This is great to see @JessicaMeixner-NOAA!!  I'll start the regression tests.

**Comment by MatthewMasarik-NOAA** [comment]
Status update: I just spoke with @JessicaMeixner-NOAA, and we are both following up one difference that came up in the regtests results.

**Comment by MatthewMasarik-NOAA** [comment]
Status:  Hera is unavailable today for maintenance. This PR will finish being process tomorrow once hera is back online for developers.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/11151463/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/11151464/matrixCompFull.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/11151465/matrixDiff.txt)

**Code Revew** PASS
**Testing** PASS

This is a very exciting capability to now for restart files!  Thank you @JessicaMeixner-NOAA for your determined work to bring this to fruition!!

**Comment by ukmo-ccbunney** [comment]
This is a really useful feature. Thanks @JessicaMeixner-NOAA .

**Pull request merged**
