### PR TITLE
Fb variable rhoair

### LINKED ISSUE #448: Variable air density not used
The present code has the capability of reading an air density field and use it in the calculations. If this field is not read, the default value of DAIR=1.225 is used.

At the moment some of the code does not use this capability and the constant value of DAIR is used. Furthermore, the air density is overwritten with this constant value after it is read from the restart file.

### PR DESCRIPTION
**Pull request by ukmo-juan-castillo**
# Pull Request Summary
The air density was previously changed so that it can be read from file, or use the default constant value otherwise. The code is not completely adapted to use this functionality, and the constant value is used in some places anyway. This will be fixed there.

Furthermore, when reading the air density from file the field is not interpolated in time. This is due to a limitation of the routine that reads the input fields, as interpolation is supposed to take place only on vectorial fields such as wind and currents, but that can be easily fixed.

## Description
Uses the air density as read from file through the code, or the default constant value if it is not read. Performs time interpolation of air density when read from file, so that for example the first time step contains the field read from file rather than the default constant value.

Change of answers are expected only in tests reading air density from file.

### Issue(s) addressed
- fixes #448
- fixes noaa-emc/ww3/issues/448

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)?
YES
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number)
DONE
* Please list appropriate labels code managers should add for this PR:   
 _enhancement_
 
* Reviewers: @mentions of suggested reviewers of the proposed changes
@mickaelaccensi @ukmo-ccbunney 

### Commit Message
Use the air density read from file and time interpolate it. 

### Testing
* How were these changes tested?
Regtests and the amm15 coupled configuration at the Met Office
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
YES
* If a new feature was added, was a new regression test added?
N/A
* Have regression tests been run?
YES
* Which compiler / HPC you used to run the regression tests in the PR? 
GNU compiler in the CrayXC40 HPC at the Met Office
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

[matrixCompSummary.txt](https://github.com/ukmo-waves/WW3/files/7105902/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/ukmo-waves/WW3/files/7105903/matrixDiff.txt)

Expected changes: 

None

NOTE: This is a copy of an existing PR in the ukmo-waves repository - the reviewer suggested that this should be merged directly to the NOAA-EMC develop branch rather than to the ukmo-waves fork:

https://github.com/ukmo-waves/WW3/pull/34

### CODE REVIEW

**Comment by aliabdolali** [comment]
@ukmo-ccbunney can we put it in the commit queue?

**Comment by ukmo-ccbunney** [comment]
> @ukmo-ccbunney can we put it in the commit queue?

Yes please @aliabdolali. 
Please not that all the conversation history is in a separate PR in the UKMO repo: ukmo-waves#34

**Comment by ukmo-juan-castillo** [comment]
Just in case I am running again the regtests, as I made some minor modifications to correct for SMC grids when we were looking for the ww3_ts1 differences. They will be ready today and I will upload the results when they are ready.

**Comment by aliabdolali** [comment]
Hi @ukmo-juan-castillo Could you fix the conflicts,  and sync it with the top of develop?

**Comment by ukmo-juan-castillo** [comment]
Hi, git did not let me push the changes as this PR has not been accepted by any reviewer. Could any of you please accept it?

**Comment by ukmo-ccbunney** [comment]
> Hi, git did not let me push the changes as this PR has not been accepted by any reviewer. Could any of you please accept it?

That's odd - I've never had that before. Are you trying to push to your branch on ukmo-waves repo? This PR should not affect that in any way...

**Comment by ukmo-juan-castillo** [comment]
The error I receive is:

remote: error: GH006: Protected branch update failed for refs/heads/fb_variable_rhoair.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/ukmo-waves/WW3.git
 ! [remote rejected]   fb_variable_rhoair -> fb_variable_rhoair (protected branch hook declined)
error: failed to push some refs to 'https://github.com/ukmo-waves/WW3.git'

I followed the instructions on the twiki.

**Comment by ukmo-ccbunney** [comment]
@ukmo-juan-castillo - I think I know what is causing this. Try again now...

**Comment by ukmo-juan-castillo** [comment]
Thanks, done now successfully.

**Comment by aliabdolali** [comment]
Hi @ukmo-juan-castillo have you checked ww3_tp2.15? I have differences in the results. The rests are expected (preknown).
See attached the outputs of matrix.comp
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7186928/matrixDiff.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7186929/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7186930/matrixCompFull.txt)
.

**Comment by ukmo-juan-castillo** [comment]
Yes, the changes in ww3_tp2.15 are expected. Please notice that they only happen in the RHO tests, i.e. the test that read air density from the input. As this ticket fixes the time interpolation of the air density, and uses the read air density instead of its default constant value, it makes sense that these configurations change results.

**Comment by aliabdolali** [comment]
> Yes, the changes in ww3_tp2.15 are expected. Please notice that they only happen in the RHO tests, i.e. the test that read air density from the input. As this ticket fixes the time interpolation of the air density, and uses the read air density instead of its default constant value, it makes sense that these configurations change results.

Good, I checked your comparison and did not see it. Also, you mentioned there are no expected changes, so I wanted to ask you for clarification. Thanks.

**Comment by ukmo-juan-castillo** [comment]
Sorry I was not clear - the ww3_tp2.15 were expected changes, so there were no unexpected changes (we found some before, see https://github.com/ukmo-waves/WW3/pull/34, but these have been explained).

**Review by aliabdolali — APPROVED** [review]

**Pull request merged**
