### PR TITLE
More efficient test for binary files in matrix.comp.

### LINKED ISSUE #1031: matrix.comp very slow
**Describe the bug**
Since the update to CMake, I have noticed that the `matrix.comp` script is very slow; it can take several hours to complete.
It has always been a bit slow, but the move to cmake has made it worse.

I believe that this line is a particular bottleneck:
https://github.com/NOAA-EMC/WW3/blob/3eb8161fdc999f4046fac7d77febff70c399c4f8/regtests/bin/matrix.comp#L172

It is grepping for `.` (i.e. anything) recursively in all files to check whether grep returns that the file is a "binary file".
This is very inefficient as it is unnecessarily reading the entirety of any text files.
Also, now we are using CMake, there are `build` directories in each regtest work directory that contain many many files - these are also being recursively grepped too (unnecessarily).

A quick manual test on a work directory shows that this single command is taking up to 15 seconds or more to complete. That quickly adds up over a full regression test matrix.

**To Reproduce**
Run matrix.comp on any test.
Add a "time" command around the above line to get timings if wanted.

**Expected behavior**
It's slow!

**Proposed fix**
I propose that we get rid of the line mentioned above and instead perform a `file` test on individual files as they are processed.
The `file` command will return the mime type of the file and we can check the output for the string "text" to check whether it is a text file. Any other kind of file can be considered binary. That should be a lot quicker than a recursive grep.

Example output of `file` command in a regtest directory
```
finished:            ASCII text
ice.ww3:             data
log.ww3:             ASCII text
mod_def.ww3:         MPEG sequence
out_grd.ww3:         data
out_pnt.ww3:         data
restart.ww3:         data
tab50.ww3:           ASCII text
tab51.ww3:           ASCII text
ww3.196806.nc:       NetCDF Data Format data
ww3.196806_spec.nc:  NetCDF Data Format data
ww3.68060600.hs:     ASCII text
ww3.68060601.hs:     ASCII text
ww3.68060602.hs:     ASCII text
ww3.68060603.hs:     ASCII text
ww3.68060604.hs:     ASCII text
ww3.68060605.hs:     ASCII text
ww3.68060606.hs:     ASCII text
ww3.68060607.hs:     ASCII text
ww3.68060608.hs:     ASCII text
ww3.68060609.hs:     ASCII text
ww3.68060610.hs:     ASCII text
ww3.68060611.hs:     ASCII text
ww3.68060612.hs:     ASCII text
ww3_grid.nml.log:    ASCII text
ww3_grid.out:        ASCII English text, with very long lines
ww3_ounf.nml.log:    data
ww3_ounf.out:        ASCII Pascal program text
ww3_ounp.nml.log:    ASCII text
ww3_ounp.out:        ASCII Pascal program text
ww3_outf.out:        ASCII Pascal program text
ww3_outf_file.out:   ASCII Pascal program text
ww3_outf_screen.out: ASCII Pascal program text
ww3_outp_tab50.out:  ASCII Pascal program text
ww3_outp_tab51.out:  ASCII Pascal program text
ww3_prep.out:        ASCII Pascal program text
ww3_shel.nml.log:    ASCII text
ww3_shel.out:        ASCII English text
ww3_strt.out:        ASCII Pascal program text
```

We could also be more robust and check on the mime-type (rather than "human readable description"):
E.G.

```
file -i *
ab50.ww3:           text/plain charset=us-ascii
tab51.ww3:           text/plain charset=us-ascii
ww3.196806.nc:       application/octet-stream
ww3.196806_spec.nc:  application/octet-stream
ww3.68060600.hs:     text/plain charset=us-ascii
ww3.68060601.hs:     text/plain charset=us-ascii
ww3.68060602.hs:     text/plain charset=us-ascii
```

Piping the output through grep would be a good check for binary/text files:

```
if [[ file -i ${FILE} | grep -qi "\<text\>" ]]; then
   # text
else
  # binary
fi
```

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
# Pull Request Summary
Provides a more efficient test for binary files when running matrix.comp

## Description
Currently, matrix.comp recursively checks all files in a work directory using the command
```
 binaryfiles=`grep . -r * | grep 'Binary file' | sed -e "s/^Binary file //" -e "s/ matches$//"` 
```

This is very slow as:
1. It will unnecessarily read the entirety of any text files (`.` matches "any character")
2. It recurses into the CMake `build*` and `exe` directories which have a **lot** of files in.

A better solution is to use the standard linux [`file`](https://www.man7.org/linux/man-pages/man1/file.1.html) command to check whether individual files are "plain text" files or binary. This is not only a much quicker and more efficient test, but it will only be called when needed (as apposed on a complete recursive listing of the directory)

I assuming a fairly modern implementation of the `file` command that accepts the `-i` or `--mime` flags for robustness purposes. The test is encapsulated as a function at the top of the `matrix.comp` script to facilitate modification if needed.

#### Performance
Some results of running new vs old version of matrix.comp:
 - `ww3_tp2.2` (10 work directories):
   - original version: 3m 7s
   - new version: **9s**
 - `ts1` (11 work directories):
   - original version 2m2s
   - new version:  **7s** 
  - `tp2.9` (20 work directories):
    - 6m 9s
    - **20s**

_Note: When testing performance, it is important to **not** rerun `matix.comp` twice on the **same** regression test directory as the file system will likely have cached the files and the timings will be much quicker the second time._

I make performance comparisons by testing in two separate WW3 regtest trees (and testing the regtests against themselves)

### Issue(s) addressed
Fixes #1031 

### Commit Message
More efficient test for binary files in matrix.comp

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? **Comparison of regression test output; diffs out matrixCompFull.txt are same**
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) **N/A**
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? **N/A**
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.) **N/A**

### CODE REVIEW

**Comment by ukmo-ccbunney** [comment]
As part of this PR,  I wonder if others would also agree to the removal of the "do not compare build or exe directory" messages to STDOUT?

```
 testing case: ww3_tp2.9; run: ./work_PR2_UQ_a_MPI
do not compare build or exe directories build
do not compare build or exe directories build_SHRD
do not compare build or exe directories exe
do not compare build or exe directories build
do not compare build or exe directories build_SHRD
do not compare build or exe directories exe
```

these get printed multiple times for each test and dominate the output to the screen.

**Comment by JessicaMeixner-NOAA** [comment]
> As part of this PR, I wonder if others would also agree to the removal of the "do not compare build or exe directory" messages to STDOUT?
> 
> ```
>  testing case: ww3_tp2.9; run: ./work_PR2_UQ_a_MPI
> do not compare build or exe directories build
> do not compare build or exe directories build_SHRD
> do not compare build or exe directories exe
> do not compare build or exe directories build
> do not compare build or exe directories build_SHRD
> do not compare build or exe directories exe
> ```
> 
> these get printed multiple times for each test and dominate the output to the screen.

@ukmo-ccbunney I'm okay with that

**Comment by MatthewMasarik-NOAA** [comment]
I'm also OK with removing the repeated prints of "do not compare build or exe directory".

**Comment by ukmo-ccbunney** [comment]
Timing results from running `matrix.comp` on a full regression test matrix:
  - old code: 272m (~4.5 hours)
  - new code 63m

So - not as fast a speedup as the results for individual regtests show above (not sure why?), but still a significant improvement!

**Comment by ukmo-ccbunney** [comment]
> I'm also OK with removing the repeated prints of "do not compare build or exe directory".

I've pushed a commit to remove this message.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @ukmo-ccbunney !   I am running tests to do comparisons between the old and the new on our machines. Those should be finished soon and then I can submit the two matrix.comps for comparisons.   I'll let you know how it goes!

**Review by JessicaMeixner-NOAA — APPROVED** [review]
This improved the speed from 80min to 53 min on hera for me.  Thank you for this speed up @ukmo-ccbunney !

**Comment by ukmo-ccbunney** [comment]
> This improved the speed from 80min to 53 min on hera for me. Thank you for this speed up @ukmo-ccbunney !

I'm impressed they were running in 80 minutes before! I think the regtests really stress the filesystem on our HPC... it takes over 4.5 hours for me to run them!

**Comment by JessicaMeixner-NOAA** [comment]
@ukmo-ccbunney well, i just had a set of matrix.comp take 4.5 hours.... with the updates, so .... I wonder if we need to rethink what we're comparing and how we're comparing it to relieve some of the stress.  4.5 hours is crazy, but I get that once in a blue moon these days.  I usually have the tests get stuck on the ufs tests at the end if something does take a long time.

**Comment by ukmo-ccbunney** [comment]
> @ukmo-ccbunney well, i just had a set of matrix.comp take 4.5 hours.... with the updates, so .... I wonder if we need to rethink what we're comparing and how we're comparing it to relieve some of the stress. 4.5 hours is crazy, but I get that once in a blue moon these days. I usually have the tests get stuck on the ufs tests at the end if something does take a long time.

Wow. 4.5 hours with this update? I wonder if that is just some spurious filesystem contention that you are experiencing.
This update has certainly helped speed thiings up a lot on my HPC, but every system is different! 
I think it is definitely high time we looked at the matrix.comp script and what/how it is comparing.

**Pull request merged**
