### PR TITLE
Fix for missing grid corner coordinates

### LINKED ISSUE #434: The corner coordinates are not reproducible due to the R8 -> R4 conversion
**Describe the bug**
The recent testing of CMEPS PR (https://github.com/ESCOMP/CMEPS/pull/216) under HAFS application revealed that the `MED_wav_area` field in mediator history file is not reproducible. The three-component configuration of HAFS application works fine and there is no answer change but this particular value is reported as changed with the CESM `cprnc` tool. There is no answer change because currently we are not using conservative type Regridding between atmosphere and wave components but this could be a issue when conservative type interpolation is used between them. 

The issue might be resolved by following approaches:
1. Force WW3 cap to use R8 rather than R4.
2. Create R4 version of the _GET\_SCRIP\_INFO\_STRUCTURED ()_ call - https://github.com/NOAA-EMC/WW3/blob/1f128e68372637d18e5d017b89d262aad55373c4/model/ftn/wmscrpmd.ftn#L863
3. Use appropriate type conversion in the WW3 cap to be sure that there is no answer change such as using _real()_ function provided by the Fortran itself. This needs to be implemented in two different place in the WW3 cap,
https://github.com/NOAA-EMC/WW3/blob/1f128e68372637d18e5d017b89d262aad55373c4/model/ftn/wmesmfmd.ftn#L3082
https://github.com/NOAA-EMC/WW3/blob/1f128e68372637d18e5d017b89d262aad55373c4/model/ftn/wmesmfmd.ftn#L3519

Currently, i am testing approach (3) first since it is very easy to implement and if that works I'll create very small fix PR for it.

**To Reproduce**
Steps to reproduce the behavior: Since the WW3 is coupled with CMEPs only under HAFS application at this point. Running three component configuration twice and comparing the `MED_wav_area` will reveal the issue. The HAFS workflow is able to run three component configuration at this point. So, it would be easy to reproduce the issue.

**Expected behavior**
There is a slight change in the `MED_wav_area` variable but there is no answer change.

```
MED_wav_area   (MED_wav_nx,MED_wav_ny,time)  t_index =      1     1
        167   397341  (     0,     9,     1) (     0,     1,     2) (     0,   223,     1) (    81,   441,     1)
              397341   6.084841554444137E+00   0.000000000000000E+00 5.5E+00  2.768168675503156E-01 2.6E-04  4.309843238733993E+00
              397341   6.084841554444137E+00   0.000000000000000E+00          5.818140359473252E+00          0.000000000000000E+00
              397341  (     0,     9,     1) (    81,   441,     1)
          avg abs field values:                      NaN    rms diff:     NaN   avg rel diff(npos):  2.6E-04
                                                     NaN                        avg decimal digits(ndif):  1.2 worst:  0.0
 RMS MED_wav_area                            NaN            NORMALIZED  0.0000E+00
```

### PR DESCRIPTION
**Pull request by uturuncoglu**
# Pull Request Summary
This PR aims to fix the corner coordinates, which is used by the CMEPS to convert ESMF Grid to mesh, in the WW3 grid.

## Description
An issue is found in the ESMF_GridAddCoord() call that is used to add corner coordinates. That was adding one more extra row and column to the corner coordinates and those extra region has no corresponding data in the data returned by the scrip call to calculate the corner coordinates. The dimension returning from ESMF call is 902x442 but scrip call returns 901x441. The PR basically includes the code that fill the missing corner coordinate data in the top and right edges of the grid.

### Issue(s) addressed
* Is there an issue associated with this development (bug fix, enhancement, new feature)?
- fixes https://github.com/NOAA-EMC/WW3/issues/434

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)? Yes
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number)
* Please list appropriate labels code managers should add for this PR:   
 _bug_
 
* Reviewers: @JessicaMeixner-NOAA

### Commit Message
* Please provide a short summary of this PR, which will be used during _Squash and Merge_ and will be shown as git log message 

### Testing
* How were these changes tested?
The three-component configuration (FV3 regional+HYCOM+WW3) under HAFS application is running without any issue. 
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) There is no need to add new test.
* If a new feature was added, was a new regression test added? No
* Have regression tests been run? All wave related RTs (S2SW and ATMW ones) run and pass.
* Which compiler / HPC you used to run the regression tests in the PR? Intel, Orion
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):    
Please indicate the expected changes in the outputs ([excluding the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)). No answer change
* Please list which labels code managers should add to indicate code changes:    
_mod_def change_, _out_grd change_, _out_pnt change_, _restart file change_, _Regression test_, ...

### CODE REVIEW

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA I updated PR description and include testing information. All wave related RTs (S2SW and ATMW ones) pass with this PR.

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA i change the way of implementation of fix. It was using center coordinate dimension but after discussing with the ESMF team, we decided to use array bounds of corner coordinates to prevent confusion. I also tested this version with the HAFS configuration that uses wave component and also I run wave related regression tests. All of them is passing without any error. BTW, let me know about the schedule of this PR because it is getting older and we might need to sync with develop.

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali told me he would be testing with the up to date ufs-weather-model this morning.  He can let you know more about the exact timing for commit.   With the new change he might need to re-run his test.

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA Okay. That is great. Let me know if you find anything.

**Comment by JessicaMeixner-NOAA** [comment]
@MatthewMasarik-NOAA is working on this exact thing for the global application right now - so he might have more comments on the change that I do.  @aliabdolali let me know if I need to provide any additional help w/the testing

**Comment by aliabdolali** [comment]
@uturuncoglu thanks for the update.
Are you done with the changes? can I go ahead and re-run tests and ufs-weather tests?
Have you merged ther upstream WW3 to your feature branch?

**Comment by uturuncoglu** [comment]
@aliabdolali Yes. That is done. I have already tested wave related RTs and they are fine. I did not sync the branch with the develop but if you want I could do it. Since the changes are isolated into the ESMF cap, I am not expecting any conflict.

**Comment by aliabdolali** [comment]
> @aliabdolali Yes. That is done. I have already tested wave related RTs and they are fine. I did not sync the branch with the develop but if you want I could do it. Since the changes are isolated into the ESMF cap, I am not expecting any conflict.

please merge it. I am going to re-test them tonight.

**Comment by uturuncoglu** [comment]
@aliabdolali done.

**Review by aliabdolali — APPROVED** [review]

**Comment by aliabdolali** [comment]
The WW3 standalone regtests ran successfully on Hera with pre-known non-b4b tests.
The ufs-weather-model tests ran successfully on Hera.

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7136833/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7136834/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7136835/matrixDiff.txt)

**Pull request merged**
