### PR TITLE
Fix knint

### LINKED ISSUE #443: Regtest tp2.17 failing to compile since #350
**Describe the bug**
The ww3_tp2.17 regtest is failing since PR #350 due to an unknown intrinsic KNINT in ww3_grib.ftn.
#350 added ww3_grib.inp files to ww3_tp2.17 and these are being compiled with the NCEP2 switch.
The NCEP2 switch enables lines in ww3_grib.ftn that call the intrinsic KNINT, which is an unknown intrinsic.

**To Reproduce**
Run one of the tp2.17 regression tests, e.g.:
./bin/run_test -c ukmo_cray_gnu -S -s MPI -s NO_PDLIB -w work_a -g a -f -p mpiexec -n 16  -o all ../model ww3_tp2.17

**Expected behavior**
It fails when using the GNU compiler with `Error: Function 'knint' at (1) has no IMPLICIT type`

Interestingly, it DOES compile ok with the CrayFtn compiler, so is KINIT a non-standard extension? I have not managed to fine any reference to it online...

### LINKED ISSUE #531: KNINT is an Intel extension and not portable
**Describe the bug**
The intrinsic routine `knint`, which is a specific routine of `nint`, used in `ww3_grib` is an Intel extension and does not work with GNU compilers.

See: 

https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/a-to-z-reference/m-to-n/nint.html

`knint` takes a real32 argument and returns an int64.

The generic `nint` should be used instead, which is just the generic form on `knint`. Pretty sure`knint` can simply be replaced with `nint` and the compiler handles the overload automatically. I was able to build with gfortran with this change, but haven't actually tested the output.

**To Reproduce**

Attempt to compile ww3_grib with gfortran

**Expected behavior**
Code should be portable

### PR DESCRIPTION
**Pull request by aliabdolali**
# Pull Request Summary
replace KNINT with NINT to be compatible with all compiler options.

## Description
The `knint` in model/src/ww3_grib.F90 routine is an Intel extension and does not work with GNU compilers.
Replacing it with `nint` makes it generic, compatible with GNU and INTEL.
Is a change of answers expected from this PR?  NO

### Issue(s) addressed
* Is there an issue associated with this development (bug fix, enhancement, new feature)?   
- fixes #531
- fixes #443

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)? Yes
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number)
* Please list appropriate labels code managers should add for this PR:   
 _bug_
 
* Reviewers: @kgerheiser 

### Commit Message
*  Portability fix for all compiler options in ww3_grib (KNINT > NINT)

### Testing
* How were these changes tested? regression test
* Are the changes covered by regression tests? yes
* If a new feature was added, was a new regression test added? No
* Have regression tests been run? Yes
* Which compiler / HPC you used to run the regression tests in the PR? Intel/Hera
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_): 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (7 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (6 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (5 files differ)
ww3_ufs1.3/./work_a                     (2 files differ)
```

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7535087/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7535088/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7535089/matrixDiff.txt)

### CODE REVIEW

**Review by kgerheiser — APPROVED** [review]

**Comment by aliabdolali** [comment]
Hi @kgerheiser 
Have you been able to comple ww3_grib with gnu with the fix? Could you tell me which machine you did it?

**Comment by kgerheiser** [comment]
Yep, I was able to compile with this change using GCC 9.4.0 on my local macOS machine.

**Comment by kgerheiser** [comment]
I don't really know how WW3 tests work, but is your test log showing differences in output? I wouldn't expect this change to affect results.

**Comment by aliabdolali** [comment]
Hi @ukmo-ccbunney 
could you check ./bin/run_test -c ukmo_cray_gnu -S -s MPI -s NO_PDLIB -w work_a -g a -f -p mpiexec -n 16 -o all ../model ww3_tp2.17 with GNU compiler to make sure it fixes the problem?

**Comment by ukmo-ccbunney** [comment]
> Hi @ukmo-ccbunney could you check ./bin/run_test -c ukmo_cray_gnu -S -s MPI -s NO_PDLIB -w work_a -g a -f -p mpiexec -n 16 -o all ../model ww3_tp2.17 with GNU compiler to make sure it fixes the problem?

Hi @aliabdolali  - so, this now compiles for me (the KNINT -> NINT fix works for me), but it fails to link.
This is because this test now enables the `NCEP2` switch which hardcodes the following compiler options in the `link` file
```bash
opt="$opt -convert big_endian -assume byterecl -prec-div -prec-sqrt -ip"
```
I believe these options are Intel IFORT specific, so I needed to modify these for the GNU compiler. Additionally, I need to compile the relevant grib/bacio/g2lib libraries to get this regtest to actually compile (link) for me (we don't routinely use grib with the wave model).

However, I am going to approve this PR as the fix for KNINT looks to be working OK.

**Review by ukmo-ccbunney — APPROVED** [review]
KNINT fix worked for me.
I am struggling to test the ww3_tp2.17 regtest at the moment though due to other issues described in this PR's comments.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Pull request merged**
