### PR TITLE
Bugfix/spconv : spectral discretization conversion

### PR DESCRIPTION
**Pull request by mickaelaccensi**
linked to issue #193

**model**
ww3_bounc.ftn : update conversion and interpolation of the spectral discretization
cmplr.env : add "datarmor" in OMP intel

**regtests**
run_test : add tool ncgen to convert ascii to netcdf for input files
matrix.base : add regtest ww3_tp1.11
matrix_datarmor update PATH
create ww3_tp1.11 : nesting with spectral interpolation
                                        ncgen tool needed to convert input ascii files to netcdf files

**matrix**
[matrix_spconv.zip](https://github.com/NOAA-EMC/WW3/files/4581076/matrix_spconv.zip)
done with intel-comp/18, impi/2018.1.163, netCDF-Fortran 4.5.2
expected changes : ww3_tp2.8, ww3_tp2.17 (print in log file ww3_bounc.out)
not b4b : mww3_test_03

**version 7.XX**
regtests/bin/run_test
model/ftn/ww3_bounc.ftn

### CODE REVIEW

**Review by aliabdolali — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
I don't see any code issues, however I am curious if the ww3_bound should also be updated? Or why it wasn't? 

I did try to run: 
./bin/run_test -b slurm -c hera -S -T -o netcdf   -w work_PR3_UQ    ../model ww3_tp1.11 
on NCEPs machine and it failed, so I'm not sure what the issue with that is exactly.

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA 
You need to insert **-N** in your run_test command to use namelist. tp1.11 does not have inp files
i checked it and it ran successfully, including conversion of ascii file to netcdf
./bin/run_test -b slurm -c hera -S -T -N -o netcdf -w work_PR3_UQ ../model ww3_tp1.11

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali  if -N needs to be inserted, then it needs to be inserted in matrix.base.  The command I copied is what I got from matrix after running regtests/bin/matrix_ncep.  That regression test will fail when running matrix on NCEP.  Bug since it does run with the -N option, I'll approve this PR, assuming that -N will be added in matrix.base on a subsequent commit.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by mickaelaccensi** [comment]
@JessicaMeixner-NOAA , ww3_bound.ftn is not updated since it's not used at Ifremer
about the regtest, it is only available with namelist, I've updated the matrix.base

**Pull request merged**
