### PR TITLE
Fix for inconsistent time in air density input

### LINKED ISSUE #811: Inconsistent time in air density input
**Describe the bug**
If driving data is read from file, the consistency of the times in the file is checked in the W3WAVE subroutine. This is done to make sure that the driving data contains valid data for the time of the run. In the case of air density, the times read from the momentum driving data file are used, which is wrong and can cause false errors. To fix the problem, the variables TR0 and TRN have to be used instead of TU0 and TUN when testing the air density file.

**To Reproduce**
Any run using air density but not momentum driving data.

**Expected behavior**
The previously described configuration will fail will with the error:

' *** WAVEWATCH III ERROR IN W3WAVE :'
'     NEW AIR DENSITY BEFORE OLD AIR DENSITY ' 
irrespective of the validity of the driving data.

**Screenshots**

**Additional context**
The proposed fix has been successfully tested at the Met Office using the AMM15-SMC configuration.

### PR DESCRIPTION
**Pull request by ukmo-juan-castillo**
# Pull Request Summary
Fix inconsistent time check in air density input

## Description
f driving data is read from file, the consistency of the times in the file is checked in the W3WAVE subroutine. This is done to make sure that the driving data contains valid data for the time of the run. In the case of air density, the times read from the momentum driving data file are used, which is wrong and can cause false errors. To fix the problem, the variables TR0 and TRN have to be used instead of TU0 and TUN when testing the air density file, which should be evident by reading the code with care.

No change in answers in expected, although configurations using as driving data air density but not momentum will now not fail if set correctly.

Labels that should be added: _bug_

### Issue(s) addressed
- fixes #811 
- fixes noaa-emc/ww3/issues/811

### Commit Message
Fix for inconsistent time check in air density input

### Check list  

- [YES ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ YES] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ N/A] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ N/A] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
Regtests, and the amm15-smc configuration at the Met Office driven by air density.
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
Not covered, and not vital to have it added. Usually, when driving the model with air density the user would like to drive it with momentum too, so the configuration that is failing will not typically be used.
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
Yes, on the CrayXC40 at the Met Office using the GNU compiler.
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
No changes expected
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):
See comment below.

### CODE REVIEW

**Comment by ukmo-ccbunney** [comment]
Changes look good to me. I am running the regressions tests.

**Comment by ukmo-ccbunney** [comment]
Regression tests passed ok, just the usual suspects not B4B
```

**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (11 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (10 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
```

**Comment by MatthewMasarik-NOAA** [comment]
Hi @ukmo-juan-castillo , thank you for this pull request!  I've started running the regressions tests on our end.  @JessicaMeixner-NOAA is out today, but will return on Monday and we will finalize this PR at that time.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
regression tests passed on hera with the known non-identicals + unstructured mod_defs.
```bash
**********************************************************************                                                             
********************* non-identical cases ****************************                                                             
**********************************************************************                                                             
mww3_test_03/./work_PR2_UNO_MPI_d2                     (10 files differ)                                                           
mww3_test_03/./work_PR1_MPI_d2                     (16 files differ)                                                               
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (12 files differ)                                                         
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)                                                          
mww3_test_03/./work_PR3_UNO_MPI_d2                     (15 files differ)                                                           
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)                                                            
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)                                                            
ww3_ta1/./work_UPD0F_U                     (0 files differ)                                                                        
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)                                                                    
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)                                                                    
ww3_tp2.17/./work_ma                     (1 files differ)                                                                          
ww3_tp2.17/./work_mc1                     (1 files differ)                                                                         
ww3_tp2.17/./work_mb                     (1 files differ)                                                                          
ww3_tp2.17/./work_mc                     (1 files differ)                                                                          
ww3_tp2.17/./work_ma1                     (1 files differ)                                                                         
ww3_tp2.6/./work_ST0                     (1 files differ)                                                                          
ww3_tp2.6/./work_ST4                     (1 files differ)                                                                          
ww3_tp2.6/./work_pdlib                     (1 files differ)                                                                        
ww3_ufs1.3/./work_a                     (1 files differ)                                                                                                                                                                                             
**********************************************************************                                                             
************************ identical cases *****************************                                                             
**********************************************************************
```

* [matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/9700608/matrixCompSummary.txt)
* [matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/9700609/matrixCompFull.txt)
* [matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/9700613/matrixDiff.txt)

**Comment by MatthewMasarik-NOAA** [comment]
Thanks again for your work, @ukmo-juan-castillo !

**Pull request merged**
