### PR TITLE
Cleaned version of production/GLWUv2

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
To satisfy operational needs, provide a clean version of production/GLWUv2 in the branch prod/GLWUv2 

## Description

Clean out manual and testing directories to provide a simplified code for operational GLWUv2. 

### Commit Message
Reduce the list of executables compiled and clean out testing and manual code for operational hand-off. 

### Check list  
N/A

### Testing

* How were these changes tested? This was tested via operational workflow.

### CODE REVIEW

**Review by MatthewMasarik-NOAA — APPROVED** [review]
**Code review**
This PR trims down the GLWUv2 branch to just what is needed for it's operations.  Changes include:
* files removed.
* edits to `./model/src/CMakeLists.txt` to remove programs from the list of executables being built to just those been used.

**Testing**
This branch has been tested by @JessicaMeixner-NOAA via the operational workflow.

This PR is approved.

**Comment by JessicaMeixner-NOAA** [comment]
> **Testing** This branch has been tested by @JessicaMeixner-NOAA via the operational workflow.

To clarify this testing was done by @sbanihash not me.

**Comment by JessicaMeixner-NOAA** [comment]
@sbanihash - you've been officially added as a reviewer.  I'll wait for your confirmation before merging this.

**Comment by MatthewMasarik-NOAA** [comment]
> > **Testing** This branch has been tested by @JessicaMeixner-NOAA via the operational workflow.
> 
> To clarify this testing was done by @sbanihash not me.

Thank you for clarifying @JessicaMeixner-NOAA.

**Review by sbanihash — APPROVED** [review]

**Pull request merged**
