### PR TITLE
Flexible restart write times (restart_fh)

### PR DESCRIPTION
**Pull request by NickSzapiro-NOAA**
# Pull Request Summary
 
This PR enables writing forecast hour defined restarts ("restart_fh") in the same way as space-delimited floating point forecast hours in model_configure attributes, like `restart_fh: 0.25 2.5 6 17 24`. The [current restart_fh in MOM6](https://github.com/ufs-community/ufs-weather-model/pull/2099) is for integer forecast hours. This will allow CMEPS, MOM6, CICE, and WW3 to have option of forecast hour restarts in addition to existing functionality. Restart writes are triggered when input restart_fh forecast hours are evenly divisible by a component's timestep (internally compared in units of integer seconds) and skipped otherwise.

Testing with cpld_control_gfsv17 confirms that restarts are b4b when (1) sharing common times with RESTART_N and (2) instead of RESTART_N. This feature is exercised in ufs-weather-model regression testing (see https://github.com/ufs-community/ufs-weather-model/pull/2419)

## Description

Building on recent netcdf restart capability, enhancement allows for arbitrary restart times. This is useful for IAU methods, for example.

### Issue(s) addressed

Closes https://github.com/ufs-community/ufs-weather-model/issues/2348

### Commit Message

Flexible restart write times (restart_fh)

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [x] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by NickSzapiro-NOAA** [comment]
Maybe I don't have permissions to suggest you as reviewers, @MatthewMasarik-NOAA @JessicaMeixner-NOAA

**Comment by MatthewMasarik-NOAA** [comment]
> Maybe I don't have permissions to suggest you as reviewers, @MatthewMasarik-NOAA @JessicaMeixner-NOAA

@NickSzapiro-NOAA I just added myself as a reviewer for the time being.  @JessicaMeixner-NOAA, @sbanihash and I will talk offline to decide on who will take the lead reviewing.

**Comment by NickSzapiro-NOAA** [comment]
Hi, can I ask if there is any feedback? fwiw, I imagine the "is_restart_fh?" module could be duplicated and added to WW3 source as well (it only depends on ESMF) if the linking is the issue

**Comment by sbanihash** [comment]
@NickSzapiro-NOAA Nick, I have your reviewed the changes in this PR and I don't have any concerns over your particular changes, but what is holding us up at this point is the [build issue](https://github.com/ufs-community/ufs-weather-model/issues/2502) that has been caused by the last PR that was merged into dev/ufs-weather-model branch. We are working on a fix for that issue and as soon as that is final, I could do a final check on this PR and we should be good to go. Thanks for your patience.

**Comment by NickSzapiro-NOAA** [comment]
Thanks for letting me know, @sbanihash !

**Review by sbanihash — APPROVED** [review]
Changes have been reviewed. WW3 build with this PR and with the addition of PR[#1324](https://github.com/NOAA-EMC/WW3/pull/1324) have been successful in both the stand alone mode and within the global workflow (build_ww3prepost). No changes required other than PR#1324 that is needed to address  issue [#2502](https://github.com/ufs-community/ufs-weather-model/issues/2502)

**Comment by FernandoAndrade-NOAA** [comment]
Testing on [#2419](https://github.com/ufs-community/ufs-weather-model/pull/2419) has completed successfully, please continue with the merge process.

**Pull request merged**
