### PR TITLE
Fix block explicit loop index

### LINKED ISSUE #974: block explict breaks domain reproducibility
**Describe the bug**

This work is related to UFS Issue [1556](https://github.com/ufs-community/ufs-weather-model/issues/1556)

Prior to the merge of the WISE PR (#888), I tested the changes in my feature branch for the unstructured mesh extension to the mesh cap. Not being a wave modeler however, it did not occur to me that I needed to create a new mod_def to flip namelist switches. So I made my test using the wrong settings.

@aliabdolali provided me the correct values for the unstructured mesh + explicit from the standalone regtest (``ww3_ufs1.1/input_unstr/ww3_grid_b.inp``)

When I re-tested with an appropriate mod_def, the domain-decomposition test in my ATM-WAV case now failed. The difference in the exported ``Z0`` between a 5PE and 10PE case is shown below

wavImp_Sw_z0_2021-03-22-24480

Clearly a ghost update is missing. I have a fix and will open a PR.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# Pull Request Summary
 

Extends the update of ``VA`` at the end of the block explict to use the ghost points also.

### Issue(s) addressed

- fixes #974 (LN 6599 in ``w3profsmd_pdlib.F90``)
- also removes trailing whitespace and fixes the indenting for ``w3wavemd.F90`` associated with the removal of an if statement (PR #888)

### Commit Message

Extend loop to include ghost points for ``VA``

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
@DeniseWorthen this is excellent news!  What a great way to end the week, thank you.  

On the last PR we merged (ww3_gint), @JessicaMeixner-NOAA and I noticed the restart files for the ww3_ufs1.1 grid b unstr regtest were not reproducing.  It was not related to the gint PR so we added it to the list of known non-b4b tests and had planned to return to investigate.  This is a real big help for us.  I'll submit the regtests right now.

@aliabdolali @aronroland @thesser1 requesting reviews as the original developers

**Comment by MatthewMasarik-NOAA** [comment]
Update:  I needed to re-run a test for this today, which is currently running.  This is on track to be merged this afternoon or early tomorrow if no issues are found.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
**Code review** Pass

**Regtests** Pass
* develop vs. fix confirm non-b4b except for the knowns, and ww3_ufs1.1 unstructured grid b.
[1.matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/11201271/1.matrixCompFull.txt)
[1.matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/11201272/1.matrixCompSummary.txt)
matrixDiff.txt - too large to include.

* fix against itself confirms ww3_ufs1.1 unstructured grid b reproduces.
[2.matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/11201291/2.matrixDiff.txt)
[2.matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/11201292/2.matrixCompFull.txt)
[2.matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/11201293/2.matrixCompSummary.txt)

**Comment by MatthewMasarik-NOAA** [comment]
Thank you @DeniseWorthen for this bug fix for the new block explicit solver.

**Review by aronroland — COMMENTED** [review]
Hey Denise, great catch! This is all valid!
Cheers
Aron

**Pull request merged**
