### PR TITLE
Remove NCC switch

### LINKED ISSUE #353: Remove the NCC switch
The NCC switch is used for coupling via the in-house NCEP coupler.  We plan to remove support for NCC in the develop branch of the code and remove all NCC switch related code. 

This work is planned for the end of May 2021.  FYI @BinLiu-NOAA

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
This PR removes the NCC switch, which was used for the in-house NCEP coupler.   

## Description
As NCEP is not going to use the in-house NCEP coupler moving forward, the NCC switch, which was used for this coupling, is being removed.  There should be no answer changes with this PR. 

### Issue(s) addressed
- closes #353 

### Testing
* The regression tests were ran and compared with an older version of the develop branch using hera.intel.  Only the expected tests were not b4b. The regression tests will be re-run and the matrix results will be attached before committing to the repository.

### CODE REVIEW

**Review by aliabdolali — APPROVED** [review]
It looks ok to me.

**Comment by aliabdolali** [comment]
I assume the ncc(s) in regtests/ww3_tp2.16/input/*.pro are not related, right?

**Comment by JessicaMeixner-NOAA** [comment]
Correct, there is no association to the NCC switch to the ncc in the regtests/ww3_tp2.16/input/*.pro. 

I'm running the comparison script now and will post the results here in an hour or so.

**Comment by JessicaMeixner-NOAA** [comment]
Only the normal tests are not b4b: 
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (10 files differ)
mww3_test_04/./work_PR3_UQ_MPI_NC_b_c                     (1 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.15/./work_5km                     (1 files differ)
ww3_tp2.15/./work_MPI_5km                     (1 files differ)
ww3_tp2.18/./work_TIDE_MPI                     (1 files differ)

Comparison output files: 
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/6631995/matrixDiff.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/6631996/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/6631998/matrixCompSummary.txt)

**Pull request merged**
