### PR TITLE
UKMO Cray bugfixes

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
Changes required to run full regtest suite on Cray HPC using the crayftn compiler.

Adds the following fearures:
 - New comp/link scripts for matrix generation file. (d85e386)

And addresses the following issues:
- #95 Erroneous commas in w3uostmd and w3iogrmd (cf1ad39)
- #96 Invalid Fortran unit number in w3uostmd (ad28d89)
- #93 regtest ww3_tp2.10 instability (0d17768)
- #92 OMP switches missing in w3psmcmd (6a3864d)
- #98 Non advancing WRITE statement causing "record too long" error (5362e11)
- #94 Typo in WMINITMD with MPRF switch (2b41012)
- Removed extraneous brackets from implied DO loop read statment (fdfd93e)

### CODE REVIEW

**Comment by ajhenrique** [comment]
Thanks @ukmo-ccbunney. We are moving away from the platform/compiler-specific comp and link files towards using the cmplr.env and generic comp.tmpl and link.tmpl. Does this PR include changes to those files that would allow usage of the cmplr.env, comp.tmpl and link.tmpl without referring to any other external script/file? In the near future we will eliminate all platform/compiler-specific comps and links from the package.

**Comment by ukmo-ccbunney** [comment]
@ajhenrique - yes the PR does include an update to cmplr.env to include "cray_xc". Would you prefer it if I removed the comp.cray_xc.CCE and link.cray_xc.CCE scripts?

**Comment by ajhenrique** [comment]
@ukmo-ccbunney please merge the auth repo develop into the branch associated with this PR. We can then move to get it merged into the NOAA-EMC/WW3 develop. Thanks!

**Comment by ukmo-ccbunney** [comment]
Develop branch has been merged in: https://github.com/NOAA-EMC/WW3/pull/105/commits/56857cdfc01c0629bd2c96037fbb33ac32b39fb1

Do you want me to rerun the regtests matrix?

**Comment by aliabdolali** [comment]
Hi @ukmo-ccbunney @ajhenrique 
I ran the regression tests at our end and came with the following differences:
- For ww3_tp2.10, the time step has changed from `450 90 90 90` to `450 60 60 60`. Was it on purpose? As a result, we have different answers.
- The outputs for _ww3_ts1/work_ST6_ are different. Do we expect these differences?

The rests look ok to me. 
Comparison attached.
Regards
AA
[COMP_UKMO.zip](https://github.com/NOAA-EMC/WW3/files/3772314/COMP_UKMO.zip)

**Comment by ukmo-ccbunney** [comment]
Hi @aliabdolali 

The differences in _ww3_tp2.10_ are expeced as the timestep was too large resulting in the model going unstable (when I ran the test originally, the output was mostly NaN values!)

However, I cannot see reason why the output _ww3_ts1_ should be different. I have not changed anything to do with the source terms. I notice that the tab*.ww3 files are identical in the work directories, so the differences must be very small. I can't see why only the _ww3_ts1_ test should be affected. Could it be linked to the fact that the _mww3*_ tests are not bit comparible?

Chris.

**Comment by ajhenrique** [comment]
Hi @aliabdolali could you provide details of the differences you encountered in ww3_ts1?

**Comment by aliabdolali** [comment]
@ukmo-ccbunney @ajhenrique 
For ww3_tp2.10, we will go with smaller time steps. 
For ww3_ts1, I see the differences in ww3.196806.nc
Please check the end of matrixDiff.out in the zip folder. 
Ali

**Comment by ajhenrique** [comment]
> @ajhenrique - yes the PR does include an update to cmplr.env to include "cray_xc". Would you prefer it if I removed the comp.cray_xc.CCE and link.cray_xc.CCE scripts?

@ukmo-ccbunney that would be great if it doesn't affect your work. The idea will be to soon remove all individual comp and link files, not adding new ones unless they are essential is a good way to start cleaning up! Thanks.

**Comment by ukmo-ccbunney** [comment]
@aliabdolali, @ajhenrique 
Regarding the differences in the `ww3_ts1` regtest: I have just run the all the `ww3_ts1` tests on the `develop` branch code and compared them with the results from the `bf_ukmo_cray` branch and the results are identical.

**Comment by ukmo-ccbunney** [comment]
> @ajhenrique - yes the PR does include an update to cmplr.env to include "cray_xc". Would you prefer it if I removed the comp.cray_xc.CCE and link.cray_xc.CCE scripts?

>> @ukmo-ccbunney that would be great if it doesn't affect your work. The idea will be to soon remove all individual comp and link files, not adding new ones unless they are essential is a good way to start cleaning up! Thanks.

@ajhenrique OK -  I will remove the comp and link files for the Cray XC and add the cray_xc.GNU compiler setup to the cmplr.env file (I've already added the cray_xc.CCE one).

One question regarding the compiler setups - why are the Intel and GNU compiler options set up to hardcode the byte order to "big-endian"? I would prefer to keep the native (little-endian in our case) byte order when compiling with the GNU compiler. Are you happy if I modify the GNU section of `cmplr.env` slightly to make `-fconvert=big-endian` a system dependent option (native for cray_xc, big-endian for everything else)?

**Comment by ghost** [comment]
Hi @ukmo-ccbunney, from what I remember about the big-endian option, the aim was to avoid mixing the way binary files are created by ww3 on differents file systems to be able to safely exchange binary files. So it would be better to keep it as default except if it slow down your computation time.

**Comment by ukmo-ccbunney** [comment]
@maccensi I note that profiling (-p switch) is always enabled via the "common options". Is this intentional?
We probably would not want that enabled for operational executables (there must be a perfomance hit to having it on?)

**Comment by ghost** [comment]
There is almost no extra overhead using -p switch since it's just camping time functions. At least from I tested on our system and from what I read on the documentation about flat profiling but it could be good to test it again, I will do it

**Comment by ukmo-ccbunney** [comment]
> There is almost no extra overhead using -p switch since it's just camping time functions. 
Ok - thanks @mickaelaccensi.

**Comment by ajhenrique** [comment]
@ukmo-ccbunney @mickaelaccensi I've read here and there that there may be a performance hit in runs over long periods of time using massive resources. I am currently running a test with our coupled system with and without the profiling flag, and will report back to this thread as well.

**Comment by ajhenrique** [comment]
> Hi @ukmo-ccbunney, from what I remember about the big-endian option, the aim was to avoid mixing the way binary files are created by ww3 on differents file systems to be able to safely exchange binary files. So it would be better to keep it as default except if it slow down your computation time.

@ukmo-ccbunney, I agree with @mickaelaccensi . Please indicate if this results in overheads for your system.

**Comment by ajhenrique** [comment]
@mickaelaccensi @ukmo-ccbunney I've completed a first set of tests running our coupled FV3-WW3 ensemble system. This is currently the operational cube sphere for FV3, and a mosaic of 3 grids in WW3 at 1/4 deg resolution (Arctic, core and Antarctic), with 30 perturbed members + 1 control, which are run out to 16 days. I used a Dell machine with 28 cores per node, the run had 14 ppn and 2 OMP threads, and a total of 38 nodes (532 MPI processes per member). With/without the -p flag the control  ran ~61min/57min, and the perturbed members averaged ~69min/66min. There is small but noticeable shaving off of time in our system when -p is removed.

**Comment by JessicaMeixner-NOAA** [comment]
@ajhenrique  Did you remove the -p just for WW3 or both FV3 and WW3?

**Comment by ajhenrique** [comment]
> @ajhenrique Did you remove the -p just for WW3 or both FV3 and WW3?

@JessicaMeixner-NOAA, Only WW3.

**Comment by JessicaMeixner-NOAA** [comment]
Adding more WW3 pets might further reduce the runtime since it seems that WW3 is potentially what's holding back the total timing. Or if you now hit the FV3 time, that -p could even further reduce your runtime from the amount you already saw.  Either way it looks like good news for the GEFSv12 timings!

**Comment by ghost** [comment]
that's a great news ! so it would be good to put the '-p-' option in a specific profiling section, with _prof suffix like it's done for debugging option with suffix _debug

**Comment by ajhenrique** [comment]
@mickaelaccensi that would be preferable. I can do that in a commit to our GEFS_v12 implementation branch and merge it back to develop.

**Comment by ukmo-ccbunney** [comment]
Excellent! Sounds like an easy win. :)

**Comment by ukmo-ccbunney** [comment]
I've just pushed up a commit (c134eff ) that removes the Met Office specific comp/link files and updates the cmplr.env with build configs for our Cray HPC using craytfn and gfortran.

**Comment by ajhenrique** [comment]
@aliabdolali what is the final recommendation for this PR? I've added both you and @JessicaMeixner-NOAA as reviewers. I look forward to both reviews.

**Comment by aliabdolali** [comment]
@ajhenrique The suspicious regression test behaves differently on our machine than UKMO's machine. As you can see, Chris has tested that test with the code before and after development and they were identical. So we either need to move on or we investigate more. The rest of the tests are OK.

**Review by aliabdolali — APPROVED** [review]

**Comment by ajhenrique** [comment]
@ukmo-ccbunney @aliabdolali @JessicaMeixner-NOAA I reran the matrix for ww3_ts1 and had the following output in matrixCompSummary.out
test(s)        :
ww3_ts1

********************* non-identical cases ****************************

************************ identical cases *****************************
ww3_ts1/./work_ST6
ww3_ts1/./work_ST1_RWND
ww3_ts1/./work_ST4_WRT
ww3_ts1/./work_ST4_GMD
ww3_ts1/./work_ST4_TSA
ww3_ts1/./work_ST4
ww3_ts1/./work_ST1
ww3_ts1/./work_ST2
ww3_ts1/./work_ST3

I'm not sure what happened in the previous matrix run, but I'll consider this a done deal and will be ready to merge asap, given @aliabdolali accepted his review, if @JessicaMeixner-NOAA concurs in her review.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by ajhenrique** [comment]
Thanks everybody in this thread for your comments. @ukmo-ccbunney please close issues related to this PR, and make sure you back up some of the discussions above that may be useful elsewhere. Merging!

**Comment by ukmo-ccbunney** [comment]
Fantastic. Thanks everyone.

**Pull request merged**
