### PR TITLE
update run_cmake_test to catch build errors and exit

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
Update run_cmake_test to better capture build errors 

## Description
Updates run_cmake_test to make sure we catch build errors and exit instead of continuing on. 

Please also include the following information: 
* Add any suggestions for a reviewer  @ukmo-ccbunney @MatthewMasarik-NOAA 
* Mention any labels that should be added:  _bug_,
* Are answer changes expected from this PR? No 

### Issue(s) addressed
No issue, found investigating other issues. 

### Commit Message
update run_cmake_test to catch build errors and exit

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? Yes - I made sure it caught build errors in a branch with known errors and I ran full matrix of test 
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Yes, bug fix
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? yes  hera, intel 
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.) Only the known non-b4b tests. 
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (18 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)

```
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/14389087/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/14389088/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/14389089/matrixDiff.txt)

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@ukmo-ccbunney would you mind testing to make sure this also captures the build errors that were not being properly caught before?

**Comment by MatthewMasarik-NOAA** [comment]
Glad this was caught and a solution found!  I'll start the testing for EMC.

**Comment by JessicaMeixner-NOAA** [comment]
@ukmo-ccbunney  any objections to this PR? Does this also catch the build errors you saw?

**Comment by ukmo-ccbunney** [comment]
> @ukmo-ccbunney any objections to this PR? Does this also catch the build errors you saw?

Apologies - I entirely missed this PR for some reason. On the face of it I have no objections - it looks good. I will do a quick test today,

**Comment by ukmo-ccbunney** [comment]
@JessicaMeixner-NOAA - I've tested this and it works well for me. Thanks for the update!

**Comment by MatthewMasarik-NOAA** [comment]
> @JessicaMeixner-NOAA - I've tested this and it works well for me. Thanks for the update!

Thanks for testing this @ukmo-ccbunney!  I'll submit the tests @JessicaMeixner-NOAA.

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA as we discussed offline, my tests had some extra non-b4b's, so I'm going to re-run the tests.  They've been submitted.

**Comment by MatthewMasarik-NOAA** [comment]
> @JessicaMeixner-NOAA as we discussed offline, my tests had some extra non-b4b's, so I'm going to re-run the tests. They've been submitted.

The new runs had only the known non-b4b's as differences.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
**Code review**
Pass

**Testing**
Pass

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (19 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
 
**********************************************************************
************************ identical cases *****************************
**********************************************************************
```

Approved.
* [matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/14572524/matrixCompSummary.txt)
* [matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/14572522/matrixCompFull.txt)
* [matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/14572523/matrixDiff.txt)

**Comment by MatthewMasarik-NOAA** [comment]
Thanks for catching this bug @JessicaMeixner-NOAA.

**Pull request merged**
