### PR TITLE
Bring additional changes to support UFS Coastal App

### PR DESCRIPTION
**Pull request by uturuncoglu**
# Pull Request Summary
This PR aims to bring minor modifications to support UFS Coastal App specific model configurations.

## Description
Following is the list of the changes,

- Optional `BUILD_TOOLS` option is included to build system to build tools. This is `OFF` by default and does not change the current behavior.
- We add `SCRIP` and `SCRIPNC` to `model/bin/switch_meshcap_pdlib` switch file since the mesh file was not generated by default. If this is not right way to do it maybe we could create another copy of this file and point that one under UFS Coastal App.
- The mesh cap `model/src/wav_comp_nuopc.F90` is modified to support standalone runs under ufs-weather-model. Once `standalone` option under wave section of `ufs.configure` is set to `true`, then the model reads its own forcing rather than getting data from coupling. So, this will allow standalone wave configurations without any other component.
- The mesh cap is fixed to export stress components (`Sw_wavsuu`, `Sw_wavsuv` and `Sw_wavsvv`) in a correct way.  This is tested with SCHSIM ocean model coupling with DATM+SCHSIM+WW3 configuration.

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? 
The changes are tested under UFS Coastal App.

* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA I created a draft PR that includes minor changes for UFS Coastal App. I was using `dev/ufs-weather-model` branch as a reference for UFS Coastal since it is used by the UFS Weather Model. Please let me know what you think. I am not sure about the right way to merge these changes but I think this PR will start the discussion and I could adjust the changes according to your suggestions. Maybe we need to port this changes to develop and open a PR to it. I am also adding @janahaddad to the discussion since she is the project manager in UFS Coastal side and she might need to aware of this PR.

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA I'll also run couple of tests that is found in ufs-weather-model to be sure those changes are not affecting any existing configurations.

**Comment by JessicaMeixner-NOAA** [comment]
@uturuncoglu  thanks for making this PR!!!  I look forward to looking into this PR in detail.  It will likely be early next week before I provide additional comments so I can take the time to look with proper attention. Again - thanks for making this PR!

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA Sure. No worries. I am still on vacation but will return next week.

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA Sorry for being late about changes that we discussed in our last call. As we decided, I'll remove the modifications related with build, cap changes to allow standalone WW3 run and also the switch file. So, the only remaining part would be the fix for the NUOPC cap that allows coupling through the radiation stress component. I am plaining to create another branch for it and new PR in here. Once, it is ready, I'll close this draft PR and continue to the conversation in new PR. Let me know what you think?

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA I have just checked the `dev/ufs-weather-model` branch and it seems that the fix that we put for coastal model about radiation stress is already in there. It seems that `Sw_wavsuu`, `Sw_wavsuv` and `Sw_wavsvv` are fine. So, maybe we don't need to push anything from coastal side since the fix is already is in place. I am plaining to check the once of the WW3 regression test with `dev/ufs-weather-model` branch to see what happens. I'll keep you updated.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for the update @uturuncoglu that sounds great!

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA Closing this since we have new PR - https://github.com/NOAA-EMC/WW3/pull/1272

**Pull request closed without merging**
