### PR TITLE
NCEP regtest module updates:  uses spack-stack/1.5.0, includes scotch/7.0.4

### LINKED ISSUE #1121: Update RDHPCS regtest modules for spack-stack 1.5.0 and scotch/7.0.4
**Is your feature request related to a problem? Please describe.**
Bring the NCEP RDHPCS regtest modules up-to-date with the current `spack-stack` containing the updated `scotch` install.

**Describe the solution you'd like**
The modules should be updated relative to the current ufs-weather-model modulefiles.

**Describe alternatives you've considered**
The modules could be left using the `hpc-stack` settings, and not make use of the new `spack-stack` RDHPCS installations of the bugfix scotch version, `v7.0.4`.  This would involve maintenance of the code manager install of `scotch`.

**Additional context**
NA.

### PR DESCRIPTION
**Pull request by MatthewMasarik-NOAA**
# Pull Request Summary
Updates the module environment used for NCEP's regtests on RDHPCS machines to use the `spack-stack/1.5.0` stack which includes `scotch/7.0.4`.

## Description
* Key points about this update:
  * Switches to `spack` -based `spack-stack` module stack.  Previously the `hpc-stack` module stack has been used.
  * A module version of `scotch` is used.  Previously the `export`-ed `SCOTCH_PATH` parameter pointed to a local installation.
  * The RDHPCS machines this update applies to are `hera` and `orion`.  
* Mention any labels that should be added: 
  *  _enhancement_
* Are answer changes expected from this PR? 
  * Yes. 
* Please describe the changes and the reason why in addition to which of the following labels would apply: 
  *  Some answers changes are expected and due only to the change in the **module environment**.
  *  _out_grd change_, _out_pnt change_, _restart file change_, _Regression test_ 

### Issue(s) addressed
* Please list any issues associated with this PR, including those the PR will fix/close. For example:  
  - fixes #1121 

### Commit Message
NCEP regtest module updates:  uses spack-stack/1.5.0, includes scotch/7.0.4

### Check list  
- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [na] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [na] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
  *  Answers cannot be expected to reproduce between differing modules stack environments, so the PR branch was run against itself on both `hera` and `orion`.
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
  * NA (we cannot/do not test for module environment changes).
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
  * `hera/intel`, `orion/intel`. 
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
  * Changes are expected from previous stack.  The PR branch runs against itself have no unexpected changes. 
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

**orion**
Note:  The `(0 files differ)` all checkout as soft links from `input/` that have gone bad.  It is completely benign.  Once these are removed only the known non-b4b are left.

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_02/./work_PR3_UQ_MPI_b_c                     (0 files differ)
mww3_test_02/./work_PR3_UNO_d                     (0 files differ)
mww3_test_02/./work_PR3_UQ_MPI_d                     (0 files differ)
mww3_test_02/./work_PR2_UNO_MPI_a                     (0 files differ)
mww3_test_02/./work_PR2_UQ_a                     (0 files differ)
mww3_test_02/./work_PR2_UNO_c                     (0 files differ)
mww3_test_02/./work_PR3_UQ_c                     (0 files differ)
mww3_test_02/./work_PR3_UQ_MPI_c                     (0 files differ)
mww3_test_02/./work_PR3_UNO_MPI_b                     (0 files differ)
mww3_test_02/./work_PR3_UQ_MPI_a                     (0 files differ)
mww3_test_02/./work_PR1_a                     (0 files differ)
mww3_test_02/./work_PR1_MPI_c                     (0 files differ)
mww3_test_02/./work_PR3_UNO_MPI_c_c                     (0 files differ)
mww3_test_02/./work_PR3_UNO_MPI_d_c                     (0 files differ)
mww3_test_02/./work_PR2_UNO_d                     (0 files differ)
mww3_test_02/./work_PR3_UQ_MPI_c_c                     (0 files differ)
mww3_test_02/./work_PR3_UQ_c_c                     (0 files differ)
mww3_test_02/./work_PR3_UQ_MPI_d_c                     (0 files differ)
mww3_test_02/./work_PR3_UQ_b_c                     (0 files differ)
mww3_test_02/./work_PR3_UQ_a_c                     (0 files differ)
mww3_test_02/./work_PR3_UNO_a                     (0 files differ)
mww3_test_02/./work_PR3_UNO_b_c                     (0 files differ)
mww3_test_02/./work_PR2_UNO_b                     (0 files differ)
mww3_test_02/./work_PR2_UQ_MPI_a                     (0 files differ)
mww3_test_02/./work_PR2_UQ_MPI_c                     (0 files differ)
mww3_test_02/./work_PR2_UQ_b                     (0 files differ)
mww3_test_02/./work_PR2_UNO_MPI_c                     (0 files differ)
mww3_test_02/./work_PR3_UQ_MPI_a_c                     (0 files differ)
mww3_test_02/./work_PR3_UQ_d                     (0 files differ)
mww3_test_02/./work_PR1_MPI_a                     (0 files differ)
mww3_test_02/./work_PR3_UQ_b                     (0 files differ)
mww3_test_02/./work_PR1_MPI_d                     (0 files differ)
mww3_test_02/./work_PR3_UNO_MPI_c                     (0 files differ)
mww3_test_02/./work_PR3_UNO_MPI_b_c                     (0 files differ)
mww3_test_02/./work_PR3_UQ_MPI_b                     (0 files differ)
mww3_test_02/./work_PR1_c                     (0 files differ)
mww3_test_02/./work_PR3_UQ_d_c                     (0 files differ)
mww3_test_02/./work_PR3_UNO_MPI_d                     (0 files differ)
mww3_test_02/./work_PR2_UQ_MPI_b                     (0 files differ)
mww3_test_02/./work_PR2_UNO_MPI_d                     (0 files differ)
mww3_test_02/./work_PR3_UNO_MPI_a                     (0 files differ)
mww3_test_02/./work_PR2_UQ_c                     (0 files differ)
mww3_test_02/./work_PR1_b                     (0 files differ)
mww3_test_02/./work_PR2_UNO_a                     (0 files differ)
mww3_test_02/./work_PR3_UNO_c                     (0 files differ)
mww3_test_02/./work_PR3_UNO_b                     (0 files differ)
mww3_test_02/./work_PR2_UNO_MPI_b                     (0 files differ)
mww3_test_02/./work_PR3_UQ_a                     (0 files differ)
mww3_test_02/./work_PR2_UQ_MPI_d                     (0 files differ)
mww3_test_02/./work_PR2_UQ_d                     (0 files differ)
mww3_test_02/./work_PR1_d                     (0 files differ)
mww3_test_02/./work_PR3_UNO_a_c                     (0 files differ)
mww3_test_02/./work_PR3_UNO_MPI_a_c                     (0 files differ)
mww3_test_02/./work_PR1_MPI_b                     (0 files differ)
mww3_test_02/./work_PR3_UNO_c_c                     (0 files differ)
mww3_test_02/./work_PR3_UNO_d_c                     (0 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (11 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (18 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_ta1/./work_UPD5_U                     (0 files differ)
ww3_ta1/./work_UPD6_U                     (0 files differ)
ww3_ta1/./work_UPD0F_O                     (0 files differ)
ww3_ta1/./work_UPD5_O                     (0 files differ)
ww3_ta1/./work_UPD2_O                     (0 files differ)
ww3_ta1/./work_UPD6_O                     (0 files differ)
ww3_ta1/./work_UPD5_U_cap                     (0 files differ)
ww3_ta1/./work_UPD6_U_cap                     (0 files differ)
ww3_ta1/./work_UPD3_O                     (0 files differ)
ww3_ta1/./work_UPD3_U                     (0 files differ)
ww3_ta1/./work_UPD2_U                     (0 files differ)
ww3_ta1/./work_UPD2_U_cap                     (0 files differ)
ww3_ta1/./work_UPD3_U_cap                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
 
**********************************************************************
************************ identical cases *****************************
**********************************************************************
```

[orion.matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/13602285/orion.matrixCompSummary.txt)
[orion.matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/13602284/orion.matrixDiff.txt)
[orion.matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/13602286/orion.matrixCompFull.txt)

**hera**
Here only known non-b4bs present.

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
 
**********************************************************************
************************ identical cases *****************************
**********************************************************************
```

[hera.matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/13602302/hera.matrixCompSummary.txt)
[hera.matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/13602301/hera.matrixDiff.txt)
[hera.matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/13602303/hera.matrixCompFull.txt)

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA  PR header will be cleaned up tomorrow.

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA PR header is cleaned up and ready.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Thanks for making this update Matt.  It's good that things are now running on orion again.  

Testing orion vs itself I got the following diffs: 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_02/./work_PR1_MPI_c                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (16 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/13605060/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/13605061/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/13605062/matrixDiff.txt)



So essentially the normal + an odd log file diff for mww3_test_02/./work_PR1_MPI_c  which is not concerning.  
For record keeping here's the diffs vs develop (which did not have an existing scotch library so not all tests succeeded): 

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/13605063/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/13605064/matrixCompSummary.txt)


For Hera, which is what most regtests are looking for we have the following diffs when comparing against itself: 
```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (12 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (18 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```


[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/13605073/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/13605074/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/13605075/matrixDiff.txt)


For tracking purposes here are the differences with develop: 

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/13605080/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/13605081/matrixCompSummary.txt)

The main differences here are that the gribs do not match themselves and scotch tests have differences that are small in magnitude.

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA thanks for the detailed review.  It's great to have that info for posterity.

**Pull request merged**
