### PR TITLE
Update mesh cap branch w/ latest develop; add time off-set fix 

### LINKED ISSUE #870: Wave model cannot restart if mediator flag is set to startup
**Describe the bug**
The wave model cannot start if wave information is not in the coupler.  The solution should be to set
start_type = startup in the nems.configure file, but when doing this, WW3 gets the wrong model time.

**To Reproduce**
set KEEP to true in rt.sh
Run the cpld_control_p8 and cpld_restart_p8 tests.
In the cpld_restart_p8 directory change
start_type = continue to
start_type = initial
and model will have an error with a time mismatch.

**Expected behavior**

The wave model should be initialing with the current time, not the forecast start time.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# Pull Request Summary
 

Update dev/ufs-weather-model branch 

## Description

- Updates mesh cap branch to replace ``ifdef MEMCHECK`` code blocks with single ``print_memcheck``  call
- Updates setting of charn to use ST3 or ST4 flags in place of ``CESMCOUPLED`` and ``UWM``
- Updates the clock to use add time-offset for initial runtypes, which can be non-zero for UWM in certain cases

### Issue(s) addressed

- fixes #870
### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

All RTs using dev/ufs-weather-model are B4B on hera.intel and hera.intel. See https://github.com/ufs-community/ufs-weather-model/pull/1591

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen    ----  Please do not combine a merge from develop with your updates here.  @MatthewMasarik-NOAA and I will take care of merging develop into the dev/ufs-weather-model branch.  This is a bit delayed from what we'd like due to unforseen debugging issues for an upcoming PR to develop we're waiting for.    If there are delays past another week or two, we can make a merge from develop to dev/ufs-weather-model but in the meantime please plan for this PR to just be for the "add time off-set fix".

**Comment by DeniseWorthen** [comment]
That leaves the time-offset PR to be a single line change (other than the additional time messages being written to the log files). Is this really necessary?

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen  This is our procedure for this branch that updates to the code itself be separate from merges from develop.  If this is not clear enough in our wiki documentation we apologize and we do have plans to update it so that it's clearer moving forward.  Your one line change does not need to be held up by waiting for a merge from develop.  There is no need to wait for that PR to move forward with this one.

**Comment by DeniseWorthen** [comment]
It is pointless to go through the entire UWM commit process for a one-line change.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen this is not pointless, this is a needed change.  I'm sorry to see this get closed and I hope we can find a way to reopen and get this needed change in to UWM.

**Comment by DeniseWorthen** [comment]
It is a pointless waste of my time. Thanks.

**Pull request closed without merging**
