### PR TITLE
removing comp.* link.* files as we now use the cmplr.env

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
This PR removes all of the model/bin/comp.<> & link.<> files as we have transitioned to using the cmplr.env files. 

I have not run regression tests yet, as I wanted to make sure there were no objections to the removal of these files.  If someone is still using one of the independent comp/link files, we could add them to the cmplr.env. 

Update: 
PR #283 which removes unused files in the bin directory and PR #279 which got rid of .swp files not intended to be committed to repo  have been combined with this PR.

### CODE REVIEW

**Comment by mickaelaccensi** [comment]
I agree to remove those comp & link files. 
Also it would be good to remove the if tests on comp and link in section `# 3.c Setup comp & link files` in w3_setup

**Comment by ukmo-ccbunney** [comment]
Sounds like a good idea to me - it would significantly tidy up the bin directory.
On the subject of removing old files, is anyone still using the `regtest/matrix.base.v1` file? Can this also be removed (maybe in a different PR?)

**Comment by mickaelaccensi** [comment]
> Sounds like a good idea to me - it would significantly tidy up the bin directory.
> On the subject of removing old files, is anyone still using the `regtest/matrix.base.v1` file? Can this also be removed (maybe in a different PR?)

I don't use it. so ok for me to also remove it

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali we could also remove https://github.com/NOAA-EMC/WW3/blob/develop/regtests/bin/matrix_zeus_HLT since we use the ncep one now if you agree.  

@mickaelaccensi @ukmo-ccbunney I will remove the extra regtest/matrix.base.v1 file, because I agree it's not being used.  In terms of the extra if statements in the w3_setup, I can clean that up too if we want.  Do we think everyone has fully transitioned at this point so that's okay to do?

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA, @ukmo-ccbunney I agree, we can remove regtest/matrix.base.v1 and regtests/bin/matrix_zeus_HLT. The Matlab scripts haven't been used for a long time, so we can also remove them.

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali the other 2 clean-up related PRs have been added to this branch and it has been updated w/the most recent develop branch.  This PR is ready for review and regression testing.

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA Awesome, I'll review it and will check regtests today.

**Review by mickaelaccensi — APPROVED** [review]
approved.
the next step would be clean up w3_setup and probably move the variables comp_seq and comp_mpi from cmplr.env to wwatch3.env

**Comment by aliabdolali** [comment]
Full regtest results attached:
[matrixDiffHERA.zip](https://github.com/NOAA-EMC/WW3/files/5826423/matrixDiffHERA.zip)
All tests compared OK, apart from the usual suspects.

**Review by aliabdolali — APPROVED** [review]

**Pull request merged**
