### PR TITLE
Remove support for compiler directive switches

### LINKED ISSUE #357: Remove support for compiler directive switches ( C90, NEC, SX6, SX8)
There are several switches that are used for compiler directives: C90/NEC switches for Cray C90 and SX6/SX8.  These do not appear to be used by anyone at this time and therefore we propose removing support for these switches. 

If you use any of these switches, please let us know as soon as possible, so that we do not remove support for these.  If no one is using these switches, the removal of support for these switch would be planned for the end of May 2021.

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary

Remove support for compiler directive switches ( C90, NEC, SX6, SX8). 

## Description
This PR removes support for compiler directive switches ( C90, NEC, SX6, SX8), which were originally used when certain compilers in the past did not handle various aspects for either OMP or other needed code.  These work arounds have not been used for a long time and are being removed.  There is no expectation of any answer changes for regression tests. 

### Issue(s) addressed
* closes #357 

### Testing
*  The regression tests matrix_ncep were run using hera.intel and no errors were found.  The regression tests need to be rerun and checked (no expectation that anything other than the normal not-b4b tests will be different) when it's merged with the top of develop pre-commit. At that time, the matrix results will be posted.

### CODE REVIEW

**Review by aliabdolali — COMMENTED** [review]
The followings still need clean up: 
model//ftn/w3pro2md.ftn:581:!       !/NEC   Enable NEC SXF90 compiler directives.
model//ftn/w3pro1md.ftn:368:!     !/NEC Enable NEC SXF90 compiler directives.

**Comment by JessicaMeixner-NOAA** [comment]
> The followings still need clean up:
> model//ftn/w3pro2md.ftn:581:! !/NEC Enable NEC SXF90 compiler directives.
> model//ftn/w3pro1md.ftn:368:! !/NEC Enable NEC SXF90 compiler directives.

Good catch! Since these are commented out, I'm assuming you will be okay if I do not restart regression tests.  If you want me to, just let me know and I'll restart them now.  They are almost done running now.

**Comment by aliabdolali** [comment]
> > The followings still need clean up:
> > model//ftn/w3pro2md.ftn:581:! !/NEC Enable NEC SXF90 compiler directives.
> > model//ftn/w3pro1md.ftn:368:! !/NEC Enable NEC SXF90 compiler directives.
> 
> Good catch! Since these are commented out, I'm assuming you will be okay if I do not restart regression tests. If you want me to, just let me know and I'll restart them now. They are almost done running now.

No need to rerun the tests due to the reason you mentioned.

**Comment by JessicaMeixner-NOAA** [comment]
Updated per review. Let me know if that's not correct.

**Comment by JessicaMeixner-NOAA** [comment]
Only the usual regtests did not pass: 
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/6638411/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/6638412/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/6638413/matrixDiff.txt)

@aliabdolali I believe this PR is ready for your final review

**Review by aliabdolali — APPROVED** [review]

**Pull request merged**
