### PR TITLE
Feature/is2update

### PR DESCRIPTION
**Pull request by mickaelaccensi**
IS2 update default parameterization - linked to issue #186 
[matrix.zip](https://github.com/NOAA-EMC/WW3/files/4492203/matrix.zip)

update default values for IS2
regtest ww3_tic1.4 updated
manual update in eqs/IS2.tex
RREF initialized just after allocation to get b4b with unst regtest ww3_tp2.7
(RREF is not used for unst grid but it's written in mod_def anyway)
expected changes in results for regtests : ww3_tic1.4, ww3_tic2.3
expected changes in mod_def.ww3 for regtests : ww3_ts4
expected not b4b regtests : mww3_test_03

### CODE REVIEW

**Review by aliabdolali — APPROVED** [review]
@mickaelaccensi Very neat. Let's wait for Henrique as the second reviewer and then we will merge it.

**Comment by mickaelaccensi** [comment]
I have not mentioned that I let in the code comments the version 7.XX. I let you overwrite it to the new version with the corresponding milestone.

**Comment by mickaelaccensi** [comment]
I have not mentioned that I let in the code comments the version 7.XX. I let you overwrite it to the new version with the corresponding milestone.

**Comment by aliabdolali** [comment]
@mickaelaccensi Do you see this conflict ok? I can go ahead and merge it or wait for your PR with the fix this conflict + 7.XX version number?

**Comment by mickaelaccensi** [comment]
I've resolved the conflict. you can merge to develop branch and update the versions 7.XX

**Pull request merged**
