### PR TITLE
fix equal logical variable to comply GFORTRAN 

### LINKED ISSUE #710: GFortran compilation fails due to logical variable comparison in model/ftn/wmesmfmd.ftn
**Describe the bug**
The compilation of the file model/ftn/wmesmfmd.ftn fails when WW3 is compiled using the GFortran compiler.
The issue is with the **non-standard** logical variable comparisons:
   **if ( LPDLIB == .FALSE. ) then**
instead of:
**if ( LPDLIB .EQV. .FALSE. ) then**
where gfortran issues an error

**To Reproduce**
Compile WW3 using GFortran (tested with gcc >= 8.3)

**Expected behavior**
Successful compilation of wmesmfmd.F90

**Additional context**
Need to replace all occurences of: **LPDLIB == .FALSE.** with **LPDLIB .EQV. .FALSE.** in model/ftn/wmesmfmd.ftn, see below:

wmesmfmd.F90:6374:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:6387:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:6398:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:6417:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:6465:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:5263:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:4256:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:4291:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:4334:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:4362:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:4394:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:4426:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:4503:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:3875:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:3910:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:3954:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:3982:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:4014:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==
wmesmfmd.F90:4046:11:

       if ( LPDLIB == .FALSE. ) then
           1
Error: Logicals at (1) must be compared with .eqv. instead of ==

### PR DESCRIPTION
**Pull request by aliabdolali**
# Pull Request Summary
The compilation of the file model/ftn/wmesmfmd.ftn fails when WW3 is compiled using the GFortran compiler.

## Description
The issue is with the non-standard logical variable comparisons:
**if ( LPDLIB == .FALSE. ) then**
instead of:
**if ( LPDLIB .EQV. .FALSE. ) then**

Please also include the following information: 
* Add any suggestions for a reviewer @pvelissariou1
* Mention any labels that should be added:  _bug_
* Are answer changes expected from this PR? NA

### Issue(s) addressed
- fixes #710

### Commit Message
fix equal logical variable to comply GFORTRAN 

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

tests are running on hera

### CODE REVIEW

**Review by MatthewMasarik-NOAA — COMMENTED** [review]
I agree this change should be made -- the equality operator for logical values is `.EQV.` (vs. `==`).  

@aliabdolali mentioned the tests are running on hera.  I'll update this comment to an approve when tests return, assuming they come back with no unexpected changes.

**Comment by aliabdolali** [comment]
Here is summary of regtests, with preknown non-b4b
```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (19 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
```
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/8779005/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/8779006/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/8779007/matrixDiff.txt)

**Comment by aliabdolali** [comment]
> I agree this change should be made -- the equality operator for logical values is `.EQV.` (vs. `==`).
> 
> @aliabdolali mentioned the tests are running on hera. I'll update this comment to an approve when tests return, assuming they come back with no unexpected changes.

@MatthewMasarik-NOAA Thanks for the review, I just added the matrix.comp outputs

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali the standalone WW3 regression tests do not test wmesmf.  Have you tested this PR with the ufs-weather-model (perhaps with a commit before the intel change)?

**Comment by aliabdolali** [comment]
> @aliabdolali the standalone WW3 regression tests do not test wmesmf. Have you tested this PR with the ufs-weather-model (perhaps with a commit before the intel change)?

@JessicaMeixner-NOAA this is for unstructured cases, Takis tested this for Coastal App and it worked fine (it was needed for gfortran but also worked with intel). And ufs-weather-model does not cover unstr cases as you might know.

**Comment by MatthewMasarik-NOAA** [comment]
@aliabdolali the matrix output's look good, thanks.  @JessicaMeixner-NOAA mentions a point I overlooked, is there a plan to address that?

**Comment by aliabdolali** [comment]
> @aliabdolali the matrix output's look good, thanks. @JessicaMeixner-NOAA mentions a point I overlooked, is there a plan to address that?

@MatthewMasarik-NOAA there is no need to run ufs-weather-model for these changes for LPDLIB.

**Comment by MatthewMasarik-NOAA** [comment]
@aliabdolali I looked back over the changes and they are all protected by PDLIB `if`'s, so I agree all should be fine.  I'd like to do my due diligence just in case of something unforeseen and run one check case with UFS.  I'll do that now and approve if OK.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
UFS was run for cpld_control_p8 with this branch and passed.  I approve these changes.

**Review by MatthewMasarik-NOAA — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
If we are looking to replace == with .eqv. should the following also be updated: 
https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L1643
https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3313-L3314
https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3326
https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3336
https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3346
https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3803-L3804
https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3816
https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3826
(and so on... )

**Comment by JessicaMeixner-NOAA** [comment]
> If we are looking to replace == with .eqv. should the following also be updated: https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L1643 https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3313-L3314 https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3326 https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3336 https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3346 https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3803-L3804 https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3816 https://github.com/aliabdolali/WW3/blob/fix/equallogic/model/src/wmesmfmd.F90#L3826 (and so on... )

Actually this is just for logicals, not numerical values. One second, let me re-check...

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Pull request merged**
