### PR TITLE
Fb smc datadim

### PR DESCRIPTION
**Pull request by UKMO-lsampson**
# Pull Request Summary
Implement the removal of some redundant indices that are currently used in the cell (IJKCel) and face arrays (IJKUFc, IJKVFc) of the SMC propagation module.

## Description
The current array accesses that are used for the SMC propagation are assigning some components that are never called. By limiting the index, we can reduce the memory usage while maintaining the ability to use the current input file and input arrays.

This does not fix any bug as the program still processes accordingly, but rather focuses on improving the memory usage for the SMC grid, and hence is referred to as a feature branch.

The regression tests should produce a difference when the mod_def.ww3 is produced using a SMC grid. This is because we have changed the declaration of the IJKCel array which is written to and read from mod_def.ww3.

Reviewers (to be requested):

- @ukmo-jianguo-li  JianGuo-Li [Met Office]
- Ali Abdolali [NOAA]
- Chris Bunney [Met Office]

### Commit Message
Implement the removal of some redundant indices that are currently used in the cell (IJKCel) and face arrays (IJKUFc, IJKVFc) of the SMC propagation module.

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ N/A ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ N/A  ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? Regtests
* Are the changes covered by regression tests? Yes, the SMC grid is used by a few regtests.
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? Yes. Met Office Cray XC40 system, XCE. ftn compiler.
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.) The mod_def.ww3 file for any smc grid regtest will be different as the definition of IJKCel has changed. 
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

Regtest shows known differences, and changes due to mod_def.ww3:

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UQ_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (11 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (9 files differ)
ww3_ta1/./work_UPD0F_U                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (1 files differ)
     mod_def.ww3 differ (binary)

ww3_tp2.10/./work_MPI                     (1 files differ)
     mod_def.ww3 differ (binary)

ww3_tp2.14/./work_OASACM5                     (0 files differ)
ww3_tp2.14/./work_OASACM                     (1 files differ)
     core differ (binary)

ww3_tp2.14/./work_OASICM                     (1 files differ)
     core differ (binary)

ww3_tp2.14/./work_OASOCM                     (1 files differ)
     core differ (binary)

ww3_tp2.16/./work_MPI_OMPH                     (1 files differ)
     mod_def.ww3 differ (binary)

ww3_tp2.16/./work_MPI                     (1 files differ)
     mod_def.ww3 differ (binary)
```

### CODE REVIEW

**Comment by ukmo-ccbunney** [comment]
Hi @UKMO-lsampson 
Can you paste the results of the regtests summary in the PR description?
Thanks

**Comment by UKMO-lsampson** [comment]
> Hi @UKMO-lsampson Can you paste the results of the regtests summary in the PR description? Thanks

Hi @ukmo-ccbunney, I am still in the process of running the regtests. I had to rerun the develop and comparison regtests as the NOAA and UKMO-wave develop updated. I will attach them ASAP, and change the PR to be ready for review once available.

**Comment by UKMO-lsampson** [comment]
> > Hi @UKMO-lsampson Can you paste the results of the regtests summary in the PR description? Thanks
> 
> Hi @ukmo-ccbunney, I am still in the process of running the regtests. I had to rerun the develop and comparison regtests as the NOAA and UKMO-wave develop updated. I will attach them ASAP, and change the PR to be ready for review once available.

@ukmo-ccbunney I have run the regtests and compared them with the output from the head of develop. This PR has been updated according to the results, but I will need to continue to investigate the reasons for some differences.

**Comment by JessicaMeixner-NOAA** [comment]
@UKMO-lsampson these look like pretty familiar//expected output.  See https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results and then an unresolved issue for the unstructured grid mod_defs here: https://github.com/NOAA-EMC/WW3/issues/700

**Comment by UKMO-lsampson** [comment]
> @UKMO-lsampson these look like pretty familiar//expected output. See https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results and then an unresolved issue for the unstructured grid mod_defs here: #700

@JessicaMeixner-NOAA thank you for looking at this PR. I think you're correct, I have rerun the regtests that contain mod_def and core differences, with the same source code and this is still reporting differences in the binary files.

**Comment by ukmo-ccbunney** [comment]
@ukmo-jianguo-li Would you be able to do a quick review of this change please? Thanks.

**Comment by ukmo-jianguo-li** [comment]
I have viewed Lewis' changes and they look fine to me.  Although some more columns in the face array could be removed from memory as I originally suggested, it could be left for later update.  As this is Lewis' first pull request for the WW3 model, I think it is better to keep it as simple as possible and get it merged as quick as possible.

**Comment by ukmo-jianguo-li** [comment]
Have forgot how to submit the review approval.  The system seems not taking my comment as approval.

**Comment by ukmo-ccbunney** [comment]
> Have forgot how to submit the review approval. The system seems not taking my comment as approval.

Thanks @ukmo-jianguo-li - we could not add you explicitly as a reviewer, so your approval in the comments is fine.
Edit - I think you need to be added as a "collaborator" to the NOAA WW3 repo to allow you to be a reviewer. @aliabdolali  - can you do this for @ukmo-jianguo-li  please? Thanks.

**Review by ukmo-ccbunney — APPROVED** [review]
I've run the regression tests and get the following differences (ignoring the known differences in `mww3_test_03`):
```
mww3_test_09/./work_MPI                     (3 files differ)
ww3_tp2.10/./work_MPI                     (1 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (1 files differ)
ww3_tp2.14/./work_OASACM6                     (1 files differ)
ww3_tp2.16/./work_MPI                     (1 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (1 files differ)
```

In each case the difference is in the `mod_def.*` files, as expected (the `IJKCel` array is now a different size).

I'm happy to approve this PR.

**Comment by JessicaMeixner-NOAA** [comment]
I will run the regtests here one more time just as an extra sanity check.  It might take a day as our queues are a little slow, but then we should have this merged tomorrow or Friday.

**Comment by aliabdolali** [comment]
> > Have forgot how to submit the review approval. The system seems not taking my comment as approval.
> 
> Thanks @ukmo-jianguo-li - we could not add you explicitly as a reviewer, so your approval in the comments is fine. Edit - I think you need to be added as a "collaborator" to the NOAA WW3 repo to allow you to be a reviewer. @aliabdolali - can you do this for @ukmo-jianguo-li please? Thanks.

I just did it again, he was invited but never accepted the invitation so it was expired.

**Comment by JessicaMeixner-NOAA** [comment]
Here's my full list of cases that are different: 

mww3_test_03/./work_PR2_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
mww3_test_09/./work_MPI                     (3 files differ)
ww3_tp2.10/./work_MPI                     (1 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.14/./work_OASACM6                     (1 files differ)
ww3_tp2.16/./work_MPI                     (1 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (5 files differ)
ww3_tp2.17/./work_a                     (1 files differ)
ww3_tp2.17/./work_c                     (1 files differ)
ww3_tp2.17/./work_b                     (1 files differ)
ww3_tp2.6/./work_ST0                     (1 files differ)
ww3_tp2.6/./work_ST4                     (1 files differ)
ww3_tp2.6/./work_pdlib                     (1 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)


These are known-issue files: 

mww3_test_03/./work_PR2_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_tp2.16/./work_MPI                     (1 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (5 files differ)
ww3_tp2.17/./work_a                     (1 files differ)
ww3_tp2.17/./work_c                     (1 files differ)
ww3_tp2.17/./work_b                     (1 files differ)
ww3_tp2.6/./work_ST0                     (1 files differ)
ww3_tp2.6/./work_ST4                     (1 files differ)
ww3_tp2.6/./work_pdlib                     (1 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)


These are known to change from this PR:  
mww3_test_09/./work_MPI                     (3 files differ)
ww3_tp2.10/./work_MPI                     (1 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)  -- 6 is normal, extra 1 for mod_def
ww3_tp2.14/./work_OASACM6                     (1 files differ)

**Comment by JessicaMeixner-NOAA** [comment]
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/9478144/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/9478145/matrixDiff.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/9478146/matrixCompFull.txt)

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Pull request merged**
