### PR TITLE
Add PIO switch 

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
This PR adds a PIO switch, which is one way to address compile time issues when not building the mesh cap.  

## Description
This PR adds a PIO switch to create barriers around the section of ftn_source code to avoid compiling issues when building other WW3 executables.  The compile time issues were described in the issue here: https://github.com/ufs-community/ufs-weather-model/issues/2502 

Alternative solutions will be continued to be explored, however this removes a blocking issue from the global-workflow.  

Please also include the following information: 
* Add any suggestions for a reviewer 
* Mention any labels that should be added:  _bug_ / _new feature_
* Are answer changes expected from this PR? Please describe the changes and the reason why in addition to which of the following labels would apply:no answer chages 

### Issue(s) addressed
- addresses https://github.com/ufs-community/ufs-weather-model/issues/2502 

### Commit Message
Add PIO switch 

### Check list  

- [x ] Branch is up to date with the authoritative repository (NOAA-EMC) dev/ufs-weather-model  branch. 
- [x ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? These were tested using matrix compared against a baseline from dev/ufs-weather-model 2 commits ago, in the ufs-weather-model regression tests, and in the global-workflow (however, with out enabling pio yet). 
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) yes. 
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? hera, intel 
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
 no changes expected. 
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (11 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```

[matrixCompFull.txt](https://github.com/user-attachments/files/17874094/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/user-attachments/files/17874095/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/user-attachments/files/17874096/matrixDiff.txt)

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA I think the block of code in the ``use_restartnc`` in w3init should also be entirely under an PIO ifdef. For example, the ``restart_from_binary`` setting will only be read from config if restartnc is also true. And there will be no ability to use a custom ww3 restart file name, which would break the various lines which set the filename.

In short, I think it better to have that entire ``use_restartnc`` block in w3initmd under a W3_PIO flag also

```
diff --git a/model/src/w3initmd.F90 b/model/src/w3initmd.F90
index 0f136227..a496ec2c 100644
--- a/model/src/w3initmd.F90
+++ b/model/src/w3initmd.F90
@@ -959,6 +959,7 @@ CONTAINS
     ! 3.a Read restart file
     !
     VA(:,:) = 0.
+#ifdef W3_PIO
     if (use_restartnc) then
       if (runtype == 'continue' )then
         call set_user_timestring(time,user_timestring)
@@ -983,6 +984,7 @@ CONTAINS
         flcold = .true.
       end if
     else
+#endif
 #ifdef W3_DEBUGCOH
       CALL ALL_VA_INTEGRAL_PRINT(IMOD, "Before W3IORS call", 1)
 #endif
@@ -1016,7 +1018,9 @@ CONTAINS
 #ifdef W3_TIMINGS
       CALL PRINT_MY_TIME("After restart inits")
 #endif
+#ifdef W3_PIO
     end if ! if (use_restartnc)
+#endif
```

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for your super fast feedback @DeniseWorthen  - I'll implement that update now.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen  - Updates are there.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
**Code review**
Pass

**Testing**
Pass

* WW3 standalone - successfully built under the regtest framework
* ufs-weather-model coupled - b4b ([RegressionTests_hera.log.txt](https://github.com/user-attachments/files/17909875/RegressionTests_hera.log.txt))
* global-workflow - WW3 pre/post programs now build successfully.

Approved.

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA thank you for quickly finding and testing a solution.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen do you have any other comments for this?  I wanted to check with you before I mark this PR as being reviewed by sub component in the ufs-weather-model PR.

**Comment by DeniseWorthen** [comment]
I'm OK w/ it. Thanks.

**Comment by FernandoAndrade-NOAA** [comment]
Testing on #[2483](https://github.com/ufs-community/ufs-weather-model/pull/2483) has completed successfully, please continue with the merge process.

**Pull request merged**
