### PR TITLE
NC4 ,F90 ,XX0 switches removed from ww3_tp2.19 regtest.

### PR DESCRIPTION
**Pull request by Ghazal-Mohammadpour**
# Pull Request Summary
NC4,F90,XX0 switches removed from ww3_tp2.19 regtest.

## Description
We looked for all deprecated switched in all of the regtests and we found XX0, NC4 and f90 in regtest (ww3_tp2.19). The only changes were in the netcdf switch output for that test.

### Issue(s) addressed
Issue #1051 

### Commit Message
NC4 ,F90 ,XX0 switches removed from ww3_tp2.19 regtest.

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? Matrix
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Yes.
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? Hera.
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
The ww3.tp2.19 had difference in the netcdf output of the switch which is expected.
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):
```

**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (9 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_07/./work_PR3_UQ                     (0 files differ)
ww3_ta1/./work_UPD5_O                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.14/./work_OASACM4                     (0 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.19/./work_1A_a                     (9 files differ)
ww3_tp2.19/./work_1C_a                     (9 files differ)
ww3_tp2.19/./work_1B_a                     (9 files differ)
ww3_ts1/./work_ST3                     (0 files differ)
ww3_ufs1.2/./work_c                     (8 files differ)
```

1-[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/12318595/matrixCompFull.txt)
2-[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/12318611/matrixCompSummary.txt)
3-[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/12318612/matrixDiff.txt)

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
@Ghazal-Mohammadpour thanks for submitting this PR!  It's great to have these switches reviewed and cleaned out.  

I looked at the list of matrix.comp summary you posted above and it is close to the known non-b4b tests, but with some small differences, some of which are OK, but a couple I'd like to know more about.

**0 files differ**
These are most likely OK.  We could look at the details to confirm.
```
mww3_test_07/./work_PR3_UQ                     (0 files differ)
ww3_tp2.14/./work_OASACM4                      (0 files differ)
ww3_ts1/./work_ST3                             (0 files differ)
```

**ww3_ufs1.2,3**
These are the tests I'd like to know more about.  It is actually quite curious that
```
ww3_ufs1.2/./work_c                     (8 files differ)
```
shows up with differences, because it is not known to have differences.  But then test 
```
ww3_ufs1.3/./work_a
```
which normally has `(3 files differ)` does not show up at all.

We should get to the bottom of why `ww3_ufs1.2` is showing differences with this update while `ww3_ufs1.3` does not.  I'll soon be on leave the remainder of the week though I can pick this up with you on Monday if you like.

**Comment by JessicaMeixner-NOAA** [comment]
@MatthewMasarik-NOAA great catch, I didn't see that when @Ghazal-Mohammadpour and I looked over this together.  As you'll be on leave, I'll take over testing this.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/12321743/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/12321744/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/12321745/matrixDiff.txt)

I'm unsure why @Ghazal-Mohammadpour had the ufs1.2 regtest differ.  @MatthewMasarik-NOAA we might need to keep an eye on this, they were just files that we're there but I didn't see errors or other issues.   My tests are as expected with the following differences (tp2.19 netcdf switch differences but a triple checked expected differences):


```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (11 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (13 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.19/./work_1B_a                     (9 files differ)
ww3_tp2.19/./work_1A_a                     (9 files differ)
ww3_tp2.19/./work_1C_a                     (9 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)

```

One thing I do note is we have some more mww3_test_03 files that are randomly showing up as different.  I'm confident it doesn't have anything to do with this PR, but something we should probably keep an eye on @MatthewMasarik-NOAA

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA Thanks for the follow up on the differences for ufs1.2 and ufs1.3.

**Pull request merged**
