### PR TITLE
uniformize regtests output option

### LINKED ISSUE #604: uniformize matrix outputs
**Is your feature request related to a problem? Please describe.**
avoid having multiple -o options in the regtest command lines

**Describe the solution you'd like**
set -o all or -o both in the main matrix script instead of having separated -o options defined for each run_test command line

### PR DESCRIPTION
**Pull request by mickaelaccensi**
# Pull Request Summary
add option -o all in matrix_*
except for ukmo which is -o both
remove all -o statements in matrix.base
correct a test in run_test to avoid warnings

## Description
uniformize the option -o to setup the kind of output type (ascii, netcdf, grib) in the main matrix script

### Issue(s) addressed
- fixes #604 

### Commit Message
uniformize regtests output by setting a global output type in the matrix script

### Check list  

- [X] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [X] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [X] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [X] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
yes all
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
on going on datarmor with intel compiler
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):    
* Please indicate the expected changes in the regression test output ([Note the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)).
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for making this a separate PR!

**Comment by JessicaMeixner-NOAA** [comment]
Started running the regtests so we can document what output changes and make sure everything runs if we are triggering any additional outputs.

**Comment by JessicaMeixner-NOAA** [comment]
So I got one error with the test: 
in run_test -b slurm -o all -c hera.intel -S -T -w work_IC2IS2 ../model ww3_tic2.2
```
 *** WAVEWATCH III ERROR IN W3OUTP :
     ERROR IN READING FROM INPUT FILE
     LAST POINT INDEX IS NOT -1
     OR TOO MANY POINT INDEXES DEFINED
```

Did you have any issues with this test @mickaelaccensi ? I'm running the comparison now and will look into this error later today.

**Comment by mickaelaccensi** [comment]
> So I got one error with the test: in run_test -b slurm -o all -c hera.intel -S -T -w work_IC2IS2 ../model ww3_tic2.2
> 
> ```
>  *** WAVEWATCH III ERROR IN W3OUTP :
>      ERROR IN READING FROM INPUT FILE
>      LAST POINT INDEX IS NOT -1
>      OR TOO MANY POINT INDEXES DEFINED
> ```
> 
> Did you have any issues with this test @mickaelaccensi ? I'm running the comparison now and will look into this error later today.

yes, I've made the corrections and pushed them

**Comment by JessicaMeixner-NOAA** [comment]
The fix worked for me, running the matrix.comp now.

**Comment by JessicaMeixner-NOAA** [comment]
Only the known not b4b: 
```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (9 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (5 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)

```

Output: 
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/8036509/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/8036510/matrixCompFull.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/8036511/matrixDiff.txt)

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Pull request merged**
