### PR TITLE
adding IO unit test

### PR DESCRIPTION
**Pull request by edwardhartnett**
# Pull Request Summary

Add a test for existing binary point output.

## Description

This PR does not include any code changes to the model, only test code and configuration.

The existing GitHub action CI runs do not attempt to execute unit tests (because there are none, so that would fail). In this PR I introduce a new CI YML file that runs the tests. Once this PR is merged, I will submit a follow-up PR which causes all the CI runs to run ctest.

The new CI also runs a code coverage report and uploads it to GitHub actions. This only needs to be done by one of the CI runs.

Some small data files are necessary for this test to work, the are included in model/tests/data and are copied to the binary build directories by the model/tests/CMakeLists.txt file.

Once the unit test is merged and running, @MatthewMasarik-NOAA can make it a "Required Status Check", which means that merges will not be permitted if this test fails. (And that's how you want to treat all your unit tests.)

Once we have at least one required status check, I believe that GitHub will automatically enforce that the PR has been updated with the latest version of the develop branch, so you can stop asking that in the PR checklists. We can test this to confirm.

### Issue(s) addressed

Part of #682

### Commit Message

Add a test for existing binary point output.

### Check list  

- [ x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [x ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [x ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? On my branch.
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) No.
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? No, no code changes.
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.) No changes expected.
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@edwardhartnett we do not allow binary files in the WW3 repository.  This PR adds 2.  Can you please close this PR so that we do not have binary file in our repository?   I'm happy to set-up an offline meeting to discuss other ways to create these files without saving binary files to the repository.

**Comment by JessicaMeixner-NOAA** [comment]
@edwardhartnett can we please re-close this PR and/or remove the binary files?  Thanks in advance for your help keeping the WW3 repo free of binary files.

**Comment by MatthewMasarik-NOAA** [comment]
@edwardhartnett I wanted to add some context regarding the binary files.  @JessicaMeixner-NOAA and I discussed this shortly after we met today. If something gets in that we don't allow, and we don't notice it, it could be a lot of pain manually removing it and then rewriting history.  Because if a file has already been committed to your fork, I believe even if you remove the files in new commits, it will still be a part of the repo.  Based on the risk, please create a new branch with the work carried over, minus binaries, when your ready for the PR to be reviewed.

**Comment by edwardhartnett** [comment]
@JessicaMeixner-NOAA I am removing the binary files but I need to leave the PR open so that the CI can run.

I have converted the PR to draft and will not mark it "ready to review" until both binary files are removed.

**Comment by JessicaMeixner-NOAA** [comment]
In the past, CI tests could also be run from branches in forks and did not require a PR to the main repository.

**Pull request closed without merging**
