### PR TITLE
UKMO SMC Bugfixes [Staging Aug 2021]

### LINKED ISSUE #429: [ww3_ounf] NetCDF compression sometimes not applied when using SMC grids
**Describe the bug**
When using outputting netCDF NC4 files using `ww3_ounf` on an SMC grid the netCDF compression is not applied when creating variables in a new file.

**To Reproduce**
Run `ww3_ounf` on an SMC grid with NC4 switch.

**Expected behavior**
Some output variables will not have compression applied (you can verify this using `ncdump -h -s`

**Proposed fix**
Move `NF90_DEF_VAR_DEFLATE` statement on line 2423 and 2438 outside the `IF-ELSE-ENDIF` block so it is applied for both SMC and regular grids:

 https://github.com/NOAA-EMC/WW3/blob/3c4732490b8d1d4e1ca2af81e71d8cd30c1de950/model/ftn/ww3_ounf.ftn#L2411-L2425

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
# Pull Request Summary

This staging branch is composed of 4 PRs from the UKMO repository:

Bug fixes to SMC ww3_ounf output; comprises the following 3 PRs:
 - inconsistencies in SMC re-gridding #437 
 - netCDF compression not being applied in SMC grid outputs #436 
 - RTD pole meta data fix in ww3_ounf #439 

New features:
 - New "coordinates" variable in ww3_ounf: https://github.com/ukmo-waves/WW3/pull/35

## Description
See individual PRs listed above. Summary:
 - SMC re-gridding; fixes issues with grid alignment.
 - Adds compression to netCDF SMC output variables
 - Fix incorrect RTD pole metadata due to variable name change.

### Issue(s) addressed
- fixes #429

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)? Yes

### Commit Message
UKMO Staging branch Aug 2021. Fixes following SMC output issues:
  - inconsistencies in SMC regridding #437 
  - netCDF compression not being applied in SMC grid outputs #436 
  - RTD pole meta data fix in ww3_ounf #439 

### Testing
* How were these changes tested? Local tests, regression tests
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Yes
* If a new feature was added, was a new regression test added? N/A
* Have regression tests been run? Yes
* Which compiler / HPC you used to run the regression tests in the PR?  Cray HPC, GNU Fortran and CrayFtn
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):    
Please indicate the expected changes in the outputs ([excluding the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)).
* Please list which labels code managers should add to indicate code changes:    
_mod_def change_, _out_grd change_, _out_pnt change_, _restart file change_, _Regression test_, ...

### Regtest outputs

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (9 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
ww3_tp2.14/./work_OASACM6                     (2 files differ)
ww3_tp2.17/./work_mc1                     (1 files differ)
ww3_tp2.17/./work_ma1                     (1 files differ)
```

- ww3_tp2.17 is currently not running on the Met Office HPC due to issue #443 
- ww3_tp2.14 has a change to the extents of the gridded netCDF file; an extra longitude is output (this was being incorrectly missed prior to the re-gridding change).

Full regression test matrix results: [matrixComp_ukmo_staging_aug2021.zip](https://github.com/NOAA-EMC/WW3/files/6947064/matrixComp_ukmo_staging_aug2021.zip)

### CODE REVIEW

**Comment by aliabdolali** [comment]
Hi @ukmo-ccbunney are we done with this? can we test them?

**Review by aliabdolali — APPROVED** [review]
I approve this PR until this point. But from a conversation with Chris, other PR might be integrated here, then those ones should be reviewed.

**Comment by ukmo-ccbunney** [comment]
Hi @aliabdolali 
@ukmo-juan-castillo and I are still chasing the b4b issue with ww3_tr1 and PR https://github.com/ukmo-waves/WW3/pull/34
I had intended to add that one to this staging branch, but we are struggling to get to the bottom of the issue (it feels like an existing issue that has shown up due to Juan's changes).

So - I think perhaps to keep things moving it would be best to consider this staging branch ready for your review now and we can merge https://github.com/ukmo-waves/WW3/pull/34 in at a later date.

**Comment by JessicaMeixner-NOAA** [comment]
@ukmo-ccbunney sounds good.  @aliabdolali is on leave today, but I ran the regtests last night, so I just have to run the matrix.comp this morning.  Assuming that all goes fine as expected and we already have the review from Ali we should be able to merge this here in a few hours.

**Comment by JessicaMeixner-NOAA** [comment]
Only the known regtests had issues: 
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7145458/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7145459/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7145460/matrixDiff.txt)

**Pull request merged**
