### PR TITLE
Update IS_IN_UNGRID to handle if grid lon defintions are mismatched

### LINKED ISSUE #1273: Be able to handle point output if point/grid mismatch because  -180 to 180 vs 0 to 360
**Is your feature request related to a problem? Please describe.**
As reported by @NickSzapiro-NOAA  here: https://github.com/ufs-community/ufs-weather-model/issues/2368 

One can run into issues where point output and the grids do not match because they are defined by -180 to 180 vs 0 to 360 for one or the other.  

**Describe the solution you'd like**
Solutions posed by  @NickSzapiro-NOAA  here: https://github.com/ufs-community/ufs-weather-model/issues/2368 

* modifying the (non-polar) longitudes in parm/ww3_points.list
* enhancing the internals used in W3IOPP to preprocess point output (or for unstructured grids in: https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3triamd.F90#L1604) 

**Describe alternatives you've considered**

While the first solution is a great immediate solution, ideally we should enhance WW3 so that this is a non-issue.  

**Additional context**

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
Update IS_IN_UNGRID to handle if grid lon defintions are mismatched
## Description

This PR adds a modified longitude point for the point that you are trying to find in a triangle element.  If for example this point is -180 but the grid is defined from 0 to 360 this will address this mismatch and the point will be found in an element. 

If there are regtests where the requested point output does not match the grid definition (ufs1.1) then there will be answer changes.  This followed the work of the "fix periodicity" routine. 

### Issue(s) addressed
Fixes https://github.com/NOAA-EMC/WW3/issues/1273 

### Commit Message
Update IS_IN_UNGRID to handle if grid lon defintions are mismatched

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? regression tests 
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) yes 
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? hera, intel 
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)

We expect that  unstructured grid regtests with points defined outside of it's domain definition, such as ufs1.1 will have answer changes. 

* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (11 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (19 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.21/./work_ma                     (3 files differ)
ww3_tp2.21/./work_mb                     (3 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.1/./work_unstr_b                     (4 files differ)
ww3_ufs1.1/./work_unstr_a                     (5 files differ)
ww3_ufs1.1/./work_unstr_c                     (4 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```

Not  originally expected non-b4b: 
```
ww3_tp2.21/./work_ma                     (3 files differ)
ww3_tp2.21/./work_mb                     (3 files differ)
```

Looking into this test case closer, it looks like we're actually finding more points for the interpolation.  This test might actually need further investigation (unrelated to this PR) as the interpolated output doesn't seem quite right.  However it's the same before and after this PR, but the weights are slightly different. 

The ufs1.1 tests now have more output points - indicating this fix is working.

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA thank you for tracking this down.  Sorry for the delayed reply, I'm going to get the tests going now.

**Review by MatthewMasarik-NOAA — COMMENTED** [review]
@JessicaMeixner-NOAA my testing gives the same output you got regarding b4b's.

```
**********************************************************************          
********************* non-identical cases ****************************          
**********************************************************************          
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)              
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)         
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)          
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)           
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)          
mww3_test_03/./work_PR2_UNO_MPI_d2                     (14 files differ)        
mww3_test_03/./work_PR1_MPI_d2                     (15 files differ)            
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (8 files differ)       
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)       
mww3_test_03/./work_PR3_UNO_MPI_d2                     (15 files differ)        
mww3_test_03/./work_PR2_UQ_MPI_d2                     (14 files differ)         
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)           
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)        
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)         
mww3_test_09/./work_MPI_ASCII                     (0 files differ)              
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ)                 
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)                 
ww3_tp2.21/./work_ma                     (3 files differ)                       
ww3_tp2.21/./work_mb                     (3 files differ)                       
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)                 
ww3_ufs1.1/./work_unstr_b                     (4 files differ)                  
ww3_ufs1.1/./work_unstr_a                     (4 files differ)                  
ww3_ufs1.1/./work_unstr_c                     (4 files differ)                  
ww3_ufs1.3/./work_a                     (3 files differ)                        
                                                                                
**********************************************************************          
************************ identical cases *****************************          
**********************************************************************
```

I'm okay approving this, I think first it would be good to know what plan you had in mind for addressing the unexpected non-b4b's?

```
ww3_tp2.21/./work_ma                     (3 files differ)                       
ww3_tp2.21/./work_mb                     (3 files differ)                       
```

**Comment by JessicaMeixner-NOAA** [comment]
My preference would be to create an issue to investigate what is going on in that regression test - which has issues regardless of this PR, the interpolation is not performing as I think we would expect.   I can create that issue if you agree on this path forward or please suggest an alternative.

**Comment by MatthewMasarik-NOAA** [comment]
> My preference would be to create an issue to investigate what is going on in that regression test - which has issues regardless of this PR, the interpolation is not performing as I think we would expect. I can create that issue if you agree on this path forward or please suggest an alternative.

Since it's not related to this PR, I agree that creating in issue to look into it is a good path forward.

**Comment by JessicaMeixner-NOAA** [comment]
Issue made: https://github.com/NOAA-EMC/WW3/issues/1332

**Comment by MatthewMasarik-NOAA** [comment]
> Issue made: #1332

Looks great!  Thank you @JessicaMeixner-NOAA, I'll wrap up the review.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
**Code Review**
Pass

**Testing**
Pass

See https://github.com/NOAA-EMC/WW3/pull/1325#pullrequestreview-2503010700 for matrixCompSummary non-b4b's.

* [matrixCompSummary.txt](https://github.com/user-attachments/files/18131516/matrixCompSummary.txt)
* [matrixCompFull.txt](https://github.com/user-attachments/files/18131518/matrixCompFull.txt)
* Note matrixDiff.txt was too large to post in this case.

Approved.

**Comment by MatthewMasarik-NOAA** [comment]
Thank you @JessicaMeixner-NOAA for fixing this mismatch, and posting the issue to follow up on the non-b4b's.

**Pull request merged**
