### PR TITLE
Fb gefsv12

### PR DESCRIPTION
**Pull request by ajhenrique**
Adding small changes to adjust to NCEP operations:
* Changed compile options for NCEP Dell Phase 3, 
* Removed ampty line on w3iogomd, 
* Expanded output parameters to include Tz, depth, mean direction on ww3_grib, 
* Enforced NOSW=3 on ww3_grid for NCEP operations (NCO switch).

### CODE REVIEW

**Comment by ajhenrique** [comment]
@aliabdolali @mickaelaccensi please review this PR. It includes minor but urgent changes to adjust for NCEP operations in the path for integrating WW3 to our global ensemble forecast system GEFS.

**Comment by ghost** [comment]
Hi, 
some requests about cmplr.env, could you insert the section line 125-132 in the "system-dependant options" starting line 161.

about the options you defined:
 * fp-model source is strictly equivalent to fp-model precise
 * align array64byte performance is compiler dependant (good for intel avx, not really for intel xeon phi)
 * did you had any problem to use O2 instead of O3 ? many optimizations are anyway disabled by fp-model precise (or source)
 * sox option should be added as common option since it save the compilation options in the exe
 * ftz to flush denormal results to zero is included in O1, O2 and O3, so no need to add it
 * ip in my opinion is only needed for compilation, not for linking
 * xHOST and xCORE-AVX2 must be specified for both comp and link (keywords are in reality not case sensitive even if it's written in the documentation)

so instead of :
  if [ ! -z "$(echo $cmplr | grep wcoss_cray)" ] ; then
    optc="-c -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -nowarn -sox -align array64byte"
    optc="$optc -xCORE-AVX2 -qno-opt-dynamic-align -ip -module $path_m"
  elif [ ! -z "$(echo $cmplr | grep wcoss_dell_p3)" ] ; then
    optc="-c $list -O2 -Wp,-w -fno-alias -auto -ftz -assume byterecl -nowarn -sox -align array64byte"
    optc="$opt -xHOST -qno-opt-dynamic-align -fp-model source -ip -module $path_m"
    optl="-O2 -ip -o $prog"
  fi

I would recommend you to use the common options (updated with sox) and define wcoss_cray and wcoss_dell_p3 in "compiler-dependant" section : 

 # common options
  optc='-c -module $path_m -no-fma -ip -p -g -i4 -real-size 32 -fp-model precise -assume byterecl -convert big_endian -fno-alias -fno-fnalias -sox'
  optl='-o $prog -p -g'

 # system-dependant options
  if [ ! -z "$(echo $cmplr | grep datarmor)" ] ; then
    optc="$optc -xcore-avx2"
    optl="$optl -xcore-avx2"
  elif [ ! -z "$(echo $cmplr | grep wcoss_cray)" ] ; then
    optc="$optc -xCORE-AVX2 -qno-opt-dynamic-align -auto -nowarn -align array64byte -safe-cray-ptr"
    optl="$optl -xCORE-AVX2"
  elif [ ! -z "$(echo $cmplr | grep wcoss_dell_p3)" ] ; then
    optc="$opt -xHOST -qno-opt-dynamic-align -auto -nowarn -align array64byte -Wp,-w"
    optl="$optl -xHOST"
  else
    optc="$optc -xhost"
    optl="$optl -xhost"
  fi

could you try with this setting and keep me in touch.

FYI, on ifremer HPC I don't have any reproductibility problem with those comp/link settings on the regtests, so it could be a good thing to try.

Mickael

**Comment by ajhenrique** [comment]
Thanks @mickaelaccensi I am compiling and running tests with your proposed options.

**Comment by ajhenrique** [comment]
@mickaelaccensi please review the changes made following your suggestions. My tests on my NCEP operational prototype all passed.

**Review by aliabdolali — APPROVED** [review]
@ajhenrique You are good to go !!!

**Comment by ajhenrique** [comment]
Thanks @aliabdolali! I've redirected this PR to the GEFSv12 branch and will push it over to develop as soon as we hear back from @mickaelaccensi.

**Comment by ghost** [comment]
Hi Henrique,

all sounds good, it seems to me that I can't approved the PR since you've redirected the PR to GEFv12. anyway, go for it !

**Pull request merged**
