### PR TITLE
Add support for IntelLLVM compiler

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# Pull Request Summary
 
This PR adds support for Intel LLVM compiler.

## Description

`model/src/CMakeLists.txt` has been updated to recognize 'IntelLLVM as a valid compiler id and to define compiler flags for Intel LLVM compiler.

### Commit Message

Add support for IntelLLVM compiler

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? ufs-weather-model regression test on Hera. See https://github.com/ufs-community/ufs-weather-model/pull/2224. 
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
Thank you @DusanJovic-NOAA, I will start reviewing this.

**Comment by DusanJovic-NOAA** [comment]
When I build ufs-weather-model with WW3 component I noticed the following compiler warning:

```
Scanning dependencies of target ufs_model
[100%] Building Fortran object CMakeFiles/ufs_model.dir/driver/UFS.F90.o
ifx: command line warning #10121: overriding '-real-size 64' with '-real-size 32'
[100%] Linking Fortran executable ufs_model
[100%] Built target ufs_model
```
I traced to source of this warning WW3 cmake where compiler flags are set to ww3_lib target as PUBLIC.

https://github.com/NOAA-EMC/WW3/blob/dev/ufs-weather-model/model/src/CMakeLists.txt#L94-L96

I think these flags should be set as PRIVATE. @aerorahul 

I can make this change in this PR if it's acceptable.

**Comment by jkbk2004** [comment]
@MatthewMasarik-NOAA Can you review this pr? We are going to start testing at https://github.com/ufs-community/ufs-weather-model/pull/2224

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA Can you review this pr? We are going to start testing at [ufs-community/ufs-weather-model#2224](https://github.com/ufs-community/ufs-weather-model/pull/2224)

@jkbk2004, yes will do.  I can complete it by later today or early tomorrow

**Review by MatthewMasarik-NOAA — APPROVED** [review]
**Code review**
Pass

**Testing**
Pass

* Machine:  Hera
* Description:  WW3 standalone was cmake configured and built using Intel-LLVM stack.

Selection of LLVM for C and Fortran compilers confirmed in cmake config output:
```
-- The C compiler identification is IntelLLVM 2023.2.0
-- The Fortran compiler identification is IntelLLVM 2023.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /apps/oneapi/compiler/2023.2.0/linux/bin/icx - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /apps/oneapi/compiler/2023.2.0/linux/bin/ifx - skipped
-- Checking whether /apps/oneapi/compiler/2023.2.0/linux/bin/ifx supports Fortran 90
-- Checking whether /apps/oneapi/compiler/2023.2.0/linux/bin/ifx supports Fortran 90 - yes
```

Full logs:
* [ww3_llvm_config.txt](https://github.com/user-attachments/files/17152443/ww3_llvm_config.txt)
* [ww3_llvm_build.txt](https://github.com/user-attachments/files/17152444/ww3_llvm_build.txt)

**Comment by MatthewMasarik-NOAA** [comment]
@jkbk2004 @DusanJovic-NOAA, sorry for the delay, this is cleared from my end.

**Comment by jkbk2004** [comment]
@MatthewMasarik-NOAA all tests are done https://github.com/ufs-community/ufs-weather-model/pull/2224. Please, go ahead to merge this pr.

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA all tests are done [ufs-community/ufs-weather-model#2224](https://github.com/ufs-community/ufs-weather-model/pull/2224). Please, go ahead to merge this pr.

Will do @jkbk2004.  I'll let you know shortly

**Comment by MatthewMasarik-NOAA** [comment]
@jkbk2004, done.

**Comment by MatthewMasarik-NOAA** [comment]
@DusanJovic-NOAA, thanks for spearheading this.

**Pull request merged**
