### PR TITLE
Make ww3_grid into a callable subroutine

### PR DESCRIPTION
**Pull request by sbrus89**
# Pull Request Summary
The idea behind this PR is to make ww3_grid functionality callable from a coupled model initialization subroutine

## Description

The `ww3_grid.ftn` has been renamed `w3gridmd.ftn`. Then the W3GRID `PROGRAM` section has been converted to a W3GRIDMD `MODULE`. All local variables of the previous W3GRID program become module variables in the new W3GRIDMD module. The code from the W3GRID program is contained in a new `SUBROUTNE` called W3GRID. A new file is then created called `w3_grid.ftn` with a PROGRAM called WW3GRID which uses W3GRIDMD and calls W3GRID. 

### Issue(s) addressed
Addresses #348

### CODE REVIEW

**Comment by sbrus89** [comment]
The files changed tab is a little messy because of the file name change in the first commit. A clearer comparison of the changes is here: https://github.com/sbrus89/WW3/compare/61354541546ee33bce3bc231fcfc541eba6e82b8..23ae3f542bca3198ac686b233f5643d31f8ec301
This is the diff after the ww3_grid.ftn -> w3gridmd.ftn rename

**Comment by aliabdolali** [comment]
@sbrus89 Hi, did you have a chance to review my PR to this feature branch?

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA ok, that makes sense, please review it and I'll check the regtests today.

**Comment by aliabdolali** [comment]
The matrix ran fine on NOAA HPC
See the summary of matrix.comp with expected non-b4b cases.
[MatrixCOMP_GRID.zip](https://github.com/NOAA-EMC/WW3/files/6435182/MatrixCOMP_GRID.zip)

 and I reviewed the development. It looks fine to me.

**Comment by sbrus89** [comment]
Thanks for running the regtests, @aliabdolali. Glad there weren't any issues.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Thanks for adding the updates to w3_new @sbrus89  

I see no issues with this PR.  My approval is based on the assumption that before this PR goes in (I believe we have a few ahead in the queue if we go in order), that a diff between ww3_grid in the develop branch to w3gridmd in this branch is done to make sure that any updates to ww3_grid are captured in the new subroutine and not lost.

**Comment by sbrus89** [comment]
@JessicaMeixner-NOAA, I agree. Absolutely we should check the diffs before this goes in to make sure all the updates are there. I will rebase and fix conflicts if necessary.

**Comment by aliabdolali** [comment]
Hi @JessicaMeixner-NOAA @sbrus89 
I have reviewed and checked the regtests successfully on our HPC with known non-b4b identical cases.
[DIFF_SBRUS.zip](https://github.com/NOAA-EMC/WW3/files/6548163/DIFF_SBRUS.zip)

**Comment by aliabdolali** [comment]
@sbrus89 Please merge noaa/develop to your PR, so I can merge it afterwards.
When I was checking regtests with your PR, I merged NOAA/develop and there was a conflict in w3_new. Please solve that conflict (1 files is added from your PR to w3_new and one other in NOAA/Develop, so you just need to keep both). Please let me know once you did it and we are good to go with accpting your PR.

**Comment by sbrus89** [comment]
@aliabdolali, I'll do that  right now. Would you like me to squash the commits as well?

**Comment by sbrus89** [comment]
@aliabdolali - Also, I believe I saw the conflict you mentioned in `make_makefile.sh` and not in `w3_new`. Was that the case for you as well?

**Comment by aliabdolali** [comment]
> @aliabdolali - Also, I believe I saw the conflict you mentioned in `make_makefile.sh` and not in `w3_new`. Was that the case for you as well?

Yes, I mean make_makefile.sh.

**Comment by sbrus89** [comment]
I just pushed the rebase, let me know if you'd like my changes squashed to a single commit.

**Comment by JessicaMeixner-NOAA** [comment]
@sbrus89 we will squash them into one when it's merged to the develop branch, so it's not necessary for you to do it on your end.  Do you have a preferred commit message for when we squash and merge?

**Comment by sbrus89** [comment]
> @sbrus89 we will squash them into one when it's merged to the develop branch, so it's not necessary for you to do it on your end. Do you have a preferred commit message for when we squash and merge?

Sounds good @JessicaMeixner-NOAA.  For a commit message, maybe something like: "Modularize ww3_grid functionality"? I don't have a strong preference though, so feel free to modify.

**Comment by sbrus89** [comment]
Thanks very much for your help with this, @aliabdolali and @JessicaMeixner-NOAA. Issue #348 can be closed now as well.

**Pull request merged**
