### PR TITLE
Bugfix/trnc

### PR DESCRIPTION
**Pull request by mickaelaccensi**
see issue #245 

this is a bug introduced with the last PR from UKMO
ukmo-waves#8: 360 day climate calendar

in ww3_trnc.ftn
END CASE
should be replaced by
END SELECT

### CODE REVIEW

**Comment by ukmo-ccbunney** [comment]
Regtest `ww3_t2.2` is the only test that has an input file file for `ww3_trnc`. Perhaps we should add a `-o both` switch to the matrix.base for this test to enable netCDF outputs so the `ww3_trnc` program is properly tested?

**Comment by mickaelaccensi** [comment]
> Regtest `ww3_t2.2` is the only test that has an input file file for `ww3_trnc`. Perhaps we should add a `-o both` switch to the matrix.base for this test to enable netCDF outputs so the `ww3_trnc` program is properly tested?

in matrix_datarmor, the option "-o both" is set in rtst so all the regtests have both ASCII and netCDF outputs.

Should we add the option in matrix_ukmo_cray, matrix_ncep and matrix_zeus_HLT to be sure to never break the netcdf outputs ?
same question for namelist use instead of inp ?

@JessicaMeixner-NOAA , @aliabdolali , @ukmo-ccbunney , @thesser1 , what's your opinion about netcdf and namelist use by default for regtests ?

**Comment by ukmo-ccbunney** [comment]
>@JessicaMeixner-NOAA , @aliabdolali , @ukmo-ccbunney , @thesser1 , what's your opinion about netcdf and namelist use by default for regtests ?

@mickaelaccensi I have no objection to this, especially as namelists are the way forward.

**Comment by aliabdolali** [comment]
@ukmo-ccbunney @mickaelaccensi I am ok with adding this option. However, the ww3_ounp(f).inp/nml should be in the input, otherwise it skips NetCDF output.

**Review by ukmo-ccbunney — APPROVED** [review]

**Comment by mickaelaccensi** [comment]
@aliabdolali , I'll add the missing namelist files in the regtests within 2 weeks

**Comment by mickaelaccensi** [comment]
@aliabdolali , you can merge the change into the develop branch. I'll create a new branch for namelist use as default in regtests

**Comment by mickaelaccensi** [comment]
Hi @aliabdolali ,
I don't understand why I had the permissions to merge it, but I've merged intentionally the branch bugfix/trnc into noaa/develop branch ! I can still make a PR to revert the changes if you prefer to do the PR on your own. BTY, I don't know if you changed something in the github permissions but it's maybe not really safe if other users than you have the permissions to merge into develop branch.

**Comment by aliabdolali** [comment]
Hi @mickaelaccensi, thanks for notifying us. It was just a few people with write permission. 
I had a conversation with @JessicaMeixner-NOAA. We made some modifications to the git access section, so from now on, only Jessica and myself have the write access.

**Comment by mickaelaccensi** [comment]
ok. do you want to revert the merge I did or that's fine ?

**Comment by aliabdolali** [comment]
@mickaelaccensi Yes, please.

**Comment by mickaelaccensi** [comment]
there is a branch revert-246-bugfix/trnc on the NOAA-EMC but I'm not allowing to do the PR. maybe the permissions are too restrictives now. BTW, you can probably do it ?

**Pull request merged**
