### PR TITLE
doxygen marked code:  subset 2

### PR DESCRIPTION
**Pull request by MatthewMasarik-NOAA**
# Pull Request Summary
A second batch of source files has been marked with `doxygen` tags.  These are all the `wm*` _multi_ related files, with the one exception of wmesmfmd.F90.

## Description
Provide a detailed description of what this PR does.
* Adds a second round of source files that have been marked-up with doxygen tags.
* The WW3 ESMF cap, wmesmfmd.F90, has been put aside from this subset.  All the markup is complete in the file, but only a small number of the subroutines documented are reflecting this in the http doxygen output.  It will be debugged and included in a later PR.
* Additionally, all http output has been looked at closely and some documentation updated accordingly.  The regtest matrix has been re-run and the new output files attached below.

What bug does it fix, or what feature does it add?
*  Adds documentation to the files listed in the form of doxygen tags.
* **Filelist**
  * [ ] _wmesmfmd.F90 (on hold)_
  * [x] wmfinlmd.F90
  * [x] wmgridmd.F90
  * [x] wminiomd.F90
  * [x] wminitmd.F90
  * [x] wmiopomd.F90
  * [x] wmmdatmd.F90
  * [x] wmscrpmd.F90
  * [x] wmunitmd.F90
  * [x] wmupdtmd.F90
  * [x] wmwavemd.F90

Is a change of answers expected from this PR?
*  No.  

Please also include the following information: 
* Add any suggestions for a reviewer 
  * NA 
* Mention any labels that should be added: 
  * _documentation_
* Are answer changes expected from this PR? Please describe the changes and the reason why in addition to which of the following labels would apply: 
  * No, answers are not expected to change.  The edits made to code were for documentation purposes only.  It's always possible though that a typo or other unintended edit could introduce a bug, so for this reason the full matrix was run to verify.

### Issue(s) addressed
* Addresses:  issue #586 , though does not close it.

### Commit Message
doxygen:  add marked-up wm* multi files

### Check list  
- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [na] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [na] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
  * By running the full matrix of regression tests on the edits vs current develop, and confirming no answers changed.
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
  * No changes -- documentation only.  No new tests needed, documentation is not tested. 
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
  * Yes.  Hera, Intel.
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):    
  * [matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/8600515/matrixCompSummary.txt)
  * [matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/8600518/matrixCompFull.txt)
  * [matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/8600521/matrixDiff.txt)
 
* Please indicate the expected changes in the regression test output ([Note the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)).
  * Only the expected non-b4b differences. 
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):
```bash
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (17 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (20 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_ta1/./work_UPD0F_U                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST0                     (1 files differ)
ww3_tp2.6/./work_ST4                     (1 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
**********************************************************************
************************ identical cases *****************************
**********************************************************************
```

### CODE REVIEW

**Comment by aliabdolali** [comment]
@MatthewMasarik-NOAA I did the reivew, looks good to me. Could you merge the develop into this branch? I'd like to run regrests. Also, I wonder if you have checked the http version of it? to make sure they all look as expected?

**Comment by MatthewMasarik-NOAA** [comment]
@aliabdolali  I've merged in develop and have reviewed the http output.  I made several fixes for typo's and a few malformed doxygen output snippets.  The regtest matrix and comp have been run with the updated output included above.  This is ready for review.

**Comment by aliabdolali** [comment]
@MatthewMasarik-NOAA thanks, I am going to do my final review

**Review by aliabdolali — APPROVED** [review]

**Comment by aliabdolali** [comment]
The regtests ran successfully on NOAA RDHPC, with pre-known non-identical cases
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/8640146/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/8640147/matrixCompFull.txt)


```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (22 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (12 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4                     (1 files differ)
ww3_tp2.6/./work_ST0                     (1 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
```

**Pull request merged**
