### PR TITLE
Bugfix/cap cha flx5

### PR DESCRIPTION
**Pull request by ukmo-nievesvaliente**
# Pull Request Summary
Correction of Charnock coefficient for low winds inside FLX5 switch. 

## Description
This fix includes a correction and capping of the Charnock coefficient when using FLX5 switch including the aerodynamically smooth regime contribution. This should reduce the previous very large values of the Charnock coefficient during light winds when using FLX5. Additionally, charnock is now computed inside the switch.

No regtest change is expected.

* Reviewers: @ukmo-ccbunney @ukmo-juan-castillo 
* Mention any labels that should be added:  _bug_
* Are answer changes expected from this PR? Yes. Please describe the changes and the reason why in addition to which of the following labels would apply: Charnock parameter model output when using flx5 switch.

### Issue(s) addressed
N.a.

### Commit Message
Capping for charnock when using FLX5 switch; aerodynamically smooth regime correction.

### Check list  

- [Yes ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ Yes] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ N.a.] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ N.a.] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? Regtest and Met Office wave models.
* Are the changes covered by regression tests? No (If not, why? Do new tests need to be added?) N.a.
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? Yes, Cray compiler in the CrayXC40 HPC at the Met Office.
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):   
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/8388601/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/8388607/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/8388608/matrixDiff.txt)

* Please indicate the expected changes in the regression test output ([Note the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)). No changes should be expected; however, 4 files differ in regtest ww3_ts1/NL5. As no changes are expected, we compared the source terms and confirmed that there are no changes between develop and this branch. For more details with this regtest refer to issue #471.

### CODE REVIEW

**Review by ukmo-juan-castillo — APPROVED** [review]
The calculation of the Charnock coefficient has changed, so it will change results even if it is only in the Charnock parameter output. I understand that the changes are related to a new parameterization of Charnock that works better in this particular case, so it makes sense to update it.

The code simplification in w3src4md, and moving the calculation of Charnock to w3flx5md are very good changes.

**Comment by ukmo-nievesvaliente** [comment]
> The changes in the charnock parameter results are now mentioned in the Pull Request Summary.

**Review by ukmo-ccbunney — APPROVED** [review]
All looks good to me.
The w3src4md code looks a lot tidier now too. 👍

**Comment by JessicaMeixner-NOAA** [comment]
Regtests ran as expected here, with not b4b tests: 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (12 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (18 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.15/./work_ST6FLX5                     (0 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
```

and full matrix: 
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/8392140/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/8392141/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/8392142/matrixDiff.txt)

@aliabdolali I think this PR can be merged.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Pass regression tests at NCEP

**Comment by aliabdolali** [comment]
@ukmo-nievesvaliente 

could you check the following test:

`./bin/run_cmake_test -b slurm -o all -c hera.intel -S -T -s ST6 -i input_rho -w work_ST6FLX5 ../model ww3_tp2.15
`
**And here is the logfile.**

```
model/src/w3flx5md.F90(145): error #6580: Name in only-list does not exist or is not accessible.   [AALPHA]
      USE W3GDATMD, ONLY: AALPHA
--------------------------^
model/src/w3flx5md.F90(191): error #6404: This name does not have a type, and must have an explicit type.   [AALPHA]
        CHARN = MAX( CHARN , AALPHA )
-----------------------------^
model/src/w3flx5md.F90(191): error #6363: The intrinsic data types of the arguments must be the same.   [MAX]
        CHARN = MAX( CHARN , AALPHA )
-----------------------------^
model/src/w3flx5md.F90 (code 1)
make[2]: *** [model/src/CMakeFiles/ww3_lib.dir/w3flx5md.F90.o] Error 1
make[1]: *** [model/src/CMakeFiles/ww3_lib.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ukmo-nievesvaliente** [comment]
@aliabdolali there was a problem with the minimum charnock coefficient not being defined when using ST6. This is fixed now using ALPHA0 value in order to be consistent with other configurations. 

The relevant regtests were completed successfully after the last modification (see attached .txt file).
run_test -o both -c ukmo_cray_gnu -S -s ST4 -i input_rho -w work_ST4FLX5 ../model11 ww3_tp2.15
run_test -o both -c ukmo_cray_gnu -S -s ST6 -i input_rho -w work_ST6FLX5 ../model11 ww3_tp2.15
[matrix_FLX5_regtests.txt](https://github.com/NOAA-EMC/WW3/files/8417456/matrix_FLX5_regtests.txt)

**Comment by aliabdolali** [comment]
> @aliabdolali there was a problem with the minimum charnock coefficient not being defined when using ST6. This is fixed now using ALPHA0 value in order to be consistent with other configurations.
> 
> The relevant regtests were completed successfully after the last modification (see attached .txt file). run_test -o both -c ukmo_cray_gnu -S -s ST4 -i input_rho -w work_ST4FLX5 ../model11 ww3_tp2.15 run_test -o both -c ukmo_cray_gnu -S -s ST6 -i input_rho -w work_ST6FLX5 ../model11 ww3_tp2.15 [matrix_FLX5_regtests.txt](https://github.com/NOAA-EMC/WW3/files/8417456/matrix_FLX5_regtests.txt)

Thanks @ukmo-nievesvaliente 
Now, I also tested it after your fix at our end. Thanks, it is now working as expected.
Here is a summary of the whole matrix comparison with the base.
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/8429070/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/8429071/matrixCompFull.txt)

with known non-b4b cases.

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (18 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (12 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
```

**Pull request merged**
