### PR TITLE
add coupling field for mean direction without projection

### PR DESCRIPTION
**Pull request by mickaelaccensi**
# Pull Request Summary
add coupling field for mean direction without projection

## Description
this PR is about exchanging the mean direction instead of the cos and sin of the direction. This useful when the ww3 grid is rotated.

### Issue(s) addressed
linked to issue #459 
also solve issue #457 (only typo)
also solve issue #463 (matrix.comp not behaving correctly on ww3_tp2.18)
also solve issue #442 (incorrect statements in inp file in ww3_tp2.17)

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)? yes
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number)
* Please list appropriate labels code managers should add for this PR:   
_new feature_
 
* Reviewers: @ukmo-ccbunney  @aliabdolali 

### Commit Message
exchange the mean direction directly as a coupled field instead of the projected cos and sin of the direction

### Testing
* How were these changes tested? matrix
* Are the changes covered by regression tests? no
* If a new feature was added, was a new regression test added? no
* Have regression tests been run? yes
* Which compiler / HPC you used to run the regression tests in the PR? intel
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):   
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7116764/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7116765/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7116766/matrixDiff.txt)

Please indicate the expected changes in the outputs ([excluding the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)).

no changes expected except usual not b4b regtest
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (14 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
ww3_tp2.17/./work_mc1                     (1 files differ)
ww3_tp2.17/./work_ma1                     (1 files differ)
ww3_tp2.18/./work_TIDE                     (0 files differ)
ww3_tp2.18/./work_TIDE_MPI                     (0 files differ)

### CODE REVIEW

**Review by ukmo-ccbunney — COMMENTED** [review]
Changes look sensible to me, although I cannot test them as they are not covered by a regression test.

Just two comments:
 - I was a bit confused by the difference in `ww3_tp2.17/work_m[ac]1` as it appears to be just a single dividing line that is missing in log output.

 - Also, I notice that the comments on the direction convention for coupled fields in `w3oacpmd` are not quite right, example:
  `"dir : oceanographic convention (GRIDDED files) - 0 degree from north, 90 from east"`. Isn't that describing nautical/meteorological convention? Oceanographic convention is direction **_to_**, is it not?

**Comment by mickaelaccensi** [comment]
I've corrected some minor bugs and typo and reran the full matrix.
results are here :
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7128729/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7128730/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7128731/matrixDiff.txt)

**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (14 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
ww3_tp2.17/./work_mc1                     (2 files differ)
ww3_tp2.17/./work_ma1                     (2 files differ)

so now differences in ww3_tp2.17 are : 
work_ma1 : crash on develop branch due to bad inp file (corrected in this branch)
work_mc1 : due to pdlib which is not installed on my HPC so it crash on ww3_multi

differences on grid.out are because I've rerun it without removing old files so it used a ST4 file previously created

**Review by ukmo-ccbunney — APPROVED** [review]
@mickaelaccensi I have run the regression tests and have the same results as you.

**Comment by JessicaMeixner-NOAA** [comment]
The output from running tests at NCEP, we get the typical results: 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (7 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ)
ww3_tp2.17/./work_ma1                     (0 files differ)
ww3_tp2.17/./work_mc1                     (1 files differ)
ww3_tr1/./work_bndin                     (1 files differ)
ww3_ufs1.1/./work_b                     (0 files differ)
ww3_ufs1.2/./work_b                     (0 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
```

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7154328/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7154329/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7154330/matrixDiff.txt)

**Review by aliabdolali — APPROVED** [review]

**Pull request merged**
