### PR TITLE
Feature/ptnme

### PR DESCRIPTION
**Pull request by mickaelaccensi**
**description :**
extend the output points name from 10 characters to 40 to be able to have the same buoy names as the one provided by the European Marine Environment Monitoring service
linked to issue #236 
**model :**
update VERXXX : w3iopomd
**matrix :**
done with intel-comp/18, impi/2018.1.163, netCDF-Fortran 4.5.2
changes in all results but only spaces.
not b4b : mww3_test_03

see original matrix :
[matrix.zip](https://github.com/NOAA-EMC/WW3/files/5007356/matrix.zip)
and matrix with diff -b (ignore-space-change) :
[matrix_nospacechange.zip](https://github.com/NOAA-EMC/WW3/files/5007361/matrix_nospacechange.zip)

### CODE REVIEW

**Comment by aliabdolali** [comment]
Hi Mickael,
I am doing final checks on UKMET PR, then I'll merge your two PR.
AA

**Comment by mickaelaccensi** [comment]
Hi Ali,
ok thanks. I'll be on holidays for 3weeks tonight but I'll try to check my github messages

**Review by ukmo-ccbunney — CHANGES_REQUESTED** [review]
Hello @mickaelaccensi ,
I am on vacation at the moment (and for the next two weeks), so this is only a very quick look at the code. The changes look sensible; the only thing that I can see that needs updating is the documentation. 

For example, there are several references to the length of the point names being `C*10` in the input file templates, these just need changing to `C*40`:
```
model/inp/ww3_ounp.inp:$ - Point name (C*10), lat, lon, d, U10 and    |  loop     | over
model/inp/ww3_ounp.inp:$ - Point name (C*10), depth, wind speed and   |  loop     | over
model/inp/ww3_outf.inp:$ extension name (C*$), a scale factor (R), a unit identifier (C*10),
model/inp/ww3_outp.inp:$ - Point name (C*10), lat, lon, d, U10 and    |  loop     | over
model/inp/ww3_outp.inp:$ - Point name (C*10), depth, wind speed and   |  loop     | over
model/inp/ww3_outp.inp:$ - Point name (C*10), lat, lon, d, U10 and    |  loop     | over
model/inp/ww3_shel.inp:$          longitude, latitude and name (C*10) of output points.
```

I can't see anything specific about the point name length in the manual - it just includes the raw `*.inp` files, so perhaps that is the only place it needs updating.

**Comment by mickaelaccensi** [comment]
-update conversion scripts inp2nml (ww3_multi_inp2nml.sh and ww3_shel_inp2nml.sh)

-update C*10 to C*40 in inp and nml files

-mww3_test06/input/ww3_multi_grdset_d_r.nml :
             update values to be consistent with inp file

-ww3_ta1/*/ww3_multi.nml : correct copy/paste typo for TYPE%POINT%FILE
                          (always using input_UPD3_U_cap/points.list)

-ww3_tc1/input/ww3_shel.nml : correct error in start/stop date and
                             remove unused CUR homogeneous forcing

**Comment by chrisbunney** [comment]
I'm happy with these changes now @mickaelaccensi .
I assume your changes to the ww3_tc1 and ww3_ta1 regtests do not affect their output?

**Review by ukmo-ccbunney — APPROVED** [review]

**Comment by ukmo-ccbunney** [comment]
I'm happy with these changes now @mickaelaccensi .
I assume your changes to the ww3_tc1 and ww3_ta1 regtests do not affect their output (in the current regtest matrix)?

**Comment by mickaelaccensi** [comment]
> I'm happy with these changes now @mickaelaccensi .
> I assume your changes to the ww3_tc1 and ww3_ta1 regtests do not affect their output (in the current regtest matrix)?

it doesn't change the regtest matrix. Only nml are modified for ww3_tc1 and ww3_ta1 regtests

**Review by aliabdolali — APPROVED** [review]

**Pull request merged**
