### PR TITLE
logic and restart corruption fixes

### LINKED ISSUE #945: initialization of mpi_send and recv is hardwired regardless of grid or decomposition type in w3initmd
**Describe the bug**

This line

https://github.com/NOAA-EMC/WW3/blob/ea0de58feec301f319cf87aa4ececbc010b00238/model/src/w3initmd.F90#L2192-L2193

hardwires setting up all the mpi_send and recv inits for flout (1) or (7) regardless of domain decomposition or grid type. However, the domain decomposition case does make use of these and instead uses ``do_output_exchanges``.

**To Reproduce**
Steps to reproduce the behavior. 

**Expected behavior**

Since the domain decomposition case does not use these mpi calls, the code should only check for whether ``lpdlib`` is true or false. However, in the current code removing the ``.true.`` results in a out-of bounds reference when using domain-decomposition at

https://github.com/NOAA-EMC/WW3/blob/ea0de58feec301f319cf87aa4ececbc010b00238/model/src/pdlib_field_vec.F90#L1331-L1334
 
because the ``hs`` does not point to the "extended output arrays" on NAPFLD. This is  because the call to ``w3xdma`` within the send/recv initialization block is bypassed when  removing the ``.true.``.

The failure occurs at the model startup time, although I'm not clear why it occurs when no output is being created.

The following change in ``pdlib_field_vec`` resolves the issue and allows the ``.true.`` to be removed from ``w3initmd``. Initial testing is that it is B4B w/ the current code. There may be a different or more preferred way to fix and I'm open to suggestions. 

```
diff --git a/model/src/pdlib_field_vec.F90 b/model/src/pdlib_field_vec.F90
index 95c817d9..ce7a42e3 100644
--- a/model/src/pdlib_field_vec.F90
+++ b/model/src/pdlib_field_vec.F90
@@ -1325,7 +1325,7 @@ CONTAINS
         END DO
       END IF
       IF ( IAPROC .EQ. NAPFLD ) THEN
-        !              CALL W3XDMA ( IMOD, NDSE, NDST, FLGRDALL )
+        IF (.not. WADATS(IMOD)%AINIT2) CALL W3XDMA ( IMOD, NDSE, NDST, FLGRDALL )
         CALL W3XETA ( IMOD, NDSE, NDST )
         IH     = 0
         IF ( FLGRDALL( 2, 1) ) THEN
```

**Screenshots**

**Additional context**

### LINKED ISSUE #946: ill-defined logic constructs for domain decomposition and grid type
**Describe the bug**

In Discussion https://github.com/NOAA-EMC/WW3/discussions/944, it was verified that domain decomposition works only with the unstructured mesh. There are multiple ``if`` statements in the code which imply that domain decomposition + structured is a possible application. These should be re-written to provide the user with a clear understanding of the grid-type restrictions with domain decomposition. 

**Expected behavior**

Statements such as``IF ((.NOT. LPDLIB).OR.(GTYPE .NE. UNGTYPE))``  should be replaced with ``if (LPDLIB .eqv. .FALSE.)`` or ``(.NOT. LPDLIB)``. This  evaluates as T for card-deck + any grid type, and false otherwise. This reproduces the current logic, except that it eliminates the combination of "lpdlib=true,grid=structured", which evaluates as T currently.

Statements such as ``IF (LPDLIB .and. (GTYPE.eq.UNGTYPE)) THEN`` should be replaced with ``if (LPDLIB)``. This is consistent with domain decomposition only being available with unstructured meshes.

### LINKED ISSUE #948: field corruption at the restart-writing frequency (cross-posting from UFS)
**Describe the bug**

**NOTE:** This is a cross-post of UFS Issue [1556](https://github.com/ufs-community/ufs-weather-model/issues/1556).

An issue has been found relating to the domain decomposition, the restart-write frequency and the failure to reproduce when changing the decomp for WW3.

The test case is the ATM-WAV app, coupled through CMEPS. This app resides in within my fork and uses as a test case a global (77S-85N) unstructured mesh with the MOM6 1-deg tripole land mask (no land points exist in the mesh). The time-stepping mode is explicit for WW3. 

In ww3_shel.nml, the following values are set:

```
&output_date_nml
  date%field%outffile  = '1'
  date%field%stride    = '720'
  date%restart2%stride = '3600'
```

When run on 5PEs for WW3, the following decomposition is used:

emesh decomp

Using the mediator history file, the following fields for the export of ``z0`` from the wave model are shown at the timestep prior to the restart write, at the restart write, and following the restart write. Note the value of ``z0`` has been multipled by 1.0e3. 

wavImp_Sw_z0

The export of ``z0`` is clearly corrupted on the last decomposition PE. This occurs each time the restart file is written. If N PEs are used for WW3, then every Nth value of ``UST`` has the value of 1.0e-4.

Using simple print statements, this was found to be related to ``UST`` and to occur just after the ``MPI_STARTALL`` line in ``w3wavemd.F90``. 

```
#ifdef W3_MPI
        IF ( FLOUT(8) .AND. NRQRS.NE.0 ) THEN
          IF ( DSEC21(TIME,TONEXT(:,8)).EQ.0. ) THEN
	    CALL MPI_STARTALL ( NRQRS, IRQRS , IERR_MPI )
            FLGMPI(8) = .TRUE.
            NRQMAX    = MAX ( NRQMAX , NRQRS )
#endif
```

Commenting out the call to ``MPI_STARTALL`` removed the corruption. This is a repeat of the previous figure with the commented out line:
fix wavImp_Sw_z0

With this line commented out, the ATM-WAV case run out for 24 hours on either 20PE or 30PE reproduces. The 30PE case also restart reproduces. 

In the ATM-WAV case, failure to reproduce w/ changing decomposition is due to the corrupted ``z0`` field which depends explicitly on the location of the final decomposition element and which occurs when WW3 writes a restart file. This is confirmed by setting ``date%restart2%stride`` to a value outside of the total run length. This gives reproducibility across tasks with no code modification. 

Finally, WW3 history files written to out do not show any corruption of the field ``ust``. I believe this is because the ``z0`` field is put into the export state after WW3 has completed it's model advance, including any model output and restart writing.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# Pull Request Summary
 

This work is part of UFS Issue [1556](https://github.com/ufs-community/ufs-weather-model/issues/1556)

Fixes for logic and restart-write corruption for domain-decomposition case.

## Description

Cleans up the logical if statements for combinations of lpdlib and grid type to clarify that lpdlib + structured is not valid use-case.

Fixes corruption of ``Z0`` exported by the wave model at the restart writing frequency by by-passing the code blocks in ``w3initmd`` which initialize the mpi sends/recvs even when running with domain decomposition (where they are not used).

### Issue(s) addressed

- fixes #945 
- fixes #948 
- fixes #946 

### Commit Message

Clarify allowed grid type logic when running with domain decomposition. By-pass mpi send/recv set-up in ``w3initmd`` when using domain decomposition.

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

Tested in UFS branch containing mesh cap with these fixes for ATMW + CMEPS for 24hr control, restart, decomposition (results on 30PE are B4B w/ 20PE) and debug test. The coupled model case does *not* show decomposition reproducibility however.

UFS will also be run for existing RTs using the mesh cap branch with these changes.

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
Thanks @DeniseWorthen!  I'll submit the regtests.

**Comment by DeniseWorthen** [comment]
Hera and GNU RTs with waves all pass.

**Comment by MatthewMasarik-NOAA** [comment]
Great, thanks for that update @DeniseWorthen.  The WW3 regtests are still running though should be done shortly.

**Comment by DeniseWorthen** [comment]
Note that whitepaces have changed in ``w3initmd.F90`` because an if/endif was removed. This will mean the indenting of the enclosed block will change.

**Comment by MatthewMasarik-NOAA** [comment]
Update:  fyi @DeniseWorthen.  I found my compare script job on hera hung near the end.  I'm going to re-submit it to get clean logs, but from what I can tell so far it doesn't look like any answers have changed. I'll be able to merge it this afternoon or early tomorrow.

**Comment by MatthewMasarik-NOAA** [comment]
Hi @DeniseWorthen, the job I re-ran yesterday hung on the same test comparison, so it is being run once more to be certain there is no issue, and to get the log output.  This would normally be ~1hr job, but the queue on `hera` seems to be quite slow today.  My intention is to merge it today as soon as the job returns.  Thanks for your patience.

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA OK, thanks. Are you sure that the issue isn't actually w/ the changes in the PR?

**Comment by MatthewMasarik-NOAA** [comment]
@DeniseWorthen, that's a possibility.  I'm hoping it is just a hiccup in running the compare script, which can happen, but I haven't ruled out that there is an issue with the PR.  I will hopefully know more shortly.

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA Is there any update on the RT testing for this PR?

**Comment by MatthewMasarik-NOAA** [comment]
Hi @DeniseWorthen, the third attempt that went through over the weekend had the same effect of hanging, and I've been looking into the cause today.  There's a file difference between your branch and the develop run for the `ww3_ufs1.3` regression test.  We are currently investigating this.  Please bear with us for the delay, with the fairshare levels we have had very slow turn around times the past few days.  We've moved some over to orion to hopefully help speed things up.  I'll report back as soon as I have some answers.

**Comment by DeniseWorthen** [comment]
Thanks for the update.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
On hera, both @MatthewMasarik-NOAA and I had ww3_ufs1.3 differences in the rmp_src_to_dst_conserv_002_001.nc and rmp_src_to_dst_conserv_003_001.nc files.  I have looked multiple times at the code changes and there is no explanation for this.  Moreover, the results other than  the known diffs in the restart files are the same for this regression test.  Looking at the results they are on the order of 1e-16.   We're having trouble getting through the queue on hera, so I re-ran regression tests on orion, in which there was no issue.  Those logs are posted here.  The information about the ww3_ufs1.3 test is mentioned here in case we need to back trace problems.  



Matrix results from running with intel on Orion: 

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/11030161/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/11030162/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/11030163/matrixDiff.txt)


Only the expected not b4b tests: 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (12 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (13 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (18 files differ)
ww3_ta1/./work_UPD0F_U                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.14/./work_OASACM5                     (1 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.17/./work_ma                     (1 files differ)
ww3_tp2.17/./work_mc1                     (4 files differ)
ww3_tp2.17/./work_mc                     (4 files differ)
ww3_tp2.17/./work_a                     (1 files differ)
ww3_tp2.17/./work_b                     (4 files differ)
ww3_tp2.17/./work_mb                     (4 files differ)
ww3_tp2.17/./work_c                     (4 files differ)
ww3_tp2.17/./work_ma1                     (1 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```

**Comment by MatthewMasarik-NOAA** [comment]
Thank you @JessicaMeixner-NOAA for the regtests and documentation of the experience we had on hera.  

And thank you to @DeniseWorthen for the all work that went into this which fixes 3 issues.  Your hard work is very much appreciated.

**Pull request merged**
