### PR TITLE
Update dev/ufs-weather-model branch with develop - 2023-jun-27

### LINKED ISSUE #1028: Update dev/ufs-weather-model branch with develop
**Is your feature request related to a problem? Please describe.**
The WW3 `dev/ufs-weather-model` branch needs to be updated with `develop` branch additions since last sync.

**Describe the solution you'd like**
Sync `dev/ufs-weather-model` branch with `develop`.

**Describe alternatives you've considered**
NA.

**Additional context**
NA.

### PR DESCRIPTION
**Pull request by MatthewMasarik-NOAA**
# Pull Request Summary
Syncs updates in `develop` branch to `dev/ufs-weather-model` branch.

## Description
Sync develop to dev/ufs-weather-model.  No change of answers.

Please also include the following information: 
* Are answer changes expected from this PR? 
  *  No. 

### Issue(s) addressed
- fixes #1028
- related to ufs-community/ufs-weather-model/issues/1808

### Commit Message
Sync develop to dev/ufs-weather-model

### Check list  
- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [na] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [na] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing
Tested within UFS by running the full RT's.  WW3 regression tests are not run for `dev/ufs-weather-model`.  Test logs are attached to the ufs-weather-model PR, ufs-community/ufs-weather-model/pull/1811.

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
fyi @JessicaMeixner-NOAA we just need to approve to get into the UFS queue.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by MatthewMasarik-NOAA** [comment]
Thanks @JessicaMeixner-NOAA 👍

**Comment by BrianCurtis-NOAA** [comment]
@JessicaMeixner-NOAA Can you please give a look over the commits after your approval and re-approve if all looks OK?

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
@BrianCurtis-NOAA Thanks for your request of re-approval.  Everything looks good here!

**Comment by zach1221** [comment]
Hello, testing is complete on UFS-WM PR #1811. @JessicaMeixner-NOAA can you please go ahead to merge this PR?

**Pull request merged**
