### PR TITLE
QP

### PR DESCRIPTION
**Pull request by mickaelaccensi**
add output parameter for k bandwidth

# Pull Request Summary
correct bug fix for peakedness computation and add k bandwidth output parameter

# Description
correct the computation of QP parameter
add QKK output parameter 
change UST scale factor (impacts on UST and CHA precisions)
update output parameters listing to add QP and QKK and missing ones

# Issue(s) addressed
#1061 

# Commit Message
correct the computation of QP parameter, add QKK output parameter, change UST scale factor

# Testing
 
- How were these changes tested? matrix
- Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) outputs added in ww3_tp2.6 and ww3_tp2.15. A dedicated regtest will be added in the next PR
- Have the matrix regression tests been run (if yes, please note HPC and compiler)? yes
- Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.) 
- ww3_tp2.6 : differences on cha and ust output parameters due to increase of ust scale factor
- ww3_tp2.21 : crash due to nml option - see issue #1062 
- ww3_tp2.10 and ww3_tp2.17 : out_grd differs but not the outputs
- Please provide the summary output of matrix.comp (matrix.Diff.txt, matrixCompFull.txt and matrixCompSummary.txt): only tmp file because for some unknown reasons, matrix.comp get stuck on ww3_tp2.7/work_ST0 for hours!

[fulldiff.tmp.txt](https://github.com/NOAA-EMC/WW3/files/12535591/fulldiff.tmp.txt)
[notIdenticalList.tmp.txt](https://github.com/NOAA-EMC/WW3/files/12535592/notIdenticalList.tmp.txt)
[summary.tmp.txt](https://github.com/NOAA-EMC/WW3/files/12535593/summary.tmp.txt)

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi two quick comments: 
1: Can you put back the extra info about testing in the PR template?
2: Can you explain why the regression test is not included in this PR?

**Comment by CarstenHansen** [comment]
This sounds good! A long time ago (Issue https://github.com/NOAA-EMC/WW3/issues/210) I considered a possible solution to this bug because I was looking at those parts of the code when a user reported it on the ww3 mailing list. I didn't really have interest in the QP (used for the Benjamin-Feir instability index). But I later found that it is still applied in some academic studies, so it is important. I remember it was a bit complex to reach a complete fix of the bug - the bug is present at more than one location in the code.

**Review by MatthewMasarik-NOAA — CHANGES_REQUESTED** [review]
Hi @mickaelaccensi, just a note that there are still some questions from @JessicaMeixner-NOAA to be addressed.

**Comment by mickaelaccensi** [comment]
I've updated the PR message and created an issue for QP bugfix.
I've merged it with the last develop branch, I'm running now the matrix since my pdlib issue seems to be solved (both parmetis and scotch works now on my HPC).
I'll provide you the matrix.comp files for tomorrow.

**Comment by MatthewMasarik-NOAA** [comment]
Hi @mickaelaccensi, I don't see a regtest.  Is there a reason you haven't added one?

**Comment by mickaelaccensi** [comment]
it is because I had to split the Fabrice branch into 3 and the regtest is designed to work with the next feature branch

**Comment by JessicaMeixner-NOAA** [comment]
> it is because I had to split the Fabrice branch into 3 and the regtest is designed to work with the next feature branch

This is adding an output of QKK?  I see this in the code, but not in the text of the PR.  I get that this is part of larger work, but I'm concerned we aren't testing features when they're added.  Could we  add the output request of QKK to an existing regression test or 2 (maybe 1 structured 1 unstructured), even temporarily?

**Comment by mickaelaccensi** [comment]
added and tested in ww3_tp2.6 and ww3_tp2.15

**Review by MatthewMasarik-NOAA — CHANGES_REQUESTED** [review]
Hi @mickaelaccensi, here's what I see is still outstanding:
* `tp2.17` - diffs in `out_grd.*` and `restart`s.  Are these diffs expected?
* `tp2.21` - diffs in `out_grd/pnt` and `restart`s.  Are these expected?
<br>

(This can be addressed at a later time)
  * #1062

**Comment by mickaelaccensi** [comment]
I would tend to say that it is due to the bug #1062, I'm working on it right to provide a separated PR
could you try to run matrix with inp on your side to confirm that the only differences are the expected ones in ww3_tp2.6 and ww3_tp2.15 ?

**Comment by MatthewMasarik-NOAA** [comment]
> could you try to run matrix with inp on your side to confirm that the only differences are the expected ones in ww3_tp2.6 and ww3_tp2.15 ?

Sure, I will run the matrix to get a reference on what is failing and what is not.  

> I would tend to say that it is due to the bug #1062, I'm working on it right to provide a separated PR 

If just using `ww3_multi.nml` is causing the issue you saw for #1062, then that is fine and it can be resolved later.  If it's a symptom of a greater issue -- if it is potentially affecting the diffs for `tp2.21`, `tp2.17` -- then we should get to the bottom of what is going on _prior_ to the PR being merged.

**Comment by MatthewMasarik-NOAA** [comment]
Update:  some of the tests submitted yesterday reached time limits.  Our primary RD machine was unavailable then, but is back today.  I've resubmitted the runs and should have the results later today.

**Comment by MatthewMasarik-NOAA** [comment]
Hi @mickaelaccensi,
Here's the logs from matrix.comp

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
## known non-b4b
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
##

ww3_tp2.15/./work_PR3_UQ_RHO                     (5 files differ)
ww3_tp2.15/./work_PR3_UQ_RHO_MPI                     (5 files differ)
ww3_tp2.15/./work_ST6FLX5                     (5 files differ)
ww3_tp2.15/./work_ST4FLX5                     (5 files differ)
ww3_tp2.6/./work_ST0                     (4 files differ)
ww3_tp2.6/./work_ST4                     (16 files differ)
ww3_tp2.6/./work_pdlib                     (4 files differ)

**********************************************************************
************************ identical cases *****************************
**********************************************************************
```
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/12560887/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/12560888/matrixCompFull.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/12560886/matrixDiff.txt)
<br>

Please add the required regtest so we can proceed with the review.  Thanks

**Comment by mickaelaccensi** [comment]
Hi Mat,

I've already added the QP and QKK outputs in ww3_tp2.6 and ww3_tp2.15, we should find them in work_ST4

**Comment by MatthewMasarik-NOAA** [comment]
> I've already added the QP and QKK outputs in ww3_tp2.6 and ww3_tp2.15, we should find them in work_ST4

Hi Mickael, okay I see.  Thanks for that.  

Then the only thing outstanding is updating the relevant scripts in `/model/inp/` and `model/nml/` to reflect this.  Could you add documentation for `QKK` to these scripts?

**Comment by mickaelaccensi** [comment]
good catch ! it's now done

**Comment by MatthewMasarik-NOAA** [comment]
Great, thanks for making those changes @mickaelaccensi.  I'll work on finishing the review.

**Comment by MatthewMasarik-NOAA** [comment]
@mickaelaccensi 

#### Accounting of non-b4b differences
The first four files of each test below are the same (log files and 1 binary gridded output), and their differences are
accounted for by the `QP` and `QKK` variable outputs.  The `ww3_tp2.15` file `ww3.201403.nc` is also due to these variable outputs.

This leaves just the 12 additional netCDF files seen below in `ww3_tp2.6/work_ST4/`.  The difference in these files turned out to be in the list of WW3 switches in the `global_attributes`.  In particular, `NCEP2` is replaced by `NOGRB`.  I believe this is sneaking in at the call to `run_cmake_test` where the `-o both` option has been added, and will affect a condition within `run_cmake_test` that `sed`'s `NCEP2` for `NOGRB`. 

Was the `-o both` option intended just for debugging, or did you want it as part of the PR?  
```
ww3_tp2.15/./work_PR3_UQ_RHO                       (5 files differ)
ww3_tp2.15/./work_PR3_UQ_RHO_MPI                   (5 files differ)
ww3_tp2.15/./work_ST6FLX5                          (5 files differ)
ww3_tp2.15/./work_ST4FLX5                          (5 files differ)
-------------------------------------              ----------------------
  1)  log.ww3 
  2)  out_grd.ww3
  3)  ww3_ounf.out
  4)  ww3_outf.out

  5)  ww3.201403.nc



ww3_tp2.6/./work_ST0                                 (4 files differ)
ww3_tp2.6/./work_pdlib                               (4 files differ)
-------------------------------------              ----------------------
  1)  log.ww3 
  2)  out_grd.ww3
  3)  ww3_ounf.out
  4)  ww3_outf.out



ww3_tp2.6/./work_ST4                                  (16 files differ)
-------------------------------------              ----------------------
  1)  log.ww3
  2)  out_grd.ww3
  3)  ww3_ounf.out
  4)  ww3_outf.out

  5)  ww3.201008_cfd.nc
  6)  ww3.201008_cfx.nc
  7)  ww3.201008_cge.nc
  8)  ww3.201008_cha.nc 
  9)  ww3.201008_dtd.nc
 10)  ww3.201008_fc.nc
 11)  ww3.201008_hs.nc
 12)  ww3.201008_lm.nc
 13)  ww3.201008_t01.nc
 14)  ww3.201008_t02.nc
 15)  ww3.201008_t0m1.nc
 16)  ww3.201008_ust.nc
```

**Comment by mickaelaccensi** [comment]
Hi @MatthewMasarik-NOAA ,

I've added QKK as output field in ww3_outf.F90 to be consistent and to allows ww3_tp2.6 and ww3_tp2.15 to output QP and QKK as ASCII output. So I've removed the -o both which was intented to output netCDF. However I don't catch your remark about the global attributes. NCEP2 is not present in the switch files for ww3_tp2.6 and ww3_tp2.15, so I don't understand why it should appear in the global attributes. Let me know.

**Comment by MatthewMasarik-NOAA** [comment]
> I've added QKK as output field in ww3_outf.F90 to be consistent and to allows ww3_tp2.6 and ww3_tp2.15 to output QP and QKK as ASCII output.

This is sounds good, thanks for making that update.

> So I've removed the -o both which was intented to output netCDF. 

Great, this should remove the differences from `ww3_tp2.6/work_ST4`.

> However I don't catch your remark about the global attributes. NCEP2 is not present in the switch files for ww3_tp2.6 and ww3_tp2.15, so I don't understand why it should appear in the global attributes.

Yes, I found this confusing too.  I believe that `run_cmake_test` uses `sed` on the switchfile to change between `NOGRB` and `NCEP2`. 

**develop:  ww3.201008_cfd.nc**
image

**bugfix/QP:  ww3.201008_cfd.nc**
image


I'll re-run the regtests and let you know the result.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
#### Updated regtests 
The update fixed the extra non-b4b differences that were seen in 
`ww3_tp2.6/work_ST4`, so now all non-b4b's are accounted for.

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
## known non-b4b
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (13 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (9 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (14 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
##

ww3_tp2.15/./work_PR3_UQ_RHO             (5 files differ)
ww3_tp2.15/./work_PR3_UQ_RHO_MPI         (5 files differ)
ww3_tp2.15/./work_ST6FLX5                (5 files differ)
ww3_tp2.15/./work_ST4FLX5                (5 files differ)
ww3_tp2.6/./work_ST0                     (4 files differ)
ww3_tp2.6/./work_ST4                     (4 files differ)
ww3_tp2.6/./work_pdlib                   (4 files differ)

**********************************************************************
************************ identical cases *****************************
**********************************************************************
```

* [2023sep13.matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/12608821/2023sep13.matrixCompSummary.txt)
* [2023sep13.matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/12608822/2023sep13.matrixCompFull.txt)
* [2023sep13.matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/12608819/2023sep13.matrixDiff.txt)

<hr/>

**Code review**
PASS

**Testing**
PASS

**Comment by MatthewMasarik-NOAA** [comment]
@mickaelaccensi Thank you for this nice PR.  Extra thanks for the manual documentation!

**Comment by mickaelaccensi** [comment]
great ! let me know when you can check and merge the branch bugfix/nml, I have then 2 others PR to send about ST4 and GQM  ;)

**Comment by MatthewMasarik-NOAA** [comment]
I will be able to start working on the bugfix/nml PR, likely tomorrow.  I'm finishing some work today on #1034 and will be able to start it right after.

**Pull request merged**
