### PR TITLE
Output OMP threading info to screen [ww3_shel, ww3_multi]

### LINKED ISSUE #1032: Regtest cmake build.log overwritten
**Describe the bug**
When the regression tests are running their CMake builds, the `build.log` for the shared build is overwritten when the MPI build is run. This means we lose any compiler messages/warnings from the shared build.

**To Reproduce**
Run any MPI enabled regression test

**Expected behavior**
If you run `tail -f build.log` when the build is running, you will see the compiler output for the shared build.
When the MPI build starts, this output will be overwritten (tail will report the file as being truncated).

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
# Pull Request Summary
Added screen output in `ww3_shel` and `ww3_multi` showing number of (available) threads when OMP enabled.
Also includes a fix to avoid truncation of the `build.log` file (see: https://github.com/ukmo-waves/WW3/pull/46)

## Description
When running an OMP enabled version of `ww3_shel` or `ww3_multi` (i.e. compiled with `OMPG`), the program will output a message to the screen stating that OMP is enabled and the number of threads available to the parallel regions.

Note, in MPI/OMP hybrid mode only the "screen" processor will output this message, so the number of OMP threads will be relevant to that processor. I imagine that most people are not running a different number of threads per processor, but that is something to bear in mind!

No change to the regtests outputs are expected, other than the new line in the screen output for `ww3_shel` and `ww3_multi` in the `OMP`/`OMPH` regtests.

### Issue(s) addressed
Fixes: #1032

### Commit Message
Output OMP threading info to screen when running ww3_shel/ww3_multi compiled with the OMPG switch.
Also fixes truncation of build.log when running `run_cmake_build`.

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? **Regtests.**
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) **Yes.**
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? **Cray XC; GNU Compiler.**
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.) **Only expected change is a new output line in the ww3_shel/ww3_multi screen output for OMP/OMPH regtests.**
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

**Regtest results**
```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_02/./work_PR3_UNO_MPI_c_c                     (3 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (17 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (18 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
```

There are some differences in the `ww3_shel.out` and `ww3_multi.out` files for OMP/OMPH tests, but these differences are filtered out by the `matrix.comp` script. The differences are all like this:
```
9,10d8
<   OMP threading enabled. Number of threads:   4
< 
```

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for sharing this @ukmo-ccbunney ! I'll run some tests on my end with this.

**Comment by ukmo-ccbunney** [comment]
Update with regtest results.
One thing I note is that the new output regarding the number of OMP threads is filtered our of `ww3_shel.out` and `ww3_multi.out` when running a comparison with `matrix,.comp`. This is unfortunate as it would be good to capture this in the regrest comparison to catch cases where we might accidentally change the OMP support. I'll have a look and see if the filtering can be amended at all...

**Comment by JessicaMeixner-NOAA** [comment]
@ukmo-ccbunney I was finally able to run some tests with this, and I do at least get the expected number of threads that I request, although I'm not seeing any impact on model performance using various thread counts...

**Comment by ukmo-ccbunney** [comment]
> @ukmo-ccbunney I was finally able to run some tests with this, and I do at least get the expected number of threads that I request, although I'm not seeing any impact on model performance using various thread counts...

How strange! Do you have another machine you can test on? I sometimes run stuff on my linux desktop to check non-MPI code (including OMP runs).

**Comment by JessicaMeixner-NOAA** [comment]
I do, but it's on maintenance today... I'll try that tomorrow!

**Comment by JessicaMeixner-NOAA** [comment]
@ukmo-ccbunney I made a PR to your branch because I was running this and realized I wasn't getting all the build information to the log file that I wanted to see.  It's here: https://github.com/ukmo-waves/WW3/pull/46 I can put it in a new PR if you'd like but I was on this branch so just pushed here. 

The good news is my tests this afternoon are finally showing OMP speed-up closer to what's expected so maybe the other day was just an off day... I don't know.  But this is a nice update to WW3 for a sanity check.

**Comment by ukmo-ccbunney** [comment]
> @ukmo-ccbunney I made a PR to your branch because I was running this and realized I wasn't getting all the build information to the log file that I wanted to see. It's here: [ukmo-waves#46](https://github.com/ukmo-waves/WW3/pull/46) I can put it in a new PR if you'd like but I was on this branch so just pushed here.

Thanks - that's a really useful update. I've merged it into this branch.

> The good news is my tests this afternoon are finally showing OMP speed-up closer to what's expected so maybe the other day was just an off day... I don't know. But this is a nice update to WW3 for a sanity check.

That's good news. Odd how you were experiencing such a lot of variability. It almost sounds like CPU over-subscription on your HPC? Is there a chance that other jobs are grabbing resources from a node you are running on? Also, it could be a result of file system contention too (although our WW3 files are not huge...) When our HPC is running it's weekly RAID check the I/O throughput is degraded and I can see an impact on model runtimes. Just a thought!

Perhaps it's just gremlins...

**Comment by JessicaMeixner-NOAA** [comment]
Would not be surprised by the gremlins!!! I have no idea what is going on to be honest but am happy to see what I was expecting finally.  File system or other things would not surprise me at all...

**Comment by MatthewMasarik-NOAA** [comment]
@ukmo-ccbunney @JessicaMeixner-NOAA 

I wanted to see if either of you are still looking at this, or is it ready for final review?

**Comment by ukmo-ccbunney** [comment]
Hi @MatthewMasarik-NOAA 
It's all ready to go as far as I am concerned.
I'll update the description as this PR now also includes Jessica's [ukmo-waves/#46](https://github.com/ukmo-waves/WW3/pull/46) PR too.

**Comment by MatthewMasarik-NOAA** [comment]
> Hi @MatthewMasarik-NOAA It's all ready to go as far as I am concerned. I'll update the description as this PR now also includes Jessica's [ukmo-waves/#46](https://github.com/ukmo-waves/WW3/pull/46) PR too.

Awesome, thanks @ukmo-ccbunney, I'll get the tests going!

**Review by MatthewMasarik-NOAA — APPROVED** [review]
**Code review**
Pass

**Testing**
Pass

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
**********************************************************************
************************ identical cases *****************************
**********************************************************************
```

* [matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/14558774/matrixCompSummary.txt)
* [matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/14558772/matrixCompFull.txt)
* [matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/14558773/matrixDiff.txt)


Approved.

**Comment by MatthewMasarik-NOAA** [comment]
Thank you @ukmo-ccbunney and @JessicaMeixner-NOAA, having the OMP thread count and full build log output will be very useful for troubleshooting build and runtime issues.

**Pull request merged**
