### PR TITLE
Bugfix/st4wcf

### PR DESCRIPTION
**Pull request by mickaelaccensi**
**description :** 
 bugfix for ST4 b4b reprodctibility
 linked to issue #249 

**model :**
  w3iogrmd : write/read variables AIRCMIN and AIRGB in mod_def.ww3
  w3src4md : initialize array 
  update VERXXX in w3iogrmd

**matrix :**
 done with intel-comp/18, impi/2018.1.163, netCDF-Fortran 4.5.2
 ww3_ts1 : results are correct now
 ww3_ta1 : results are correct now
 ww3_tp2.14 : differences due to metadata history in remap file (not relevant)
 ww3_tp2.18 : now differences due to output messages order (dedicated bugfix in progress)
mww3_test_03 : expected not b4b results
mww3_test_04 : different dates in metadata 'history'  (it will be skipped in another bugfix branch)

[matrix_ST4wcf.zip](https://github.com/NOAA-EMC/WW3/files/5414157/matrix_ST4wcf.zip)

### CODE REVIEW

**Comment by ukmo-ccbunney** [comment]
Great work Mickael - well done on finding that bug.
I'll approve once you have the full regression matrix results.

**Comment by mickaelaccensi** [comment]
I've added the matrix results

**Comment by ukmo-ccbunney** [comment]
ww3_ta1 and ww3_ts1 are still showing differences in the out_grd.ww3 files (which is expected if you are comparing against the original develop branch, of course).

Just to confirm - are these tests now self consistent with each other?

**Comment by mickaelaccensi** [comment]
I've compared the figures against the ones from the develop branch in April 21st (before st4tail merge) and I get the similar plots some differences due to the new parameterization. Does this reply to your question ? (it's also now b4b reproducible on my side)

**Comment by ukmo-ccbunney** [comment]
> 
> 
> I've compared the figures against the ones from the develop branch in April 21st (before st4tail merge) and I get the similar plots some differences due to the new parameterization. Does this reply to your question ? (it's also now b4b reproducible on my side)

Yes - thank you Mickael.

**Review by ukmo-ccbunney — APPROVED** [review]
All good to go!

**Review by aliabdolali — APPROVED** [review]

**Comment by aliabdolali** [comment]
Thanks @mickaelaccensi 
I checked the regtests on NOAA HPC with intel, impi and netcdf
[matrix_bugfix_ST4wcf.zip](https://github.com/NOAA-EMC/WW3/files/5430131/matrix_bugfix_ST4wcf.zip)

**Pull request merged**
