### PR TITLE
Fix cross product comparison for corners when the first is zero

### LINKED ISSUE #431: ww3_prnc grid point not found
**Describe the bug**
When reading a netcdf input field with ww3_prnc, it is possible to obtain error messages of the type:

GRID POINT  [...] NOT COVERED BY INPUT GRID

when actually the source grid point lies inside the model grid. This in part happens due to the bug fixed in issue #314, as the fix was done only for rotated pole grids. Another issue is that, in order to decide if there is a grid point match, the cross product of values at the corner points need to have the same sign. This is tested by comparing the cross product of the first corner with the same values of the other corners, but this is problematic when the first cross product is zero, which happens when the longitude or latitude of the corner in the source grid matches a destination grid point. The proposed solution is looping through all cross products until one different than zero is found, and use this value to compare with the rest of the cross products.

**To Reproduce**
This bug produces a segmentation fault in the current develop branch when running the PR3_UQ_RHO test of ww3_tp2.15 using the intel compiler, caused by an air density value set to zero that is used in a division. See issue #419 for mor details.

**Expected behavior**
The ww3_prnc program will produce an error indicating that some grid points are not covered by the input grid, which in the case of reading a density field will cause a segmentation fault.

**Screenshots**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ukmo-juan-castillo**
# Pull Request Summary
This branch fixes one bug in ww3_prnc that happens when the cross product of the first corner of the input grid is zero, which causes that some points from the input grid are not interpolated to the model grid.

## Description
This PR fixes the bug described above, by instead of comparing the cross product of the first corner of a grid point, comparing the first that is different to zero. This is necessary because the signs of the corner cross products are compared, and if the cross product is zero the sign is not well defined.

There will be change of answers in those configuration reading netcdf input fields in a grid containing points that match the destination grid.

### Issue(s) addressed
* Is there an issue associated with this development (bug fix, enhancement, new feature)?    
YES

- fixes #431 
- fixes noaa-emc/ww3/issues/431

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)?
YES
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number)
DONE
* Reviewers: @ukmo-ccbunney @JessicaMeixner-NOAA @aliabdolali 

### Testing
* How were these changes tested?
Regtests
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
YES
* If a new feature was added, was a new regression test added?
N/A
* Have regression tests been run?
YES
* Which compiler / HPC you used to run the regression tests in the PR? 
Intel compiler at the Met Office CrayXC40 supercomputer for test ww3_tp2.15. All regtests were also run using the GNU compiler, and the results are copied below. 
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):    
Please indicate the expected changes in the outputs ([excluding the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)).

[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/6801805/matrixCompSummary.txt)

Some changes in ww3_tp2.15 tests due to differences in regridding of some points from the input netcdf files to the model grid. It is possible that some tests still crash due to some missing information in the density.nc input file, as described in #419. Adding matrixDiff for the rest of the tests to demonstrate that these differences are as expected.

[matrixDiff.txt-mww3_test_03.txt](https://github.com/NOAA-EMC/WW3/files/6801923/matrixDiff.txt-mww3_test_03.txt)
[matrixDiff.txt-mww3_test_05.txt](https://github.com/NOAA-EMC/WW3/files/6801924/matrixDiff.txt-mww3_test_05.txt)
[matrixDiff.txt-ww3_tp2.17.txt](https://github.com/NOAA-EMC/WW3/files/6801925/matrixDiff.txt-ww3_tp2.17.txt)

### CODE REVIEW

**Review by ukmo-ccbunney — APPROVED** [review]
Changes look sensible to me. Thanks Juan.

**Comment by aliabdolali** [comment]
@ukmo-juan-castillo could you merge noaa/develop and modify model/bin/ww3_from_ftp.sh (7.12.4 to 7.12.5)?

**Comment by aliabdolali** [comment]
I ran regtests with known non-b4b cases:

```
mww3_test_03/./work_PR2_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (7 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (10 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ)

```

I know the ww3_tp2.15 should change, could you confirm @ukmo-juan-castillo ?

```
ww3_tp2.15/./work_PR3_UQ_MPI                     (38 files differ)
ww3_tp2.15/./work_PR3_UQ_RHO_MPI                     (8 files differ)
ww3_tp2.15/./work_5km                     (7 files differ)
ww3_tp2.15/./work_PR3_UQ_RHO                     (13 files differ)
ww3_tp2.15/./work_PR3_UQ                     (6 files differ)
ww3_tp2.15/./work_MPI_5km                     (4 files differ)
```
[DIFFF.zip](https://github.com/NOAA-EMC/WW3/files/6823700/DIFFF.zip)

**Comment by ukmo-juan-castillo** [comment]
Yes, these are exactly the changes I would expect, and also matches the number of points I fixed in the density.nc file and the points that the bug fixes based on the grid point warnings in the output.

**Review by aliabdolali — APPROVED** [review]

**Pull request merged**
