### PR TITLE
fix unassociated pointer

### LINKED ISSUE #1000: unassociated pointer when compiling with GNU in debug mode with domain decomposition
**Describe the bug**

When testing the unstructured mesh feature branch for UFS Issue # [1556](https://github.com/ufs-community/ufs-weather-model/issues/1556), compiling in GNU + DEBUG + PDLIB segfaults on an unassociated pointer in ``w3iorsmd.F90``.

**To Reproduce**

**Expected behavior**

A check should be made that the pointer ``irqrs`` is associated before use.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# Pull Request Summary
 

Check if pointer is associated before use. 

### Issue(s) addressed

- fixes #1000 

### Commit Message

Check if irqrs is associated before use in w3iorsmd.F90

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
Thank you catching this @DeniseWorthen!!  I'll start the regtests

**Review by MatthewMasarik-NOAA — APPROVED** [review]
**Code review**  Pass

**Regtests**  Pass
Only the known non-b4b's for non-identicals.
```
**********************************************************************                            
********************* non-identical cases ****************************                            
**********************************************************************                            
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)                            
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)                             
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)                          
mww3_test_03/./work_PR1_MPI_d2                     (12 files differ)                              
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (14 files differ)                        
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)                         
mww3_test_03/./work_PR3_UNO_MPI_d2                     (10 files differ)                          
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)                           
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)                             
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)                          
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)                           
ww3_ta1/./work_UPD0F_U                     (0 files differ)                                       
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)                                   
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)                                   
ww3_ufs1.3/./work_a                     (3 files differ)                                          
                                                                                                  
**********************************************************************                            
************************ identical cases *****************************                            
**********************************************************************
```

[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/11323590/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/11323591/matrixDiff.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/11323592/matrixCompFull.txt)

Approved.

**Comment by MatthewMasarik-NOAA** [comment]
Thanks for your continued great work @DeniseWorthen.

**Comment by MatthewMasarik-NOAA** [comment]
@DeniseWorthen I wanted to check with you regarding getting this into dev/ufs-weather-model.  We can get a PR going quickly for dev/ufs-weather-model if desired.  Please let us know

**Comment by aronroland** [comment]
@DeniseWorthen this is a great catch, can u provide some details on how u did catch that one? Did it just pop up in this flags and constellation or what was your strategy?

**Comment by DeniseWorthen** [comment]
@aronroland We have regression tests for UFS in debug mode for both Intel and GNU (GNU is only on two of our platforms though). Our experience is that GNU will often catch errors that Intel does not, which is one of the primary reasons we test w/ GNU. This was simply the case of compiling with our debug GNU flags and getting a run-time error about an unassociated pointer.

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA Regarding the update to dev/ufs-weather-model, I checked during the morning CM tagup. There are no upcoming PRs that will not also change baselines through next week. I can commit the fix though when I open the PR for the unstructured mesh, though I realize that is not the preferred thing.

**Comment by aronroland** [comment]
@DeniseWorthen , well yes this is the right way to proceed on our end thomas and mathieu r working a lot with gnu. I am doing intel as this goes mostly into production and so it slipped, but i will need to double check with GNU. We should design a standard procedure using both compilers with dedicated flags in terms of future pull requests.

**Comment by aliabdolali** [comment]
WW3 code management at my time was solely with intel as some of the standalone tests failed with gnu for the sake of libraries on the RDHPC. Ifremer used to test everything with GNU, so we usually got feedback from them on GNU. It might be the time to think about multiple platforms and multiple compilers, ...
As we move towards more ONR tests in our development, we need to consider it. Thanks @aronroland and @DeniseWorthen for bringing it up. FYI: @thesser1

**Comment by aronroland** [comment]
@aliabdolali yeah ... we will standardise...we must ...

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA Regarding the update to dev/ufs-weather-model, I checked during the morning CM tagup. There are no upcoming PRs that will not also change baselines through next week. I can commit the fix though when I open the PR for the unstructured mesh, though I realize that is not the preferred thing.

@DeniseWorthen Yes, to stick to our procedure's I'll start on a PR to dev/ufs-weather-model.

**Comment by DeniseWorthen** [comment]
For UFS, GNU debug compile produces these flags for WW3 code:
 
```
-g -O0 -fno-unsafe-math-optimizations -frounding-math -fsignaling-nans -ffpe-trap=invalid,zero,overflow -fbounds-check -Jmod -g -fno-second-underscore -ffree-line-length-none -Wall -fcheck=all -ffpe-trap=invalid,zero,overflow -frecursive -fbacktrace -c
```

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA Will you or Jessica be making a PR to update dev/ufs-weather-model in UFS?

**Comment by JessicaMeixner-NOAA** [comment]
@MatthewMasarik-NOAA will be making this PR to update dev/ufs-weather-model in UFS.

**Comment by MatthewMasarik-NOAA** [comment]
Hi @DeniseWorthen, I've got a PR in progress.  It will be posted shortly this afternoon.

**Pull request merged**
