### PR TITLE
Develop including FB_pdlib_changes from Mathieu

### PR DESCRIPTION
**Pull request by thesser1**
Reg tests have been completed. I have attached the resulting files.  
[FB_pdlib_changes.zip](https://github.com/NOAA-EMC/WW3/files/3516018/FB_pdlib_changes.zip)

"This PR yields smaller memory usage for the PDLIB and is an unambiguous win.
Let me know if there are any problem.
Mathieu"

### CODE REVIEW

**Comment by ajhenrique** [comment]
@JessicaMeixner-NOAA and @mickaelaccensi please review this pull request. Thanks for your help!

**Comment by mickaelaccensi** [comment]
sounds ok for me since the regtests are correctly passed

**Comment by JessicaMeixner-NOAA** [comment]
Based on comparing with https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results 
The tests mww3_test_04/./work_PR3_UQ_MPI_NC_b_c  has files that are different but not on the list of expected differences (likely this is a new test and the netcdf files are not being compared properly by the script from what it maybe looks like?)  Also mww3_test_03/./work_PR2_UQ_MPI_d2 test has double the expected number of different files.   There were lots of tests with the a file gmon.out that is different?  What is this file? 

The changes themselves are in PDLIB which I don't know well enough to judge if the code is good/bad.  The PDLIB regression tests passed with the exception of the gmon.out file, so depending on what that file is I'm assuming everything is okay.

**Comment by mickaelaccensi** [comment]
Hi Jessica,
gmon.out is a profiling file which can be usefull to track where the run took the most part of its time. This file should be excluded from the regtest comparison.

**Comment by mickaelaccensi** [comment]
It's not part of PDLIB, it's based on the compilation options for profiling "-p"

**Comment by thesser1** [comment]
Thanks.  I will look into it.
Ty

**Comment by JessicaMeixner-NOAA** [comment]
Yes - The gmon.out is not pdlib related, but the updates to the actual code are pdlib related.

**Comment by ajhenrique** [comment]
@thesser1 @aliabdolali please address Issue #87 (add files gmon and time_count.txt in files to be excluded from matrix_comp comparisons in parameter skipfiles L162).

**Comment by ajhenrique** [comment]
@thesser1 @aliabdolali have you made progress on ironing out the pending issues to get this PR merged to our develop branch? Thanks.

**Comment by ajhenrique** [comment]
@JessicaMeixner-NOAA has provided a fix for issue #87 at 
[6c8c0f0](https://github.com/JessicaMeixner-NOAA/WW3/commit/6c8c0f01b7360ef98e051707610118a207a9c2ef)

**Comment by thesser1** [comment]
I reran the matrix with the rollback develop on the erdc repo since I had already merge the FB_pdlib branch in the erdc develop branch.  The test returned some new differences.  I am now running the matrix on the EMC develop branch to make sure I understand what is going on.
[FB_pdlib_changes_v2.zip](https://github.com/NOAA-EMC/WW3/files/3647355/FB_pdlib_changes_v2.zip)

**Comment by aliabdolali** [comment]
@thesser1 @ajhenrique 
Hi Henrique, 
I checked the report, looks good to me, I can merge it or you do it.
Regards
AA

**Comment by ajhenrique** [comment]
> @thesser1 @ajhenrique
> Hi Henrique,
> I checked the report, looks good to me, I can merge it or you do it.
> Regards
> AA

Hi @aliabdolali @thesser1 I was not able to open the report, I would like to have a look at it as well. @thesser1 can you explain what new differences were there, @aliabdolali why do you think they are not relevant. Thanks!

**Comment by ajhenrique** [comment]
@thesser1 @aliabdolali @mickaelaccensi  @JessicaMeixner-NOAA I ran the regtest matrix on Hera, our new R&D machine for both an update for porting the package to the new resource and for the ERDC PR. The differences reporduced those pointed our by Jessica in the thread above. I will assume all is OK, however need that @mickaelaccensi approves this PR as a reviewer to complete the process, then I'll merge this PR to the NOAA-EMC/WW3 develop.

**Pull request merged**
