### PR TITLE
Issue #998 - coupling update error fix

### LINKED ISSUE #998: Coupling update error
**Describe the bug**
In certain coupled configurations, the piece of code testing the coupling frequency to check if 'receive' coupling exchanges need to take place fail, resulting in an infinite loop causing the integration between time zero and the first time step to repeat indefinitely.

**To Reproduce**
This bug was discovered using the amm15 ocean/wave coupled configuration at the Met Office, when coupling currents every 10 minutes (equal to the wave's time step), and reading winds and air density as driving data every hour on the half an hour. This configuration resulted in an infinite loop in ww3_shel.ftn (the loop reading driving data, calling the w3wave subroutine, and advancing time), as after the first time step the currents were supposed to be received via coupling and the time advanced, but this never happened. The cause is that the check  testing if a coupling exchange needs to take place, the lines:

https://github.com/NOAA-EMC/WW3/blob/97b9e8bf00fc2ec83a4837fce299ee10aa539040/model/src/ww3_shel.F90#L2065-L2066

do not provide the expected result, probably due to rounding errors (or a compiler bug? I am using the Cray compiler version 8.7.7 on the Met Office Cray XC40 machine). Some debug lines show the result of the calculations:

TIME00 = 20141207,  0
TIME = 20141207,  1000
DTOUT(7) = 600.
DSEC21(TIME00,TIME) = 600.
MOD(DSEC21(TIME00,TIME), DTOUT(7)) = 600.
NINT(MOD(DSEC21(TIME00,TIME), DTOUT(7))) = 600

The result of the last calculation should be zero, so in this loop cycle currents coupling should be taking place. As this does not happen, the time within the loop is not updated and therefore we have the infinite loop.

The error was fixed when the testing condition was changed from:

NINT(MOD(DSEC21(TIME00,TIME), DTOUT(7))) .EQ. 0

to:

MOD(NINT(DSEC21(TIME00,TIME)), NINT(DTOUT(7))) .EQ. 0

i.e. applying the MOD intrinsic function to integer rather than real numbers. This fix was successfully tested in different coupled configurations with different coupling frequencies.

Furthermore, issue #816 was revisited and it was checked that this fix also fixes that issue, meaning that the changes in issue #816 can be reverted, resulting in a simpler code.

**Expected behavior**
An infinite loop after the first model time step occurs in some coupled configurations.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by ukmo-juan-castillo**
# Pull Request Summary
In certain coupled configurations, the piece of code testing the coupling frequency to check if 'receive' coupling exchanges need to take place fail, resulting in an infinite loop causing the integration between time zero and the first time step to repeat indefinitely.

## Description
The intention of this PR is to fix issue #998, which describes in detail what the problem and the proposed solution are.

* Suggested reviewer: ukmo-ccbunney, mickaelaccensi
* Labels that should be added:  _bug_
* Are answer changes expected from this PR? No, just fixing infinite loop and deadlocks in certain coupled configurations

### Issue(s) addressed
- fixes #998 
- Also fixing #816 in a simpler way than how it was originally fixed

### Commit Message
In certain coupled configurations, the piece of code testing the coupling frequency to check if 'receive' coupling exchanges need to take place fail, resulting in an infinite loop causing the integration between time zero and the first time step to repeat indefinitely. This check needs to be rewritten, which fixes also issue #816 in a simpler way.

### Check list  

- [Yes] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [Yes] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [N/A] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [N/A] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
@ukmo-juan-castillo, thank you for this fix for coupling exchange check.  I'll start the regression tests.

**Comment by MatthewMasarik-NOAA** [comment]
@ukmo-juan-castillo, could you please sync your branch to bring it current with develop?

**Comment by MatthewMasarik-NOAA** [comment]
Thank you for syncing @ukmo-juan-castillo.

**Review by MatthewMasarik-NOAA — COMMENTED** [review]
**Code review** Pass

**Regtests**  Pass

The only non-identicals are the known non-b4b's.
```
**********************************************************************                            
********************* non-identical cases ****************************                            
**********************************************************************                            
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)                                
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)                            
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)                            
mww3_test_03/./work_PR2_UNO_MPI_d2                     (18 files differ)                          
mww3_test_03/./work_PR1_MPI_d2                     (10 files differ)                              
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (17 files differ)                        
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)                         
mww3_test_03/./work_PR3_UNO_MPI_d2                     (20 files differ)                          
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)                           
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)                             
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)                          
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)                           
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)                                   
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)                                   
ww3_ufs1.3/./work_a                     (3 files differ)                                          
                                                                                                  
**********************************************************************                            
************************ identical cases *****************************                            
**********************************************************************
```
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/11332932/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/11332930/matrixCompFull.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/11332931/matrixDiff.txt)

This is OK to proceed from the EMC side.  I'll give some time today for @ukmo-ccbunney @mickaelaccensi to comment since it deals with OASIS coupling.

**Review by ukmo-ccbunney — APPROVED** [review]
Changes look good to me @ukmo-juan-castillo. It's great that this has also simplified and cleaned up the code of the bugfix from the other issue too - double win!

Results of the the OASIS coupling regtests are all looking fine.

**Comment by MatthewMasarik-NOAA** [comment]
> Changes look good to me @ukmo-juan-castillo. It's great that this has also simplified and cleaned up the code of the bugfix from the other issue too - double win!
> 
> Results of the the OASIS coupling regtests are all looking fine.

Great!  Thank you for your review @ukmo-ccbunney.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
This has previously been reviewed (https://github.com/NOAA-EMC/WW3/pull/999#pullrequestreview-1401931694), and passed both the code review and regtests.  @ukmo-ccbunney has given the OK with respect to the OASIS coupling (https://github.com/NOAA-EMC/WW3/pull/999#pullrequestreview-1405934408).

Approved.

**Comment by MatthewMasarik-NOAA** [comment]
@ukmo-juan-castillo, Thank you for providing this fix that addresses #998, as well as #816!  Excellent work!

**Pull request merged**
