### PR TITLE
Add code comments about WRST switch 

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
Adding comments in the code for the WRST switch in both wmesmf and w3iors 

Also changed the type of a few files 

This should hopefully close Issue #110

### CODE REVIEW

**Comment by ajhenrique** [comment]
@flampouris and @ukmo-ccbunney would you be so kind to review this PR? Thanks!

**Review by ukmo-ccbunney — APPROVED** [review]
These look like very sensible comments to me!

**Review by flampouris — CHANGES_REQUESTED** [review]
Very useful. One small comment:

@JessicaMeixner-NOAA Could you add the WRST also at the section 5.9 of the manual?

**Comment by ajhenrique** [comment]
> Very useful. One small comment:
> 
> @JessicaMeixner-NOAA Could you add the WRST also at the section 5.9 of the manual?

@JessicaMeixner-NOAA would you like to add the changes to the manual as part of this PR? Otherwise, I will start a documentation branch to provide manual updates on other recent changes that you can use for expediting this PR.

**Comment by flampouris** [comment]
> @JessicaMeixner-NOAA would you like to add the changes to the manual as part of this PR? Otherwise, I will start a documentation branch to provide manual updates on other recent changes that you can use for expediting this PR.

This kind of question does not make sense, as long code review is required for merging updates to the develop branch, and it could be considered disrespectful towards the reviewers' time.

This PR is needed because of an earlier expedited PR, so despite the reviewer's request, by expediting the current PR, a 3rd PR will be required to address issues of the original PR.

**Comment by ajhenrique** [comment]
> This kind of question does not make sense, as long code review is required for merging updates to the develop branch, and it could be considered disrespectful towards the reviewers' time.
> 
> This PR is needed because of an earlier expedited PR, so despite the reviewer's request, by expediting the current PR, a 3rd PR will be required to address issues of the original PR.

@flampouris thank you for your reply. There was no intent to be disrespectful to your time and suggestions.  The question was perhaps a bit naive as it intended to clarify if you would be willing to accept that your suggestions be implemented as part of changes that would be performed later. From the tone of your response, it is clear this is not the case.

**Comment by JessicaMeixner-NOAA** [comment]
@flampouris That's a great idea! I already added it to the list of switches in section 5.9.  I also previously (at time of the original commit) made an update mentioning this feature in the appendix about NUOPC/ESMF appendix.  To be honest, I'm not sure what further details I should add or that were requested in issue #110 since the manual updates (albeit brief) were there already.  I think the comments in the code are a good addition, but I'd appreciate having feedback on what exactly would be useful information to add in the manual or the code so that this feature is fully documented and can be easily used by others.  

@ajhenrique  I'd prefer to just complete this task as part of this PR.

**Comment by JessicaMeixner-NOAA** [comment]
@flampouris I'm trying to revisit this PR to get it in.  The switch is listed in the manual here: https://github.com/NOAA-EMC/WW3/blob/develop/manual/impl/switch.tex#L375  any other changes?

**Comment by flampouris** [comment]
It does not ring any bell, but the documentation looks great.

**Review by flampouris — APPROVED** [review]

**Review by aliabdolali — APPROVED** [review]
It looks ok to me.

**Pull request merged**
