### PR TITLE
clean up and add ST4 variables

### PR DESCRIPTION
**Pull request by mickaelaccensi**
# Pull Request Summary
clean up and add ST4 variables

## Description
clean up and add ST4 variables

### Commit Message
clean up and add ST4 variables

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
@mickaelaccensi, I see you requested a review, but no test information?

**Comment by mickaelaccensi** [comment]
it is just a file changed so no impact on the code

**Comment by MatthewMasarik-NOAA** [comment]
Okay, good deal.  Thanks.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
**Code review**
Pass

- documentation added
- formatting

**Testing**
NA

- Changes only to documentation namelist file


Approved.

**Comment by MatthewMasarik-NOAA** [comment]
@mickaelaccensi, much thanks for this ST4 documentation!

**Pull request merged**
