### PR TITLE
Hybrid OMP/MPI updates [ukmo-develop] 

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
This PR covers two feature branch PRs that have been merged into the [UKMO develop](https://github.com/ukmo-waves/WW3/tree/develop) branch:

- https://github.com/ukmo-waves/WW3/pull/3 : Hybrid features update for SMC module
- https://github.com/ukmo-waves/WW3/pull/4 : MPI/OMP hybrid thread safe MPI initialization

See individual PRs for full matrix comparison results.

### CODE REVIEW

**Comment by aliabdolali** [comment]
Hi @ukmo-ccbunney 
Here is the matrix.comp outputs with the following non-identical tests:
mww3_test_03/./work_PR2_UQ_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (7 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (10 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (directory not found)
ww3_tp2.10/./work_MPI                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (directory not found)
ww3_tp2.16/./work_MPI                     (6 files differ)

I see most of them marginal, do we expect these?
[Regtest.zip](https://github.com/NOAA-EMC/WW3/files/4455986/Regtest.zip)
 AA

**Comment by ukmo-ccbunney** [comment]
Hi @aliabdolali 
> I see most of them marginal, do we expect these?

Yes - the `mww3_test_03` always has b4b issues.

The `ww3_tp2.10` and `ww3_tp2.16` are the two SMC grid tests. There are expected small differences in the output fields due to re-ordering of some terms in the SMC code to allow ATOMIC access OpenMP directives.

**Review by mickaelaccensi — COMMENTED** [review]
sounds good but I don't catch why the operations enabled by the B4B switch are not done by default. Is there a reason for that ? computation time ?

**Comment by ukmo-ccbunney** [comment]
> 
> 
> sounds good but I don't catch why the operations enabled by the B4B switch are not done by default. Is there a reason for that ? computation time ?

The B4B flag probably imposes an artificial precision limit on the energy transfer between cells due to the scaling and conversion to an integer value. Whilst the differences between it being enabled and disabled are probably negligible in the output fields, I preferred not to impose this on the end user.

**Comment by ukmo-ccbunney** [comment]
@aliabdolali I don't think that this PR needs to be reviewed - it encompasses the two PRs in the UKMO trusted repo that have already been fully reviewed (following the procedure in the "Review framework for PRs" document)

@ajhenrique  - can you confirm my understanding is correct in this case?

**Review by mickaelaccensi — APPROVED** [review]

**Review by ajhenrique — APPROVED** [review]
Looks good, as previous reviews within the UKMO repo indicated. Let's discuss the procedure for additional reviews in these cases which have been reviewed within trusted repos in our next meeting.

**Pull request merged**
