### PR TITLE
fix ust,ustdir,asf and add ussp to output_exchanges

### LINKED ISSUE #941: Add ussp to history output for unstructured mesh with domain decomposition
**Is your feature request related to a problem? Please describe.**
The stokes drift fields are not available as output of mean wave fields when running with the unstructured mesh and domain decomposition. These fields are needed for comparison purposes during development of the coupled application for UFS ([Issue 1556](https://github.com/ufs-community/ufs-weather-model/issues/1556)).

**Describe the solution you'd like**
Add USSP as available output when running with domain decomposition.

### LINKED ISSUE #942: output history fields of ust,ustdir and asf are incorrect when running with unstructured mesh with domain decomposition
**Describe the bug**

UST, USTDIR and ASF are dimensioned as NSEALM*NAPROC. When added to the Arrexch in ``do_output_exchanges``, the index ``jsea`` is used. It should be ``isea``. 

**To Reproduce**

The following figures demonstrates the issue in three test cases using the mesh-based cap. This is work under development for use in UFS (see issue [#1556](https://github.com/ufs-community/ufs-weather-model/issues/1556)). It uses a branch of dev/ufs-weather-model and couples ATM-WW3. All three cases utilized run-time generation of netCDF history files.

Also, all cases were run with the restart frequency set > run length to avoid the issue reported in [#1556](https://github.com/ufs-community/ufs-weather-model/issues/1556) with the corruption of fields at the restart frequency.

For reference, the domain decomposition for the domain on 10PEs is

emesh decomp 10pe

The three test cases in the figures below are 

- unstructured mesh with domain decomposition (top)
- identical unstructured mesh with card-deck (middle). This case does not use ``do_output_exchanges``.
- a structured grid over the same domain (bottom). This case does not use ``do_output_exchanges``.

The ``Z0`` exported to the atmosphere (*1e3) in the three cases is

nofix wavImp_Sw_z0_2021-03-22-28800

For the domain decomposition case, the ``Z0`` field is clearly corrupted on ``NAPROC-1`` (in this case PE=9)

This is because of corrupted ``UST,USTDIR`` fields after the ``output_exchange`` step.  This shows the ``USTX`` field for the three cases using the current code

nofix USTX_2021-03-22-28800

Changing the index of UST,USTDIR and ASF to ``isea`` when filling Arrexch produces the following:

fix USTX_2021-03-22-28800

And the ``Z0`` field exported the the ATM is no longer corrupted

fix wavImp_Sw_z0_2021-03-22-28800

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# Pull Request Summary

This work is part of UFS [1556](https://github.com/ufs-community/ufs-weather-model/issues/1556)

Fixes output of ust,ustdir and asf when using domain decomposition. 
Adds the ability to output USSP when running with domain decomposition.

### Issue(s) addressed

- fixes #942 
- fixes #941 

### Commit Message

Fixes output of ust,ustdir and asf  and adds USSP when running with domain decomposition.

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
The regression tests had no only expected differences:  

```
 **********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_ta1/./work_UPD0F_U                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.17/./work_ma                     (1 files differ)
ww3_tp2.17/./work_a                     (1 files differ)
ww3_tp2.17/./work_mc1                     (1 files differ)
ww3_tp2.17/./work_mb                     (1 files differ)
ww3_tp2.17/./work_mc                     (1 files differ)
ww3_tp2.17/./work_ma1                     (1 files differ)
ww3_tp2.17/./work_c                     (1 files differ)
ww3_tp2.17/./work_b                     (1 files differ)
ww3_tp2.6/./work_ST0                     (1 files differ)
ww3_tp2.6/./work_ST4                     (1 files differ)
ww3_tp2.6/./work_pdlib                     (4 files differ)
ww3_ts4/./work_ug_MPI                     (1 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```


How were these changes tested? Tested by @DeniseWorthen and results in issues.  matrix of regtests run on hera 
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) No - I will take care of adding a regression test for this after this and pr 888 have been merged, we will make sure to add these variables to a regression test output. 
Have the matrix regression tests been run (if yes, please note HPC and compiler)? Yes - Hera Intel 
Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
No expected changes. See above
Please provide the summary output of matrix.comp (matrix.Diff.txt, matrixCompFull.txt and matrixCompSummary.txt):

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/10957663/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/10957664/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/10957665/matrixDiff.txt)

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Thank you @DeniseWorthen for this fix!  

I ran all the WW3 standalone tests and will add a regression test to add this to the output in a seperate PR.  

I would like to give @aronroland an opportunity to review this as well as he knows this code portion the best.  But we can get this merged ASAP after that.  I think he's already looked at it, so hopefully it will be a quick review process.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
Thank you for catching this @DeniseWorthen!!

**Comment by DeniseWorthen** [comment]
I anticipate two more bug fixes for unstructured. One to resolve the restart-frequency corruption (documented in UFS issue [1556](https://github.com/ufs-community/ufs-weather-model/issues/1556)) and one to fix the hard-wiring in w3initmd https://github.com/NOAA-EMC/WW3/blob/ea0de58feec301f319cf87aa4ececbc010b00238/model/src/w3initmd.F90#L2192-L2193 Those may or may not be ready this week.

**Comment by JessicaMeixner-NOAA** [comment]
@aronroland if you do not object I'd like to merge this today.  If you need more time for a review please let us know, otherwise I'll plan to merge this around 5pm ET time.

**Review by aronroland — APPROVED** [review]
@DeniseWorthen , @JessicaMeixner-NOAA i  have checked everything and from my point of view this can go in.

**Comment by MatthewMasarik-NOAA** [comment]
@aronroland thanks for your approval.  @JessicaMeixner-NOAA and myself have already approved this as well.

**Comment by MatthewMasarik-NOAA** [comment]
Thanks again @DeniseWorthen for catching this issue and supplying the fix!

**Pull request merged**
