### PR TITLE
Make NC4 switch default 

### LINKED ISSUE #359: Make NC4 the default switch
After support for NetCDF 3 is removed (Gith Hub issue), the NC4 switch could then be made the default option and the switch itself would no longer be necessary. 

This work is planned for the end of May 2021 and would be completed after the support for NetCDF 3 is removed (Issue #358).

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
Make the NC4 switch "default" by removing the "!/NC4"  from code and remove NC4 from switch files.   

## Description
After NetCDF v3 support is removed, the NC4 switch is no longer necessary to have for compilation of the code.  NCTYPE=3 or 4 is still an option.  Anything previously only behind the NC4 switch is now behind a "if NCTYPE=4" statement. 

PR #410 which removes NetCDFv3 support must be merged first, as this PR builds on it

Before merging, all switch files will need the "NC4" switch removed.  

### Issue(s) addressed
* fixes #359 

### Check list  
* Reviewers: @mickaelaccensi @aliabdolali 

### Testing
* How were these changes tested? matrix or regtests
* Are the changes covered by regression tests?  yes, there are tests with both NCTYPE=3 and NCTYPE=4 
* If a new feature was added, was a new regression test added? no
* Have regression tests been run? yes, but they'll need to be run again 
* Which compiler / HPC you used to run the regression tests in the PR? 
* Please provide the summary output of matrix.comp (_matrix.Diff.out_, _matrixCompFull.out_ and _matrixCompSummary.out_):    
I'll wait to attach the full summary until after the NC4 switches have been removed.  They are not being removed now to avoid merge conflicts later. The regtests were run after removing the NC4 switch.

### CODE REVIEW

**Review by mickaelaccensi — APPROVED** [review]
it's ok for me if it pass goes fine for the regtests

**Review by aliabdolali — COMMENTED** [review]
Hi @JessicaMeixner-NOAA 
could you take a look at the followings and see if they need correction:
```
model/inp/ww3_systrk.inp:15
manual/impl/switch.tex:358
```

**Comment by aliabdolali** [comment]
The matrix went fine as expected with known non-b4b 
```
mww3_test_03
mww3_test_07
ww3_tp2.10
ww3_tp2.15
```
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/6683603/matrixDiff.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/6683604/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/6683605/matrixCompFull.txt)

Considering Mickael's approval, once you reply to my comments, then we can merge it.

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali the NC4 switches need to be removed (see note at the end of PR description with the testing info) and then regtests should be re-run.  That is why this PR is marked as a draft.  I will merge with develop, remove the switches, re-run regression tests as well as address your comments today.

**Comment by JessicaMeixner-NOAA** [comment]
> Hi @JessicaMeixner-NOAA
> could you take a look at the followings and see if they need correction:
> 
> ```
> model/inp/ww3_systrk.inp:15
> manual/impl/switch.tex:358
> ```

Agreed, both of these needed to be fixed.  Thanks for catching this!

**Comment by JessicaMeixner-NOAA** [comment]
This PR is no longer a draft, it has been updated to the top of develop, the NC4 switch has been removed from switch files and my final testing shows only the expected differences: 
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (7 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (3 files differ)

@aliabdolali This PR is now ready for your final review and testing.

**Comment by JessicaMeixner-NOAA** [comment]
The PR title and description is updated to hopefully make it clear that support for NC4 is not removed, but that since NetCDF v3 support is removed that the NC4 switch is no longer needed. 

Suggested commit message (assuming it conveys the above message): Make the NC4 switch "default" by removing the "!/NC4"  from code and remove NC4 from switch files.

**Comment by JessicaMeixner-NOAA** [comment]
ufs-weather-model regression test w/hera.intel passed.

**Comment by JessicaMeixner-NOAA** [comment]
Okay, the first time I ran matrix.comp ncdump was not running so I think the list of different retests were too short, so I look forward to @aliabdolali test and confirmation.  However the differences are then in the netcdf output files because the list of switches are different: 
      ***
         /scratch2/NCEPDEV/climate/Jessica.Meixner/PR_WW3/PR411/regtests/output/ww3_tp2.14/work_OASICM/ww3.201109.nc_diff.txt
     ***
     230c230
     <               :WAVEWATCH_III_switches = "F90 NOGRB NC4 TRKNC SHRD PR3 UQ FLX0 LN1 ST4 STAB0 NL1 BT4 DB1 MLIM         TR0 BS0 IC2 IS2 REF1 XX0 WNT0 WNX1 RWND CRT1 CRX1 COU OASIS OASICM O0 O1 O2 O2a O2b O2c O3 O4 O5 O6 O7" ;
     ---
     >               :WAVEWATCH_III_switches = "F90 NOGRB TRKNC SHRD PR3 UQ FLX0 LN1 ST4 STAB0 NL1 BT4 DB1 MLIM TR0 BS0 IC2 IS2 REF1 XX0 WNT0 WNX1 RWND CRT1 CRX1 COU OASIS OASICM O0 O1 O2 O2a O2b O2c O3 O4 O5 O6 O7" ;

**Review by aliabdolali — COMMENTED** [review]
Do we need?
 model/bin/w3_make#L343: `if [ ! -n "`grep NC4 $switch_file`" ]`
model/bin/w3_make#L345:         ` echo "WARNING: NC4 is set in WWATCH3_NETCDF but not in the switch file"; echo ' '`

and NC4 in the following?
model/bin/switch_UKMO_reg
model/bin/switch_UKMO_gbl
model/bin/switch_UKMO_uk
regtests/mww3_test_09/input/switch_MPI
regtests/ww3_tp2.16/input/switch
regtests/ww3_tp2.16/input/switch_MPI_OMPH
regtests/ww3_tp2.16/input/switch_MPI
regtests/ww3_tp2.6/input/switch_PDLIB
regtests/ww3_tpt1.1/input/switch
regtests/ww3_tpt1.1/input/switch_MPI

**Comment by aliabdolali** [comment]
The regtest all done successfully with expected non-b4b cases:
```
mww3_test_03/./work_PR2_UQ_MPI_d2                     (7 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (5 files differ)

```

and expected ones due to the changes in the switch and netcdf outputs:
```
ww3_tic1.4/./work_IC2IS2_IC2d                     (2 files differ)
ww3_tic1.4/./work_IC2IS2_IC2b                     (2 files differ)
ww3_tnc1/./work                     (14 files differ)
ww3_tp2.14/./work_OASACM5                     (1 files differ)
ww3_tp2.14/./work_OASACM6                     (1 files differ)
ww3_tp2.14/./work_OASACM4                     (1 files differ)
ww3_tp2.14/./work_OASACM3                     (1 files differ)
ww3_tp2.14/./work_OASACM                     (1 files differ)
ww3_tp2.14/./work_OASICM                     (1 files differ)
ww3_tp2.14/./work_OASOCM                     (1 files differ)
ww3_tp2.14/./work_OASACM2                     (1 files differ)
ww3_tp2.15/./work_5km                     (1 files differ)
ww3_tp2.15/./work_PR3_UQ_RHO                     (1 files differ)
ww3_tp2.15/./work_PR3_UQ                     (1 files differ)
ww3_tp2.17/./work_a                     (1 files differ)
ww3_tp2.17/./work_mc                     (1 files differ)
ww3_tp2.17/./work_c                     (1 files differ)
ww3_tp2.17/./work_b                     (1 files differ)
ww3_tp2.17/./work_ma                     (1 files differ)
ww3_tp2.17/./work_mb                     (1 files differ)
ww3_tp2.18/./work_TIDE                     (1 files differ)
ww3_tp2.18/./work_TIDE_MPI                     (1 files differ)
ww3_ts1/./work_ST6                     (1 files differ)
ww3_ufs1.1/./work_a_nth                     (1 files differ)
ww3_ufs1.1/./work_a_npl                     (1 files differ)
ww3_ufs1.1/./work_a                     (1 files differ)
ww3_ufs1.1/./work_b                     (1 files differ)
ww3_ufs1.2/./work_a                     (4 files differ)
ww3_ufs1.2/./work_b                     (4 files differ)
```

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/6912742/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/6912743/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/6912744/matrixDiff.txt)

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali good catch! That is not needed and double checking the w3_make I found one other comment message that needed updated as well.  Those changes have been pushed.

**Review by aliabdolali — APPROVED** [review]
I ran the tests that had NC4 in the switch but now removed and they ran successfully.

**Pull request merged**
