### PR TITLE
optimize do loops

### LINKED ISSUE #978: loops in explict block are in wrong order
**Describe the bug**

This issue was found as a result of Issue #974 and is related to UFS Issue [1556](https://github.com/ufs-community/ufs-weather-model/issues/1556)

In SR ``PDLIB_EXPLICIT_BLOCK``, several do loops are nested inefficiently for fortran because they are not in column-major order. For example,

```
      DO ITH = 1, NTH
        ISP = ITH + (IK-1) * NTH
        DO IP = 1, NP
          VA(ISP,IP)  = U(ITH,IP) * CGSIG(IP) / CLATS(IPLG(IP))
        ENDDO
     ENDDO
```

Since the ``IP`` loop is over the number of resident points on this decomposition element, the impact is greatest for relatively large node density.

**To Reproduce**
Steps to reproduce the behavior. 

**Expected behavior**

The loops should be ordered so that the inner-most index varies the fastest.

```
      do ip = 1,np
        isp = 0
        do ith = 1,nth
          isp = ith + (ik-1)*nth
          va(isp,ip) = u(ith,ip) * cgsig(ip) / clats(iplg(ip))
        end do
      end do
```

**Screenshots**

**Additional context**

A test was carried out using the fully coupled test case for UFS. It used a 500K mesh on only 36 PEs, integrated for 24 hours with the existing code and one w/ modified loops. The answers were B4B. The wall clock times are as follows:

current code: ``The total amount of wall time                        = 2404.501605``
reordered loops: ``The total amount of wall time                        = 1955.846262``

The ESMF Profile gives the following values for the WAV RunPhase1 (min time, mean time, max time):

current code:      1746.3447    1056.5148   2326.2212
reordered loops: 1323.0430     640.5865  1878.7823

The wall clock time is reduced by ~20%, the mean WAV run phase time is reduced by ~39%. 

I would consider this a high node density test case. Cases w/ lower node density would probably not show as great an impact.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# Pull Request Summary
 

Reorders the loops in ``PDLIB_EXPLICIT_BLOCK`` for efficiency.

## Description

Reorders several loops across ``ip=1,npa`` or ``ip=1,np`` so that the inner most index varies the fastest. 
Note: this PR was built on top of the changes in PR #975 and so depends on that PR being merged first. 

### Issue(s) addressed

- fixes #978 

### Commit Message

Reorders some loops in PDLIB_EXPLICIT_BLOCK for efficiency.

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
More exciting work, thank you @DeniseWorthen.  The matrix.comp for #975 is running now so that PR should be ready for merging later this morning if no issues.  I'm looking forward to seeing the speed improvements from this PR!

**Comment by MatthewMasarik-NOAA** [comment]
@DeniseWorthen, the dependency #975 was just merged.  I'll start the regtests for this now.

**Comment by MatthewMasarik-NOAA** [comment]
@DeniseWorthen could you please update your branch?

**Review by aronroland — APPROVED** [review]
Hey Denise, 
missed that one, thanks for optimizing this part!
Cheers
Aron

**Comment by DeniseWorthen** [comment]
> More exciting work, thank you @DeniseWorthen. The matrix.comp for #975 is running now so that PR should be ready for merging later this morning if no issues. I'm looking forward to seeing the speed improvements from this PR!

I re-ran my tests using 4x as many tasks for the WAV model. The improvement is still there, but is reduced (as expected):

current code: ``The total amount of wall time                        =  870.122403``
reordered loops: ``The total amount of wall time                        =  830.824244``

The ESMF Profile gives the following values for the WAV RunPhase1 (min time, mean time, max time):

current code:     385.2281 187.5005 806.7036
reordered loops:  364.6094 170.1290 763.8478

So these are reductions of ~4.5% in wall clock, and ~10% in mean run phase time.

**Comment by MatthewMasarik-NOAA** [comment]
Thanks for the update @DeniseWorthen.  The testing will finish this morning and then complete the review this afternoon if there's no problems.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
**Code review** Pass

**Regtests** Pass
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/11214301/matrixCompFull.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/11214302/matrixDiff.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/11214303/matrixCompSummary.txt)
* Summary of non-identicals shows only the known non-b4b cases with unstructured mod_defs.
```
**********************************************************************           
********************* non-identical cases ****************************           
**********************************************************************           
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)               
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)          
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)           
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)            
mww3_test_03/./work_PR2_UNO_MPI_d2                     (15 files differ)         
mww3_test_03/./work_PR1_MPI_d2                     (14 files differ)             
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (17 files differ)       
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)        
mww3_test_03/./work_PR3_UNO_MPI_d2                     (10 files differ)         
mww3_test_03/./work_PR2_UQ_MPI_d2                     (14 files differ)          
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)            
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)         
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)          
ww3_ta1/./work_UPD0F_U                     (0 files differ)                      
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ)                  
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)                  
ww3_tp2.17/./work_ma                     (1 files differ)                        
ww3_tp2.17/./work_a                     (1 files differ)                         
ww3_tp2.17/./work_mc1                     (1 files differ)                       
ww3_tp2.17/./work_mb                     (1 files differ)                        
ww3_tp2.17/./work_mc                     (1 files differ)                        
ww3_tp2.17/./work_ma1                     (1 files differ)                       
ww3_tp2.17/./work_c                     (1 files differ)                         
ww3_tp2.17/./work_b                     (1 files differ)                         
ww3_tp2.19/./work_1B_a                     (1 files differ)                      
ww3_tp2.19/./work_1A_a                     (1 files differ)                      
ww3_tp2.19/./work_1C_a                     (1 files differ)                      
ww3_ufs1.3/./work_a                     (3 files differ)                         
                                                                                 
**********************************************************************           
************************ identical cases *****************************
```

**Comment by MatthewMasarik-NOAA** [comment]
Thanks again, @DeniseWorthen for this excellent catch.

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA Thanks. Could you or Jessica please create a PR to update the ufs-weather-model branch?

**Comment by JessicaMeixner-NOAA** [comment]
Yes, we will do that today or tomorrow at the latest.

**Pull request merged**
