### PR TITLE
Changes to fix issue #341

### LINKED ISSUE #341: Initialization of extra restart fields
**Describe the bug**
In a previous issue the possibility of writing extra fields in the restart file was added to the code. By default, when running a OASIS coupled configuration, the fields that are sent to other models is always written to the restart file.

The problem happens when no extra fields are requested and no coupling takes place, as in this case the flags indicating if extra restart is taking place is not explicitly initialized. It is assumed that these flags are implicitly set to .FALSE., but this is not always the case, causing that some of the oasis send variables may be initialized to zero, and generating non-reproducible results.

**To Reproduce**
This behaviour has been discovered after comparing the ww3_tp2.16/work_MPI_OMPH regtests of two branches, the WW3 develop and the fb_coupling fields. Although the results are the same, the out_pnt.ww3 file is different, containing values of 0.0 and 1000.0 (the expected value) for the variable ICEF, respectively.

**Expected behavior**
The flags indicating extra restart fields should be set to .FALSE. explicitly and modified only in the two cases described before: when oasis coupling takes place, or when the user specifies extra restart fields; in this way there will be no unexpected difference in the output fields and the results will always be reproducible.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by ukmo-juan-castillo**
# Pull Request Summary
Fixes to issue #341 

## Description
The bug is described in the issue description.
Initializes to .FALSE. the flags that indicate extra fields to be written to the restart file to avoid unexpected behaviour and allow reproducibility. Random changes to regtests may be observed, in particular to the out_pnt.ww3 or out_grd.ww3 files.

### Issue(s) addressed

- fixes #341 
- fixes noaa-emc/ww3/issues/341

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)?
YES
* Reviewers: @ukmo-ccbunney 

### Testing
* How were these changes tested?
The branches giving different results were tested with this change merged, and now they gave the same answers.
* Are the changes covered by regression tests?
Yes, although the bug occurrence is random - we discovered the bug in the test ww3_tp2.16/work_MPI_OMPH
* If a new feature was added, was a new regression test added?
No new feature added
* Have regression tests been run?
Yes
* Which compiler / HPC you used to run the regression tests in the PR? 
Met Office Cray XC40, GNU compiler
* Please provide the summary output of matrix.comp (_matrix.Diff.out_, _matrixCompFull.out_ and _matrixCompSummary.out_):    
Please indicate the expected changes in the outputs:
Possible changes to out_pnt.ww3 and out_grd.ww3, in fields that can be sent to other models via oasis coupling.

### CODE REVIEW

**Comment by ukmo-ccbunney** [comment]
Results of full regression tests matrix attached:
[matrix_full_fb_oasis_restart.zip](https://github.com/NOAA-EMC/WW3/files/6229259/matrix_full_fb_oasis_restart.zip)

Expected differences:
  - **ww3_tp2.14/*** : `output.ww3` file has extra line stating "no fields defined"
  - `ww3_tp2.16/work_MPI_OMPH` : value for ICEF now has a correct value set in the `out_pnt.ww3` binary file.

Existing known differences:
  - **mww3_test_03/*** : not b4b
  - **ww3_tp2.18/work_TIDE_MPI**  : random ordering of output to stdout.

**Review by ukmo-ccbunney — APPROVED** [review]

**Comment by aliabdolali** [comment]
Thanks @ukmo-juan-castillo 
@ukmo-ccbunney 
I am going to test this one while waiting for Ty for his PR.
The #285 requires some tests with our UFS weather application, so I need some extra time to investigate if #285 does not affect it.

**Comment by aliabdolali** [comment]
I checked the regtests and it came as expected. For the file changes, there is just one line of change and the other ones are exactly the same. Why did you do it @ukmo-juan-castillo 
For the future, could you make sure you have merged the latest NOAA/develop? I had to merge the upstream locally before running the test.
Here is the summary of matrix comp.
[MatrixCompNCEP.zip](https://github.com/NOAA-EMC/WW3/files/6238908/MatrixCompNCEP.zip)
Could you take a look and once we cleared the exact line shifts, we can merge it.
Thanks
AA

**Comment by ukmo-juan-castillo** [comment]
> I checked the regtests and it came as expected. For the file changes, there is just one line of change and the other ones are exactly the same. Why did you do it @ukmo-juan-castillo
> For the future, could you make sure you have merged the latest NOAA/develop? I had to merge the upstream locally before running the test.
> Here is the summary of matrix comp.
> [MatrixCompNCEP.zip](https://github.com/NOAA-EMC/WW3/files/6238908/MatrixCompNCEP.zip)
> Could you take a look and once we cleared the exact line shifts, we can merge it.
> Thanks
> AA

Sorry, I created this branch as a copy of the ukmo-waves/develop branch, and I thought it was up to date.

The problem here is that the FLOGR and FLOGRR flags were not initialized, so I initialized them in the same way as similar sets of flags (FLGD, FLGRD, FLG2, FLGR2), i.e., by using the W3FLGRDFLAG subroutine. This subroutine is the one that is adding the extra lines in the output. 

As an improvement to clarify the output of ww3_shel, it would be possible to add an output line before each call to W3FLGRDFLAG to indicate which set of flags is being initialized, as now you only receive a set of lines containing:

Fields   :  XXXXX

and it is not very clear what they relate to.

**Review by aliabdolali — APPROVED** [review]
It looks ok to me.

**Comment by aliabdolali** [comment]
> > I checked the regtests and it came as expected. For the file changes, there is just one line of change and the other ones are exactly the same. Why did you do it @ukmo-juan-castillo
> > For the future, could you make sure you have merged the latest NOAA/develop? I had to merge the upstream locally before running the test.
> > Here is the summary of matrix comp.
> > [MatrixCompNCEP.zip](https://github.com/NOAA-EMC/WW3/files/6238908/MatrixCompNCEP.zip)
> > Could you take a look and once we cleared the exact line shifts, we can merge it.
> > Thanks
> > AA
> 
> Sorry, I created this branch as a copy of the ukmo-waves/develop branch, and I thought it was up to date.
> 
> The problem here is that the FLOGR and FLOGRR flags were not initialized, so I initialized them in the same way as similar sets of flags (FLGD, FLGRD, FLG2, FLGR2), i.e., by using the W3FLGRDFLAG subroutine. This subroutine is the one that is adding the extra lines in the output.
> 
> As an improvement to clarify the output of ww3_shel, it would be possible to add an output line before each call to W3FLGRDFLAG to indicate which set of flags is being initialized, as now you only receive a set of lines containing:
> 
> Fields : XXXXX
> 
> and it is not very clear what they relate to.

Thanks @ukmo-juan-castillo 
Please always check the noaa/develop is merged in your PR.

**Pull request merged**
