### PR TITLE
Init bugs

### PR DESCRIPTION
**Pull request by aronroland**
# Pull Request Summary
This solves issue #1071 

## Description
See #1071 

Please also include the following information: 
Dear reviewer, as described in #1071 bugs have been found for the case when certain source terms or all source terms are switched off within the implicit UG scheme. The bugs have been solved and tested within the cases provided by ERDC. 
 
* Mention any labels that should be added:
 _bug_

* Are answer changes expected from this PR? Please describe the changes and the reason why in addition to which of the following labels would apply: 

Reg-tests may change where the described settings are used. 

### Issue(s) addressed
See #1071 

### Commit Message
Non initialized Arrays for TR0, DB0 or FLSOU = .false. and erroneous boundary handling of the source terms for the Neumann boundary condtion on unstructured grids (implicit scheme) 

### Check list  

- [X ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [X ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

Regression tests, will be done within the PR review ...

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
Hi @aronroland, thanks for submitting this bugfix PR!

Its sounds like you did testing with ERDC for this.  Is there a reason though that the regtests haven't been run?  This should be done so you can fill out the PR header with specifically what tests have changed answers so we already have that information when we do testing for the review.

**Comment by aronroland** [comment]
Dear Mathew, as I have no computational resources to carry out the regtest we will do that within the review, please give us some time to do so.

**Comment by MatthewMasarik-NOAA** [comment]
Hi @aronroland, sure, can you clarify if you are asking for time to allow you guys to run the tests?

**Comment by aronroland** [comment]
yes, exactly this what i am asking for.

**Comment by MatthewMasarik-NOAA** [comment]
Sure thing, then.  There are a few PR's in front of yours, so that gives some time already before your's is up.  If we get to your's and you would still like more time, no problem, we can review it once you're ready.  Thank you @aronroland

**Comment by aronroland** [comment]
thank u, Matthew ...

**Comment by ukmo-ccbunney** [comment]
I'm watching this PR with interest as I am currently experiencing B4B reproducibility issues with some of the PDLIB regression tests after my refactoring of W3SRCE. I am hoping this PR might make them disappear! 🤞

**Comment by aronroland** [comment]
Hi Chris, 

 

There is a possibility … soon I can also look at your stuff more detailed, since I have a vital interest in your work.

 

Cheers

 

Aron

 

Von: Chris Bunney ***@***.***> 
Gesendet: Mittwoch, 13. September 2023 10:07
An: NOAA-EMC/WW3 ***@***.***>
Cc: Aron Roland ***@***.***>; Mention ***@***.***>
Betreff: Re: [NOAA-EMC/WW3] Init bugs (PR #1073)

 

I'm watching this PR with interest as I am currently experiencing B4B reproducibility issues with some of the PDLIB regression tests after my refactoring of W3SRCE. I am hoping this PR might make them disappear! 🤞

**Review by MatthewMasarik-NOAA — CHANGES_REQUESTED** [review]
@aronroland  We can start reviewing once the testing results have been added.  Thanks

**Comment by MatthewMasarik-NOAA** [comment]
@aronroland please sync this branch for merged pr #1070.

**Comment by MatthewMasarik-NOAA** [comment]
@thesser1 @aronroland I know you guys are testing, note that this branch needs to be synced to be current.

**Comment by MatthewMasarik-NOAA** [comment]
Closing on behalf of @thesser1 and @aronroland.

**Pull request closed without merging**
