### PR TITLE
Fixes for issue #417

### LINKED ISSUE #417: multi grids is not working as expected
The _GFSv16_ wave setup has 3 grids (_gnh_10m, gsh_15m and aoc_9km_) with wind, ice and current forcings.
The forcings are:

1. WIND (hourly- plotted every 3 hrs)
Forcing_WIND
2. Current (hourly- plotted every 3 hrs)
Forcing_Current
3. ICE (daily)
Forcing_ICE

It was working fine prior to [e756361](https://github.com/NOAA-EMC/WW3/commit/e756361cee6c0e3bfac064376fcec3eba986719d) as shown in the following animation
**Expected behaviour (gfsv16 wave setup):**
GFSv16_correct

However, it shows a weird significant wave height field if the top of NOAA/[develop](https://github.com/NOAA-EMC/WW3/commit/6cfe1bd0961354c778947da6b6a30f8711b54024) is used. The wave height drops significantly every few time steps.
**Strange HS (gfsv16 wave setup):**
Multi_GFSv16

I did some additional tests to make sure it is related to multiple grids. 
I ran a global grid with 1deg resolution using _ww3_multi_ and it worked as expected.

**Expected behaviour (single grid with 1 deg resolution):**
Global1Deg

**To Reproduce**
There is a [Feature branch](https://github.com/aliabdolali/WW3/tree/fb_ufs_regtests) with _ww3_ufs1.1_ (1deg global grid) and _ww3_ufs1.2_ (GFSv16 multi grids) tests. The inputs are on ftp server, so if this feature branch is cloned, the `model/bin/ww3_from_ftp.sh` can be used to retrieve the inputs.

To reproduce them, the _regtest/bin/run_test_ can be used:
**ww3_ufs1.1 (working with [e756361](https://github.com/NOAA-EMC/WW3/commit/e756361cee6c0e3bfac064376fcec3eba986719d)  and top of noaa/[develop](https://github.com/NOAA-EMC/WW3/commit/6cfe1bd0961354c778947da6b6a30f8711b54024))**
`./bin/run_test -b slurm -c hera.intel -S -T -w work_a -m grdset_a -f -p mpirun -n 140 -t 4  -o all ../model ww3_ufs1.1`
and 
**ww3_ufs1.2 (working with the commits before [e756361](https://github.com/NOAA-EMC/WW3/commit/e756361cee6c0e3bfac064376fcec3eba986719d) and not working with the top of noaa/[develop](https://github.com/NOAA-EMC/WW3/commit/6cfe1bd0961354c778947da6b6a30f8711b54024))**
`./bin/run_test -b slurm -c hera.intel -S -T -w work_ali -m grdset_a -f -p mpirun -n 140  -t 4  -o all ../model ww3_ufs1.2`

**Note** 
For the commits prior to [482c500](https://github.com/NOAA-EMC/WW3/commit/482c500da51c2caf41ce3f8f011855bb4ab38d76), Flags for the two additional variables in ww3_multi.inp should be removed (Atmospheric momentum and Air density). 

Linked Pull Request: https://github.com/NOAA-EMC/WW3/pull/350

### PR DESCRIPTION
**Pull request by ukmo-juan-castillo**
# Pull Request Summary   
Please describe the PR summary
It was reported that, after merging some branches containing changes for oasis coupling, the results of some multi grid configurations, and of some mww3_test_03 regtests changed.

## Description
This branch aims to address the change of answers after merging branches containing changes for oasis coupling. The problem was traced to the setting up of MPI communicators in the subroutine W3MPIO, where some if conditions where modified to add communication for extra fields to be written in the restart file. These if conditions for the original fields in the restart file were reverted, and appropriate new conditions were written for the extra restart fields.

A change of answers is expected to match the results of the code before the oasis coupling changes were introduced.

### Issue(s) addressed
* Is there an issue associated with this development (bug fix, enhancement, new feature)?    
YES

- fixes #417 
- fixes noaa-emc/ww3/issues/417

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)?
YES
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number)
DONE
* Reviewers: @aliabdolali  @JessicaMeixner-NOAA @ukmo-ccbunney 

### Testing
* How were these changes tested?
Compared mww3_test_04 and ww3_tp2.14 test between commits:

commit 9735c7d (HEAD)
Author: Mickael Accensi 49198861+mickaelaccensi@users.noreply.github.com
Date: Fri Oct 23 16:40:22 2020 +0200

commit e756361 (HEAD)
Author: Chris Bunney 48915820+ukmo-ccbunney@users.noreply.github.com
Date: Thu Nov 5 16:08:39 2020 +0000

The Met Office atmosphere+ocean+wave coupled configuration in the UKV domain was also tested to make sure that no changes in results took place in coupled configurations.

* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
YES - reviewers are encouraged to run further tests to make sure that the differences in results they observed disappear
* If a new feature was added, was a new regression test added?
N/A
* Have regression tests been run?
YES - output will be attached to the request once they are completed
* Which compiler / HPC you used to run the regression tests in the PR?
Cray compiler in the CRAYXC40 machinge at the Met Office 
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):    

Expecting changes in the mww3_test_03 test, PR1_MPI_e and PR1_MPI_d2

### CODE REVIEW

**Comment by ukmo-juan-castillo** [comment]
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/6775464/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/6775465/matrixDiff.txt)

I believe the regtests show changes only in multi configurations as expected. I modified the code so that the extra restart for oasis coupling will work for multi grid runs, although I did not have any configuration to test it.

**Comment by aliabdolali** [comment]
The fix is working for our global case now. In the setup, we had restart dump every 3 hrs and it was initiated from zero every 3 hrs before, now it is working just fine. Thanks @ukmo-juan-castillo
glo15mGrid_a

**Comment by aliabdolali** [comment]
The full regtest shows non-b4b for mww3_test04 + the following:
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (27 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (27 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (10 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (7 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (27 files differ)
mww3_test_03/./work_PR1_MPI_e                     (27 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (27 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (27 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (27 files differ)
mww3_test_04/./work_PR2_UNO_MPI_d                     (139 files differ)
mww3_test_04/./work_PR3_UQ_MPI_d                     (155 files differ)
mww3_test_04/./work_PR3_UNO_MPI_d                     (139 files differ)
mww3_test_04/./work_PR1_MPI_d                     (127 files differ)
mww3_test_04/./work_PR3_UNO_MPI_d_c                     (139 files differ)
mww3_test_04/./work_PR3_UQ_MPI_d_c                     (155 files differ)
mww3_test_04/./work_PR2_UQ_MPI_d                     (155 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ) **expected**
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ) **expected**
ww3_tp2.15/./work_5km                     (1 files differ) **expected**
ww3_tp2.15/./work_MPI_5km                     (1 files differ) **expected**
ww3_tp2.17/./work_a                     (3 files differ) 
ww3_tp2.17/./work_c                     (3 files differ)
ww3_tp2.17/./work_b                     (3 files differ)
ww3_tp2.17/./work_mc1                     (1 files differ)
ww3_ufs1.2/./work_a                     (36 files differ) **expected**
ww3_ufs1.2/./work_b                     (39 files differ) **expected**

@ukmo-juan-castillo you had identical results for mww3_test04? 

[diff_fix.zip](https://github.com/NOAA-EMC/WW3/files/6788427/diff_fix.zip)

**Comment by ukmo-juan-castillo** [comment]
I will have a second look at the mww3_test_04 tests.

**Comment by ukmo-juan-castillo** [comment]
When I compare the versions:

commit 9735c7d (HEAD)
Author: Mickael Accensi 49198861+mickaelaccensi@users.noreply.github.com
Date: Fri Oct 23 16:40:22 2020 +0200

commit e756361 (HEAD) + branch changes
Author: Chris Bunney 48915820+ukmo-ccbunney@users.noreply.github.com
Date: Thu Nov 5 16:08:39 2020 +0000

I only see differences in the mww3_test_03 tests as expected. When I compare the latest version of develop and the branch I indeed observe the differences you describe, I imagine you are also comparing these codes. I guess there are more changes in the intermediate develop versions that cause these differences.

How would you like to proceed? I could start comparing develop versions, but this will take a good bit of time.

**Comment by JessicaMeixner-NOAA** [comment]
@ukmo-juan-castillo I see the differences in the 04 tests when comparing your branch versus the develop branch, but only expected the 03 tests.  So I think the question is why are we getting those differences, when we don't expect them. Let me know if there is something I can do to help.

**Comment by ukmo-juan-castillo** [comment]
I will investigate further, I will have to look at other develop versions to understand what happens as the differences must come from other code changes.

**Comment by ukmo-juan-castillo** [comment]
I am still looking at this, sorry it is taking so long. I know now that commit 6d95c334eebdb55d3ac1211240fa24d9f959cc83 introduced something that is causing the differences. I just need to know what is this something.

I think I know what is causing the problem, I need to understand it better to provide a permanent solution.

**Comment by ukmo-juan-castillo** [comment]
I think I know what happens now. The fix I propose seems right, and it will affect the multi tests writing a restart file, which also explains the observed changes in ww3_tp2.17. When applying the fix to version e756361 there are no changes in the mww3_test_04 test though. This happens because there was a bug in the code affecting these tests that was only fixed in version 6d95c33, in particular changes in the routine W3SETO to assign the pointers IRQRSS and VAAUX for all processors and not just when NRQRS==0:

6d95c33#diff-939f91a8acb5a641add991630802f1bfd7f2d322046224043be109fd2a15ae91

Only after this bug is fixed the current bug fix will change results in mww3_test_04.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by aliabdolali** [comment]
I ran the regtests successfully with expected changes due to the fix for restart files in multi cases.
I also plotted the fields for ww3_ufs1.2 and ww3_tp2.17 cases and they all look reasonable. There is no reinitiation in the hs field.

**Comment by aliabdolali** [comment]
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/6895220/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/6895221/matrixCompFull.txt)

mww3_test_03/./work_PR2_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (27 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (27 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (7 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (27 files differ)
mww3_test_03/./work_PR1_MPI_e                     (27 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (27 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (27 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (27 files differ)
mww3_test_04/./work_PR2_UNO_MPI_d                     (139 files differ)
mww3_test_04/./work_PR3_UQ_MPI_d                     (155 files differ)
mww3_test_04/./work_PR3_UNO_MPI_d                     (139 files differ)
mww3_test_04/./work_PR1_MPI_d                     (127 files differ)
mww3_test_04/./work_PR3_UNO_MPI_d_c                     (139 files differ)
mww3_test_04/./work_PR3_UQ_MPI_d_c                     (155 files differ)
mww3_test_04/./work_PR2_UQ_MPI_d                     (155 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ)
ww3_tp2.17/./work_a                     (3 files differ)
ww3_tp2.17/./work_c                     (3 files differ)
ww3_tp2.17/./work_b                     (3 files differ)
ww3_tp2.17/./work_mc1                     (1 files differ)
ww3_ufs1.2/./work_a                     (36 files differ)
ww3_ufs1.2/./work_b                     (39 files differ)

**Review by aliabdolali — APPROVED** [review]

**Pull request merged**
