### PR TITLE
fix explicit pdlib case when running fully coupled with currents and ice

### LINKED ISSUE #961: when coupled with ice model, pdlib case does not reproduce with different decompositions
**Describe the bug**

This is work associated with UFS Issue [#1556](https://github.com/ufs-community/ufs-weather-model/issues/1556)

For UFS, PR #949 resolved the lack of reproducibility for changes in domain decomposition for the case of ATM-WAV case. But in the fully coupled (ATM-OCN-ICE-WAV), changes in WW3 domain decomposition still break reproducibility. 

The test case uses the same mesh as before (still using explicit) with the fully coupled case running on either 10PEs or 5PEs for WW3. When fully coupled, WW3 exports the partitioned stokes drift to the OCN in addition to Z0 to the ATM. It imports the ice fraction from the ICE model. 

On the 4th time-step, WW3 has received identical values from all other components at the start of the timestep but sends back a different value at a single point for the 3rd partition of stokes drift (both x and y), depending on decomposition. The cause is a difference in the last two (k=32,33) frequencies of array ``a``. 

The non-reproducing point is located on the edge of one domain element in the 10PE case. The same point is in the interior of a domain element in the 5PE case. The location is shown below in green, where black and red are the points on adjacent domains.

Screen Shot 2023-03-27 at 2 55 29 PM

The issue appears associated with the imported ice fraction. For timesteps 1,2,3 the imported ice fraction at this point is zero. On the 4th timestep, it is 0.49 (ficen = 0.75). Mapsta is 1.0 at the non-reproducing point and does not change.

A test was made with the imported ice fraction set to a constant value (0.15). In that case, the fully coupled case can be integrated 24 hours and results are B4B using two different WW3 decompositions.

A second test was made with the exported stokes drift set to a constant value and allowing the ice concentration to change. In that case, differences are found in the WW3 history files at the same location, in arrays ``TAUWNX,Y`` and ``TAUWI,X``.

**To Reproduce**
Steps to reproduce the behavior. 

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# Pull Request Summary
 

- Extends calculations in explict block to ghost points
- Adds exchange of ``u`` prior to start of iteration loop

### Issue(s) addressed

- fixes #961 

### Commit Message

Extend calculations in the explicit pdlib code to ghost points and adds halo exchange prior to iteration loop

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
Thank you, @DeniseWorthen.  This will go after #984.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
This has minor differences in the ww3_ufs1.1 regression test when compared with develop, but as expected this solved the issues with MPI reproduciblity when ice is changing and using block explicit.  I will follow this PR up shortly by adding a test that tests for this so we can maintain this feature.  I'll also  post regression test info in an few hours. (Although we can re-run them if we want to @MatthewMasarik-NOAA after the last PR just was merged).

**Comment by MatthewMasarik-NOAA** [comment]
> This has minor differences in the ww3_ufs1.1 regression test when compared with develop, but as expected this solved the issues with MPI reproduciblity when ice is changing and using block explicit. I will follow this PR up shortly by adding a test that tests for this so we can maintain this feature. I'll also post regression test info in an few hours. (Although we can re-run them if we want to @MatthewMasarik-NOAA after the last PR just was merged).

@JessicaMeixner-NOAA, I'm OK with using the regression tests you've run.

**Comment by JessicaMeixner-NOAA** [comment]
Tests on hera with intel and the matrix regtests: 

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/11266286/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/11266287/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/11266288/matrixDiff.txt)


```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (17 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
ww3_ta1/./work_UPD0F_U                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_ufs1.1/./work_unstr_b                     (3 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```


There are expected differences in ww3_ufs1.1/./work_unstr_b     that relate to the bug-fix here.  When you run this regression test with different MPI tasks, you get the same answer on the output variables.  The restarts still have differences though.

**Comment by MatthewMasarik-NOAA** [comment]
> When you run this regression test with different MPI tasks, you get the same answer on the output variables.

That's fabulous news!!

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen thank you so much for this fix!!!!!   I will start the regression tests this morning to make the PR to dev/ufs-weather-model to have this fix.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Thanks for the quick turn-around. The next PR will be to add the unstructured mesh to the dev/ufs-weather-branch and the tests to UFS.

Is SCOTCH installed everywhere, or only on hera, orion and wcoss2? If it is not everywhere, I will need to remove those platforms. 

Also, am I right that we can build a SCOTCH application with GNU?

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I'd have to check on the SCOTCH installations being everywhere because we suspect we'll have to re-install scotch once we determine what the scaling issues are, so there has been some hesitation on it being installed in the official locations so I'll have to check to see the status for the machine I have access for. SCOTCH is in the process of being approved for WCOSS2 and so it's not on cactus/dogwood for sure right now. 

We should be able to build and run SCOTCH with GNU we've done some testing with that on the standalone side for trying to figure out scaling issues.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA OK. 

It is easy enough for me to just have a +hera,orion,wcoss2 restriction in the rt.conf for the coupled pdlib tests. I'm not sure that even METIS is installed for the other RDHPCS machines.

**Pull request merged**
