### PR TITLE
Several corrections to the coherency checks.

### PR DESCRIPTION
**Pull request by MathieuDutSik**
# Pull Request Summary
Simplifying and correcting debugging statements.

## Description

Simplify and corrects a few parts of the coherency checks.
(like identifying VA(0:NSEAL) with FIELD(1:NSEAL) which is problematic and cause memory problems).

I thus believe it is useful to merge as it helps debugging and has zero impact on normal use.

### Issue(s) addressed

The DEBUG statements are a very useful feature of the WW3 system. I thus believe
that it is very important to have correct debugging feature that do not lead to the wrong
idea about errors.

### Commit Message

Simplifying and correcting debugging statements

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by aliabdolali** [comment]
> This PR simplifies and corrects a few parts of the coherency checks (like identifying VA(0:NSEAL) with FIELD(1:NSEAL) which is problematic).
> 
> I thus believe it is useful to merge as it helps debugging and has zero impact on normal use.

Hi @MathieuDutSik Thanks for providing this development. I'd appreciate it if you provide an extended description of why you did this and how you expect it would benefit WW3. Could you fill out the PR template completely? If some of them are not applicable, you can leave NA in front.

**Comment by JessicaMeixner-NOAA** [comment]
@MathieuDutSik thanks for updating more of the descriptions. Would it be okay if the eventual commit message is "Simplifying and correcting debugging statements" as I think it might be more informative than "sync simplify_logs with develop"?   Can you address the checklist and provide any information about testing.  Thank you so much for this update! I'm testing two other PRs right now and then will run regression tests for this PR.

**Comment by MathieuDutSik** [comment]
> @MathieuDutSik thanks for updating more of the descriptions. Would it be okay if the eventual commit message is "Simplifying and correcting debugging statements" as I think it might be more informative than "sync simplify_logs with develop"? Can you address the checklist and provide any information about testing. Thank you so much for this update! I'm testing two other PRs right now and then will run regression tests for this PR.

Ok, I did a renaming of the "eventual commit message".
Regarding the checklist, I do not understand what I should do because some merged PRs like https://github.com/NOAA-EMC/WW3/pull/714 have not the checklist done.
So, I would like things to be clarified on that.

**Comment by JessicaMeixner-NOAA** [comment]
@MathieuDutSik the checklist is simply a quick list of reminders for developers as they submit the PR.  For example, if your branch is up to date with the develop branch of WW3, you would check the box (or in the edit mode its [x]).  For the testing, we'll do testing on our end as well, but we'd like to hear how this PR was tested by the developer submitting the PR.    

Our HPC is very full right now, but I will be running the regtests for this PR and completing the review of this PR this week.  I apologize for the delay and long queue time for this PR.  We will work to reduce this time in the queue in the future.  I appreciate your patience with us and most importantly we appreciate your contributions to WW3!

**Comment by JessicaMeixner-NOAA** [comment]
@MathieuDutSik I just wanted to let you know that I ran the regtests for this PR, but it was on a machine that disk is having some issues, so I'm having to re-run them now on another machine.  I'm also in the process of finalizing the review of PR741.  I don't think I"m going to be able to merge this PR this week as I said 2 days ago and Monday is a holiday, so my best guess of a timeline is Tuesday or Wednesday of next week.  I've reviewed the code itself and do not see any issues there.  Thanks again for your patience!

**Comment by MathieuDutSik** [comment]
Thank you for your answer. Let me know how I can help you.
As you have seen, there is plenty of further corrections down the line, but I am waiting for this one to go through before writing them.

**Comment by JessicaMeixner-NOAA** [comment]
Only the expected cases have issues: 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_ta1/./work_UPD0F_U                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
```
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/9497389/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/9497391/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/9497392/matrixDiff.txt)

**Review by JessicaMeixner-NOAA — APPROVED** [review]
@MathieuDutSik  thank you for your updates! Looking forward to the next set of updates!

**Pull request merged**
