### PR TITLE
Remove user supplied switches

### LINKED ISSUE #355: Remove support for experimental switch options (FLXX, PRX, STX, NLX, BTX, DBX, TRX, BSX)
There are various options for experimental switches FLXX, PRX, STX, NLX, BTX, DBX, TRX, BSX which could be used as an example for how to add another switch option.  We propose removing this example code and switch options, as they do not appear to be used. 

This work is planned for the end of May 2021.

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
This PR removes the switches that could be used to add a new source term. 

## Description
This PR removes the following switches: 
* LNX 
* FLXX 
* PRX 
* TRX 
* STX 
* BSX 
* DBX 
* BTX 
* NLX

### Issue(s) addressed

- fixes #355

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)?  _yes_
* Reviewers: @aliabdolali 

### Testing
* How were these changes tested? regtests
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) 
* If a new feature was added, was a new regression test added? removed features that was not tested by regtests
* Have regression tests been run? yes 
* Which compiler / HPC you used to run the regression tests in the PR?  ncep, hera.intel 
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):    

This PR is in a draft state.  Before merging the following needs to happen: 
* this builds on PR#408 
* in case any switches are used anywhere, they need to be removed first 
* regtests should be re-run (they all run to completion now).

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
A few regtests had errors, so I'm working on resolving those.

**Comment by JessicaMeixner-NOAA** [comment]
Many of the regression tests changed, due to the new mod_defs, in my examination of the output, the tests with meaningful differences are the normal tests: 
* test case: ww3_tp2.10; test run: ./work_MPI_OMPH
* test case: mww3_test_03; test run: ./work_PR3_UQ_MPI_d2
* test case: mww3_test_03; test run: ./work_PR3_UQ_MPI_d2_c
* test case: mww3_test_03; test run: ./work_PR1_MPI_d2
* test case: mww3_test_03; test run: ./work_PR2_UNO_MPI_d2
* test case: mww3_test_03; test run: ./work_PR3_UNO_MPI_d2
* test case: mww3_test_03; test run: ./work_PR3_UNO_MPI_d2_c
* test case: mww3_test_03; test run: ./work_PR2_UQ_MPI_d2
* test case: mww3_test_03; test run: ./work_PR3_UNO_MPI_e
There were a few ww3_grid.out that show up as diffs in the output, but this I believe is because the files somehow got set as binary and not a text file. 

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7022322/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7022323/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7022324/matrixDiff.txt)



@aliabdolali this is ready for your review now.

**Comment by JessicaMeixner-NOAA** [comment]
The ufs-weather-model  regression tests also passed after creating new mod_defs.

**Comment by aliabdolali** [comment]
> Many of the regression tests changed, due to the new mod_defs, in my examination of the output, the tests with meaningful differences are the normal tests:
> 
> * test case: ww3_tp2.10; test run: ./work_MPI_OMPH
> * test case: mww3_test_03; test run: ./work_PR3_UQ_MPI_d2
> * test case: mww3_test_03; test run: ./work_PR3_UQ_MPI_d2_c
> * test case: mww3_test_03; test run: ./work_PR1_MPI_d2
> * test case: mww3_test_03; test run: ./work_PR2_UNO_MPI_d2
> * test case: mww3_test_03; test run: ./work_PR3_UNO_MPI_d2
> * test case: mww3_test_03; test run: ./work_PR3_UNO_MPI_d2_c
> * test case: mww3_test_03; test run: ./work_PR2_UQ_MPI_d2
> * test case: mww3_test_03; test run: ./work_PR3_UNO_MPI_e
>   There were a few ww3_grid.out that show up as diffs in the output, but this I believe is because the files somehow got set as binary and not a text file.
> 
> [matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7022322/matrixCompFull.txt)
> [matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7022323/matrixCompSummary.txt)
> [matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7022324/matrixDiff.txt)
> 
> @aliabdolali this is ready for your review now.

Awsome, I'll finish the review today.

**Review by aliabdolali — COMMENTED** [review]
Hi Jessica, Could you confirm that the followings are left intentionally:
**LNX**
model/ftn/gx_outp.ftn:606:!       !/LNx    Linear input package
model/ftn/w3srcemd.ftn:270:!         a Input.                                  ( W3SLNx, W3SINn )
model/ftn/ww3_uprstr.ftn:205:!        VALNX*NY
model/ftn/ww3_outp.ftn:1047:!       !/LNx    Linear input package
model/ftn/w3iorsmd.ftn:236:!     !/LNx
model/ftn/ww3_ounp.ftn:1372:!       !/LNx    Linear input package
model/ftn/ww3_outp.ftn:1049:!       !/NLx    Nonlinear interaction package
model/ftn/ww3_ounp.ftn:1374:!       !/NLx    Nonlinear interaction package
**NLX**
model/bin/make_makefile.sh:640:        nlx=$NULL ;;
model/bin/make_makefile.sh:642:        nlx='w3snl1md' ;;
model/bin/make_makefile.sh:644:        nlx="$nl" ;;
model/bin/make_makefile.sh:646:        nlx='w3snl3md' ;;
model/bin/make_makefile.sh:648:        nlx='w3snl4md' ;;
model/bin/make_makefile.sh:650:        nlx="$nl" ;;
model/bin/make_makefile.sh:655:        nlx="$nlx w3snlsmd" ;;
model/ftn/ww3_outp.ftn:1049:!       !/NLx    Nonlinear interaction package
model/ftn/ww3_ounp.ftn:1374:!       !/NLx    Nonlinear interaction package
model/ftn/gx_outp.ftn:608:!       !/NLx    Nonlinear interaction package
model/bin/make_makefile.sh:814:             source="w3parall w3triamd w3gridmd $stx $nlx $btx $is $uostmd"
model/bin/make_makefile.sh:831:             source="$pdlibcode $pdlibyow $db $tr $trx $bt $setupcode $stx $nlx $btx $is wmmdatmd w3parall $uostmd"
model/bin/make_makefile.sh:838:             source="$pdlibcode $pdlibyow $db $bt $setupcode $tr $trx $stx $nlx $btx $is wmmdatmd w3parall w3triamd $uostmd"
model/bin/make_makefile.sh:845:             source="$pdlibcode $pdlibyow $db $bt $setupcode $stx $nlx $btx $is wmmdatmd w3parall w3triamd $uostmd"
model/bin/make_makefile.sh:852:             source="$pdlibcode $pdlibyow $db $bt $setupcode w3triamd $stx $nlx $btx  $is $uostmd"
model/bin/make_makefile.sh:859:             source="$pdlibcode $pdlibyow $db $bt $setupcode w3triamd $stx $nlx $btx $is w3parall $uostmd"
model/bin/make_makefile.sh:866:             source="$pdlibcode $pdlibyow $db $bt $setupcode w3triamd $stx $nlx $btx $is w3parall $uostmd"
model/bin/make_makefile.sh:931:             source="$pdlibcode $pdlibyow $db $bt $setupcode $tr $trx $stx $nlx $btx $is $uostmd"
model/bin/make_makefile.sh:939:             source="$pdlibcode $pdlibyow $db $bt $setupcode w3parall w3triamd $stx $nlx $btx  $is $uostmd"
model/bin/make_makefile.sh:976:             source="$pdlibcode $pdlibyow $db $bt $setupcode $stx $nlx $btx $is $uostmd"
model/bin/make_makefile.sh:984:             source="$pdlibcode $pdlibyow $db $bt $setupcode wmmdatmd w3parall w3triamd $stx $nlx $btx $is $uostmd"
model/bin/make_makefile.sh:999:             source="$pdlibcode $pdlibyow $db $bt $setupcode wmmdatmd w3parall w3triamd $stx $nlx $btx $tr $bs $is $uostmd"
model/bin/make_makefile.sh:1007:             source="$pdlibcode $pdlibyow $db $bt $setupcode wmmdatmd w3parall w3triamd $ln $flx $st $nlx $btx $tr $bs $is $ic $uostmd"
model/bin/make_makefile.sh:1014:             source="$pdlibcode $pdlibyow $db $bt $setupcode wmmdatmd w3dispmd w3triamd $ln $stx $nlx $btx $tr $bs $is $uostmd"
**FLXX**
model/ftn/gx_outp.ftn:605:!       !/FLXx   Flux/stress computation.
model/ftn/w3gdatmd.ftn:774:!/FLXX        REAL                  :: DUMMY
model/ftn/ww3_outp.ftn:1046:!       !/FLXx   Flux/stress computation.
model/ftn/ww3_ounp.ftn:1371:!       !/FLXx   Flux/stress computation.
model/ftn/ww3_ounp.ftn:1862:!/FLXX                CALL W3FLXX
model/ftn/ww3_ounp.ftn:1980:!/FLXX                CALL W3FLXX
model/bin/make_makefile.sh:537:         flxx=$NULL ;;
model/bin/make_makefile.sh:540:         flxx=$NULL ;;
model/bin/make_makefile.sh:543:         flxx=$NULL ;;
model/bin/make_makefile.sh:546:         flxx=$NULL ;;
model/bin/make_makefile.sh:549:         flxx=$NULL ;;
**TRX**
model/ftn/gx_outp.ftn:612:!       !/TRx    Triad interaction package
model/ftn/ww3_outp.ftn:1053:!       !/TRx    Triad interaction package
model/ftn/ww3_ounp.ftn:1378:!       !/TRx    Triad interaction package
model/bin/make_makefile.sh:676:        trx=$NULL ;;
model/bin/make_makefile.sh:678:        trx=$NULL ;;
model/bin/make_makefile.sh:831:             source="$pdlibcode $pdlibyow $db $tr $trx $bt $setupcode $stx $nlx $btx $is wmmdatmd w3parall $uostmd"
model/bin/make_makefile.sh:838:             source="$pdlibcode $pdlibyow $db $bt $setupcode $tr $trx $stx $nlx $btx $is wmmdatmd w3parall w3triamd $uostmd"
model/bin/make_makefile.sh:931:             source="$pdlibcode $pdlibyow $db $bt $setupcode $tr $trx $stx $nlx $btx $is $uostmd"
**STX**
model/ftn/gx_outp.ftn:607:!       !/STx    Source term package
model/ftn/ww3_outp.ftn:1048:!       !/STx    Source term package
model/ftn/ww3_ounp.ftn:1373:!       !/STx    Source term package
model/bin/make_makefile.sh:570:        stx=$NULL ;;
model/bin/make_makefile.sh:572:        stx='w3src1md' ;;
model/bin/make_makefile.sh:574:        stx='w3src2md' ;;
model/bin/make_makefile.sh:576:        stx='w3src3md' ;;
model/bin/make_makefile.sh:578:        stx='w3src4md' ;;
model/bin/make_makefile.sh:580:        stx='w3src6md' ;;
model/bin/make_makefile.sh:814:             source="w3parall w3triamd w3gridmd $stx $nlx $btx $is $uostmd"
model/bin/make_makefile.sh:831:             source="$pdlibcode $pdlibyow $db $tr $trx $bt $setupcode $stx $nlx $btx $is wmmdatmd w3parall $uostmd"
model/bin/make_makefile.sh:838:             source="$pdlibcode $pdlibyow $db $bt $setupcode $tr $trx $stx $nlx $btx $is wmmdatmd w3parall w3triamd $uostmd"
model/bin/make_makefile.sh:845:             source="$pdlibcode $pdlibyow $db $bt $setupcode $stx $nlx $btx $is wmmdatmd w3parall w3triamd $uostmd"
model/bin/make_makefile.sh:852:             source="$pdlibcode $pdlibyow $db $bt $setupcode w3triamd $stx $nlx $btx  $is $uostmd"
model/bin/make_makefile.sh:859:             source="$pdlibcode $pdlibyow $db $bt $setupcode w3triamd $stx $nlx $btx $is w3parall $uostmd"
model/bin/make_makefile.sh:866:             source="$pdlibcode $pdlibyow $db $bt $setupcode w3triamd $stx $nlx $btx $is w3parall $uostmd"
model/bin/make_makefile.sh:931:             source="$pdlibcode $pdlibyow $db $bt $setupcode $tr $trx $stx $nlx $btx $is $uostmd"
model/bin/make_makefile.sh:939:             source="$pdlibcode $pdlibyow $db $bt $setupcode w3parall w3triamd $stx $nlx $btx  $is $uostmd"
model/bin/make_makefile.sh:976:             source="$pdlibcode $pdlibyow $db $bt $setupcode $stx $nlx $btx $is $uostmd"
model/bin/make_makefile.sh:984:             source="$pdlibcode $pdlibyow $db $bt $setupcode wmmdatmd w3parall w3triamd $stx $nlx $btx $is $uostmd"
model/bin/make_makefile.sh:999:             source="$pdlibcode $pdlibyow $db $bt $setupcode wmmdatmd w3parall w3triamd $stx $nlx $btx $tr $bs $is $uostmd"
model/bin/make_makefile.sh:1014:             source="$pdlibcode $pdlibyow $db $bt $setupcode wmmdatmd w3dispmd w3triamd $ln $stx $nlx $btx $tr $bs $is $uostmd"
**BSX**
model/ftn/gx_outp.ftn:613:!       !/BSx    Bottom scattering package
model/ftn/ww3_outp.ftn:1054:!       !/BSx    Bottom scattering package
model/ftn/ww3_ounp.ftn:1379:!       !/BSx    Bottom scattering package
model/bin/make_makefile.sh:683:        bsx=$NULL ;;
model/bin/make_makefile.sh:685:        bsx=$NULL ;;
**DBX**
model/ftn/gx_outp.ftn:611:!       !/DBx    Depth-induced breaking package
model/ftn/ww3_outp.ftn:1052:!       !/DBx    Depth-induced breaking package
model/ftn/ww3_ounp.ftn:1377:!       !/DBx    Depth-induced breaking package
model/bin/make_makefile.sh:669:        dbx=$NULL ;;
model/bin/make_makefile.sh:671:        dbx=$NULL ;;
**BTX**
model/ftn/ww3_outp.ftn:1050:!       !/BTx    Bottom friction package
model/ftn/ww3_ounp.ftn:1375:!       !/BTx    Bottom friction package
model/ftn/gx_outp.ftn:609:!       !/BTx    Bottom friction package
model/ftn/w3srcemd.ftn:213:!       PHIBBL  Real   O   Energy flux to BBL             ( !/BTx )
model/ftn/w3srcemd.ftn:214:!       TAUBBL  R.A.   O   Momentum flux to BBL           ( !/BTx )

**Comment by JessicaMeixner-NOAA** [comment]
> model/ftn/w3gdatmd.ftn:774:!/FLXX REAL :: DUMMY
> model/ftn/ww3_ounp.ftn:1862:!/FLXX CALL W3FLXX
> model/ftn/ww3_ounp.ftn:1980:!/FLXX CALL W3FLXX

These were all oversights and have now been removed. Thanks for catching these! 

The grep's that found variables in make_makefile should all be there as these are actual variable names and cannot be removed, but are the same name as the removed switch.  The commented text that has SWITCHx is to signify any "x" option, so ST1, ST2 or for short STx.  Therefore all of those comments should stay as is. 

> model/ftn/ww3_uprstr.ftn:205:! VALNX*NY

Is a part of a variable name, and should also stay

**Review by aliabdolali — APPROVED** [review]

**Pull request merged**
