### PR TITLE
Doxygen documentation - marked source PR 3

### LINKED ISSUE #586: Add doxygen marked-down source
# Add Doxygen Documentation

For each file, document each contained Fortran code units (file, module, subroutine, etc.) using the agreed upon doxygen headers:

- [ ] ctest.F90 (paused, to be outdated.)
- [ ] pdlib_field_vec.F90
- [ ] serv_xnl4v5.f90
- [ ] w3arrymd.F90
- [ ] w3dispmd.F90
- [ ] w3fld1md.F90
- [ ] w3fld2md.F90
- [ ] w3fldsmd.F90
- [ ] w3gdatmd.F90
- [ ] w3getmem.c
- [ ] w3gig1md.F90
- [ ] w3gkemd.F90
- [ ] w3gridmd.F90
- [ ] w3gsrumd.F90
- [ ] w3macros.h
- [ ] w3meminfo.F90
- [ ] w3nmlbouncmd.F90
- [ ] w3nmlgridmd.F90
- [ ] w3nmlmultimd.F90
- [ ] w3nmlounfmd.F90
- [ ] w3nmlounpmd.F90
- [ ] w3nmlprncmd.F90
- [ ] w3nmlshelmd.F90
- [ ] w3nmltrncmd.F90
- [ ] w3nmluprstrmd.F90
- [ ] w3oacpmd.F90
- [ ] w3odatmd.F90
- [ ] w3ogcmmd.F90
- [ ] w3profsmd.F90
- [ ] w3profsmd_pdlib.F90
- [ ] w3servmd.F90
- [ ] w3sic3md.F90
- [ ] w3sic5md.F90 (troubleshooting)
- [ ] w3sis2md.F90 (troubleshooting)
- [ ] w3strkmd.F90 (MatthewMasarik-NOAA)
- [ ] w3tidemd.F90 (MatthewMasarik-NOAA)
- [ ] w3timemd.F90 (MatthewMasarik-NOAA)
- [ ] w3uostmd.F90 (troubleshooting)
- [ ] wmesmfmd.F90 (troubleshooting)
- [ ] PDLIB/yowdatapool.F90
- [ ] PDLIB/yowelementpool.F90
- [ ] PDLIB/yowerr.F90
- [ ] PDLIB/yowexchangeModule.F90
- [ ] PDLIB/yowfunction.F90
- [ ] PDLIB/yownodepool.F90
- [ ] PDLIB/yowpd.F90
- [ ] PDLIB/yowpdlibmain.F90
- [ ] PDLIB/yowrankModule.F90
- [ ] PDLIB/yowsidepool.F90
- [ ] SCRIP/scrip_constants.f
- [ ] SCRIP/scrip_errormod.f90
- [ ] SCRIP/scrip_grids.f
- [ ] SCRIP/scrip_interface.F90
- [ ] SCRIP/scrip_iounitsmod.f90
- [ ] SCRIP/scrip_kindsmod.f90
- [ ] SCRIP/SCRIP.mk
- [ ] SCRIP/SCRIP_NC.mk
- [ ] SCRIP/scrip_netcdfmod.f90
- [ ] SCRIP/scrip_remap_conservative.f
- [ ] SCRIP/scrip_remap_read.f
- [ ] SCRIP/scrip_remap_vars.f
- [ ] SCRIP/scrip_remap_write.f
- [ ] SCRIP/scrip_timers.f
- [x] constants.F90
- [x] gx_outf.F90
- [x] gx_outp.F90
- [x] mod_constants.f90
- [x] mod_fileio.f90
- [x] mod_xnl4v5.f90
- [x] w3adatmd.F90
- [x] w3agcmmd.F90
- [x] w3bullmd.F90
- [x] w3canomd.F90
- [x] w3cspcmd.F90
- [x] w3flx1md.F90
- [x] w3flx2md.F90
- [x] w3flx3md.F90
- [x] w3flx4md.F90
- [x] w3flx5md.F90
- [x] w3idatmd.F90
- [x] w3igcmmd.F90
- [x] w3initmd.F90
- [x] w3iobcmd.F90
- [x] w3iogomd.F90
- [x] w3iogrmd.F90
- [x] w3iopomd.F90
- [x] w3iorsmd.F90
- [x] w3iosfmd.F90
- [x] w3iotrmd.F90
- [x] w3metamd.F90
- [x] w3ounfmetamd.F90
- [x] w3parall.F90
- [x] w3partmd.F90
- [x] w3pro1md.F90
- [x] w3pro2md.F90
- [x] w3pro3md.F90
- [x] w3psmcmd.F90
- [x] w3ref1md.F90
- [x] w3sbs1md.F90
- [x] w3sbt1md.F90
- [x] w3sbt4md.F90
- [x] w3sbt8md.F90
- [x] w3sbt9md.F90
- [x] w3sdb1md.F90
- [x] w3sic1md.F90
- [x] w3sic2md.F90
- [x] w3sic4md.F90
- [x] w3sis1md.F90
- [x] w3smcomd.F90
- [x] w3snl1md.F90
- [x] w3snl2md.F90
- [x] w3snl3md.F90 
- [x] w3snl4md.F90
- [x] w3snl5md.F90
- [x] w3snlsmd.F90
- [x] w3src0md.F90
- [x] w3src1md.F90
- [x] w3src2md.F90
- [x] w3src3md.F90
- [x] w3src4md.F90
- [x] w3src6md.F90
- [x] w3srcemd.F90
- [x] w3str1md.F90
- [x] w3str2md.F90
- [x] w3triamd.F90
- [x] w3uno2md.F90
- [x] w3updtmd.F90
- [x] w3uqckmd.F90
- [x] w3wavemd.F90
- [x] w3wavset.F90
- [x] w3wdasmd.F90
- [x] w3wdatmd.F90
- [x] wmfinlmd.F90
- [x] wmgridmd.F90 
- [x] wminiomd.F90 
- [x] wminitmd.F90
- [x] wmiopomd.F90 
- [x] wmmdatmd.F90 
- [x] wmscrpmd.F90 
- [x] wmunitmd.F90
- [x] wmupdtmd.F90
- [x] wmwavemd.F90
- [x] ww3_bounc.F90
- [x] ww3_bound.F90
- [x] ww3_gint.F90
- [x] ww3_grib.F90
- [x] ww3_grid.F90
- [x] ww3_gspl.F90
- [x] ww3_multi.F90
- [x] ww3_ounf.F90
- [x] ww3_ounp.F90
- [x] ww3_outf.F90
- [x] ww3_outp.F90
- [x] ww3_prep.F90
- [x] ww3_prnc.F90
- [x] ww3_prtide.F90
- [x] ww3_sbs1.F90
- [x] ww3_shel.F90
- [x] ww3_strt.F90
- [x] ww3_systrk.F90
- [x] ww3_trck.F90
- [x] ww3_trnc.F90
- [x] ww3_uprstr.F90

### PR DESCRIPTION
**Pull request by MatthewMasarik-NOAA**
# Pull Request Summary
Collection of `doxygen` marked files.

## Description
The following list of files has been marked with `doxygen` tags for documentation:
* [x] mod_xnl4v5.f90
* [x] mod_fileio.f90
* [x] mod_constants.f90
* [x] constants.F90
* [x] w3src2md.F90
* [x] w3src1md.F90
* [x] w3src0md.F90
* [x] w3swldmd.F90
* [x] w3uno2md.F90
* [x] w3uqckmd.F90
* [x] w3wavemd.F90
* [x] w3wavset.F90
* [x] w3wdatmd.F90
* [x] w3wdasmd.F90
* [x] w3str2md.F90
* [x] w3str1md.F90

Is a change of answers expected from this PR?
No.  Documentation only added.

Please also include the following information: 
* Mention any labels that should be added:   _documentation_.
* Are answer changes expected from this PR?  No.

### Issue(s) addressed
- addresses, though does not close #586 

### Commit Message
Doxygen documentation - marked source PR 3
Co-author:  @JessicaMeixner-NOAA 

### Check list  
- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
By running the matrix of regression tests against develop.

* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
No.  The changes are only documentation.  Documentation is not tested.

* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
Yes.  Hera / Intel.

* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
No expected changes except for the known non-identical tests.

* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):
Currently running.  Will be posted prior to switching from a Draft PR.

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Just the normal regtests + the unstructured grid mod_defs: 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UNO_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_ta1/./work_UPD0F_U                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.17/./work_a                     (1 files differ)
ww3_tp2.17/./work_c                     (1 files differ)
ww3_tp2.17/./work_b                     (1 files differ)
ww3_tp2.6/./work_ST0                     (1 files differ)
ww3_tp2.6/./work_ST4                     (1 files differ)
ww3_tp2.6/./work_pdlib                     (1 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
```
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/9222896/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/9222897/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/9222898/matrixDiff.txt)

**Comment by JessicaMeixner-NOAA** [comment]
@MatthewMasarik-NOAA the tests on this PR passed.  Is there anything else you are waiting for or can this be moved from draft?

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA Awesome!  If they passed, it is all ready.  I hadn't moved forward because I had some mod_def. differences, but I believe I just updated my repo and ran ww3_from_ftp.sh in a way that may have been inconsistent with the recent update... so I was in the process of rerunning just to make sure, but I believed they would pass, so I just hadn't got back to it yet.

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA I have marked it ready for review.

**Comment by JessicaMeixner-NOAA** [comment]
@MatthewMasarik-NOAA I'm guessing the mod_def diffs were unstructured grid cases: https://github.com/NOAA-EMC/WW3/issues/700 

I'll review and this should be merged shortly.

**Comment by JessicaMeixner-NOAA** [comment]
@MatthewMasarik-NOAA I'm assuming you did the checks for the doxygen files themselves as making sure those get created are not yet part of the regression testing?

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA , I did the full matrix against the doxygen marked files, I'm sure those changes are fine -- they all passed the regtests. On second thought, I would like to give it a once over again, before submitting.  Please leave as is for the moment and I will complete my checks and update the PR text when it is ready to review.  Sorry for the confusion.

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA , I couldn't find how to change it back to just a draft.  I deleted and will resubmit.

**Pull request closed without merging**
