### PR TITLE
R21B in IC4

### PR DESCRIPTION
**Pull request by ErickRogers**
# Pull Request Summary

Introduce IC4M8 and IC4M9 to WW3

## Description

This introduces IC4M8 and IC4M9 to WW3.
It should not change outcome of any WW3 runs which do not use the new features. (Reverse compatible.)
However, it does include two non-default options to aspects of IC4 that are not M8 or M9.
Namely:
* option for background dissipation at low frequencies
* option for using a larger number of steps in IC4M6 (was 10, and is now 16)

Some comments about "IC4 other than IC4M8/IC4M9 " are also changed/updated in the header of w3sic4md.F90.

Verbose descriptions of IC4M8 and IC4M9 can be found in header of w3sic4md.F90.

regtests to demo the new feature:
cd $REGTESTDIR
./bin/run_test -i input_IC4_M8 -w work_IC4_M8 $MODELDIR ww3_tic1.1
./bin/run_test -i input_IC4_M9 -w work_IC4_M9 $MODELDIR ww3_tic1.1

ER: I need to describe the feature in the manual. I added it to my to-do list.

* Suggested reviewers: @JessicaMeixner-NOAA , @MatthewMasarik-NOAA 
* Labels: new feature
* Changes are not expected from this PR.

### Issue(s) addressed
This is for issue #1167

### Commit Message
Introduce IC4M8 and IC4M9 to WW3

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [x] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [x] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? 2 new regression tests were added, see here: https://github.com/NOAA-EMC/WW3/commit/d4640abf74bb4e8a63b4a9a69d502044ba885812
* Are the changes covered by regression tests? Yes, see prior bullet.
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? No.
* Please indicate the expected changes in the regression test output. No changes expected.
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_): N/A. Matrix was not run.

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@ErickRogers Thanks for making this PR!   A few things to note: 
* there's a conflict with the develop branch, so you'll need to merge in the latest develop into your branch. 
* It looks like we should be adding some new tests to matrix.base but I don't see that here?  Let me know if you need any help with that.  Also I'm going to add back some testing information in the PR template that we'll get you to fill in as well.

**Comment by ErickRogers** [comment]
The conflict is resolved, @JessicaMeixner-NOAA

**Comment by ErickRogers** [comment]
I will add the new regtests to matrix.base, @JessicaMeixner-NOAA

**Comment by ErickRogers** [comment]
I added the new regtests to matrix.base, @JessicaMeixner-NOAA

**Comment by ErickRogers** [comment]
@JessicaMeixner-NOAA @MatthewMasarik-NOAA, I think it is ready to go now.

**Comment by JessicaMeixner-NOAA** [comment]
@ErickRogers I think you meant to tag @MatthewMasarik-NOAA not Matheiu.  I actually had started some regression tests last week. Unforutunatley the queue is very busy and I'm still waiting for the last of it to run.  I'll post those results when I get them and then will retest with the latest updates you've shared here.

**Comment by ErickRogers** [comment]
Right Jessica, sorry @MathieuDutSik please disregard, I meant to tag @MatthewMasarik-NOAA

**Comment by ErickRogers** [comment]
@JessicaMeixner-NOAA, thanks for starting the runs. Today's changes are just to the manual and comments, so those don't require any re-run. But some of the ones last week could of course affect the matrix outcome. Like my additions to the matrix file. But OTOH, the additions to the matrix file cannot be apply to the baseline branch (dev), since they use the new feature.

**Comment by JessicaMeixner-NOAA** [comment]
@ErickRogers can you confirm that this looks as expected, with the differences being: 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tic1.1/./work_IC4_M5                     (2 files differ)
ww3_tic1.1/./work_IC4_M6                     (2 files differ)
ww3_tic1.1/./work_IC4_M6L                     (2 files differ)
ww3_tic1.1/./work_IC4_M3                     (2 files differ)
ww3_tic1.1/./work_IC4_M6H                     (2 files differ)
ww3_tic1.1/./work_IC4_M7                     (2 files differ)
ww3_tic1.1/./work_IC4_M4                     (2 files differ)
ww3_tic1.1/./work_IC4_M8                     (directory not found)
ww3_tic1.1/./work_IC4_M2                     (2 files differ)
ww3_tic1.1/./work_IC4_M9                     (directory not found)
ww3_tic1.1/./work_IC4_M1                     (2 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```

And full log files: 
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/14024876/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/14024877/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/14024878/matrixDiff.txt)


The "unexpected" differences are: 
```
ww3_tic1.1/./work_IC4_M5                     (2 files differ)
ww3_tic1.1/./work_IC4_M6                     (2 files differ)
ww3_tic1.1/./work_IC4_M6L                     (2 files differ)
ww3_tic1.1/./work_IC4_M3                     (2 files differ)
ww3_tic1.1/./work_IC4_M6H                     (2 files differ)
ww3_tic1.1/./work_IC4_M7                     (2 files differ)
ww3_tic1.1/./work_IC4_M4                     (2 files differ)
ww3_tic1.1/./work_IC4_M8                     (directory not found)
ww3_tic1.1/./work_IC4_M2                     (2 files differ)
ww3_tic1.1/./work_IC4_M9                     (directory not found)
ww3_tic1.1/./work_IC4_M1                     (2 files differ)
```

Which are your 2 new tests plus a few other diffs in tic1.1 tests.  These diffs only appear to be the mod_defs and ww3_grid.out.  My only curiosity was why just these tests, but likely this is all okay.   I will do a quick double check on the two new tests with the version of the code + comment changes as a quick sanity check and to make sure they reproduce themselves.   Then we should be ready to merge this in.

**Comment by ErickRogers** [comment]
@JessicaMeixner-NOAA  thanks again for running the tests. The changes listed as "unexpected" look OK to me. Re: "why just these tests" ... I added new variables to the IC4 namelist, so they show up as changes to mod-def and grid.out. But the differences only will appear in the regtests where the IC4 switch is used. So that is expected/OK. And as you noticed, they don't affect the actual results, which is also expected.  
I'm puzzled about the differences in the .nc files, like /mww3_test_03/work_PR2_UNO_MPI_d2/ww3.196806.nc_diff.txt ... like... 

\<     7.424531, 7.883871, 8.097491, 8.154648, 8.00843, 7.535123, 6.881038, 
\>     7.424531, 7.883871, 8.097491, 8.154648, 8.00843, 7.535123, 6.881037, 

Yes, these differences are tiny, but I wonder why we see even tiny differences. Is that normal? Is this caused by some randomness in WW3, or in netcdf?

**Comment by JessicaMeixner-NOAA** [comment]
@ErickRogers the  mww3_test_03/*_d2 are known to have differences (https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results).  For more details please see: https://github.com/NOAA-EMC/WW3/issues/144

**Comment by ErickRogers** [comment]
@JessicaMeixner-NOAA ....OK, thanks for the info. I get it now that you were implicitly grouping those as "not unexpected differences" i.e. expected differences.

**Comment by JessicaMeixner-NOAA** [comment]
Quick sanity check that the new tests reproduce themselves passed.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Thanks  @ErickRogers !

**Pull request merged**
