### PR TITLE
Bugfix/gqm

### LINKED ISSUE #1085: [W3SRC4] WHITECAP not initialised before use
The `WHITECAP` variable in W3SDS4 is not initialised before use in the following additive loop:
https://github.com/NOAA-EMC/WW3/blob/7bbdaca7f452b23a52c3a609b03e82204653dc5e/model/src/w3src4md.F90#L2551-L2554

Elements 1 and 2 are zeroed further up in the code, but element 4 is not which can result in an undefined value in the accumulated sum on line 2553 (`WHITECAP(4)`)

Because the variable is `INTENT(OUT)`, zeroing of the WHITECAP array outside this subroutine has no affect.

### LINKED ISSUE #1126: THRCOU parameter is not correctly set for GQM implementation in w3snl1md
**Describe the bug**
changing the valeur of GQMTHRCOU has no effect with intel compiler with optimized option but it works in debug option or with gnu compiler

**To Reproduce**
./bin/run_cmake_test -f -N -S -T  -w work_ST4_T707GQM  -g ST4_T707 -i input_10ms -N ../model ww3_ts1

**Expected behavior**
it should run in 2s instead of 10s

**Screenshots**

**Additional context**
replacing the code :
```
      DO JT1=1,GQNT1
        DO IQ_OM2=1,GQNQ_OM2
          AAA=TB_FAC(IQ_OM2,JT1,JF1)*TB_TPM(IQ_OM2,JT1,JF1)
          IF (AAA.GT.AUX) AUX=AAA
          CCC=TB_FAC(IQ_OM2,JT1,JF1)*TB_TMP(IQ_OM2,JT1,JF1)
          IF (CCC.GT.AUX) AUX=CCC
        ENDDO
      ENDDO
```

by : 

```
      DO JT1=1,GQNT1
        DO IQ_OM2=1,GQNQ_OM2
          AUX=MAX(AUX,TB_FAC(IQ_OM2,JT1,JF1)*TB_TPM(IQ_OM2,JT1,JF1),TB_FAC(IQ_OM2,JT1,JF1)*TB_TMP(IQ_OM2,JT1,JF1))
        ENDDO
      ENDDO
```

Running with ddt software clearly show that intel has not optimized correctly the do loop and never goes in the if loops except if I add a print statement before to force intel to not optimize the do loop

### PR DESCRIPTION
**Pull request by mickaelaccensi**
# Pull Request Summary
correct bugs to run correctly GQM implementation

## Description
add missing documentation and correct bugs found both with debug options and ddt software
the results of ww3_ts1 should now be correct

### Issue(s) addressed
  
- fixes #1085 
- fixes #1126 

### Commit Message
correct bugs to run correctly GQM implementation

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [x] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [x] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? ww3_ts1
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) ww3_ts1
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? on going
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
 -the only differences are still due to pdlib on my HPC (ww3_tp2.17, ww3_tp2.21, ww3_tp2.6)
 -diff on ww3_ts1 are expected
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/13479619/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/13479620/matrixCompFull.txt)

### CODE REVIEW

**Comment by mickaelaccensi** [comment]
@MatthewMasarik-NOAA can you test this PR first. It should solve a few issues I had on my st4table branch and also in @ukmo-ccbunney draft PR about the whitecap variable which was not correctly initialized.

Once this branch is merged, I'll provide another branch for st4 to try to track step by step the changes

**Comment by MatthewMasarik-NOAA** [comment]
Sure thing @mickaelaccensi.  Do you have the regtest results, so I know what I should be looking for?

**Comment by mickaelaccensi** [comment]
it's running right now, I will provide once it's done. it should change the outputs in ww3_ts1

**Comment by MatthewMasarik-NOAA** [comment]
Great, thanks for sending those when their done.  I'll get the tests submitted.

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi have the tests finished running? If so, if you can post those we'll start running things on our end.

**Comment by mickaelaccensi** [comment]
@JessicaMeixner-NOAA done. The only differences are still due to pdlib on my HPC (ww3_tp2.17, ww3_tp2.21, ww3_tp2.6)

diff on ww3_ts1 are expected

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for posting the logs!

**Comment by MatthewMasarik-NOAA** [comment]
Quick clarification - I think #1124 was up first..  Are the logs for that PR, or this one?

And my apologies... I probably confused things with my posts here from last week.

**Comment by JessicaMeixner-NOAA** [comment]
> @MatthewMasarik-NOAA can you test this PR first. It should solve a few issues I had on my st4table branch and also in @ukmo-ccbunney draft PR about the whitecap variable which was not correctly initialized.
> 
> Once this branch is merged, I'll provide another branch for st4 to try to track step by step the changes


@MatthewMasarik-NOAA I think this PR was requested to go first.

**Comment by MatthewMasarik-NOAA** [comment]
> > @MatthewMasarik-NOAA can you test this PR first. It should solve a few issues I had on my st4table branch and also in @ukmo-ccbunney draft PR about the whitecap variable which was not correctly initialized.
> > Once this branch is merged, I'll provide another branch for st4 to try to track step by step the changes
> 
> @MatthewMasarik-NOAA I think this PR was requested to go first.

Its all coming back...  doh.  Sorry for my confusion.

**Comment by MatthewMasarik-NOAA** [comment]
Thanks for the logs @mickaelaccensi, I'll work on completing the review.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
#### Code review
Pass

#### Testing
Pass

**matrix.comp**
Summary output below shows: 1) known non-b4b's, 2) expected differences in `ww3_ts1` tests. 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
## known non-b4b
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (12 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
##

ww3_ts1/./work_ST4_T700                     (2 files differ)
ww3_ts1/./work_T707GQM                     (2 files differ)
ww3_ts1/./work_T713GQM                     (2 files differ)


**********************************************************************
************************ identical cases *****************************
**********************************************************************
```


[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/13490569/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/13490566/matrixCompFull.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/13490568/matrixDiff.txt)

**Comment by MatthewMasarik-NOAA** [comment]
@mickaelaccensi  thanks for finding a fix for this issue, and the documentation updates!

**Pull request merged**
