### PR TITLE
UKMO Staging (Oct 2020)

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
## Details

This PR comprises 4 indivudal PRs raised and reviewed on the [UKMO WW3](https://github.com/ukmo-waves/WW3) repo:
   * https://github.com/ukmo-waves/WW3/pull/17: Fix non-conforming WHERE statements in coupled routines
   * https://github.com/ukmo-waves/WW3/pull/16: Changes for efficient SMC grid coupling
   * https://github.com/ukmo-waves/WW3/pull/15: Enhancement to improve the way in which input data is read in and logged by the ww3_uprstr program
   * https://github.com/ukmo-waves/WW3/pull/13: OASIS coupling at T+0

### Additional files
Two new files need to be added to the `ww3_from_ftp.*.tar.gz` regtests data distribution file for the new OASIS SMC regression test. The files are attached here: https://github.com/ukmo-waves/WW3/files/5347030/weights.zip

## Regression Testing
The full regression test matrix results are attached: [maxtrixComp_staging_oct20.zip](https://github.com/NOAA-EMC/WW3/files/5460417/maxtrixComp_staging_oct20.zip)

### Expected differences:
   - **ALL** regtests show differences in the generated `restart.ww3` files due changes made for PR13 (OASIS T+0 coupling). For all non-coupled runs, the difference is just a change of the internal version string to `2020-09-25`
   - `ww3_ta1`: Small text changes to `ww3_grid.out` and `ww3_uprstst.out` log files relating to PR15.
   - New regression tests for OASIS coupling (OASACM3, OASACM4, OASACM5 and OASACM6)

### Known existing differences:
  - `mww3_test_03`: Not b4b.
  - `ww3_tp2.18/TIDE_MPI`: Differences in order of debug lines in `ww3_prtide_current.out` log file when run in MPI mode.

### CODE REVIEW

**Comment by aliabdolali** [comment]
Hi @ukmo-ccbunney 
I am running the matrix on our HPC. 
I also updated the tar file on ftp, could you update mode/bin/ww3_from_ftp.sh?
https://ftp.emc.ncep.noaa.gov/static_files/public/WW3/ww3_from_ftp.v7.07.tar.gz

**Comment by ukmo-ccbunney** [comment]
> 
> 
> Hi @ukmo-ccbunney
> I am running the matrix on our HPC.
> I also updated the tar file on ftp, could you update mode/bin/ww3_from_ftp.sh?
> https://ftp.emc.ncep.noaa.gov/static_files/public/WW3/ww3_from_ftp.v7.07.tar.gz

Hi @aliabdolali - the required update should already be in `ww3_from_ftp.sh`:
https://github.com/ukmo-waves/WW3/blame/426d42349f54faf3b0f90569e120807eac2778d9/model/bin/ww3_from_ftp.sh#L40

**Review by aliabdolali — APPROVED** [review]
@ukmo-ccbunney Looks good to me.

**Comment by aliabdolali** [comment]
I have checked the matrix on NOAA HPC and the expected differences
[matrix_diff_ukmet_staging_NOAA.zip](https://github.com/NOAA-EMC/WW3/files/5495507/matrix_diff_ukmet_staging_NOAA.zip)
 are the same as the ones reported by UKMET.

**Comment by aliabdolali** [comment]
@ukmo-ccbunney Please close any related issues which are resolved here.

**Comment by ukmo-ccbunney** [comment]
> 
> 
> I have checked the matrix on NOAA HPC and the expected differences
> [matrix_diff_ukmet_staging_NOAA.zip](https://github.com/NOAA-EMC/WW3/files/5495507/matrix_diff_ukmet_staging_NOAA.zip)
> are the same as the ones reported by UKMET.

Great - many thanks @aliabdolali .

**Pull request merged**
