### PR TITLE
Remove XX0/XXX switch 

### LINKED ISSUE #356: Remove support for supplemental & experimental supplemental source terms  (XX0, XXX)
There are two supplemental/experimental source terms XX0 and XXX.  We propose removing this example code and switch options. 

This work is planned for the end of May 2021.

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
Removes the XX0/XXX switches

## Description
The XX0 and XXX switches were examples for how to add experimental or supplemental source terms.  Other switches can also be used for this purpose.  

### Issue(s) addressed

- fixes #356

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)? yes
* Reviewers: @aliabdolali 

### Testing
* How were these changes tested? All regression tests were 
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) No tests were for the XXX switch.  
* If a new feature was added, was a new regression test added? No. 
* Have regression tests been run? Yes
* Which compiler / HPC you used to run the regression tests in the PR?  NCEP hera.intel 
* Please provide the summary output of matrix.comp (_matrix.Diff.out_, _matrixCompFull.out_ and _matrixCompSummary.out_):    
Please indicate the expected changes in the outputs ([excluding the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)).

The XX0 switch still needs to be removed from every switch file.  Since this is disruptive and will cause many merge conflicts, it was only removed locally for testing.  When this PR is ready to be merged, the XX0 switch will be removed for all switch files and then the regtests will be rerun and the summary output will be uploaded.

### CODE REVIEW

**Review by aliabdolali — COMMENTED** [review]
Hi @JessicaMeixner-NOAA 
Could you confirm the followings are left intentionally or we need to remove them?
model/ftn/gx_outp.ftn:614:!       !/XXx    Arbitrary adittional source term package
model/ftn/ww3_ounp.ftn:1380:!       !/XXx    Arbitrary adittional source term package
manual/impl/install.tex:154:\fit{switch\_{\it xxx} }{Examples of preprocessor switches provided by users

**Comment by aliabdolali** [comment]
The tests ran successfully on hera with known non-b4b tests.
All the tests are different: All the mod_def files are different but there is no change in the results. Some netcdf files are different due to changes in switch (see matrixDiff.txt).

[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/6939464/matrixDiff.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/6939465/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/6939466/matrixCompFull.txt)

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali another great catch.  I've removed the comments in : 
model/ftn/gx_outp.ftn:614:! !/XXx Arbitrary adittional source term package
model/ftn/ww3_ounp.ftn:1380:! !/XXx Arbitrary adittional source term package

But I think this xxx is just for say, switch_MPI or switch_ST4, so I think this one should stay: 
manual/impl/install.tex:154:\fit{switch_{\it xxx} }{Examples of preprocessor switches provided by users

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali the mod_def changes are because of the removal of: 
!/XX0      TNAME7 = 'Not defined                   '
 !/XXX      TNAME7 = 'Experimental                  '
in model/ftn/w3iogrmd.ftn.  

Since the mod_defs were changing I decided we should also check ufs-weather-model, which required creation of new mod_def files but then the output remained the same.

**Comment by aliabdolali** [comment]
ok, so I am going to merge this and will update the ufs-weather-model spreadsheet to make sure we will update mod_defs for next sync to WW3.

**Review by aliabdolali — APPROVED** [review]

**Pull request merged**
