### PR TITLE
removing file that should not be in repository

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**

### CODE REVIEW

**Comment by mickaelaccensi** [comment]
we should even add a rule in gitconfig to not take into account .swp files

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi we have in .gitignore: 

```
*.swp
*/*.swp
*/*/*.swp
*/*/*/*.swp

```
already. I would have thought that would have prevented this, but apparently not?

**Comment by mickaelaccensi** [comment]
it's because it's a hidden file. So we need to add : 
```
.*.swp
*/.*.swp
*/*/.*.swp
*/*/*/.*.swp
```

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi added!

**Comment by ukmo-ccbunney** [comment]
Do we need all the directory permutations?
I think that the rule `*.swp` should match any file in the repo, even if it is in a directory.

On my system `*.swp` ignores all .swp files, regardless of directory depth or if the filename is hidden (starts with a dot).

**Comment by JessicaMeixner-NOAA** [comment]
I didn't think you had to have the directory permutations but I'm not sure?  Maybe we just already had that file in the repo before the *.swp was added?

**Comment by mickaelaccensi** [comment]
it's not the case on my system. The dot must be added to filter hidden files.

**Comment by ukmo-ccbunney** [comment]
> 
> 
> it's not the case on my system. The dot must be added to filter hidden files.

Interesting that it is different on your system - maybe a different version of Git (I'm on 2.24.3).
So, perhaps we just need:
```
*.swp
.*.swp
```
??

**Comment by JessicaMeixner-NOAA** [comment]
Combined into  PR #284

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA It is merged with https://github.com/NOAA-EMC/WW3/pull/284, can we delete it?

**Pull request closed without merging**
