### PR TITLE
added documentation of w3iopo subroutine

### PR DESCRIPTION
**Pull request by edwardhartnett**
# Pull Request Summary
Adding documentation. No code changes in this PR.

## Description
Part of #682 

This is the documentation for w3iopo().

No code changes in this PR, so no changes of data output and no new tests are needed.

### Issue(s) addressed

Adding documentation to w3iopo() in preparation for code for #682.

### Commit Message

Adding documentation to w3iopo() in preparation for code for #682.

### Check list  

- [ x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [x ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [x ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

No testing needed, documentation only.

### CODE REVIEW

**Review by MatthewMasarik-NOAA — CHANGES_REQUESTED** [review]
Hi @edwardhartnett.  I reviewed this by checking the output HTML pages.  Everything looks good, though there are two variables that have '?'s in their descriptions, and I wanted to see if we could resolve those before merging.

I tried to track down the info for these, but was only partially successful for one of them. 
1. `VERTST`:  https://github.com/edwardhartnett/WW3/blob/ea3b87387b804b46caa07c5831e6e2d6e7e3def4/model/src/w3iopomd.F90#L1047
I could not find this defined anywhere.  However, it's value is compared against `VERGRD`, which is defined as _"Model definition file version number"_.  So, maybe something to the effect of _"Model definition file version number to be tested"_?

2. `ZET_SETO`:  https://github.com/edwardhartnett/WW3/blob/ea3b87387b804b46caa07c5831e6e2d6e7e3def4/model/src/w3iopomd.F90#L1068
I couldn't find this defined anywhere either.  In `w3odatmd.F90` there is a short comment after the declaration, which states it is for the wave setup, but really doesn't shed much light.  I would maybe just leave the **Meaning** field for that variable blank?

I'll approve if those two lines are resolved.

**Comment by edwardhartnett** [comment]
I've made the changes you suggest.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
#### Code review
Pass

#### Testing
Pass

As Ed pointed out, no code changes, so no regtesting needed.  The "test" in this case was loading the html output and confirming all looks well.

image

Approved.

**Comment by MatthewMasarik-NOAA** [comment]
The documentation is thorough and tables look very nice.  Thanks @edwardhartnett!

**Pull request merged**
