### PR TITLE
in w3iors use NSEA instead of NSEAL in serial write/read of VA

### LINKED ISSUE #940: w3iors NSEAL vs NSEA in non-MPI portions of read/write
**Describe the bug**
Not 100% sure this is a bug, but this should be investigated.  While working on https://github.com/NOAA-EMC/WW3/issues/829

I found that in the non-MPI sections of the read/write of the restart we are using: 

DO JSEA=1, NSEAL 

In the following lines of code: 
https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3iorsmd.F90#L631 
and 
https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3iorsmd.F90#L788

In standalone mode, perhaps we've already defined NSEAL=NSEA and this is fine, but I found I had to set NSEAL=NSEA when trying to read/write this from ww3_gint.   

To test if this is a bug or not, my plan is to: 
* run the regression tests with these NSEAL->NSEA and see if they work 
* See if there are differences, and make sure to test a non-mpi case for a restart run and make sure everything is working as expected.

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
Change NSEAL-> NSEA in w3iors in serial section of the code for writing/reading VA 

## Description

In w3iors in the serial section, NSEAL is used and while this "works" NSEAL is a variable defined for MPI and if you use w3iors in a non ww3_shel or ww3_multi program and this is not set, it could break the program.  

Please also include the following information: 
* Add any suggestions for a reviewer  @MatthewMasarik-NOAA @ukmo-ccbunney 
* Mention any labels that should be added:  _bug_
* Are answer changes expected from this PR? no

### Issue(s) addressed
fixes https://github.com/NOAA-EMC/WW3/issues/940

### Commit Message
in w3iors use NSEA instead of NSEAL in serial write/read of VA

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?  with matrix plus one extra serial restart test 
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) yes
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? intel, hera 
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.) No expected changes in answers
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_ta1/./work_UPD0F_U                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.17/./work_a                     (12 files differ)
ww3_tp2.17/./work_c                     (12 files differ)
ww3_tp2.17/./work_b                     (12 files differ)
ww3_tp2.6/./work_ST0                     (1 files differ)
ww3_tp2.6/./work_ST4                     (1 files differ)
ww3_tp2.6/./work_pdlib                     (1 files differ)
ww3_ts4/./work_ug_MPI                     (1 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/11031237/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/11031238/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/11031239/matrixDiff.txt)

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@MatthewMasarik-NOAA the regtests were run with an earlier develop.  I'm leaving that as is for now unless you want me to run additional tests in addition to the ones you've made.   If someone else wants to do a check to insure I haven't missed other NSEAL in w3iors that's probably a good idea too.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks to @MatthewMasarik-NOAA who caught an error I did not: 

There is an error when running ww3_shel for: 
 Running now options: run_test -b slurm -o all -S -T -s MPI -s NO_PDLIB -w work_a -g a -f -p srun -n 24 ../model ww3_tp2.17


```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
ww3_shel           0000000000675A1A  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B0DDE84E630  Unknown               Unknown  Unknown
ww3_shel           000000000057C5F2  w3iorsmd_mp_w3ior         636  w3iorsmd.F90
ww3_shel           00000000005D1D47  w3wavemd_mp_w3wav        2610  w3wavemd.F90
ww3_shel           0000000000410083  MAIN__                   2634  ww3_shel.F90
ww3_shel           00000000004069E2  Unknown               Unknown  Unknown
libc-2.17.so       00002B0DDEA7D555  __libc_start_main     Unknown  Unknown
ww3_shel           00000000004068E9  Unknown               Unknown  Unknown

```

I'm going to mark this as a draft for now until I can figure out why this is failing.  In the meantime I'll move forward with the gint update that sets NSEAL=NSEA. 

FYI @ukmo-ccbunney since I know you're running regtests.

**Comment by ukmo-ccbunney** [comment]
> Thanks to @MatthewMasarik-NOAA who caught an error I did not:
> 
> There is an error when running ww3_shel for: Running now options: run_test -b slurm -o all -S -T -s MPI -s NO_PDLIB -w work_a -g a -f -p srun -n 24 ../model ww3_tp2.17
> 

Hi @JessicaMeixner-NOAA 
Yes - I am getting a segfault there too. It looks like it is ocuring during the generation of the restart file (last file touched is `restartNNN.ww3`.

It looks like it is failing around line 636 in w3iorsmd, probably because of a out-of-range JSEA value:

```
DO JSEA=1, NSEA
            CALL INIT_GET_ISEA(ISEA, JSEA)
            NREC   = ISEA + 2
            RPOS  = 1_8 + LRECL*(NREC-1_8)
            WRITEBUFF(:) = 0.
            WRITEBUFF(1:NSPEC) = VA(1:NSPEC,JSEA)   # <- failing here...
            WRITE (NDSR,POS=RPOS,ERR=803,IOSTAT=IERR) WRITEBUFF
END DO
```

I think this is happening because this block of code is entered for both MPI and SHRD use cases, so the loop would have to be over NSEAL to work when run under MPI (as in this case)

As far as I can tell, the change you made at line 736 is safe as that bit of code only ever gets executed if the model is run in SHRD mode thanks to the #ifdef on line 738 and the conditional on line 740.

I guess there are two options here:
  1. Make the loop variable `NSEA` for SHRD mode and `NSEAL` for MPI mode on line 631 (with #ifdefs? You could ditch the INIT_GET_ISEA call in SHRD mode too...)
  2.  Stick to the original code and make the assumption that the calling routine always sets NSEAL appropriately even in SHRD mode

**Comment by ukmo-ccbunney** [comment]
Just to confirm, modifying w3iorsmd as per below fixes the issue (and the restarts are b4b with develop).
It's a bit ugly though - perhaps it would look nicer with a separate loop variable for the DO loop that is set to NSEA or NSEAL respectively.


```fortran
! w3iorsmd.f90: Line 631
#ifdef W3_MPI        
          DO JSEA=1, NSEAL
            CALL INIT_GET_ISEA(ISEA, JSEA)
#else            
          DO JSEA=1, NSEA
            ISEA = JSEA
#endif          
            NREC   = ISEA + 2
            RPOS  = 1_8 + LRECL*(NREC-1_8)
            WRITEBUFF(:) = 0.
            WRITEBUFF(1:NSPEC) = VA(1:NSPEC,JSEA)
            WRITE (NDSR,POS=RPOS,ERR=803,IOSTAT=IERR) WRITEBUFF
          END DO
```

**Comment by JessicaMeixner-NOAA** [comment]
Okay - I finally updated the code with @ukmo-ccbunney suggestion and am re-running regtests.

**Comment by JessicaMeixner-NOAA** [comment]
A re-run of the regtests provide expected results: 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (9 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
ww3_ta1/./work_UPD0F_U                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/11322986/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/11322987/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/11322988/matrixDiff.txt)

**Comment by ukmo-ccbunney** [comment]
Changes look good to me. Just running regression tests now.

**Comment by MatthewMasarik-NOAA** [comment]
> Changes look good to me. Just running regression tests now.

Awesome.  Thanks for testing @ukmo-ccbunney

**Review by MatthewMasarik-NOAA — APPROVED** [review]
**Code review** Pass

**Testing** Pass

Regressions tests show just the known non-b4b's as non-identical.
 ```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (12 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
 
**********************************************************************
************************ identical cases *****************************
**********************************************************************
```
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/11389759/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/11389757/matrixCompFull.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/11389758/matrixDiff.txt)

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA, thank you for this clarification of loop limit for serial IO.

**Pull request merged**
