### PR TITLE
auto-format fixes for develop

### LINKED ISSUE #796: Updates to that prohibit automatic white space changes
**Is your feature request related to a problem? Please describe.**
To use an automatic update to improve the line-spacing of WW3, several sections of code need updating for the script to work. 

**Describe the solution you'd like**
Code where the automatic line-space changes will succeed.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# Pull Request Summary

Updates required modules to  allow auto-formatting to complete without error or other line change. 

## Description

- converts ``do N ... N Continue`` to ``do N ... end do``.
- adds missing pounded ifdefs for ``W3_SHRD`` and ``W3_MPI``
- adds name association at ``end subroutine`` and ``end module``

The fixes are identified first by having emacs attempt to auto-indent. For this PR, the initial auto-format was carried out in batch mode using emacs

```
 emacs --batch FILENAME.F90 -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer
```

Failures are the reported as, for example

```
END DO does not match IF.
END SUBROUTINE does not match IF
```

Each failure must then be found and resolved manually.

### Issue(s) addressed

fixes #796 

### Commit Message

Fixes to allow auto-formatting

co-author @mvertens 

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

- Auto-formatting successfully completes w/o error for all files in ``src``, ``PDLIB`` and ``SCRIP`` subdirectories. A test branch then had the auto-formatting applied and the resultant PR include whitespace only changes.
- Matching changes were made in the dev/ufs-weather-model branch and all wave regression tests for hera.intel/gnu and cheyenne.intel/gnu were run. All baselines passed.

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA @JessicaMeixner-NOAA This is the first 5 files which need changes to allow the auto-format. Before I go any further, I wanted to make sure that these changes will be acceptable. 

The next batch would contain similar changes to w3snl4md, w3strkmd, w3tidemd, w3updtmd.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen These changes would be acceptable.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA @MatthewMasarik-NOAA In ``wmwavemd.F90`` there are multiple instances of an ``END IF`` appearing which matches an ``IF()THEN`` in *either* a preceding W3_MPI or W3_SHRD. I've resolved those, but there still appears to be an issue w/ ``wmwavemd.F90`` which breaks auto-formatting and which I cannot resolve. 

I've attached the auto-formatted wmwavemd.F90 here (gzipped so I can attach). 

The issue appears starting at LN 1329, in the section of code "! 9.d Process unified point output for selected grid". The problem in the commented out section arises at LN 1373

```
#ifdef W3_MPI
                        ELSE IF ( FLG_O1 ) THEN
#endif
```

This line is a problem because it cannot be enclosed by any matching "if-endif".  LNS 1332-1372 appear correct---there is a matching ``END IF`` for both the ``IF (UNIPTS)`` and ``IF (FLG_02)``. The preceding ``if (FLG_O1)`` at LN 1264 has been closed by the ``END IF`` at LN 1328. 

Here is the relevant section.
```
                   END IF ! IF ( FLG_O1 )
                            !
                            ! 9.d Process unified point output for selected grid
                            !
                            IF ( UNIPTS ) THEN
                               IF ( FLG_O2 ) THEN
                                  CALL W3SETO ( I, MDSE, MDST )
                                  !
#ifdef W3_MPI
                                  IF ( NRQPO.NE.0 ) CALL MPI_STARTALL      &
                                       ( NRQPO, IRQPO1, IERR_MPI )
#endif
                                  !
                                  IF ( NOPTS.NE.0 .AND. IAPROC.EQ.NAPPNT ) THEN
                                     CALL W3SETG ( I, MDSE, MDST )
                                     CALL W3SETA ( I, MDSE, MDST )
                                     CALL W3IOPE ( VA )
                                  END IF
                                  !
#ifdef W3_MPI
                                  IF ( NRQPO .NE. 0 ) THEN
                                     ALLOCATE ( STATUS(MPI_STATUS_SIZE,NRQPO) )
                                     CALL MPI_WAITALL                      &
                                          ( NRQPO, IRQPO1, STATUS, IERR_MPI )
                                     DEALLOCATE ( STATUS )
                                  END IF
#endif
                                  !
#ifdef W3_T
                                  WRITE (MDST,9092) NOPTS
#endif
                                  !
                               END IF ! IF ( FLG_O2 )
                               !
                            END IF ! IF ( UNIPTS )
                            !
#ifdef W3_MPRF
                            CALL PRTIME ( PRFTN )
                            WRITE (MDSP,991) PRFT0, PRFTN,get_memory(),      &
                                 'ST07', I
#endif
                            !
                            ! 9.e Update TOUTP outside communicator
                            !
#ifdef W3_MPI
                         ELSE IF ( FLG_O1 ) THEN
#endif
                            !
#ifdef W3_MPI
                            CALL W3SETO ( I, MDSE, MDST )
                            CALL W3SETW ( I, MDSE, MDST )
#endif
                            !
#ifdef W3_MPI
                            TIME       = TOUTP(:,I)
                            TOUTP(1,I) = -1
                            TOUTP(2,I) =  0
#endif
```





[wmwavemd.F90.gz](https://github.com/NOAA-EMC/WW3/files/9636125/wmwavemd.F90.gz)

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I've looked at this and don't have a quick answer but will continue to look into this to see if I can't figure this out.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen thank you so much for this PR.  I see no issues when reviewing the code and have started the standalone regression tests. Should get results back by tomorrow morning if not before.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Thanks @DeniseWorthen and @mvertens for these fixes! 

Expected diffs in WW3 standalone regression tests: 
```
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (20 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (18 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (17 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (15 files differ)
ww3_ta1/./work_UPD0F_U                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.17/./work_mb                     (1 files differ)
ww3_tp2.17/./work_b                     (1 files differ)
ww3_tp2.17/./work_mc                     (1 files differ)
ww3_tp2.17/./work_a                     (1 files differ)
ww3_tp2.17/./work_c                     (1 files differ)
ww3_tp2.17/./work_ma                     (1 files differ)
ww3_tp2.17/./work_mc1                     (1 files differ)
ww3_tp2.17/./work_ma1                     (1 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
```
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/9648732/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/9648733/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/9648734/matrixDiff.txt)

**Pull request merged**
